### ISSUE TITLE
Open source botframework emulator

### ISSUE THREAD

**Issue by thewhitetulip** [Microsoft/BotBuilder#558] opened 2016-06-27 07:44 UTC
The emulator is Windows only, Can we open source it so that the community can port it to Linux or Mac

**Comment by DavePilks** [comment] 2016-06-27 09:15
I have asked for this as well. If I recall, they said that they would take it under consideration.

**Comment by thewhitetulip** [comment] 2016-06-27 09:49
@DavePilks To be honest, they can just lay out the internals, we can build one for ourselves, in case they are busy.

I tried using Postman, but I wasn't able to debug my bot.

**Comment by willportnoy** [comment] 2016-06-28 00:20
http://docs.botframework.com/connector/tools/bot-framework-emulator/#mac-and-linux-support-using-command-line-emulator is an option for Linux/Mac.

**Comment by thewhitetulip** [comment] 2016-06-28 04:03
@willportnoy Yes, I know there is an option for Linux/Mac, but that's a command line editor, can we also have a UI based emulator like we have for Windows?

If you guys are busy on the botbuilder we can build a cross platform emulator.

**Comment by willportnoy** [comment] 2016-06-28 15:50
@tomlm what do you think?

**Comment by loretoparisi** [comment] 2016-06-30 15:54
That's interesting, what I'm doing now is the run a `TextBot` instance locally and listening to `stdin`

```javascript
bot = new BotBuilder.TextBot();
bot.listenStdin();
```

**Comment by thewhitetulip** [comment] 2016-07-01 05:36
Yes, even I am doing testing this way, way better than the command line version of the emulator.

**Comment by thewhitetulip** [comment] 2016-07-13 06:16
@tomlm Any thoughts?

**Comment by loretoparisi** [comment] 2016-07-13 08:40
by the way I think the problem is mostly for Linux since on MacOS you can run it with `mono` for free

```shell
macbookproloreto:BFEmulator admin$ mono BFEmulator.exe
Microsoft Framework Emulator

/exit or /quit to exit
/settings to change endpoint, appId and appSecret settings
/dump [#] to show contents of last # messages (default: 1)
/attachment [path] <- to add a file to your message
Current settings:
Endpoint: http://localhost:3978/api/messages
AppId: YourAppId
AppSecret: YourAppSecret
```

with

```shell
macbookproloreto:BFEmulator admin$ mono --version
Mono JIT compiler version 4.4.1 (mono-4.4.0-branch-c7sr0/4747417 Mon Jun 20 15:43:48 EDT 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  x86
	Disabled:      none
	Misc:          softdebug 
	LLVM:          yes(3.6.0svn-mono-master/a173357)
	GC:            sgen
```

**Comment by thewhitetulip** [comment] 2016-07-13 12:14
@loretoparisi  I am unable to Install mono itself, it says that "This app is from unidentified developer."

**Comment by loretoparisi** [comment] 2016-07-13 12:21
@thewhitetulip when on `MacOS` you have to unlock in `Preferences > Security and Privacy > Download app from: Everywhere` and then install from [here](http://www.mono-project.com/download/). You can also install [XamarinStudio](https://www.xamarin.com/platform), that will install everything you need for cross compilation of MacOS and will assure you to have a consistent environment.

**Comment by thewhitetulip** [comment] 2016-07-14 07:38
@loretoparisi Well, if the mono project is an actual real FOSS project, then why does it say that the app is from unidentified developer?

Thanks for the link!

**Comment by v-thgratMSGit** [comment] 2016-07-28 21:40
Closing this issue. @tomlm - if you have anything to add to this discussion, please do. Thanks!

**Closed by v-thgratMSGit** 2016-07-28 21:40 UTC
Labels: enhancement

**Comment by thewhitetulip** [comment] 2016-07-29 06:20
@v-thgratMSGit I am totally confused as to why we are closing issues without resolving them for real.

**Comment by loretoparisi** [comment] 2016-07-29 06:45
+1

**Comment by vitoc** [comment] 2016-11-04 09:49
+1
