### ISSUE TITLE
CoreCLR plans

### ISSUE THREAD

**Issue by jchannon** [Microsoft/BotBuilder#1290] opened 2016-09-21 09:15 UTC
Hi

Any plans to make the C# version compile on CoreCLR?

**Comment by willportnoy** [comment] 2016-09-21 16:27
https://github.com/Microsoft/BotBuilder/issues/572 has some relevant discussion.  We need some solution for the binary serialization issue, and it would probably be good to wait for the final release of the  Visual Studio tooling.

Also, .net core support can mean multiple things - ranging from "assembly depends on .net core" to "assembly depends on .net standard NuGet packaging" to "builder controller attributes work on asp.net core".  We have backlog items filed for all of these.

**Comment by jchannon** [comment] 2016-09-21 17:56
For binary serialization why not use Json, this is what we did for NancyFX. I dont see a need to wait for VS tooling, I don't require VS for example.

I would expect the project to target netstandard1.6 for example.

I'd also like to see less ties to aspnet directly, I have started porting the attribute usage for authorization for example to Nancy as we can't have attributes but this may be a whole new issue 😄

**Comment by willportnoy** [comment] 2016-09-22 16:33
JSON may be fine for serialization.  There are some features we need - for example, the ability to inject instances into the deserialization process from the dependency injection container so that not everything gets serialized with the dialog stack:
https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Fibers/FiberModule.cs#L52

**Comment by DamianReeves** [comment] 2016-10-18 18:39
@jchannon Did you get this working with NancyFX by any chance?

**Comment by jchannon** [comment] 2016-10-18 18:51
I did! Had to do some "borrowing and tweaking" to get it to work with
Nancy, mainly the conversion of attribute that authorizes the bot.

**Comment by jchannon** [comment] 2016-10-18 18:54
I ended up with this https://github.com/jchannon/HTTPStatusBot/blob/master/HTTPStatusBot/Modules/HomeModule.cs#L14

That then calls this: https://github.com/jchannon/HTTPStatusBot/blob/master/HTTPStatusBot/Extensions/BotExtensions.cs

I've tried to publish the bot but it just says "In Review" but its been like that for ages

**Comment by DamianReeves** [comment] 2016-10-18 19:01
Cool. Thanks. I'm going to give it a shot.

**Comment by DamianReeves** [comment] 2016-10-18 19:02
This should work with the .NET Core build of Nancy as well right?

**Comment by jchannon** [comment] 2016-10-18 19:11
No because the Bot framework isnt coreclr ready :(

**Comment by DamianReeves** [comment] 2016-10-18 19:13
Yeah, but if I target .NET 4.6 for example I should be covered.

**Comment by jchannon** [comment] 2016-10-18 19:43
Yeah should work. Will be interested to hear how you get on

**Comment by willportnoy** [comment] 2016-12-12 20:04
I'm going to close this issue as a duplicate of https://github.com/Microsoft/BotBuilder/issues/572.

**Closed by willportnoy** 2016-12-12 20:04 UTC
