### ISSUE TITLE
'Oops. Something went wrong and we need to start over.' with Microsoft Bot Service with LUIS Template

### ISSUE THREAD

**Issue by seetharam07** [Microsoft/BotBuilder#3692] opened 2017-10-30 22:01 UTC
## Bot Info 
* App ID: 39ba69b0-f674-4dd7-b466-4cc07ec66ca2
* SDK Platform: Node.js
* SDK Version: 
* Active Channels: DirectLine
* Deployment Environment: Azure Bot Service

## Issue Description
I have created a Bot Service with LUIS template using Node.js, I have trained my luis model with our domain utterances and it was working fine. suddenly from a week time , Am facing weird behavior form the Bot Service, for any request the bot is replying as 'Oops. Something went wrong and we need to start over.' message. Could anyone encountered the similar issue and share your inputs to resolve.

Appreciate your help.

## Reproduction Steps
1.Create any Bot Service with LUIS template

## Actual Results
Oops. Something went wrong and we need to start over

**Comment by JasonSowers** [comment] 2017-10-30 22:15
Closing as duplicate of https://stackoverflow.com/questions/47024815/oops-something-went-wrong-and-we-need-to-start-over-with-microsoft-bot-servi 

  please do not double post, we monitor both forums daily

**Closed by JasonSowers** 2017-10-30 22:15 UTC
Labels: LUIS, Node.js SDK

**Comment by seetharam07** [comment] 2017-10-31 15:18
thanks for letting know
