### ISSUE TITLE
[Question] Can not display data in HTML table format in bot?

### ISSUE THREAD

**Issue by itvignes09** [Microsoft/BotBuilder#4008] opened 2018-01-08 13:37 UTC
![18b34636-3f0d-11e7-8877-4a1e1e7d49fe](https://user-images.githubusercontent.com/4756086/34672811-e84f7402-f4a5-11e7-8d2b-c116aae2ac25.PNG)

    bot.dialog('message_with_table', function (session) { 
    var message = {
        type: 'message',
        textFormat: 'xml', 
        text: tableHTML
    };
    session.send(message);
    });

It simply displays HTML tags in response.

**Comment by nwhitmont** [comment] 2018-01-08 14:12
@itvignes09 - What channel are you using? Not all channels support HTML style message formatting.

**Comment by nwhitmont** [comment] 2018-01-08 14:38
closing as duplicate of https://stackoverflow.com/questions/48149833/how-to-display-data-in-table-format-in-microsoft-bot-framework

**Closed by nwhitmont** 2018-01-08 14:38 UTC
Labels: Node.js SDK, message formatting

**Comment by itvignes09** [comment] 2018-01-09 04:23
Hey @nwhitmont 
That StackOverflow question asked by me only. Please reopen the question.

**Comment by maheshksingh** [comment] 2019-05-21 11:45
Hello ,
I am also facing same issue. I am trying to show html content in bot.but not able to show that.

**Comment by EricDahlvang** [comment] 2019-05-21 19:59
@maheshksingh  Html is not supported, but you can use markdown-it as explained here: https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/02.b.getting-started-minimal-markdown

More information can be found in this answer: https://github.com/microsoft/BotFramework-WebChat/issues/1979
