### ISSUE TITLE
Bot on Skype When tried "Test connection to your bot "MethodNotAllowed" 405.

### ISSUE THREAD

**Issue by VishalWaman** [Microsoft/BotBuilder#828] opened 2016-07-27 05:42 UTC
Bot Name : WJBot
When we try to 'Test connection to your bot" returns error message as 

> "MethodNotAllowed"
> 405 - HTTP verb used to access this page is not allowed.
> The page you are looking for cannot be displayed because an invalid method"

Same error when we try by Fiddler.

Thanks.

**Comment by Thegaram** [comment] 2016-07-27 17:07
This suggests the problem is in your service. Maybe you're exposing the endpoint for GET instead of POST accidentally? Could you share the request you're sending with Fiddler, and the part of your code that initializes the endpoint you're trying to access?

**Comment by VishalWaman** [comment] 2016-07-28 04:35
#  MessagesController
`
namespace Microsoft.Bot.Sample.SimpleSandwichBot
{
    [BotAuthentication]
    public class MessagesController : ApiController
    {
        internal static IDialog<SandwichOrder> MakeRootDialog()
        {
            return Chain.From(() => FormDialog.FromForm(SandwichOrder.BuildForm));
        }

        /// <summary>
        /// POST: api/Messages
        /// receive a message from a user and send replies
        /// </summary>
        /// <param name="activity"></param>
        [ResponseType(typeof(void))]
        public virtual async Task<HttpResponseMessage> Post([FromBody] Activity activity)
        {
            if (activity != null)
            {
                // one of these will have an interface and process it
                switch (activity.GetActivityType())
                {
                    case ActivityTypes.Message:
                        await Conversation.SendAsync(activity, MakeRootDialog);
                        break;

                    case ActivityTypes.ConversationUpdate:
                    case ActivityTypes.ContactRelationUpdate:
                    case ActivityTypes.Typing:
                    case ActivityTypes.DeleteUserData:
                    default:
                        Trace.TraceError($"Unknown activity type ignored: {activity.GetActivityType()}");
                        break;
                }
            }
            return new HttpResponseMessage(System.Net.HttpStatusCode.Accepted);
        }
    }
}`

# FIDDLER REQUEST
![image](https://cloud.githubusercontent.com/assets/20675961/17201260/7ab66b9a-54aa-11e6-9be4-ccadb0474b22.png)

# FIDDLER RESPONSE
![image](https://cloud.githubusercontent.com/assets/20675961/17201265/8abf68a2-54aa-11e6-90a7-5d1949ee19e8.png)


# TEST BOT 
![image](https://cloud.githubusercontent.com/assets/20675961/17201271/980406ee-54aa-11e6-827c-50f4cd64befe.png)


Hope all necessary is shared,

**Comment by VishalWaman** [comment] 2016-07-28 04:39
# Something more
![image](https://cloud.githubusercontent.com/assets/20675961/17201361/49ecfee2-54ab-11e6-8681-266008d98fda.png)

**Comment by Thegaram** [comment] 2016-07-28 17:20
You need to make the request to the correct endpoint; in your case to `https://wjbotapp.azurewebsites.net/api/messages` (it might be `Messages` in your case). You also have to specify this URL for you bot registration, under *Messaging endpoint*.

**Comment by VishalWaman** [comment] 2016-07-29 08:40
@Thegaram Thanks it worked now.

Will start digging more :)

**Comment by Thegaram** [comment] 2016-07-29 17:56
@VishalWaman Happy to hear it works! Please close the issue if you judge it's resolved.

**Closed** 2016-08-01 04:31 UTC

**Comment by sunithabist** [comment] 2017-03-10 11:26
I am getting the same error message MethodNotAllowed
The page you are looking for cannot be displayed because an invalid method (HTTP verb) is being used.

**Comment by mahmoudahmedarafa** [comment] 2017-07-14 00:22
@Thegaram My bot isn't replying to messages when I text it after I publishing my app. Could you please help?

Here are my bot things:
Bot Id: mcdonaldsbot
App Id: 6c41c34e-0907-4db9-bdef-3ab73fa363aa
Messaging Endpoint: https://mcdonaldsbot.azurewebsites.net/api/messages

**Comment by jannavarro** [comment] 2017-10-02 12:37
@sunithabist @mahmoudahmedarafa I am getting the same error. Were you able to resolve this? I am already using the `/api/messages` endpoint.
