### ISSUE TITLE
Directline API : 502 Bad Gateway error

### ISSUE THREAD

**Issue by AlavudeenRafiq** [Microsoft/BotBuilder#2207] opened 2017-02-08 06:09 UTC
I am getting the response from the Bot intermittently. While sending the request, I am getting the below error.

POST https://directline.botframework.com/v3/directline/conversations/B56KT664xddDwc9SBbL4md/activities **502 (Bad Gateway)**

I am also getting error in botchat.js. Is something problem with directline api? Can anyone help me to solve this issue?

**Comment by dandriscoll** [comment] 2017-02-08 13:48
Yes, closing as this is a duplicate of https://github.com/Microsoft/BotBuilder/issues/2201

**Closed by dandriscoll** 2017-02-08 13:48 UTC
