### ISSUE TITLE
Not able to cast into (Newtonsoft.Json.Linq.JArray) for builtin.datetimeV2.daterange values

### ISSUE THREAD

**Issue by anuxps** [Microsoft/BotBuilder#3473] opened 2017-09-18 05:40 UTC
## Bot Info 
* Bot handle: 
* App ID: 
* SDK Platform: 
* SDK Version: 
* Active Channels: 
* Deployment Environment: 

## Issue Description

We are using builtin.datetimeV2.daterange values for user query related to Date & time. To parse these values we are using following code:

if (entity.Type == "builtin.datetimeV2.daterange")
{
    foreach (var vals in entity.Resolution.Values)
    {
        if (((**_Newtonsoft.Json.Linq.JArray)vals_**).First.SelectToken("type").ToString() == "daterange")
        {
            start = (DateTime)((Newtonsoft.Json.Linq.JArray)vals).First.SelectToken("start");
            end = (DateTime)((Newtonsoft.Json.Linq.JArray)vals).First.SelectToken("end");
        }
    }
}

While running this code getting error "Specified Cast is not valid". I am not able to figure out how I can cast the object to get the token values of "vals" variable here. 

## Code Example

if (entity.Type == "builtin.datetimeV2.daterange")
{
    foreach (var vals in entity.Resolution.Values)
    {
        if (((**_Newtonsoft.Json.Linq.JArray)vals_**).First.SelectToken("type").ToString() == "daterange")
        {
            start = (DateTime)((Newtonsoft.Json.Linq.JArray)vals).First.SelectToken("start");
            end = (DateTime)((Newtonsoft.Json.Linq.JArray)vals).First.SelectToken("end");
        }
    }
}

## Reproduction Steps
1.
2.
3.

## Expected Behavior

I should able to get different token values from entity.Resolution.Values like:
Type
Start
End
Timex etc

**Comment by JasonSowers** [comment] 2017-09-20 17:26
closing as duplicate of #3406

**Closed by JasonSowers** 2017-09-20 17:26 UTC
Labels: .NET SDK, question
