### ISSUE TITLE
[Question] How to display Hero Card in Angular.js web app?

### ISSUE THREAD

**Issue by RaoVenka** [Microsoft/BotBuilder#3060] opened 2017-06-29 12:45 UTC
I have created hero card in bot framework. In hero card contains Image,Text and Buttons. In Emulator it is visible.

![image](https://user-images.githubusercontent.com/28774238/27687975-883c361e-5cf6-11e7-8b91-073828672be5.png)

Below is the response format in emulator 👍 
```
{
  "type": "message",
  "timestamp": "2017-06-29T12:22:06.929Z",
  "localTimestamp": "2017-06-29T17:52:06+05:30",
  "serviceUrl": "",
  "channelId": "emulator",
  "from": {
    "id": "h4g81m35ii9lf0e86",
    "name": "Bot"
  },
  "conversation": {
    "id": ""
  },
  "recipient": {
    "id": "default-user"
  },
  "membersAdded": [],
  "membersRemoved": [],
  "locale": "en-US",
  "text": "",
  "attachments": [
    {
      "contentType": "application/vnd.microsoft.card.hero",
      "content": {
        "title": "Welcome to Brick n Click Chat bot.",
        "subtitle": " Please select one of the below option.",
        "images": [
          {
            "url": "https://gallery.azure.com/artifact/20151001/sonata-software-ltd.6f10533c-c49e-473c-8e1b-033d97a80cc5.1.0.4/Artifacts/SampleImage/sample1.png"
          }
        ],
        "buttons": [
          {
            "type": "imBack",
            "title": "Search Specific Item",
            "value": "Search Specific Item"
          },
          {
            "type": "imBack",
            "title": "Browse by Item",
            "value": "Browse by Item"
          },
          {
            "type": "imBack",
            "title": "Help",
            "value": "Help"
          }
        ]
      }
    }
  ],
  "entities": [],
  "replyToId": "2l1m3dm108nfjng3",
  "id": "7gcdm307n8c4d7j43"
}
```
Log

Bot Framework Portal I have enabled Direct Line.In UI Part I have added Secret key in Direct Line , i am using angular js , I have checked the code like message is either text and image works fine.  

Below is the sample code : 
```html
<div ng-switch="message.msgtype">
                                                                <div class="message-text" ng-switch-when="text">

                                                                    <p>{{message.text}}</p>
                                                                </div>
                                                                <div ng-switch-when="image" class="image_in_msg-container">
                                                                    <a href="{{message.contentUrl}}" target="_blank">
                                                                        <img ng-src="{{message.contentUrl}}" class="image_in_msg" onload="scroll_adjust()">
                                                                    </a>
                                                                 </div>
```
![image](https://user-images.githubusercontent.com/28774238/27688016-a75b1cf4-5cf6-11e7-9502-aad68b6cb3cd.png)

 i have passed to hero card in html (angular JS) ,But its not working and its not showing any thing . I want to show hero card in direct line using Angular JS. 

Below is the sample code:
```html
<div ng-switch-when="hero" class="card">
                                                                    <img src="{{message.contentUrl}}" alt="Avatar" style="width:100%">
                                                                    <div class="container">
                                                                        <h4><b>{{message.text}}</b></h4>
                                                                        <button type="button" onclick="alert('Hello world!')">Add To Cart!</button>
                                                                       
                                                                    </div>
```
Could you please provide some samples too.

**Comment by nwhitmont** [comment] 2017-06-29 14:32
@RaoVenka for reference, are you using .NET or Node SDK?

**Comment by nwhitmont** [comment] 2017-06-29 18:48
Have you tried embedding the webchat control in your web page?

**Comment by nwhitmont** [comment] 2017-06-29 18:56
duplicate of #2997

**Comment by nwhitmont** [comment] 2017-06-29 19:00
Hi @RaoVenka - It sounds like you are building a custom chat application with the Angular.js framework.  Building custom chat applications is outside the scope of BotBuidler SDK support on GitHub. 

We recommend the following two options:
- Embed the [WebChat](https://github.com/nwhitmont/BotFramework-WebChat) control in your website.
- Use the [Adaptive Cards](http://adaptivecards.io/documentation/#about-overview) spec, and use the [HTML client library](http://adaptivecards.io/documentation/#display-libraries-htmlclient) to render them.

**Closed by nwhitmont** 2017-06-29 19:00 UTC
Labels: Direct Line, question, Rich Cards
