### ISSUE TITLE
[Feature Request] Multiple Facebook page access tokens

### ISSUE THREAD

**Issue by vjirovsky** [Microsoft/BotBuilder#1495] opened 2016-10-23 09:18 UTC
Hello,
I would like to ask (ASAP, how else? :) for functionality of multiple facebook page access tokens for one bot => I would like to use one Microsoft Bot Framework's bot for multiple pages.

Scenario is: Our company has own Facebook page for every big product, but functionality of Bot is same - so that's why I would like to have one bot for all pages (for easier management and development)

Or if you have some workaround (like API for creating bots), please tell me.

Thank you!
Vaclav

**Comment by vjirovsky** [comment] 2016-12-18 20:12
hello, please do you have any update about that?

Thanks

**Comment by tanguydelignieresaccenture** [comment] 2017-01-26 00:44
Same use case here

**Comment by kralmajster** [comment] 2017-01-26 15:19
Same use case here as well... any updates?

**Comment by helbermc** [comment] 2017-01-29 14:46
Hi! Anybody got the answer? I have the same case...

**Comment by tanguydelignieresaccenture** [comment] 2017-02-03 13:49
At the moment the only way I see to achieve this ("one bot for X FB pages") is to create one bot config for each FB page and to set the endpoint of each bot config to the same botbuilder.

**Comment by amitbend** [comment] 2017-02-27 10:01
any update?

**Comment by vovanb** [comment] 2017-03-01 16:54
any update?

**Comment by Vrety** [comment] 2017-03-18 03:37
It seem that one bot can configure for multiple pages. I tested with enter new 'pageId' & 'pagetoken' then resubmit. It work on all my pages.

The problem is UI can not manage , when deauthorize it delete all my pages. Anybody try it?

**Comment by nwhitmont** [comment] 2017-04-18 20:51
@vjirovsky are you using C# or Node SDK for BotBuilder?

**Comment by MrRenaud** [comment] 2017-04-25 07:24
+1 for this feature. Solution from @Vrety sounds good but it would be great to have an appropriate UI to manage this.

**Comment by vjirovsky** [comment] 2017-04-25 07:51
@nwhitmont I am using C#, but this is more about Microsoft's website (administration of bots),isn't?

**Comment by CLOUD9111** [comment] 2017-06-15 07:35
Still no solution for this? If the Facebook's access token expires the bot stops completely until I manually access the bot framework site and enter the new access token by hand, this is hugely uneffecient and time consuming and the only way of solving this is to provide an API for people to update the bot's info or remove the pageid/access token entirely from FB bot requirement, I don't know the purpose of these since any page connecting to the bot will require a unique verify token, complicating things for us is not good Microsoft so please help us with this issue.

**Comment by shobankr** [comment] 2017-09-21 18:29
Any update on this?

**Comment by yochail** [comment] 2017-12-21 09:35
+1

**Comment by SamaraSara** [comment] 2018-01-16 07:00
@vjirovsky The solution you mentioned has been working with me for almost a year. But starting from Yesterday any page I add replaces the one subscribed before it

**Comment by krystiangw** [comment] 2018-01-17 12:53
+1

**Comment by SamaraSara** [comment] 2018-01-18 09:45
This has turned out to be a bug and it's now fixed with no apparent indication of the intention to provide this feature.

**Comment by amitbend** [comment] 2018-02-12 13:09
This feature is much needed, any update?

**Comment by SamaraSara** [comment] 2018-02-12 13:11
Nope. Unfortunately, I am building a Facebook bot without Microsoft Bot Framework in the middle.

**Comment by EricDahlvang** [comment] 2018-02-13 20:47
One possible workaround is to create multiple bot registrations, and point them all to the same hosted bot.  

In .net, you can use a MultiCredentialProvider as explained here: https://github.com/Microsoft/BotBuilder/issues/2258#issuecomment-280506334 

There is an explanation for how to do the same thing with a node bot here: https://www.microsoft.com/developerblog/2017/01/10/creating-a-single-bot-service-to-support-multiple-bot-applications

**Comment by SamaraSara** [comment] 2018-02-15 09:32
Yes...Someone has asked this question in the comments and the answer was yes.

**Comment by kevinport** [comment] 2018-07-16 19:57
Any update on this?

**Comment by EricDahlvang** [comment] 2018-07-16 20:21
Closing, as we are now tracking all Facebook Feature Requests with this issue: https://github.com/Microsoft/BotBuilder/issues/4360

**Closed by EricDahlvang** 2018-07-16 20:21 UTC
Labels: FB Messenger, Feature Request

**Comment by mgbennet** [comment] 2018-07-28 05:39
We just added support for multiple Facebook pages. Give it a try!

**Comment by kevinport** [comment] 2018-07-29 12:51
@mgbennet thank you very much :)

**Comment by bhushanvadgave** [comment] 2018-08-10 04:03
@mgbennet Is there any way bot service to know the FB page from where the messages are coming? Like is there any property in "session" object to refer FB page so that bot can customizations in experience for each page?

**Comment by bhushanvadgave** [comment] 2018-08-16 15:42
@mgbennet Can you help me with the above requirement?

**Comment by mgbennet** [comment] 2018-08-20 20:42
@bhushanvadgave I believe the page's Id should be at session.message.address.bot.id.

**Comment by bhushanvadgave** [comment] 2018-09-04 12:08
Thanks @mgbennet. It helped.

I need one more help:
Is there any way like Facebook channel registration, can multiple skype registrations make use of one bot service?
Or how can we handle multiple bot credentials in BotBuilder NodeJS SDK?

**Comment by Unders0n** [comment] 2019-03-25 16:00
is there ability to automate all this process using api? Question aplies both to MS Bot side (fb channel and pages registration) and to Fb (page creation using api) . Thanks
