### ISSUE TITLE
[Bot Portal] Errors in channel health but code works fine with skype channel

### ISSUE THREAD

**Issue by bhanu2507** [Microsoft/BotBuilder#3075] opened 2017-07-03 11:20 UTC
## System Information (Required)
* SDK Language: Node
* SDK Version: 3.8.4
* Development Environment: Node.JS (runkit.com)

## Issue Description
Using runkit.com (serverless node endpoint) for message endpoint. Code works fine but throwing up errors in Channel health when Skype channel is being use.

## Code Example
```js
var botbuilder = require('botbuilder');

var connector = new botbuilder.ChatConnector({
    appId: <app id>,
    appPassword: <app password>
});

var bot = new botbuilder.UniversalBot(connector, function (session) {
    session.send("You said: %s", session.message.text);
});

exports.endpoint = function (request, response) {
var listener = connector.listen();
        if (request.method == 'POST') {
        var body = '';
        request.on('data', function (data) {
            body += data;
            // Too much POST data, kill the connection!
            // 1e6 === 1 * Math.pow(10, 6) === 1 * 1000000 ~~~ 1MB
            if (body.length > 1e6)
                request.connection.destroy();
        });
        
        request.on('end', function () {
        var post = JSON.parse(body);
        var reqWrapper = {
            body: post,
            headers: request.headers
        };
        var statusCode;
        var resWrapper = {
            status: (code) => {
                statusCode = code;
            },
            end: () => {
                return(null, { statusCode: statusCode });
            }
        };
        listener(reqWrapper, resWrapper);
        });
}
}

```

**Comment by nwhitmont** [comment] 2017-07-03 14:50
@bhanu2507 can you post a screenshot of the errors you are seeing in the Bot Portal channel error/warnings?

**Comment by nwhitmont** [comment] 2017-07-03 17:21
duplicate of https://github.com/Microsoft/BotFramework-WebChat/issues/544

**Comment by nwhitmont** [comment] 2017-07-07 01:02
@bhanu2507 can you post a screenshot of the errors you are seeing in the Bot Portal channel error/warnings?

**Comment by nwhitmont** [comment] 2017-07-07 01:03
@bhanu2507 What is your bot name and bot handle? (as registered in the Bot Portal at https://dev.botframework.com)

**Comment by bhanu2507** [comment] 2017-07-07 07:53
I am very sorry for not able to respond earlier. I, kind of, was able to identify the problem. 

BTW, runkit.com is a great way to write node.js code and get a https endpoint in the development phase.

![ssltest-error](https://user-images.githubusercontent.com/6113406/27948317-102ca74a-6317-11e7-8a31-7fbd661b5d34.png)
![ssltest-error1](https://user-images.githubusercontent.com/6113406/27948318-102fa1c0-6317-11e7-958f-822aa8dca6d1.png)
![ssltest-error2](https://user-images.githubusercontent.com/6113406/27948319-10333dc6-6317-11e7-9064-ed7f6948b30c.png)

See my nodejs code here [https://runkit.com/bhanu2507/595a226cceb62d001265746d](url)

I see that my UniversalBOT connector work with Skype Channel and not webchat....my endpoint logs point to "ERROR: ChatConnector: receive - no security token sent." for webchat.

**Comment by nwhitmont** [comment] 2017-07-07 19:21
@bhanu2507 When I tested your bot on Skype just now, it was not responding.

It looks like there is a syntax error in your bot code (extra ";" char) on L66:35 which is causing your runkit endpoint to fail.
<img width="510" alt="screen shot 2017-07-07 at 12 19 55 pm" src="https://user-images.githubusercontent.com/3075047/27973382-b6e9edd0-630e-11e7-9bcd-3c777400ac13.png">

**Comment by bhanu2507** [comment] 2017-07-09 07:14
@nwhitmont Thanks for that. Actually, I was working on that code and left with that semicolon on by mistake.

I removed the semicolon, the code works now and I still get `ERROR: ChatConnector: receive - no security token sent.` error.

**Below is the request headers from the Test chat window (within the BOTframework portal). No authorization attrib with token.** 

`{ 'x-forwarded-proto': 'https',
  connection: 'close',
  'content-length': '457',
  'content-type': 'application/json; charset=utf-8',
  'x-correlating-operationid': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJvcGVyYXRpb25JRCI6Ikl5ZjRmR04vV25vPV85Wnp3OXJuTnpUSyIsImlzcyI6Imh0dHA6Ly9ib3RmcmFtZXdvcmsuY29tIiwiZXhwIjoxNDk5NTg3ODI5LCJuYmYiOjE0OTk1ODQyMjl9.Ps7C-lY4quQ2Ph6KIuYbCT-0ClVrRQr_uU8leBj4zdI',
  'user-agent': 'BF-DirectLine (Microsoft-BotFramework/3.1 +https://botframework.com/ua)',
  'runkit-rate-limit-remaining': '9991',
  'runkit-request-id': '5fdd9290-0524-4c35-8372-5129aa9569b5',
  host: 'eval4.tonic.private:39382' }`

**Request headers - from a skype messenger channel (there is authorization attrib with the token)**
`{ 'x-forwarded-proto': 'https',
  connection: 'close',
  'content-length': '477',
  'content-type': 'application/json; charset=utf-8',
  'user-agent': 'Microsoft-SkypeBotApi (Microsoft-BotFramework/3.0)',
  authorization: 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImI0eXNPV0l0RDEzaVFmTExlQkZYOWxSUER0ayIsInR5cCI6IkpXVCIsIng1dCI6ImI0eXNPV0l0RDEzaVFmTExlQkZYOWxSUER0ayJ9.eyJzZXJ2aWNldXJsIjoiaHR0cHM6Ly9zbWJhLnRyYWZmaWNtYW5hZ2VyLm5ldC9hcGlzLyIsIm5iZiI6MTQ5OTU4NDEyMiwiZXhwIjoxNDk5NTg3NzIyLCJpc3MiOiJodHRwczovL2FwaS5ib3RmcmFtZXdvcmsuY29tIiwiYXVkIjoiNWNhYmRiM2ItNzUxZi00N2Q2LTkwNjctYWE2NmY5YzUxNzVhIn0.DBSeW-F1SQqE7HCM4ssquW7f5C7EfluC65rn5_K5hOCeVlHHjcBW0KghrymZQkFh8JPvW3PnqEgLeOtC8FFvUt2K6toZsdbVGRlYun3oslwJeKR64NRKsTeK-070Dnvz9TcNdRC0_LJjBqhSdOwwpsyTCOOBPHCSGYNsPZwiR60pwuZSMhI_4d9xIb5l0WkxKYpApHx6zlItJvCbZd5JSvLWKS-J5fSpTpiD6bNWcQvK4iRmZAldD8wx5B5_KlfjpncAFypTPTY627xvd-LLHsteouDfszVT2OcdUMZI-hOr_MHEu6mp5ajKOkHWSuILAW6rKnH5RInJTbqHiItQyg',
  contextid: 'tcid=3841982722027487688, server=CO2SCH020010558',
  'runkit-rate-limit-remaining': '9992',
  'runkit-request-id': '5aac288c-353b-4c6c-90a1-4a55f68bd872',
  host: 'eval3.tonic.private:44954' }`

**Comment by nwhitmont** [comment] 2017-07-10 21:49
@bhanu2507 When I tested your bot in the web chat control in the Bot Portal at https://dev.botframework.com/bots?id=ssltest - Your bot did not respond within the 15s default timeout period. 

In your request headers in the previous message, the host is listed as `host: 'eval4.tonic.private:39382'` - this means your requests did not originate on the Bot Portal as you described.  WebChat reqeusts originating from Bot Portal website will show host as `webchat.botframework.com`.

It's possible that the error is specific to the runkit framework.  Have you tried deploying your bot to Azure App Service or other cloud provider? Did you experience the same errors when your bot is deployed to Azure?

For more information on deploying your bot to cloud providers such as Azure, see: https://docs.microsoft.com/en-us/bot-framework/deploy-bot-github

**Comment by bhanu2507** [comment] 2017-07-11 10:51
@nwhitmont Thanks for the response. But the second header from Skype has similar host details, it works. The same code works fine with Skype Channel. I am getting the response on the Skype but there is "**There was an error completing this request due to an internal channel failure.**" error in the channel health column. Since the code is working for Skype Channel, I don't think runkit environment as anything to do with it.

**Comment by bhanu2507** [comment] 2017-07-11 13:47
I did try running the same code from local machine with ngrok. It works fine. I see the Authentication with Bearer token in the request. It is possible that this may be runkit related.

**Comment by nwhitmont** [comment] 2017-07-11 18:10
@bhanu2507 Thanks for the update. If you are able to run the bot code on your localhost with ngrok, then this indicates the issue is outside of the scope of BotBuilder SDK. Closing as out of scope. If you are able to reproduce the issue via Azure bot deployment, open a new issue.

**Closed by nwhitmont** 2017-07-11 18:10 UTC
Labels: Bot Portal, Node SDK, question
