### ISSUE TITLE
[Azure Bot Service, C#]Can not compile C# 7 syntax

### ISSUE THREAD

**Issue by sposaro** [Microsoft/BotBuilder#3807] opened 2017-11-21 18:29 UTC
I'm not able to compile on Azure, but I can compile locally.
The errors I'm getting are because Azure doesn't understand the new C# syntax.
I'm getting error for inline getters and setters as well as errors for pattern matching in my case statements. 

Is there a way to update my Azure resource?

EX:
private string _name;
public string Name
{
     get => _name; // Error here
     set => _name = value; // Error here
}

switch(myObj)
{
   case Interface1 i : // error here
          break;
   case Interface2 i : // error here
          break;
}

**Comment by msmohan** [comment] 2017-11-21 19:57
@sposaro 
You are using lambda expressions on getters and setters.
getter lambda expression supported since C#6, setter lambda expression is added in C#7
make sure to set your azure app service to c#7 if supported by Azure.

**Comment by EricDahlvang** [comment] 2017-11-21 21:26
Hi @sposaro 

Great question!  

Azure Functions use a very recent version of Roslyn, and C#7 syntax should work without issue.  What is the rest of your code?  

Here is an example:

![image](https://user-images.githubusercontent.com/11055362/33097578-80d1f586-cebf-11e7-9a04-18da4770e85f.png)

**Comment by sposaro** [comment] 2017-11-22 01:17
@EricDahlvang I just sent you an email with an actual code snippet along with the error logs.
However, it clear doesn't not like the new pattern matching syntax or the inline setters.

@msmohan I'm not sure where that setting you speak of is. Am I looking in the correct place.
![image](https://user-images.githubusercontent.com/176527/33104968-ca2f4f7e-cedf-11e7-8b90-d0c0811d43b7.png)

**Comment by msmohan** [comment] 2017-11-27 23:43
@sposaro  Are you getting CS1043 and CS1513 errors, as shown below? 

![image](https://user-images.githubusercontent.com/29078812/33293738-a8b73440-d382-11e7-9d50-0d7dad5e2e5b.png)

**Comment by msmohan** [comment] 2017-11-28 02:21
@EricDahlvang  and I looked into this.

As a workaround you can update following references to its latest version in order to make lambda expressions to work on C#7. 

- Microsoft.CodeDom.Providers.DotNetCompilerPlatform  ver: 2.4.0
- Microsoft.Net.Compilers ver: 1.0.8

This is discussed [here at project Kudu](https://github.com/projectkudu/kudu/issues/2350)

 
We can repro this issue on WEB and LOCAL and we will escalate the issue with Azure Support team.
![image](https://user-images.githubusercontent.com/29078812/33299015-7c095434-d39e-11e7-94c5-0a188f2372e0.png)

**Comment by EricDahlvang** [comment] 2017-12-05 20:34
Closing this, since it is not directly related to the Bot Framework, we have a workaround, the root cause has been found and escalated to the responsible team.

**Closed by EricDahlvang** 2017-12-05 20:34 UTC
Labels: .NET SDK, Azure Bot Service
