### ISSUE TITLE
[Question] Clicking on a PromptDialog.Choice from a previous prompt

### ISSUE THREAD

**Issue by DrWala** [Microsoft/BotBuilder#4544] opened 2018-04-30 05:39 UTC
## Bot Info
* SDK Platform: .NET
* SDK Version: 
* Active Channels: Emulator
* Deployment Environment: Local development with Emulator

## Issue Description
Is it possible for the user to click the button of a previous prompt and be redirected back to that state?

For example: 
Bot: Here are your options: Menu, Promotions, Directions (given in the form of a PromptDialog.Choice)
User: *clicks on menu*
Bot: Starters, Mains, Desserts (given in the form of a PromptDialog.Choice)
User: *clicks on Mains*
Bot: Here are the mains: (list of mains, followed by a PromptDialog.Choice leading somewhere else)
User: *scrolls up, clicks on Promotions*
Alternatively,
User: *scrolls up, clicks on Starters*

I know I can handle dialog switching through scorables, but what if I have a dialog that has 4-5 prompts and the user scrolls up to tap on one of the earlier prompts within the same dialog? Is there a mechanism to handle it?

**Comment by JasonSowers** [comment] 2018-04-30 16:07
Closing as duplicate of https://stackoverflow.com/questions/50095851/clicking-on-a-promptdialog-choice-from-a-previous-prompt

**Closed by JasonSowers** 2018-04-30 16:07 UTC
Labels: .NET SDK, prompts

**Comment by DrWala** [comment] 2018-04-30 16:12
Haha I posted in both places hoping for a fast response :)
