### ISSUE TITLE
[Question] Activity is not marked as Serializable in context.Forward?

### ISSUE THREAD

**Issue by DrWala** [Microsoft/BotBuilder#3848] opened 2017-11-29 18:07 UTC
* SDK Platform: .Net
* SDK Version: 3.12
* Active Channels: NA
* Deployment Environment: Emulator

## Issue Description
This has probably been asked to death, but for some reason context.Forward doesn't let me forward an activity, stating the activity is not marked as serializable. This project is kind of time sensitive, any help would be appreciated

## Code Example
```cs
public virtual async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> result)
        {
            var activity = await result as Activity;
            var varAct = await result;
            if (activity.Type == ActivityTypes.Message)
            {
                        try
                        {
                            await context.Forward(new GetContactDetailsDialog(), FinishedContactDetails, await result, CancellationToken.None);
                        }catch(Exception e)
                        {
                            SendDiagnostic(e);
                        }
            }
            context.Wait(MessageReceivedAsync);
        }
        private async Task FinishedContactDetails(IDialogContext context, IAwaitable<object> result)
        {
            context.Wait(MessageReceivedAsync);
        }
```
I've tried sending `await result`, `activity`, and `varAct` to the context hoping for a different result. I've also tried casting to `IMessageActivity` and `IActivity` to no avail

This is the GetContactDetailsDialog class:

```cs
[Serializable]
    public class GetContactDetailsDialog : IDialog<object>
    {
        private FirebaseChat firebaseChat;
        private Activity userActivity;
        public async Task StartAsync(IDialogContext context)
        {
            //context.PostAsync("StartAsyncCalled");
            context.Wait(this.MessageReceivedAsync);
        }
        public async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> activityReceived)
        {
            userActivity = await activityReceived as Activity;
            firebaseChat = new FirebaseChat()
            {
                activityAccessor = (Activity)context.Activity,
                chatid = context.Activity.Conversation.Id,
                name = context.Activity.From.Name
            };

            PromptDialog.Confirm(
                context,
                DecideToCollectOrNot,
                GlobalConfig.NoAnswerFoundMessage);
            //return Task.CompletedTask;
        }
}
```

I've omitted the handlers for the PromptDialog for simplicity since they probably don't affect this.

The specific error I get is the following:

```cs
Type 'Microsoft.Bot.Connector.Activity' in Assembly 'Microsoft.Bot.Connector, Version=3.12.2.4, Culture=neutral, PublicKeyToken=31bf3856ad364e35' is not marked as serializable.

Trace:    at System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers(RuntimeType type)
   at System.Runtime.Serialization.FormatterServices.<>c__DisplayClass9_0.<GetSerializableMembers>b__0(MemberHolder _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at System.Runtime.Serialization.FormatterServices.GetSerializableMembers(Type type, StreamingContext context)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitMemberInfo()
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Type objectType, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, Header[] inHeaders, __BinaryWriter serWriter, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Header[] headers, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
   at Microsoft.Bot.Builder.Internals.Fibers.FormatterStore`1.Microsoft.Bot.Builder.Internals.Fibers.IStore<T>.Save(T item)
   at Microsoft.Bot.Builder.Internals.Fibers.ErrorResilientStore`1.Microsoft.Bot.Builder.Internals.Fibers.IStore<T>.Save(T item)
   at Microsoft.Bot.Builder.Internals.Fibers.FactoryStore`1.Microsoft.Bot.Builder.Internals.Fibers.IStore<T>.Save(T item)
   at Microsoft.Bot.Builder.Dialogs.Internals.DialogTask.<Microsoft-Bot-Builder-Base-IEventLoop-PollAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.DialogTask.<Microsoft-Bot-Builder-Dialogs-Internals-IDialogStack-Forward>d__17`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.DialogContext.<Microsoft-Bot-Builder-Dialogs-Internals-IDialogStack-Forward>d__18`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at NyxBot.Dialog.RootDialog.<MessageReceivedAsync>d__1.MoveNext() in Z:\path\to\my\file\RootDialog.cs:line 49
```
RootDialog.cs line 49 is `await context.Forward(new GetContactDetailsDialog(), FinishedContactDetails, await result, CancellationToken.None);`

The really silly thing is I got this to work once....without any issues... Am I hallucinating? D:

**Comment by sphanley** [comment] 2017-11-29 20:36
Have you tried forwarding just plain `result`, rather than `await result`? I think your mistake is in making any sort of modification to the incoming parameter.

**Comment by JasonSowers** [comment] 2017-11-29 21:03
I was able to reproduce with the following code, ruling out @sphanley suggestion.  Looking into this today.

```cs
        public virtual async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> result)
        {
            var activity = await result as Activity;
            //var varAct = await result;
            if (activity.Type == ActivityTypes.Message)
            {
                try
                {
                    await context.Forward(new GetContactDetailsDialog(), FinishedContactDetails, activity, CancellationToken.None);
                }
                catch (Exception e)
                {
                    //SendDiagnostic(e);
                }
            }
            context.Wait(MessageReceivedAsync);
        }
```

**Comment by JasonSowers** [comment] 2017-11-29 21:27
@DrWala Can you post the definition of your FireBaseChat object, I think I have a workaround for you.

**Comment by DrWala** [comment] 2017-11-29 22:52
To be honest I don't actually need them serialised, it was only done due to Bot Framework complaining. I'll try the non serialised workaround and update you in 2-3 hours - its not even 7am here haha

**Comment by DrWala** [comment] 2017-11-29 22:55
I used the context activity as I couldn't get the IAwaitable one to work - it was merely a temporary hack. I forgot to change it back...Oops...

**Comment by DrWala** [comment] 2017-11-30 03:01
@JasonSowers Just did a very quick test, the code doesn't throw any errors. Am now running through the full flow in order to see if anything goes wrong in relation to this

**Comment by DrWala** [comment] 2017-11-30 03:12
@JasonSowers So its throwing a null reference exception somewhere in the dialog but its not my code per se. Looking around to find it now

**Comment by DrWala** [comment] 2017-11-30 03:50
@JasonSowers Huh. That's so weird. So I found out why this was happening, but I have no clue why the behaviour is as such.

Here's my contact details class

```
[Serializable]
public class GetContactDetailsDialog : IDialog<object>
{
    private FirebaseChat firebaseChat;
    [NonSerialized]
    private Activity userActivity;
    private string mytext;
    public async Task StartAsync(IDialogContext context)
    {
        //context.PostAsync("StartAsyncCalled");
        context.Wait(this.MessageReceivedAsync);
    }
    public virtual async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> activityReceived)
    {
        try
        {
            userActivity = await activityReceived as Activity;
            mytext = userActivity.Text;
            firebaseChat = new FirebaseChat()
            {
                activityAccessor = (Activity)context.Activity,
                chatid = context.Activity.Conversation.Id,
                name = context.Activity.From.Name
            };

            PromptDialog.Confirm(
                context,
                DecideToCollectOrNot,
                GlobalConfig.NoAnswerFoundMessage);
        }
        catch (Exception e)
        {
            NyxDiagnostics.SendDiagnostic(e);
        }
        
        //return Task.CompletedTask;
    }
    private async Task DecideToCollectOrNot(IDialogContext context, IAwaitable<bool> result)
    {
        bool toCollect = await result;
        if (toCollect)
        {
            var form = new FormDialog<CollectContactDetailsForm>(
                        new CollectContactDetailsForm(),
                        CollectContactDetailsForm.BuildForm,
                        FormOptions.PromptInStart,
                        null);
            context.Call(form, CollectDetailsCallback);
        }
        else
        {
            context.PostAsync("Alright, one of my colleagues will respond to you here soon. Please hang on.");
            await FirebaseChatManager.SendChat(firebaseChat);
            context.Done(this);
        }
    }
    public async Task CollectDetailsCallback(IDialogContext context, IAwaitable<CollectContactDetailsForm> result)
    {
        CollectContactDetailsForm actlResult = await result;
        await FirebaseChatManager.SendContactDetails(firebaseChat, actlResult, userActivity);
        context.Done(this);
    }
}
```

Under `MessageReceivedAsync` I am able to get the activity, however after the prompt dialog and form come back to `CollectDetailsCallback`, `userActivity` is null. I've also tried setting `userActivity` in `firebaseChat`, and previously I marked the activity field as `NonSerializable`. However, myText has no issues. 

I'm guessing due to the unserialized nature of the activity, it won't stick around outside of the scope of the method? That's where the null reference exception was coming from - in `CollectContactDetailsCallback`, `userActivity` was null. Not entirely sure though. I think I may need your serialization magic now 😄

**Comment by JasonSowers** [comment] 2017-12-01 04:22
It's pretty simple actually, just instead of an activity serialize the activity as a string, and when you need the values to put into your firebase object just deserialize it as an activity see below
```cs
    [Serializable]
    public class GetContactDetailsDialog : IDialog<object>
    {
        private FirebaseChat firebaseChat;
        
        private string userActivity;
        private string mytext;
        public async Task StartAsync(IDialogContext context)
        {
            //context.PostAsync("StartAsyncCalled");
            context.Wait(this.MessageReceivedAsync);
        }
        public virtual async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> activityReceived)
        {
            try
            {
                
                var activity = await activityReceived as Activity;
                userActivity = JsonConvert.SerializeObject(activity);

                //use this whever you need an activity and not the JSON, like below
                activity = JsonConvert.DeserializeObject<Activity>(userActivity);

                firebaseChat = new FirebaseChat()
                {
                    activityAccessor = activity,
                    chatid = activity.Conversation.Id,
                    name = activity.From.Name
                };
            }
            catch (Exception e)
            {
//                NyxDiagnostics.SendDiagnostic(e);
            }
            //return Task.CompletedTask;
        }

    }

    public class FirebaseChat
    {
        public Activity activityAccessor { get; set; }

        public string chatid { get; set; }
        public string name { get; set; }
    }

```

**Comment by DrWala** [comment] 2017-12-01 09:52
@JasonSowers ....That is some brilliant stuff right there and I don't know why I didn't think of it.... 😭  Let me go test it out. 

Btw, I have an activityAccessor that returns an activity because I marked activity as non serialisable in the FirebaseChat class - which won't let me use the Activity as a property. I may no longer need to do that!

**Comment by JasonSowers** [comment] 2017-12-01 16:52
@DrWala I forgot to address that piece, but it sounds like you got it figured out 👍 Good Luck!

**Comment by DrWala** [comment] 2017-12-01 16:59
@JasonSowers My hack is in prod right now HAHAH I'll need to find time this week amongst the backlog to test and fix this.

I think it still stands that the context.forward should not mess with the activity's forwarding - not sure if this will result in a fix/update or a different way of moving things around.

**Comment by JasonSowers** [comment] 2017-12-01 17:32
This is actually not a bug at all.  This is the expected behavior of serialization/deserialization.  there is a [great explanation of serialization here](https://stackoverflow.com/questions/5877808/what-is-serializable-and-when-should-i-use-it)  I'm trying to find a good example of "why was my unserialized value null" but have not yet

**Comment by JasonSowers** [comment] 2017-12-01 20:09
Going to close this issue for now, but will reopen if you are still seeing problems

**Closed by JasonSowers** 2017-12-01 20:09 UTC
Labels: .NET SDK, emulator
