### ISSUE TITLE
Weird behaviour using Node ConsoleConnector

### ISSUE THREAD

**Issue by josephktcheung** [Microsoft/BotBuilder#1300] opened 2016-09-22 09:09 UTC
Hi,

I've been using Node `ConsoleConnector` extensively in my mocha test cases like what BotBuilder has in `tests` folder. I have a problem when using `ConsoleConnector` with multiple `session.send` while the last `session.send` involves attachments that `ConsoleConnector` keeps logging `..[image/png]...............................................
   test.png` attachment message

BotBuilder version I'm using: Nodejs version 3.2.3

I modified `examples/hello-ConsoleConnector/app.js` to reproduce this issue.

```
var builder = require('../../core/');

var connector = new builder.ConsoleConnector().listen();
var bot = new builder.UniversalBot(connector);
bot.dialog('/', function (session) {
   session.send('1');
   session.send('2');

   var message = new builder.Message(session)
    .attachments([{
      contentType: 'image/png',
      contentUrl: 'test.png',
    }]);

  session.send(message);
});
```

Once after user input, `..[image/png]...............................................
   test.png` will be print infinitely:

```
hi
1

2

..[image/png]...............................................
   test.png

..[image/png]...............................................
   test.png

..[image/png]...............................................
   test.png

..[image/png]...............................................
   test.png
....
```

If I only have 1 `session.send` with text message before attachment message is sent then it won't print infinitely:

```
var builder = require('../../core/');

var connector = new builder.ConsoleConnector().listen();
var bot = new builder.UniversalBot(connector);
bot.dialog('/', function (session) {
   session.send('1');

   var message = new builder.Message(session)
    .attachments([{
      contentType: 'image/png',
      contentUrl: 'test.png',
    }]);

  session.send(message);
});
```

And I tested using `ChatConnector` with multiple `session.send` text message + 1 attachment message and it will just send 1 image, which is correct. I wonder if this is a bug of `ConsoleConnector`. Thanks.

**Comment by Stevenic** [comment] 2016-10-19 11:45
May be a bug in the connector. I'll try to take a look.

**Comment by EricDahlvang** [comment] 2017-03-29 17:56
I've been unable to reproduce this issue.  I'm closing it for now.  Please feel free to re-open, or comment.

**Closed by EricDahlvang** 2017-03-29 17:56 UTC
Labels: investigate, node.js
