### ISSUE TITLE
Node.JS SDK Carousel Card in Cordova App - Slider not responding the first time, but works okay subsequently.

### ISSUE THREAD

**Issue by mitijain123** [Microsoft/BotBuilder#3707] opened 2017-11-03 03:58 UTC
I am Using NodeJs SDK:
Carousel Card works fine in web and mobile web, but when converted to Cordova App, the Carousel Card is not responding with touch when sliding the first time but sliding with touch works with subsequent carousel cards.

**Comment by JasonSowers** [comment] 2017-11-03 16:29
Closing as duplicate of https://github.com/Microsoft/BotFramework-WebChat/issues/749

**Closed by JasonSowers** 2017-11-03 16:29 UTC
