### ISSUE TITLE
Events not registering in message.type

### ISSUE THREAD

**Issue by khrome83** [Microsoft/BotBuilder#121] opened 2016-04-15 22:33 UTC
According to [StackOverflow](http://stackoverflow.com/questions/36621009/how-to-detect-when-bot-was-added-to-conversation) and [Reference Doc](http://docs.botframework.com/sdkreference/nodejs/interfaces/_botbuilder_d_.imessage.html#language), message.type should return the type of action that is being sent to the server.

The following Node.JS code when using the emulator only logs the type when the type is considered a "message".

```javascript
bot.add('/', new builder.CommandDialog()
    .matches('^set name', builder.DialogAction.beginDialog('/profile'))
    .matches('^quit', builder.DialogAction.endDialog())
    .onDefault(function (session) {
        if (!session.userData.name) {
            session.beginDialog('/profile');
        } else {
            
            console.log(session.message.text); // message entered by user
            console.log(session.message.type); // message type
            session.send('Hello %s!', session.userData.name);
        }       
}));
```

**Comment by khrome83** [comment] 2016-04-15 22:37
According to this [line](https://github.com/Microsoft/BotBuilder/blob/08fa2587b748d4799cc51d3904ee4ea683f38e9d/Node/lib/Session.js#L41) it can ONLY ever be set to "Message".

Is the intent to have this display the type (BotAddedToConversation) or act like a Boolean to dictate that it is a message. 

If it is the second, than something like `message.isMessage = true` would make more sense instead of `message.type = 'Message'`

**Comment by Stevenic** [comment] 2016-04-16 22:28
That's currently by design. The other message types are either notification only or limited to a single reply from the bot. Since you cant have a full dialog with the sender they can't be routed to the dialog system like a normal message. The BotConnectorBot does let you handle these messages you just have to do it differently. Look at the docs for the BotConnectorBot to see how to handle the other message types:

http://docs.botframework.com/builder/node/bots/BotConnectorBot/#connector-message-types

**Comment by Stevenic** [comment] 2016-04-23 01:46
Closing this for now. Please re-open if I didn't answer your question well enough.

**Closed by Stevenic** 2016-04-23 01:46 UTC
Labels: question
