### ISSUE TITLE
[Localization] Intents and Regex dialogs triggers behave differently on (choice) prompts

### ISSUE THREAD

**Issue by rasck** [Microsoft/BotBuilder#3134] opened 2017-07-14 12:30 UTC
## System Information (Required)
* SDK Language: NODE
* SDK Version:  "botbuilder": "^3.8.4",
* Development Environment: LOCALHOST

## Issue Description
I want to be able to use a custom recognizer using localized text so that i can create bot dialog triggers with a localized approach. 

I have created a dialog where a user can choose between two languages. If the user, in the middle of the prompt dialog (within the 3 retries), try to ask/write help. The prompt does not seem to know the recognizer. But if the user instead writes hilfe, the Hilfe dialog will trigger (using regex instead of intents) eventhough we are in the middle of the prompt dialog.

I assume it is because my recognizer has not been registered in the prompt. I also get the following warning:

> BotBuilder:prompt-choice - WARN: Prompt - no intent handler found for Help

I use a lot of prompts and i would like the help intent to work as the hilfe regex trigger. Right now my intents only trigger when a dialog have finished, which is not the behavoir I expected.

## Code Example

```js
const getLocale = session => {
  return session.preferredLocale();
};

const getText = (session, msgId, namespace) => {
  if (!namespace) namespace = ""; // ...bot/locale/{en/da}/index.json will be used.
  return session.localizer.gettext(getLocale(session), msgId, namespace);
};

const sendText = (session, msgId, namespace) => {
  if (!namespace) namespace = ""; // ...bot/locale/{en/da}/index.json will be used.
  session.send(session.localizer.gettext(getLocale(session), msgId, namespace));
};

let bot = new builder.UniversalBot(connector, [
    function(session) {
      // Prompt the user to select their preferred locale
      builder.Prompts.choice(
        session,
        "What's your preferred language?",
        "English|Dansk",
        {
          maxRetries: 3,
          retryPrompt: session.gettext("retry_prompt"),
          listStyle: builder.ListStyle.button
        }
      );
    },
    function(session, results, next) {
      if (!results.response) {
        // exhausted attemps and no selection, start over
        sendText(session, "start_over_prompt");
        return session.endDialog();
      }

      // Update preferred locale
      var locale;
      switch (results.response.entity) {
        case "English":
          locale = "en";
          break;
        case "Dansk":
          locale = "da";
          break;
      }
      session.preferredLocale(locale);
      next();
    }
  ]);
bot.recognizer({
recognize: function(context, done) {
  let locale = context.preferredLocale();
  let intent = { score: 0.0 };
  const getlocalizedText = msgId => {
	return context.localizer.gettext(locale, msgId);
  };
  if (context.message.text) {
	switch (context.message.text.toLowerCase()) {
	  case getlocalizedText("help"):
		intent = { score: 1.0, intent: "Help" };
		break;
	}
  }
  done(null, intent);
}
});

 bot
    .dialog("Help", function(session) {
      session.endDialog(getText(session, "help_dialog"));
    })
    .triggerAction({
      matches: "Help"
    });

 bot
    .dialog("Hilfe", function(session) {
      session.endDialog(getText(session, "help_dialog"));
    })
    .triggerAction({
      matches: /^hilfe/i
    });
```
**The localization:**
```js
bot/locale/en/index.json
{
  "retry_prompt": "Sorry, I did not understand that😕 please try again!",
  "start_over_prompt": "Sorry, we have to start the over 😢",
  "error_prompt": "Oops, something went wrong, we have to start over 😢"
}

bot/locale/dk/index.json
{
  "retry_prompt": "Det forstod jeg desværre ikke 😕 Prøv venligst igen.",
  "start_over_prompt": "Undskyld, men vi bliver nødt til at starte samtalen forfra 😢!",
  "error_prompt": "Øv! Noget gik galt 😢"
}
```
## Steps to Reproduce the Issue
1. Wait for the bot to ask for language preference
2. Instead of choosing a language, write help

## Expected Behavior
I expected the Help dialog to start
## Actual Results
The dialog just give me back the retryPrompt instead. However there is a warning:
> BotBuilder:prompt-choice - WARN: Prompt - no intent handler found for Help

My take on the warnings is that the the intent help has been found but there is no recognizer associated to the prompt.

**Comment by rasck** [comment] 2017-07-16 10:19
I tried applying this [PR](https://github.com/Microsoft/BotBuilder/pull/2859) and it now works as I expect.
I changed
 `var result = context.intent || { score: 0.0, intent: null }; ` to
` var result = { score: 0.0, intent: null };
`
In lib/dialogs/prompt.js line 108

**Comment by tinchomm** [comment] 2017-07-16 16:55
I have the same issue using `beginDialogAction `to trigger the Help dialog.

Changing the line you mention triggers the Help dialog but it still sends the retryPrompt, it is not being cancelled, so I end up with both messages.

**Comment by stevengum97** [comment] 2017-07-17 20:06
@rasck, since the fix is in an upcoming release and you've been able to implement it successfully in your bot I'm going to close this issue. If you have other questions pop up that directly relate to this issue, feel free to reopen this issue.

@tinchomm, can you open a new issue with your code or sample code that reproduces the issue? Thanks.

**Closed by stevengum97** 2017-07-17 20:06 UTC
Labels: localization, Node SDK, prompts, question
