### ISSUE TITLE
[.Net SDK, WebChat] When user clicks the adaptive card... The chat window does not scroll automatically 

### ISSUE THREAD

**Issue by maheshksingh** [Microsoft/BotBuilder#4789] opened 2018-06-25 18:08 UTC
## Bot Info
* SDK Platform: .NET
* Active Channels: web chat 
* Deployment Environment: 

## Issue Description
When the user selects an adaptive card, the chat window does not auto scroll down to show the chat response

Please help

## Expected Behavior
The chat window shud auto scroll top show the chat response

## Actual Results
The user needs to scroll manually to see the response... Sometimes he ends up clicking the button multiple times

**Comment by compulim** [comment] 2018-06-26 18:46
Dupe of https://github.com/Microsoft/BotFramework-WebChat/issues/470.

**Comment by vishwacsena** [comment] 2018-06-26 19:32
Resolving as dupe to the issue in the webchat repo.

**Closed by vishwacsena** 2018-06-26 19:32 UTC
Labels: .NET SDK, Adaptive Cards, WebChat

**Comment by maheshksingh** [comment] 2018-06-27 01:31
Thanks all.. Will try the JS solution...
