### ISSUE TITLE
[Skype] Getting "404 Not Found" when trying to get user data?

### ISSUE THREAD

**Issue by jpieres** [Microsoft/BotBuilder#3853] opened 2017-11-30 11:53 UTC
## Bot Info 
* App ID: bd7f54f2-b994-4115-a194-755fbd5c4b80
* Deployment Environment: localhost

## Issue Description
I am trying to get user data for skype channel as explained in documentation [Get user data](https://docs.microsoft.com/en-us/bot-framework/rest-api/bot-framework-rest-state#get-user-data), but I keep getting "404 Not found" all the time. 

I am able to obtain a token and use it in the header to make a GET request like:

`GET https://smba.trafficmanager.net/apis/v3/botstate/skype/users/[a_user_ID]`

with headers:

Authorization:Bearer <A_TOKEN>
Content-Type:application/json

I made sure the user id I am using is the one I get from a message received in my bot code.

I keep getting "404 Not Found". 

Not sure if I am missing something, a header maybe? I would like also to confirm that the url https://smba.trafficmanager.net/apis/ is the right serviceUrl (I got it from the documentation and also I have seen is the same in the incoming messages to the bot). Any ideas?

**Comment by msmohan** [comment] 2017-11-30 18:34
@jpieres can you please provide more information using the template?


## Bot Info 
* App ID: 
* SDK Platform: 
* SDK Version: 
* Active Channels: 
* Deployment Environment: 

## Issue Description


## Code Example


## Reproduction Steps
1.
2.
3.

## Expected Behavior


## Actual Results

**Comment by jpieres** [comment] 2017-12-05 13:39
yes, no problem, here it is:

## Bot Info 
* App ID: bd7f54f2-b994-4115-a194-755fbd5c4b80
* SDK Platform: Node.js
* SDK Version: 3.8.4
* Active Channels: Skype, MS Teams, Slack, Direct Line, Web Chat, FB Messenger
* Deployment Environment:  ngrok, localhost

## Issue Description
Using the REST API I keep getting "404 Not Found" when trying to get user data.

## Code Example
`GET https://smba.trafficmanager.net/apis/v3/botstate/skype/users/[a_user_ID]`

with headers:

Authorization:Bearer <A_TOKEN>
Content-Type:application/json

## Reproduction Steps
1. Obtain a token with:
Request: `POST https://login.microsoftonline.com/botframework.com/oauth2/v2.0/token` 
with body: 
`grant_type:client_credentials`
`client_id:bd7f54f2-b994-4115-a194-755fbd5c4b80`
`client_secret:SECRET_HERE`
`scope:https://api.botframework.com/.default`

2. Use the token in a GET request:
`GET https://smba.trafficmanager.net`
with headers:
`Authorization: Bearer <TOKEN_HERE>`
`Content-Type:application/json`

## Expected Behavior
I expect to get a 200 HTTP response with BotData object as json.

## Actual Results
I keep getting 404 HTTP response.

**Comment by JasonSowers** [comment] 2017-12-05 23:15
Are you using the default state service? If so it has been deprecated.  Also please upgrade your sdk version to 3.11+ There was [this change](https://blog.botframework.com/2017/05/07/bot-framework-auth-change/) back in July 
  
**The default state service is intended for use in prototyping only**.  Any production level bot should already be using an implementation of a state service rather than the default. 
  
**For more information**  
  
**C#**
[Blog Post With Examples](https://blog.botframework.com/2017/07/18/saving-state-azure-extensions)  
[BotBuilder-Azure Samples C#](https://github.com/Microsoft/BotBuilder-Azure/tree/master/CSharp/Samples)  
  
**Node**
[Blog Post With Examples](https://blog.botframework.com/2017/07/21/saving-state-azure-nodejs/)
[BotBuilder-Azure Samples Node](https://github.com/Microsoft/BotBuilder-Azure/tree/master/Node/examples)

**Comment by jpieres** [comment] 2017-12-11 11:08
Thanks Jason, yes, we are using the default state service and we are in the process of migrating to external persistence (CosmoDB) for state. We are planning to switch but we wanted to be able to check already existing conversations to warn users about their dialogs being reseted. That is why we tried to access the default state service through the API. Never mind, we will upgrade as you recommended, thanks.

**Comment by fanidamj** [comment] 2018-06-22 00:14
Closing the issue assuming it as resolved. Please reopen a new issue if it still persists.

**Closed by fanidamj** 2018-06-22 00:14 UTC
Labels: Node.js SDK, Skype, state service
