### ISSUE TITLE
"default_choice" & "default_error" response from Prompt.js

### ISSUE THREAD

**Issue by piyush-dholariya** [Microsoft/BotBuilder#1893] opened 2016-12-21 04:25 UTC
During communication with chatbot I am getting "default_choice" & "default_error" in response, though I didn't do any code or response texts with this strings, so can you tell me why I am getting this codes?

I want to customize those message or need to handle those messages as per my requirements. so how can I do that?

**Comment by carlosscastro** [comment] 2016-12-21 18:32
Hello,

This is related to localization. Would you mind, if possible, to share your code so we can analyze precisely what the problem is? 

Are you trying to do localization in your bot? If yes, please look at [this example ](https://github.com/Microsoft/BotBuilder/tree/master/Node/examples/basics-localization)as reference.

**Comment by piyush-dholariya** [comment] 2016-12-22 04:08
@carlosscastro  I don't mind to share code, but problem is that its not 1 class or 1 function code, the whole process is passing from 23 files & lots of methods, how can I share all of them here?

let me explain you more, we have defined many builder.Prompts.choice everywhere, so if we are passing any choice gradually one after another, then it works fine, but if its too fast process to enter choice then we are getting this kind of message.

Another scenario is when socket hang up or may be any azure problem occurred then it's throwing default_error message.

**Comment by carlosscastro** [comment] 2016-12-22 19:00
You can compress your code and drag it to the GitHub typing window, it will be attached to the conversation. Then I can take a look and help you diagnose.

default_choice and default_error are text codes, and if those text codes exist in the locale json file, the text shown will automatically honor the json file. I'd highly recommend you take a look at [this example](https://github.com/Microsoft/BotBuilder/tree/master/Node/examples/basics-localization), which has as only purpose to explain localization.

Additionally, [here is the Localization documentation for node js.](https://github.com/Microsoft/BotBuilder/tree/master/Node/examples/basics-localization)

**Comment by piyush-dholariya** [comment] 2016-12-23 12:35
`// This loads the environment variables from the .env file
require('dotenv-extended').load();

var builder = require('botbuilder');
var restify = require('restify');
var Store = require('./store');
var spellService = require('./spell-service');

// Setup Restify Server
var server = restify.createServer();
server.listen(process.env.port || process.env.PORT || 3978, function() {
    console.log('%s listening to %s', server.name, server.url);
});

// Create chat bot
var connector = new builder.ChatConnector({
    appId: 'fsfs-fsfssfsfs',
    appPassword: 'fsfsf'
});
var bot = new builder.UniversalBot(connector);
server.post('/api/messages', connector.listen());

// You can provide your own model by specifing the 'LUIS_MODEL_URL' environment variable
// This Url can be obtained by uploading or creating your model from the LUIS portal: https://www.luis.ai/
const LuisModelUrl = process.env.LUIS_MODEL_URL ||
    'https://api.projectoxford.ai/luis/v2.0/apps/7yf7sfsyf7yf7sf7sfsy7f?subscription-key=sfsfsfsd&verbose=true';

// Main dialog with LUIS
var recognizer = new builder.LuisRecognizer(LuisModelUrl);
var intents = new builder.IntentDialog({ recognizers: [recognizer] })
    .matches('getOrder', [
        function(session, args, next) {
            session.send('Welcome to the Food Bot! we are analyzing your message: \'%s\'', session.message.text);

            var foodNameEntity = builder.EntityRecognizer.findEntity(args.entities, 'foodName');
            var quantityEntity = builder.EntityRecognizer.findEntity(args.entities, 'quantity');
            var sizeEntity = builder.EntityRecognizer.findEntity(args.entities, 'size');

            if (session.dialog) {
                builder.Prompts.text(session, session.dialog.prompt);
            } else if (foodNameEntity && quantityEntity && sizeEntity) {
                var order = {
                    foodName: foodNameEntity.entity,
                    size: sizeEntity.entity,
                    quantity: quantityEntity.entity
                };
                next({ response: order });
            } else {
                builder.Prompts.text(session, 'Please enter your order properly.');
                session.endDialog();
            }
        },
        function(session, results) {
            if (results.response) {
                // Call LUIS and resolve matched entities
                builder.LuisDialog.recognize(session.message.text, LuisModelUrl, function(err, intents, entities) {
                    console.log('intents', intents);
                    console.log('entities', entities);
                    var from = builder.EntityRecognizer.resolveTime(args.entities);
                    if (from) {
                        // User said a valid date.
                        session.endDialog({ response: from });
                    } else if (session.dialogData.maxRetries > 0) {
                        // Re-prompt
                        session.dialogData.maxRetries--;
                        builder.Prompts.text(session, "I'm sorry I didn't get that. What date you arriving?");
                    } else {
                        // Too many retries. We end the dialog with a reason of notCompleted.
                        session.endDialog({ resumed: builder.ResumeReason.notCompleted });
                    }
                });
            } else {
                // User said 'nevermind' or something
                session.endDialog(results);
            }
            // session.send('Please wait, Getting order for you');

            // var order = results.response;

            // var order = 'Your order is: <div>FoodName: ' + order.foodName + ', </div><div>Size: ' + order.size + ', </div><div>Quantity:' + +order.quantity + '</div>';

            // session.send(order);
        },
        function(session, results) {
            session.send('Please confirm order, is it correct (Yes/No)');

            session.send(order);
        }
    ])
    .matches('Help',
        builder.DialogAction.send('Hi! Try asking me things like \'i want 3 medium size pizza\', \'get 5 sandwichwith jumbo size .\' or \'please give me 7 big cold drinks\''))
    .onDefault((session) => {
        session.send('Sorry, I did not understand \'%s\'. Type \'help\' if you need assistance.', session.message.text);
    });

bot.dialog('/', intents);`

**Comment by Stevenic** [comment] 2017-02-23 01:01
Sorry for the delay... We only show the default error messages for either an internal error in the SDK or when an exception is thrown in your code that isn't handled. If you want to customize the case for errors in your code you can add a `try { } catch() { }` to your code to catch the error and then you can return a custom message using `session.error()`

**Comment by Stevenic** [comment] 2017-02-24 21:56
Closing this for now. Please feel free to add further comments.

**Closed by Stevenic** 2017-02-24 21:56 UTC
Labels: answered, node.js
