### ISSUE TITLE
App Insight events from the Bot Framework not coming through

### ISSUE THREAD

**Issue by jakobpn** [Microsoft/BotBuilder#163] opened 2016-04-21 18:44 UTC
I'm curious to learn which events the bot framework will submit to Azure Application Insight so I have added an instrumentation key to my bot registration. It has been there for the past hour, but nothing has showed up yet in the Azure Portal. 

Is there anything I should do on the App Insight end or in the Bot code to make the events trigger through? 

Jakob

**Comment by willportnoy** [comment] 2016-04-21 22:12
Events should show up when you send messages through the production connector - there are no events saved when messages are sent through the emulator.

**Comment by jakobpn** [comment] 2016-04-22 13:55
Good to know that only events from the production connector are being reported to App Insight. Still, the bot has had the key for almost 24 hours now and there is still no events coming through. 

Could this be because I have picked the wrong application type (other) when I registered the app in App Insight?

**Comment by willportnoy** [comment] 2016-04-22 16:38
I'm not sure about your question.

These are the two events that I would expect to be logged based on looking at the code (forgive the approximate C# syntax):

TelemetryClient.TrackDependency("ChannelWebService", "PostMessage", DateTime, TimeSpan, bool)
TelemetryClient.TrackDependency("BotWebService", "PostMessage", DateTime, TimeSpan, bool)

 Are you able to log your own events with that App Insights key?

**Comment by jakobpn** [comment] 2016-04-22 21:50
I just added custom events to my code and they are coming through to the App Insights portal after a few minutes.

**Comment by willportnoy** [comment] 2016-04-27 16:51
I've fixed an issue where the dependency events weren't marked as successful when appropriate - it should be in the next release of the Bot Framework.  I'm not sure this was the cause of your issue.

(I also verified that these events get logged in an AppInsights container when the ApplicationInsightsKey is set to a valid value)

**Closed by willportnoy** 2016-04-27 16:51 UTC
Labels: bug
