### ISSUE TITLE
[WebChat] iframe code is working on Google Chrome , But Facing issue in Firefox and IE

### ISSUE THREAD

**Issue by RaoVenka** [Microsoft/BotBuilder#3181] opened 2017-07-24 12:59 UTC
Hi Team ,
I have created HTML Page , Inside HTML page I have used Iframe Web chat code. 

For example :<iframe width="100%" height="342" src="https://webchat.botframework.com/xxx"></iframe>

In Google chrome Application works fine.
user Types "Hi" meaasge and click on Submit button 

![image](https://user-images.githubusercontent.com/28774238/28524200-1b5bc2de-709d-11e7-91ef-d0e199113c9c.png)

Bot responses the specific query and give below output.

![image](https://user-images.githubusercontent.com/28774238/28524168-fefcba4e-709c-11e7-8263-58071ae1a83d.png)

But the same i tried to run the application in Fire Fox and Internet Explorer , 

User Types "Hi" Message and click on send button ,  it's not allowing to send the messages . I have faced Issue like " t.textInput is null.

![image](https://user-images.githubusercontent.com/28774238/28524286-733bc38c-709d-11e7-9c5f-a91b1709716d.png)

I have checked developer tool (FireFox ) and found below issue.

Please find below screen shot for the same.

![image](https://user-images.githubusercontent.com/28774238/28524005-6fb79390-709c-11e7-8a24-33cfeb90f36a.png)

Could you please provide some samples for how to overcome this above issue in Firefox and internet Explorer.

**Comment by nwhitmont** [comment] 2017-07-24 14:59
@RaoVenka Hello, are you using .NET or Node SDK? For the bot that is having the problem, what is the bot name, not handle, and App ID as registered in the [Bot Portal](https://dev.botframework.com)

**Comment by RaoVenka** [comment] 2017-07-25 10:18
@nwhitmont Hi , I am using .NET,

Below are the details.
Bot Name :  Harmony
Bot handle : Harmony  
APP ID : bffcee4d-86f8-4723-afd2-c8ee73ed5e8e

Could you pls provide steps to reproduce this issue.

**Comment by JasonSowers** [comment] 2017-07-27 15:52
This looks like it may be a problem with the webchat control it self, @danmarshall  any thoughts?

**Comment by RaoVenka** [comment] 2017-08-02 06:46
Any update on this ? Please let me know

**Comment by danmarshall** [comment] 2017-08-02 20:53
Hi @RaoVenka - I cannot repro this in Firefox 54 or IE 11. Can you give me specific browser versions and repro instructions?

**Comment by RaoVenka** [comment] 2017-08-03 06:24
Hi ,

I am using Firefox 54.0.1(32 bit) Version.
![image](https://user-images.githubusercontent.com/28774238/28908641-5737a7f8-7842-11e7-8ffc-0003c49dfee6.png)

Steps : I have opened Firebox web-chat window and tried to post "Hi" message in chat window which is not allowing to post due to below js problem.

Please find below screen shot 
https://user-images.githubusercontent.com/28774238/28524005-6fb79390-709c-11e7-8a24-33cfeb90f36a.png

**Comment by sridharbm1991** [comment] 2017-08-03 13:29
I am also facing same issue with Firefox(54.0.1) and IE(11.0.44)

**Comment by danmarshall** [comment] 2017-08-03 20:19
Thank you @RaoVenka - can you also provide your platform? I still am not able to repro. Can you also send a URL to your bot chat? Or is it happening in the Bot Framework Dev Portal?

**Comment by danmarshall** [comment] 2017-08-03 20:20
Thanks @sridharbm1991 - can you alos provide a link to your bot chat? Or, your bot handle in the Bot Framework Dev Portal.

**Comment by RaoVenka** [comment] 2017-08-04 06:58
Hi,

This issue is not showing in Bot Framework Dev Portal. 

We are using .net code and hosted on cloud platform. Please find below the link
http://sonataharmonysite.azurewebsites.net/#

**Comment by danmarshall** [comment] 2017-08-04 19:35
Hi @RaoVenka , thank you providing the URL to your WebChat. This was crucial in determining your issue. It seems that your WebChat implementation is not visible at the time that you initialize it. WebChat needs to be able to measure itself at the time it is initialized. There are 2 approaches you might take from here:

1. Instead of using "display:none" use "visibility:hidden" or render the WebChat off screen.
2. Do not initialize the WebChat control until the containing DIV is visible.

There is a related issue [here](https://github.com/Microsoft/BotFramework-WebChat/issues/515)

I am going to close this issue here, since it is not a bug with BotBuilder. Please follow up in the WebChat repo.

**Closed by danmarshall** 2017-08-04 19:35 UTC
Labels: .NET SDK, question, WebChat

**Comment by RaoVenka** [comment] 2017-08-10 06:06
Web Chat is not working in internet explorer 11 browser.Could you please help me on this.

Please find below error screenshot.

![image](https://user-images.githubusercontent.com/28774238/29156529-1193778a-7dc0-11e7-9828-7a036f9456ed.png)

**Comment by danmarshall** [comment] 2017-08-10 16:49
Hi @RaoVenka , I took another look, and I believe it is the same issue I described above.
![image](https://user-images.githubusercontent.com/11507384/29181714-06641fd6-7db1-11e7-9336-a27e92fc9e4e.png)

The iframe is inside a display:none container. Please see my message above, thanks!
