### ISSUE TITLE
LUIS bot creations fails with "ajaxExtended Call Failed" error

### ISSUE THREAD

**Issue by SiddharthSinghMOD** [Microsoft/BotBuilder#4894] opened 2018-07-23 19:59 UTC
## Bot Info
* SDK Platform: 
* SDK Version: 
* Active Channels: 
* Deployment Environment: 

## Issue Description
LUIS bot framework fails with error "ajaxExtended Call "

## Reproduction Steps
1.
2.
3.

**Comment by EricDahlvang** [comment] 2018-07-23 20:42
This is a duplicate of https://github.com/Microsoft/BotBuilder/issues/4893 and https://github.com/Microsoft/BotBuilder/issues/4892

**Closed by EricDahlvang** 2018-07-23 20:42 UTC
