### ISSUE TITLE
Reopen issue #2716 [Session Issue] session.userData.lastAccessTime seems not able to searlize inside the setTimeout function

### ISSUE THREAD

**Issue by wtam** [Microsoft/BotBuilder#2733] opened 2017-05-09 16:51 UTC
I've the following code proactively check if any user input has been idle for certain time, then close the bot session but find that the access time storing in the session.userData can't be updated inside setTimeout function.  fI using sessionState.lastAccess will return the same timestamp in the 1st and 2nd call.  And when the setTiemOut timeup, it has 2 copies of the of the lastAccess tiemstamp like what I have in the userData

I believe it's the the problem of the session not able to searailize? or referencing issue!.  But if  I replace the session to  a global variable, "lastAccessTime",  I can solve it but I need its per user session not as a global state.  Please help how to get the session state update inside the setTimeout function.  Please advise.

You can try this simple code and see it yourself
```
var lastAccessTime = null
bot.use({
    botbuilder: function (session, next) {
        session.userData.lastAccess = Date.now()
        lastAccessTime = session.userData.lastAccess
        console.log("userData.lastAccess: ", session.userData.lastAccess, " sessionState.lastAccess: ", session.sessionState.lastAccess, "session.lastSendTime", session.lastSendTime, "lastAccessTime: ", lastAccessTime)
        setTimeout(function () {
            console.log("userData.lastAccess: ", session.userData.lastAccess, " sessionState.lastAccess: ", session.sessionState.lastAccess, "session.lastSendTime", session.lastSendTime)
        }, 15000) // 15 sec
```
-----------------------------------------------
Result:
userData.lastAccess:  1494292505983  sessionState.lastAccess:  1494292505977 session.lastSendTime 1494292505977 lastAccessTime:  1494292505983
userData.lastAccess:  1494292519934  sessionState.lastAccess:  1494292505977 session.lastSendTime 1494292519933 lastAccessTime:  1494292519934

setTimeOut timeup:
userData.lastAccess:  1494292505983  sessionState.lastAccess:  1494292505977 session.lastSendTime 1494292505977 lastAccessTime:  1494292519934
userData.lastAccess:  1494292519934  sessionState.lastAccess:  1494292519933 session.lastSendTime 1494292519933 lastAccessTime:  1494292519934

**Comment by nwhitmont** [comment] 2017-05-09 17:36
duplicate of #2716

**Closed by nwhitmont** 2017-05-09 17:36 UTC
