### ISSUE TITLE
Skype Bot Running Wrong Dialog

### ISSUE THREAD

**Issue by IanBoggs** [Microsoft/BotBuilder#1804] opened 2016-12-06 21:56 UTC
Not sure this is the right place to post this, but I'll try.

I have a bot that have recently updated to V3. Everything is working fine, and the Bot is running my standard StartUpDialog when a message is received, no problem.
            
`if (activity != null)
            {
                switch (activity.GetActivityType())
                {
                    case ActivityTypes.Message:
                        await Conversation.SendAsync(activity, () => new StartUpDialog());
                        break;`

I've created a new dialog within my Bot, RelayBot, which is just a simple relay. I've modified the code as follows

`if (activity != null)
            {
                switch (activity.GetActivityType())
                {
                    case ActivityTypes.Message:
                        await Conversation.SendAsync(activity, () => new RelayBot());
                        break;`

I've republished the Bot to Azure and the test web client works exactly as expected, as does the DirectLine test client I have. However, the Skype bot is still running the original StartUpDialog. I've used remote debugging and it is jumping into the StartUpDialog from Skype, but going into RelayBot from Directline and web chat. I have no idea whats going on.

If I change the StartUpDialog, without changing the above code, that change is reflected when using Skype.

Any ideas would be appreciated.

**Comment by konstlut** [comment] 2016-12-09 14:42
Contacted @IanBoggs and he confirmed the issue got resolved within hours. However I was able to reproduce that and it looks like Azure Bot Service sometimes simply takes longer to deploy the changes.

**Comment by dandriscoll** [comment] 2016-12-21 23:22
Closing the loop on this--

There are a few operations within the Azure Bot Service that can cause code not to be updated, such as refactoring the code into a new folder. This doesn't completely explain why the code was working differently in two channels. However, we don't have a repro for this anymore.

If you see this issue or a similar problem, please open a new issue so it shows up on our radar. Thanks

**Closed by dandriscoll** 2016-12-21 23:22 UTC
