### ISSUE TITLE
Authorization for Microsoft App ID f196f57b-5b97-4653-aaac-d98824071ed1 failed with status code Unauthorized {Bot Framework V 3.5.1}

### ISSUE THREAD

**Issue by AnandChitale** [Microsoft/BotBuilder#2155] opened 2017-02-01 08:24 UTC
Authorization for Microsoft App ID f196f57b-5b97-4653-aaac-d98824071ed1 failed with status code Unauthorized {Bot Framework V 3.5.1}

Updated bot builder sdk to V3.5.1 from V3.1.0

at Microsoft.Bot.Connector.JwtTokenRefresher.d__2.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
 at Microsoft.Bot.Connector.Conversations.d__8.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.Bot.Connector.ConversationsExtensions.d__7.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
 at Synechron.MortgageBot.MessagesController.d__0.MoveNext() in C:\Users\Anand.Chitale\MortgageBot\Synechron.MortgageBot\Synechron.MortgageBot\Controllers\MessagesController.cs:line 54

Note : Works fine with version 3.1.0

**Comment by willportnoy** [comment] 2017-02-01 17:25
Are you using the new Bot Framework Emulator?

https://docs.botframework.com/en-us/tools/bot-framework-emulator/

**Comment by fercom** [comment] 2017-02-01 17:28
@willportnoy my bot throws this error only when it is published but never in the emulator

**Comment by willportnoy** [comment] 2017-02-01 22:05
We usually recommend https://docs.botframework.com/en-us/support/troubleshooting-bot-framework-authentication/ for diagnosing authentication issues.  I'm not sure the upgrade of the SDK is related, though.  If you roll back, does that fix it?

**Comment by AnandChitale** [comment] 2017-02-02 06:26
Installing new bot ramework emulator and upgrading to V3.5.1 resolved the issue.Thanks

**Comment by arnoldpistorius** [comment] 2017-02-02 10:30
Same problem here after upgrading from 3.2.1 to 3.5.1

When I use ngrok on the server to create a 'tunnel' with `ngrok http 80` the authorization issue is gone. But when I'm using the normal server domain, the autorization issue is back. I am testing this live in botframework.com console.

So:

Botframework.com -> ngrok -> Visual Studio Debug = OK
Botframework.com -> ngrok -> iis server = OK
Botframework.com -> iis server = Unauthorized

Looks like the requests **must** come from localhost in the new SDK version????
I was also deploying the bot as a web app in azure, but same errors. It used to work fine with 3.2.1


I've spent over 4 hours today to get this to work, but no luck at all.

**Comment by arnoldpistorius** [comment] 2017-02-02 14:00
We found a solution for our network on this problem @willportnoy @AnandChitale  @fercom .

Came across an old post on serverfault.com http://serverfault.com/questions/416156/isa-or-iis-removing-http-authorization-header-when-published . In our case it was the TMG server which had Authorization Delegation turned off.

I guess Microsoft started to send requests with an authorization header instead of authorization in the post body since yesterday.

When Authorization Delegation is turned off, the TMG server drops the authorization header.

**Comment by fercom** [comment] 2017-02-02 17:08
@arnoldpistorius so, what should we do to correct it?

**Comment by arnoldpistorius** [comment] 2017-02-02 17:19
Nothing, it is just a local network configuration issue. Perhaps you can
put it in the FAQ.

Op 2 feb. 2017 18:09 schreef "fercom" <notifications@github.com>:

**Comment by willportnoy** [comment] 2017-02-09 17:34
@dandriscoll: fyi, @arnoldpistorius found a solution to their 403 issue: https://github.com/Microsoft/BotBuilder/issues/2155#issuecomment-276964664

**Comment by fercom** [comment] 2017-02-09 17:38
@willportnoy but @arnoldpistorius says I cannot do anything to solve it

**Comment by willportnoy** [comment] 2017-02-24 04:47
@ferom if you have that same issue, you can fix the configuration of your local network's TMG server.

**Comment by willportnoy** [comment] 2017-02-28 03:01
I'm going to close this issue for now, but feel free to open a new issue for further discussion.

**Closed by willportnoy** 2017-02-28 03:01 UTC
Labels: C#

**Comment by ZOXEXIVO** [comment] 2017-04-12 20:23
Please, stop closing bugs without resolving! You do it not for resolved bug statistics
I walking here for many linked bugs and they all closed, but issues is present.
V3.5.5

**Comment by arnoldpistorius** [comment] 2017-04-13 10:57
This issue was not a bug, but a local firewall/gateway configuration problem. If you are using TMG in your network, you have to allow authorization delegation in order to make the authorization header work.
