### ISSUE TITLE
web chat

### ISSUE THREAD

**Issue by zxy66481** [Microsoft/BotBuilder#3671] opened 2017-10-26 07:35 UTC
Custom Web chat How to link with a robot deployed to Microsoft Azure

**Comment by FranciscoPonceGomez** [comment] 2017-10-26 15:24
Hi @zxy66481,

This looks like a duplicate of your previous question. I will close this one and answer you on the previous thread.

Francisco

**Closed by FranciscoPonceGomez** 2017-10-26 15:24 UTC
