### ISSUE TITLE
How to request undelivered messages?

### ISSUE THREAD

**Issue by Mikhail42** [Microsoft/BotBuilder#4683] opened 2018-05-31 15:51 UTC
## Bot Info
* SDK Platform: REST API
* SDK Version: v3
* Active Channels: Skype
* Deployment Environment: non Azure web server with valid sertificate

## Issue Description
How to request undelivered messages in BotFramework?

## Code Example
I use simple Echo App. 

## Reproduction Steps
1. Create Echo App
2. Run the app. Sure that you can send message to your bot from Skype
3. Stop app. Send message and wait more than 10 seconds.
4. Run app again. 
5. Sure that you again receipt new messages, but don't get a message that you send while app was been stopped.

#4682 # Expected Behavior
1) On messaging endpoint url should be delivered a message OR 
2) There should be a way to request the undelivered message.

## Actual Results
![1](https://user-images.githubusercontent.com/12397699/40792839-8f80c528-6503-11e8-91b8-e576e1135249.png)

**Comment by JasonSowers** [comment] 2018-05-31 16:19
Duplicate of https://stackoverflow.com/questions/50627928/how-to-request-undelivered-messages-in-botframework

**Closed** 2018-05-31 18:45 UTC
Labels: Skype
