### ISSUE TITLE
[Question] Microsoft.Bot.Connector.CardAction.set_Value() Throwing Exception

### ISSUE THREAD

**Issue by operacha** [Microsoft/BotBuilder#2889] opened 2017-06-05 15:51 UTC
## System Information (Required)
* SDK Language:  .NET/C#
* SDK Version: 3.8.1.0
* Development Environment: LOCALHOST

## Issue Description
Currently using AuthBot library (https://github.com/MicrosoftDX/AuthBot) for Azure Active Directory authentication with BotBuilder. When I use the sample provided in the GitHub repo for AuthBot the program compiles and works as expected but when I use the same piece of code in the bot I am creating I get an exception from `Microsoft.Bot.Connector.CardAction.set_Value()`.

## Code Example

Below is the code snippet that is causing the issue. Issue seems to occur at `var message = await result;`
```cs
public virtual async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> item)
{
    var message = await item;

    if (message.Text == "logon")
    {
         //endpoint v1
         if (string.IsNullOrEmpty(await context.GetAccessToken(ConfigurationManager.AppSettings["ActiveDirectory.ResourceId"])))
         {
               await context.Forward(new AzureAuthDialog(ConfigurationManager.AppSettings["ActiveDirectory.ResourceId"]), this.ResumeAfterAuth, message, CancellationToken.None);
          }
         else
         {
               context.Wait(MessageReceivedAsync);
         }
     }
}
        
 private async Task ResumeAfterAuth(IDialogContext context, IAwaitable<string> result)
 {
     var message = await result;

     await context.PostAsync(message);
     context.Wait(MessageReceivedAsync);
}
```

## Steps to Reproduce
1. Run bot using localhost in bot emulator
2. Send message 'logon'
3. Exception is thrown

## Expected Behavior
After sending 'logon' the expected behaviour is to get a response from bot with instructions to authenticate:

Expected response in chat:
![image](https://cloud.githubusercontent.com/assets/6385030/26791353/ad96d5e2-49cb-11e7-8a59-ca9b5cb59035.png)

## Actual Results
What actually happens is in the chat a response is sent "Exception: Stack is empty" with an exception thrown in Visual Studio

Chatbot reponse:
![image](https://cloud.githubusercontent.com/assets/6385030/26791281/6d483b34-49cb-11e7-9354-081adb9d0dc0.png)

Visual Studio exception from debugger:
![image](https://cloud.githubusercontent.com/assets/6385030/26791297/7b66db1c-49cb-11e7-9ca5-072224638c6d.png)

**Comment by JasonSowers** [comment] 2017-06-05 16:35
@operacha Hello, could you please post the code where you are constructing the adaptive card?

**Comment by operacha** [comment] 2017-06-05 17:08
@JasonSowers 

Would this be what you're looking for?

```
private List<CardAction> GetCardActions(string authenticationUrl, string actionType)
        {
            List<CardAction> cardButtons = new List<CardAction>();
            CardAction plButton = new CardAction()
            {
                Value = authenticationUrl,
                Type = actionType,
                Title = "Authentication Required"
            };
            cardButtons.Add(plButton);
            return cardButtons;
        }
```

**Comment by JasonSowers** [comment] 2017-06-05 17:25
@operacha also what channel are you using?

**Comment by msmohan** [comment] 2017-06-05 17:25
I have tried to repro the issue., but it is working fine with me. can you check the version you are using?

![image](https://cloud.githubusercontent.com/assets/29078812/26795057/00ce7636-49d9-11e7-94c3-1fed155908db.png)

![image](https://cloud.githubusercontent.com/assets/29078812/26795097/28cc2cf0-49d9-11e7-8463-370b67499d3b.png)

![image](https://cloud.githubusercontent.com/assets/29078812/26795117/3a22211c-49d9-11e7-866a-086328303c8e.png)

**Comment by msmohan** [comment] 2017-06-05 17:28
Are you on VPN?

**Comment by operacha** [comment] 2017-06-05 17:29
@msmohan I'm running version 3.6.5-alpha for authbot

@JasonSowers I'm using localhost:44353

**Comment by JasonSowers** [comment] 2017-06-05 17:35
I'm looking more for something like this method in the Authbot

```cs
        protected virtual Task PromptToLogin(IDialogContext context, IMessageActivity msg, string authenticationUrl)
        {
            Attachment plAttachment = null;
            switch (msg.ChannelId)
            {
                case "skypeforbusiness":
                    return context.PostAsync(this.prompt + "[Click here](" + authenticationUrl + ")");
                case "emulator":
                case "skype":
                    {
                        SigninCard plCard = new SigninCard(this.prompt, GetCardActions(authenticationUrl, "signin"));
                        plAttachment = plCard.ToAttachment();
                        break;
                    }
                // Teams does not yet support signin cards
                case "msteams":
                    {
                        ThumbnailCard plCard = new ThumbnailCard()
                        {
                            Title = this.prompt,
                            Subtitle = "",
                            Images = new List<CardImage>(),
                            Buttons = GetCardActions(authenticationUrl, "openUrl")
                        };
                        plAttachment = plCard.ToAttachment();
                        break;
                    }
                default:
                    {
                        SigninCard plCard = new SigninCard(this.prompt, GetCardActions(authenticationUrl, "signin"));
                        plAttachment = plCard.ToAttachment();
                        break;
                    }
//                    return context.PostAsync(this.prompt + "[Click here](" + authenticationUrl + ")");
            }

            IMessageActivity response = context.MakeMessage();
            response.Recipient = msg.From;
            response.Type = "message";

            response.Attachments = new List<Attachment>();
            response.Attachments.Add(plAttachment);

            return context.PostAsync(response);
        }
```

**Comment by msmohan** [comment] 2017-06-05 17:39
I have two suggestions.,
1. Check local AAD admin if there is any restrictions on ADFS queries., 
2. I understand, it is not working for newer version., there is a high possibility that some of the older functions/methods changed. Let us know if you need help in identifying.

**Comment by msmohan** [comment] 2017-06-05 18:08
After reviewing all., 
This is not BotBuilder framework related issue.
It should be filed under AuthBot, https://github.com/MicrosoftDX/AuthBot/issues


![image](https://cloud.githubusercontent.com/assets/29078812/26796710/4b087278-49df-11e7-8f43-1bd1e0ca8f1e.png)

**Comment by msmohan** [comment] 2017-06-05 18:30
Closing the issue under bot-builder.

**Closed by msmohan** 2017-06-05 18:30 UTC
Labels: .NET SDK, Auth

**Comment by operacha** [comment] 2017-06-06 16:33
Issue was due to AuthBot and NOT BotBuilder framework. After updating the versions and references within the code the issue was resolved.

**Comment by msmohan** [comment] 2017-06-07 01:27
@operacha Thanks for sharing the source code with me, that enabled me to help you to identify the root cause.
