### ISSUE TITLE
[Question] Cannot start a dialog consecutively twice?

### ISSUE THREAD

**Issue by austinhuang0131** [Microsoft/BotBuilder#4109] opened 2018-01-28 19:25 UTC
I know the title is terrible.

## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.13.1
* Deployment Environment: Heroku + Azure Bot Service

## Issue Description
In [my bot](https://github.com/austinhuang0131/metagon), some dialogs bind to a command. Now, if I try to trigger the dialog twice, I'll be able to trigger it first, but not the second time.

## Code Example
```js
bot.dialog("a", (session) => {session.endDialog("ok")}).triggerAction({matches: /a/gi});
bot.dialog("b", [...]).triggerAction({matches: /b/gi});
bot.dialog("/", (session) => {session.endDialog("not ok")}); // Default dialog, obviously
```

## Reproduction Steps
1. Input `a`.
2. You get "ok".
3. Input `a` again.

## Expected Behavior
You get "ok" which is written in dialog `a`.

## Actual Results
You get "not ok" which is written in dialog `/` instead.

**Comment by nodeomega** [comment] 2018-01-31 02:15
When a dialog runs and completes, it returns to the parent.  As that dialog has already executed, it goes on to the default if nothing else matches it.  I believe this is by design.

What you could try to workaround this and get your desired functionality is performing a test on the match inside the default method of the dialog you're trying to trigger multiple times in a row,

Example:

`bot.dialog("a", (session) => {session.endDialog("ok")}).triggerAction({matches: /a/gi});
bot.dialog("b", [...]).triggerAction({matches: /b/gi});
bot.dialog("/", (session) => {
    if (/a/gi.test(session.message.text)) {
        session.beginDialog("a");
        return; // prevents the rest of the default from processing.
    }
    if (/b/gi.test(session.message.text)) {
        session.beginDialog("b");
        return; // prevents the rest of the default from processing.
    }
    session.endDialog("not ok")
}); // Default dialog, obviously`

You'll want to be careful if there are choices that could trigger multiple dialogs, so you'll want to make sure the trigger conditions are unique and won't match another by accident for this to work.

**Comment by austinhuang0131** [comment] 2018-01-31 02:16
Triggers are unique. I think this can be a workaround. Thanks @nodeomega !

**Comment by microsoftly** [comment] 2018-02-01 20:43
you can write a test to automate checking this (and imo is faster and easier than using the emulator) with mocha/chai or ava using the [BotTester framework](github.com/microsoftly/BotTester)

``` javascript
const { BotTester, TestConnector } = require('bot-tester');
const FunctionToInitializeYourBotWithConnector = require('wherever it lives')

describe('Bot Test', () => {
    it('Dialog can be started consecutively twice', () => {
        const bot = FunctionToInitializeYourBotWithConnector(TestConnector);

        return new BotTester(bot)
            .sendMessageToBot('a', 'ok')
            .sendMessageToBot('a', 'ok')
            .runTest();
    });
});
```

you can also inspect session state and run expectations against it to ensure you're where you expect/want in the dialog stack.

**Comment by fanidamj** [comment] 2018-06-22 00:17
Closing the issue assuming it as resolved. Please reopen a new issue if it still persists.

**Closed by fanidamj** 2018-06-22 00:17 UTC
Labels: Node.js SDK, dialogs
