### ISSUE TITLE
Combining Prompts and channels native sendMessage

### ISSUE THREAD

**Issue by mikkhait** [Microsoft/BotBuilder#236] opened 2016-05-06 20:23 UTC
I'm trying to find a clean way of combining `builder.Prompts.choice` (and other) for an SMS channel, with enriched custom messages provided by Facebook & Telegram.

Is there any other way besides implementing those prompts separately for each channel?

And while we are on the topic, is there a way to receive `channel` back from BotConnects, so I can actually implement that?

```
function (session) {
    if (channel === 'facebook') {
      messageData = {
        "attachment": {
          "type": "template",
          "payload": {
            "template_type": "generic",
            "elements": {
              "title": "What can I help you with today?",
              "buttons": [{
                  "title": "Auto Insurance"
                }, {
                  "title"
                  "Home Insurance"
                }
              }
            ]
          }
        }
      };
      session.sendMessage(messageData)
    } else {
      builder.Prompts.choice(session, "Hi" + session.userData.name + ", what can I help you with?", ['Auto Insurance', 'Home Insurance'])
    }
```

**Comment by Stevenic** [comment] 2016-05-08 17:15
So a couple of things...
* We're planning to add Button support directly to `Prompts.choice()`. There will be a new `ListStyle` to control this but the default will be to automatically pick the style based on the channel and number of choices passed in.
* Currently you can only pass text in for Prompts prompt. We'll be expanding this to let you pass a full message object so you'll be able to fully customize the message sent for a prompt if you'd like.

Both of those changes should be coming soon (possibly this week.) 

I didn't quite follow the second part of your question about the channels. Could you elaborate?

**Comment by Stevenic** [comment] 2016-05-08 17:19
By the way here's a button version of the choice() prompt I built as a test the other day. Hopefully that helps until I get the other changes in.

```
    bot.add('/buttonChoice', function (session, args) {
        function prompt(reprompt) {
            // Map choices into actions
            var a = { actions: [] };
            for (var i = 0; i < session.dialogData.enumValues.length; i++) {
                var action = session.dialogData.enumValues[i];
                a.actions.push({ title: action, message: action });
            }
            var p = reprompt ? "I'm sorry I didn't understand. " : '';
            p += session.dialogData.prompt;
            var msg = new builder.Message()
                .setText(session, p)
                .addAttachment(a);
            session.send(msg);
        }
        
        if (args) {
            session.dialogData.prompt = args.prompt;
            session.dialogData.maxRetries = 2;
            var choices = args.choices;
            session.dialogData.enumValues = builder.EntityRecognizer.expandChoices(choices);
            prompt(false);
        } else {
            var match = builder.EntityRecognizer.findBestMatch(session.dialogData.enumValues, session.message.text);
            if (match || --session.dialogData.maxRetries == 0) {
                session.endDialog({ response: match });
            } else {
                prompt(true);
            }
        }
    });

    function buttonChoice(session, prompt, choices) {
        session.beginDialog('/buttonChoice', { prompt: prompt, choices: choices });
    }
```

**Comment by matheus208** [comment] 2016-05-09 15:08
@Stevenic is there a way of building a  complete Structured Message (with images, and multiple callbacks) with the current code?

Is there any plans on when the Prompts will include the complete buttons/payload structure for Facebook?

Cheers!

**Comment by Stevenic** [comment] 2016-05-10 00:31
I'm actually working on updating the built-in prompts now. If you look at my latest check-ins you'll see that I just updated all of docs & interfaces related to actions (button) support. I expect to be done with that this week and will hopefully publish an updated version of the library before Friday. Possibly as soon as tomorrow.

I'm not completely sure what you mean by complete Structured Message. I just updated the documentation to reflect the schema changes around building rich cards with buttons but that's just documentation. If you look at the [Attachment Docs](http://docs.botframework.com/connector/message-actions) for the Bot Connector you'll find examples of building rich cards which you can already do using Bot Builder. Just modify my sample code above.

**Comment by JpEncausse** [comment] 2016-05-10 18:06
Very interested in a Choice demo using title/text/images for choices (like in Viv demo)

**Comment by Stevenic** [comment] 2016-05-10 19:35
Haven't seen the demo yet. It's on my todo list. I'll try to watch the demo and get back to you.

**Comment by Stevenic** [comment] 2016-05-11 19:43
@JpEncausse finally watched the demo and I'm planning to add support for passing images & such to choices which should cover that need.

**Comment by Stevenic** [comment] 2016-05-12 05:49
I just published v0.10.0 with support for passing rich messages with images or any other attachments you'd like as a prompt. Not super well tested yet so please let me know if you have any issues.

**Comment by JpEncausse** [comment] 2016-05-13 14:46
Can you provide a NodeJS sample doing a Promps with 3 cards for choices ?

I can display Bendre in a Card (http://docs.botframework.com/connector/message-actions/) but I do not understand how to display 3 cards ?

**Comment by Stevenic** [comment] 2016-05-13 14:49
Let me work on that...

**Comment by Stevenic** [comment] 2016-05-13 15:15
Haven't tested this yet but this is how you'd do that:

```
    bot.add('/tests/multi-card-choice', [
        function (session) {
            var msg = new builder.Message()
                .addAttachment({ 
                    text: 'W Hotel',
                    thumbnailUrl: 'http://www.dreamsteam.it/images/files/14072009155608842433.jpg',
                    actions: [ { title: 'select', message: 'W Hotel' }]
                 })
                .addAttachment({ 
                    text: 'Marriot',
                    thumbnailUrl: 'http://www.foreign-independent-tours.com/hotelimages/Cairo,%20Egypt%20-%20Cairo%20Marriott%20Hotel1.jpg',
                    actions: [ { title: 'select', message: 'Marriot' }]
                 })
                .addAttachment({ 
                    text: 'Holliday Inn',
                    thumbnailUrl: 'http://www.destination360.com/contents/pictures/hotels/holiday-inn-anaheim.jpg',
                    actions: [ { title: 'select', message: 'Holliday Inn' }]
                 });
            builder.Prompts.choice(session, msg, "W Hotel|Marriot|Holliday Inn");
        },
        function (session, results) {
            if (results.response) {
                session.endDialog("You chose '%s'", results.response.entity);
            } else {
                session.endDialog("Nothing selected");
            }
        }
    ]);
```

**Comment by Winangel** [comment] 2016-05-13 17:34
This doesn't work for me. As soon as I use a Message with an attachment things break...

**Comment by Stevenic** [comment] 2016-05-14 06:38
I'll try and debug it this weekend. To be honest this is new functionality that hasn't been super well tested. On the plus side I have some ideas how to simplify this scenario.

**Comment by JpEncausse** [comment] 2016-05-16 15:00
Same as @Winangel I see choices but not attachement cards before

**Comment by Stevenic** [comment] 2016-05-18 04:34
I've found the issue and a fix is coming shortly

**Comment by Stevenic** [comment] 2016-05-20 01:48
I just published v0.11.0 which should fix that issue. Might try again.

**Comment by JpEncausse** [comment] 2016-05-20 10:37
Thanks,
- On Emulator a message sent wih title / text / thumbnail works now
- On Emulator, Skype, Slack

A Prompt like you descripe here:
https://github.com/Microsoft/BotBuilder/issues/236#issuecomment-219073308

Only display choices without images.
For my demo I'll try a workaroud with 3 messages + a prompt

**Comment by Stevenic** [comment] 2016-05-20 15:49
I'm going to look into this issue today.

**Comment by Stevenic** [comment] 2016-06-01 05:29
I just checked in a new [demo-facebook](https://github.com/Microsoft/BotBuilder/tree/master/Node/examples/demo-facebook) example which shows how to render a carousel of bubbles as the options for a `choice()` prompt. This could probably be made a little more elegant but it should get you started and supports multiple actions (buttons) for each card.

**Closed** 2016-06-01 08:07 UTC
Labels: question

**Comment by Sasanka93** [comment] 2017-01-06 10:02
Hey stevenic , I've a problem in choice prompt, will you please answer it. The problem is:

Bot prompts user to select from 3 choices. But if user do not select any of these choices and want to enter manually a text, it causing error prompting user to choose from the options only. How to override this situation
