### ISSUE TITLE
[Feature Request] Allow for builder.Prompts.choices to have a separate value and label.

### ISSUE THREAD

**Issue by zephinzer** [Microsoft/BotBuilder#1625] opened 2016-11-10 03:30 UTC
Current behaviour of function takes the label as the value, would be good if we can pass values down into the `result` instead of the label. See below example:

```
var builder = require('botbuilder');
builder.Prompts.choices('select one', {
  'choice 1': 1,
  'choice 2': 2,
  'choice 3': 3
});

/** assume user selects 'choice 1' **/

/** current behaviour **/
(session, result, next) => {
  console.log(result.response.entity); // 'choice 1'
}
/** suggested behaviour **/
(session, result, next) => {
  console.log(result.response.entity); // 1
}
```

**Comment by chrimc62** [comment] 2016-11-28 00:40
Adding @Stevenic and @maxpert to comment.

**Comment by Stevenic** [comment] 2016-12-12 09:47
I agree... It should also take a list of synonyms. Unfortunately I can't easily change the signature of the current version.  I've been kicking around letting you pass a function which can return a richer set of values, including dynamic values.

**Comment by gilesbutler** [comment] 2017-01-03 10:03
I think we definitely need to be able to pass a richer set of values. It makes more sense what @zephinzer is saying but I understand if that's not easy to implement. It's a lot easier to understand what is going on though if we can label the choice one thing and have it's response trigger a new dialog without having to use if/else statements

**Comment by nwhitmont** [comment] 2017-04-21 17:23
Duplicate of #2264

**Closed by nwhitmont** 2017-04-21 17:23 UTC
Labels: enhancement, Node SDK
