### ISSUE TITLE
Bot Framework Channel Emulator crashing on sending attachment

### ISSUE THREAD

**Issue by letmaik** [Microsoft/BotBuilder#897] opened 2016-08-04 10:42 UTC
What I want to do is simple:
```js
builder.Prompts.attachment(session, 'Please send me a JSON file')
```
When I use the emulator to send the JSON file (I use the lower left image icon) then nothing happens. If I try to do anything else, like sending another message, it just crashes horribly.

Does the emulator not support sending non-image files?

**Comment by willportnoy** [comment] 2016-08-04 16:41
I can reproduce this issue, where a NullReferenceException is thrown if the Attachment.ContentType is null.  It looks like a bug.

**Comment by willportnoy** [comment] 2016-08-13 00:00
I've checked in a fix for this issue, and I believe a newer version of the emulator was released today.

I'm going to close this issue, but feel free to open a new issue for further discussion.

**Closed by willportnoy** 2016-08-13 00:00 UTC
Labels: bug

**Comment by letmaik** [comment] 2016-08-17 09:08
I can confirm that this is fixed. Thanks! :)
