### ISSUE TITLE
Unable to generate new password after creating Bot channel registration / WebApp bot

### ISSUE THREAD

**Issue by aabbgithub** [Microsoft/BotBuilder#3940] opened 2017-12-16 14:00 UTC
* App ID: 16de5571-ad42-40f1-953c-a0543b585481
* SDK Platform: .NET
* SDK Version: 4.7
* Active Channels: Web
* Deployment Environment: AzureBotService

## Issue Description
Hi, I created a Bot Channel Registration, clicked on settings, and then on Microsoft App ID manage  (link). Then clicked Generate new password and I'm getting the following exception:

## Expected Behavior
I want to be able to generate a new password

## Actual Results
Unable to generate a new password

**Comment by srozga** [comment] 2017-12-17 02:22
+1, Same as #3938

**Comment by khawarashraf** [comment] 2017-12-17 05:17
I'm getting the same error on newly created Bot Channel Registration. It does work fine on existing applications.

**Comment by EricDahlvang** [comment] 2017-12-18 02:16
Thanks for reporting this to us.  This underlying issue has been identified and is being addressed by the team. We apologize for the inconvenience.  Closing as duplicate of https://github.com/Microsoft/BotBuilder/issues/3938

**Closed by EricDahlvang** 2017-12-18 02:16 UTC
