### ISSUE TITLE
[Question] WebSocket on .NET Core with Linux Docker image?

### ISSUE THREAD

**Issue by NicolasHumann** [Microsoft/BotBuilder#3290] opened 2017-08-09 10:13 UTC
## System Information
* SDK Language: .NET Core 1.1.2
* Development Environment: Docker - Linux container

## Issue Description
Hi, I connect to the direcline channel with websocket. My client is build with .net core and running in Linux container.
I have the following issue:
System.Net.WebSockets.WebSocketException: Unable to connect to the remote server ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.

The same code works well when it runs on windows.

Thanks for your help !

## Code Example

 System.Net.WebSockets.ClientWebSocket client = new System.Net.WebSockets.ClientWebSocket();
await client.ConnectAsync(new Uri("wss://directline.botframework.com/v3/directline/conversations/XXXX"));

## Actual Results
System.Net.WebSockets.WebSocketException: Unable to connect to the remote server ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ReadFrameCallback(AsyncProtocolRequest asyncRequest)

**Comment by JasonSowers** [comment] 2017-08-09 15:11
Duplicate of https://stackoverflow.com/questions/45588708/websocket-client-error-on-net-core-with-linux-docker-image-with-botframework-di

**Comment by nwhitmont** [comment] 2017-08-09 17:16
@NicolasHumann Currently, BotBuilder SDK is not officially supported in .NET Core.

Relates to https://github.com/Microsoft/BotBuilder/issues/572

**Closed by nwhitmont** 2017-08-09 17:16 UTC
Labels: .NET SDK, question
