### ISSUE TITLE
[Facebook] why am I getting message "already in use by another bot"

### ISSUE THREAD

**Issue by madukapai** [Microsoft/BotBuilder#3893] opened 2017-12-08 07:09 UTC
## Bot Info 
* App ID: 3ce561e7-dff8-47d9-b926-edca552e6e4a
* SDK Platform: .NET
* SDK Version: 
* Active Channels: Facebook
* Deployment Environment: Auzure Bot Service

## Issue Description
hi Team
I create a Bot Service on Azure
When I set up a Facebook Channel, I got this error message
![image](https://user-images.githubusercontent.com/13964722/33754884-503bc808-dc29-11e7-9cc0-cf878d439d03.png)

I'm sure this Facebook Page 125143697558679 is not connected to any Bot
Can help solve this problem?

**Comment by JasonSowers** [comment] 2017-12-08 18:01
Thanks for reporting, let us look into this for you.

**Comment by JasonSowers** [comment] 2017-12-08 18:29
I have confirmed Facebook Page 125143697558679 is already registered to another bot.  This is the reason you are seeing this error.  The bot it is registered to has a very similar name to yours.  I will reach out via the email address registered to that bot.

**Comment by madukapai** [comment] 2017-12-09 01:57
Thank you for your assistance
The Facebook page has 150,000 people tracked and contacted more than 1 million people
Connect bot framework is very important to my company

**Comment by JasonSowers** [comment] 2017-12-21 17:18
@madukapai Did you resolve this?  I never heard back from the email I sent.

**Comment by madukapai** [comment] 2017-12-22 07:05
@JasonSowers Not resolved, so can I try to connect this page id now?

**Comment by JasonSowers** [comment] 2017-12-22 16:52
For security reasons, I cannot give out the email listed on the bot. The bot registered to that facebook page is named Kuai3FacebookRobot.  I'm happy to help and provide any information I can and help resolve this.  I will send another email to the Hotmail email address listed with the Kuai3FacebookRobot bot.

**Comment by madukapai** [comment] 2017-12-23 06:38
@JasonSowers Thank you very much, 
I guess, registered BOT email address may be maduka_bor@hotmail.com or maduka_phone@hotmail.com, the both are currently in use by me, so if I provide email address is correct, I can provide more Information (ex:bot framework screen, azure web app screen...) to confirm and resolve this problem.

**Comment by JasonSowers** [comment] 2018-01-03 21:48
@madukapai whats the best email to contact you at?

**Comment by madukapai** [comment] 2018-01-04 12:23
@JasonSowers you can send email to maduka_bor@hotmail.com or maduka_phone@hotmail.com

**Comment by fsps60312** [comment] 2018-01-17 13:05
Same situation here.
I've already deleted the bot on my original Azure account, but having problems adding channel for the new bot on my new Azure account
My email: fsps60312@yahoo.com.tw

![image](https://user-images.githubusercontent.com/16624833/35044050-d59638de-fbc9-11e7-8071-6c053b89a8f6.png)

**Comment by mvanhalen** [comment] 2018-02-01 18:59
I also have this same message. I did have another bot for testing, but I removed that. So not sure what to do now. Our page ID is  103749919719606.  The web chat test is working fine in our case. Really like this product so hope we can solve this. Thanks.

**Comment by dsanabriav** [comment] 2018-02-05 17:14
Same issue here, mi page ID is: 559757797690577. Email: diegosv19@gmail.com. I deleted the previous bot and I'm trying to link the same page with a new bot with different azure account.

**Comment by yochail** [comment] 2018-02-06 13:35
Same issue here. any solution available?

**Comment by yochail** [comment] 2018-02-06 14:19
Same issue here

**Comment by yochail** [comment] 2018-02-06 14:52
I succeeded to somehow overriding this bug with the following hack:
```
 public virtual async Task<HttpResponseMessage> Post([FromBody] Microsoft.Bot.Connector.Activity activity)
        {

            //this is a stupid hack, solving the problem here: https://github.com/Microsoft/BotBuilder/issues/3893
            if (activity.Recipient.Name == "<old app name>")
            {
                activity.Recipient.Name = "<new app name>";
                activity.Recipient.Id = "<Fake page id>";
            }
```
where "old app name" is the name that the bot thinks is still connected to the FB page, 
 new app name is the current connected application, and "Fake page id" is the id you insert in the new bot service when creating the "messenger" channel connection.  i inserted my real page id with space in the end, and then i can save it.

**Comment by fanidamj** [comment] 2018-06-21 23:55
Closing the issue assuming it as resolved. Please reopen a new issue if it still persists.

**Closed by fanidamj** 2018-06-21 23:55 UTC
Labels: .NET SDK, FB Messenger, channel configuration
