### ISSUE TITLE
Is there a way to submit a form proactively?

### ISSUE THREAD

**Issue by DavidSRamirezM** [Microsoft/BotBuilder#2568] opened 2017-04-06 21:50 UTC
I'm trying to start a proactive conversation but instead of a message, I want to start with a form, does anyone have an idea how to build this or if there is an example?

**Comment by ejadib** [comment] 2017-04-06 22:19
Duplicate of http://stackoverflow.com/questions/43266417/is-there-a-way-to-submit-a-form-proactively

Please don't re-post questions. Also, please note that this repo is preferred for submitting **bug fixes and feature requests**; not for **how to** questions.

**Closed** 2017-04-06 23:59 UTC
