### ISSUE TITLE
AadV1Bot cannot get tokenResponse [Add authentication]

### ISSUE THREAD

**Issue by xiaolangxyz** [Microsoft/BotBuilder#4830] opened 2018-07-06 10:42 UTC
## Bot Info
* SDK Platform:  .NET
* SDK Version: SDK version3 
* Active Channels: botframework-emulator
* Deployment Environment:  Azure Bot Service,  local development with Emulator

## Issue Description
In local development with Emulator
I'm trying to use Sample code "AadV1Bot", following the steps in "https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-authentication?view=azure-bot-service-3.0"
I stuck in "Sign in", I can click to open a sub window and login in successfully. But it never comes back. Just tell me "Hmm. Something went wrong, let’s try again.".

![default](https://user-images.githubusercontent.com/40823365/42374623-a401ef92-8153-11e8-94bc-0f6430ca5fa1.png)

**Comment by ukphillips** [comment] 2018-07-06 13:45
Can you show us what your bot OAuth configuration looks like?

**Comment by xiaolangxyz** [comment] 2018-07-09 03:52
@ukphillips 
Sorry for my late reply.
I'm a beginner. I don't know whether i got your points. If not, tell me please. I really want to figure out .
![q1](https://user-images.githubusercontent.com/40823365/42429899-de8f358c-8376-11e8-989a-057d45bc304f.png)
![q2](https://user-images.githubusercontent.com/40823365/42429900-deb7ab2a-8376-11e8-88be-0cf79f8c12b2.png)

**Comment by xiaolangxyz** [comment] 2018-07-10 06:45
@ukphillips

For ensuring whether I could get tokenResponse, I tried use the code according to "Notes on the token retrieval flow" in "https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-authentication?view=azure-bot-service-3.0".

It seems I can. And I succeed in getting "await graphClient.Me.Request().GetAsync() as User;", but failed in "await graphClient.Me.**Manager**.Request().GetAsync() as User;"..

So I guess this manager is what you tried telling me "no manager (null)".

Question 1: Because i could get tokenResponse, can i think my setting is correct?
Question 2: Because Manager is null, so how could I use AadV1Bot in local development ? I can not understand what is "Manager".  Is it important? where could I add it?
Question 3: What is the proper way to send OAuthCard and login? AadV1Bot  is using GetTokenDialog. So I guess it is GetTokenDialog. But it's not working properly in my local. How could i make it work?

**Comment by JasonSowers** [comment] 2018-07-12 23:16
In order for the "me" command to work the follow permissions must be enabled on your AAD application:
* `User.ReadBasic.All` for AAdv2 enable in your app, pleas in scopes on your bot.
* `Read all users' basic profiles` for AADv1

WIthout this permission you will not have permission to access your manager in the graph api.

**Comment by xiaolangxyz** [comment] 2018-07-13 01:39
@JasonSowers 
Thanks very much. 
Can you help my Question 1:
**If i don't use CreateOAuthReplyAsync, just start with GetTokenDialog, it will let me to login. But it seems not working. I can't get token. And it also don't return a magic number.**

**Comment by JasonSowers** [comment] 2018-07-13 14:36
@xiaolangxyz  let me look into this, can you post a minimum code example so I can be sure I am looking at exactly what you are trying?

**Comment by xiaolangxyz** [comment] 2018-07-13 14:43
@JasonSowers 
Thank you very much. Just using the sample "AadV1Bot" without any changes. There is no CreateOAuthReplyAsync in the AadV1Bot. Only GetTokenDialog.

**Comment by JasonSowers** [comment] 2018-07-13 14:51
If you are using the exact sample, I went through this earlier this week and was able to get it working with the code as is. 

A few questions:
Are you still only testing on the emulator?
Are you getting any errors at all(check the browser console as well)?    
Have you double checked all your settings both in your AAD app and in your bot?
Might there be some setting in your tenant preventing you from doing this?

**Comment by xiaolangxyz** [comment] 2018-07-13 14:57
@JasonSowers 
Yes, I am still only testing on the emulator. There is no errors. And I think my setting is correct. In a case I will check again next week. I will tell you next week. Can you tell me the ideal login flow while using AadV1Bot. After login, will it give me a magic number?

**Comment by xiaolangxyz** [comment] 2018-07-17 03:32
@JasonSowers 
I tried a gain. It seems not work. Just keep telling me to Sign in. But when I try the fourth time (because retries is set 2), it seems the Token has been gotten successfully. i don't need to login.

![q1](https://user-images.githubusercontent.com/40823365/42795094-55165234-89bd-11e8-8f92-1ceccc0dd250.png)

**Comment by JasonSowers** [comment] 2018-07-17 15:12
Has it continued to work since working the first time?  If not can you try to set a breakpoint and see if you can get any more information from debugging?

To answer you question about the flow, If you have not enabled the magic number you will not need the magic number in the flow.  In this case the flow would be: Sign in > Redirect to sign in page > log in > Acquire token > Use the bot >Refresh token as needed.

In some channels, I know Teams and skype for sure, the magic number is required.  SO the fow would be: Sign in > Redirect to sign in page > log in > get/enter magic number > Acquire token > Use the bot > Refresh token as needed.

Does this answer your question?  I'm not exactly sure what you are looking for when you ask about flow.

**Comment by xiaolangxyz** [comment] 2018-07-18 02:55
Thanks, @JasonSowers 
You did help me a lot.
 I guess AadV1Bot  doesn't need a magic number. I don't why it doesn't work well in my case. But I can use CreateOAuthReplyAsync instead which could help me avoiding the problem.

Q1. Where could set to enable or not enabled  the magic number?
Is it the fourth parameter[ bool asSignInCard = false] in CreateOAuthReplyAsync()?

Q2. It seems there are some ways to get token. 
like,  ①activity.ReadTokenResponseContent()
        ②context.GetUserTokenAsync(Consts.ConnectionName, activity.Text)
　　　or context.GetUserTokenAsync(Consts.ConnectionName)
        ③GetTokenDialog()
In my case, the result of ① is always null. I wonder the reason, and when will it return a token?

**Comment by rjgmail88** [comment] 2018-07-18 03:20
Any thoughts on this error after setting up AADv2 for my bot's oAuth settings 

```
Sign in

Sorry, but we’re having trouble signing you in.
AADSTS70011: The provided value for the input parameter 'scope' is not valid. The scope email Mail.Read profile User.Read offline_access is not valid. openid scope is required..
```

**Comment by xiaolangxyz** [comment] 2018-07-18 03:53
@rjgmail88  
I haven't tried AADv2. according your error. I guess the scope is not set correctly. 
I guess [this](https://stackoverflow.com/questions/38150335/microsoft-graph-scopes-v2-oauth) may help.

**Comment by rjgmail88** [comment] 2018-07-18 19:58
Thanks. I will try that.

**Comment by JasonSowers** [comment] 2018-07-19 23:15
@rjgmail88 It looks like you need to add the `OpenId` permission to both your AAD app and your scopes on your bot.

 @xiaolangxyz to enable magic number in the emulator, you click on the 3 dots on the lright side of your address bar and select settings, then check the "use a sign-in verification code for OAuthCards" checkbox. I am currently looking into your second question, I will update this thread when I have more information.

**Comment by rjgmail88** [comment] 2018-07-20 00:43
Hi , I already had OpenId permission at both the place. Can you take a look at following and let me know if I need anything else?
Also, this BOT was migrated from dev. bot portal couple of months back so let me if that matters. 

Also, I am on old version on emulator which doesn't have use a sign-in verification code option so should i use latest one that came with v4 sdk ?

![image](https://user-images.githubusercontent.com/32375467/42977180-4c09b15c-8b8b-11e8-8551-fc8eb427cfd3.png)

![image](https://user-images.githubusercontent.com/32375467/42977181-4f6593ca-8b8b-11e8-8695-fa153424f6e9.png)

**Comment by JasonSowers** [comment] 2018-07-23 13:41
@xiaolangxyz  There is no reason the code from the `GetTokenDialog` like `ReadTokenResponseContent()` should not work for you using the AADv1 sample.  Something else is wrong, we need to figure out what it is.

**Comment by JasonSowers** [comment] 2018-07-23 13:43
@rjgmail88 I think you may have some overlapping permissions I would try taking them away and trying to add them one at a time to see if you can figure out which one(s) are causing the issue.

**Comment by rjgmail88** [comment] 2018-07-23 14:30
I am using AADv2 configuration.

**Comment by JasonSowers** [comment] 2018-07-23 19:45
I understand RJ, but in your error message it says:

`The scope **email Mail.Read profile User.Read offline_access** is not valid.`

So it seems something in your scopes and/or permissions are off.  It would be hard for me to say without actually being able to troubleshoot your AAD app and Azure portal settings.  I also have not been able to use admin only permissions as I am not an admin on our tenant.  So there may be an issue with the admin only ones you added

**Comment by cwtrsld** [comment] 2018-07-24 06:46
@xiaolangxyz @JasonSowers I'm having the exact same problem. Without the use of the magic numbers the focus never returns to the bot after I enter my credentials, so nothing is happening after logging in. If I trigger the function that needs authentication the error messages shows.

**Comment by xiaolangxyz** [comment] 2018-07-24 07:58
@cwtrsld 
If you are test on the emulator, try to enable magic number in the emulator, you click on the 3 dots on the lright side of your address bar and select settings, then check the "use a sign-in verification code for OAuthCards" checkbox. It does work as Jason said. But I don't know how make it work without magic numbers.

**Comment by xiaolangxyz** [comment] 2018-07-24 10:50
@JasonSowers 

Today I tested again on the emulator. After checked the "use a sign-in verification code for OAuthCards", AadV1Bot works. It returned magic number, and I could login successfully.


About ②context.GetUserTokenAsync(Consts.ConnectionName, activity.Text)
　　　or context.GetUserTokenAsync(Consts.ConnectionName)
Last week ② worked well. But today it's strange.
After I signed in, I can't get token using "context.GetUserTokenAsync(Consts.ConnectionName)" on the emulator. But It works well in Azure Wet chat Test.. I wonder the reason. Is my setting on the emulator wrong?

**Comment by JasonSowers** [comment] 2018-07-24 21:39
@xiaolangxyz  One thing you can try is using the signout command and also sending a "/deleteprofile" command to clear out any saved context.  Did you rewrite the GetTokenDialog?  or are you referring to the calls in the GetTokenDialog?  I can confirm that the GetUserTokenAsync calls in GetTokenDialog are working as expected, if you have changed the code I would not be able to troubleshoot with what you have given me.

As far as settings in the emulator the only one that should affect auth is the "use a sign-in verification code for OAuthCards" So if you want to use the magic code, check that box if you do not then leave it unchecked.

@cwtrsld Are you using the emulator? What error message are you getting? Are you using a sample if so which one?  Node? C#?  It would probably be best to just open a new issue and explain there.

**Comment by xiaolangxyz** [comment] 2018-07-25 02:16
@JasonSowers
I didn't rewrite anything. I don't know the reason. But it seems AadV1Bot  also doesn't work well.
The first time I typed "me", it worked well. But the second time I typed "me", I need to sign in again? Is it correct? I'm not sure whether my memory is correct. If it is correct, the second time, it just directly  showed my information "You are XXXXX and you report to XXXXX" without signing in again.
![q1](https://user-images.githubusercontent.com/40823365/43175684-42d6be76-8ffb-11e8-89bd-77d4575df567.png)

**Comment by JasonSowers** [comment] 2018-07-25 02:54
@xiaolangxyz No, you should not be seeing that behavior.  That was a bug that was fixed.  I will check in the morning and see if something got rolled back and the bug is back.  So if this is the behavior you are seeing in the emulator it is a bug on our end, not yours assuming you are not seeing this behavior in any other channels.

**Comment by JasonSowers** [comment] 2018-07-25 22:42
@xiaolangxyz I ran into one of the issues you are describing today.  When I clicked the sign in button, went through the login process and nothing happened. Eventually the bot responded correctly to the "me" command after a few tries. This was a result of the emulator's ngrok session expiring.  When this happens all you need to do is restart the emulator.  We are working on a notification system for the v4 that would notify when this happens.

> The first time I typed "me", it worked well. But the second time I typed "me", I need to sign in again? Is it correct? I'm not sure whether my memory is correct. If it is correct, the second time, it just directly showed my information "You are XXXXX and you report to XXXXX" without signing in again last week.

This should be fixed now,  I was able to reproduce this earlier and spoke with the correct people about fixing it.  It is now working for me

**Comment by xiaolangxyz** [comment] 2018-07-26 06:21
@JasonSowers Thank you very much! It works now.

> There is no reason the code from the GetTokenDialog like ReadTokenResponseContent() should not work for you using the AADv1 sample. Something else is wrong, we need to figure out what it is.

Do you still remember this? 
ReadTokenResponseContent()  is still not working. After I signed in, I think ReadTokenResponseContent() should not be null. Is this a correct state? is my way of using ReadTokenResponseContent() correct?

![q1](https://user-images.githubusercontent.com/40823365/43244874-4c5cb102-90e7-11e8-9afc-04aa1c367056.png)

**Comment by JasonSowers** [comment] 2018-07-26 15:06
At that breakpoint it is hard to say exactly where you are in the code. Is there a token value on Line 169 (inside the ListMe function) in the RootDialog class?

`var token = await tokenResponse;`

When you put a breakpoint on line 170 (inside the ListMe function) does the `token.Token` property above have a value? This is where it is important because that is where graph is being called.  It is also the first step after the code to get the token executes.  If you do not have a token at this point thereis a problem.

**Comment by xiaolangxyz** [comment] 2018-07-27 01:29
@JasonSowers Thank you so much.

> var token = await tokenResponse;

This is working.

> context.Activity.ReadTokenResponseContent()

This one is null. Is this a correct state?

![q1](https://user-images.githubusercontent.com/40823365/43296443-5bad91fe-9186-11e8-94a3-0a29dbf15960.png)

By the way, will it sign out automatically when no conversation continues for a long time?

**Comment by JasonSowers** [comment] 2018-07-27 14:30
You should have a token at that point.  Yes, the token will expire after some time.  When you get a token you actually get 2 tokens.  You get A token that expires after 30 or 60 minutes (I have to confirm which).  Then you also get a refresh token that will automatically refresh that token as long as it is valid.  The refresh token length is something set by your tenant admin.

I'm kind of lost in this thread with where you are at and what problems you are seeing.  At times you have said it is working and now you are saying the token is coming back as null.  I'm confused to what behavior you are seeing.  Could you please describe what the behavior of your bot is and what the issues are?  I appreciate you sharing specific lines of code where you are seeing different behaviors, but I do not understand if your bot is working or what behavior you are seeing overall.

**Comment by JasonSowers** [comment] 2018-07-30 20:15
If you would like to see what the code behind the scenes is doing you can check out [`ReadTokenResponseContent()`](https://github.com/Microsoft/BotBuilder/blob/866c2edabcffdbb8bc16ea1ebe05f5f8dad4eab1/CSharp/Library/Microsoft.Bot.Connector.Shared/ActivityEx.cs#L523) This is really just checking to see if the user has a token already and [`GetUserTokenAsync()`](https://github.com/Microsoft/BotBuilder/blob/fe4bc088dc47cb428cb9c1eb1e809b9c197a5a1a/CSharp/Library/Microsoft.Bot.Connector.Shared/OAuthAPI/OAuthApi.cs#L56) actually calls to get a token.

**Comment by xiaolangxyz** [comment] 2018-07-31 01:35
@JasonSowers 
Thank you so much. i will try it.

**Comment by JasonSowers** [comment] 2018-07-31 19:41
Are we good to close this issue, or did you still have questions?

**Comment by xiaolangxyz** [comment] 2018-07-31 22:51
m

**Closed** 2018-07-31 22:52 UTC
Labels: .NET SDK, emulator
