### ISSUE TITLE
[Azure Bot Service] Error when registering a bot

### ISSUE THREAD

**Issue by ohmusama** [Microsoft/BotBuilder#1435] opened 2016-10-14 18:49 UTC
I get the error: **This item cannot be accessed or modified** when trying to create a new bot.

![capture](https://cloud.githubusercontent.com/assets/220289/19399002/2eb8f720-9204-11e6-9d1c-9cb9442c4e09.PNG)

**Comment by danmarshall** [comment] 2016-10-14 19:47
Thanks for reporting this. Meanwhile, can you close your browser and try again?

**Comment by ohmusama** [comment] 2016-10-14 21:01
I switched to chrome, worked in chrome.

**Comment by danmarshall** [comment] 2016-10-14 23:02
If you can give any details on the browser & version that would be helpful. Thanks!

**Comment by ohmusama** [comment] 2016-10-19 17:48
Microsoft Edge 38.14393.0.0
Microsoft EdgeHTML 14.14393

**Comment by chrimc62** [comment] 2016-11-27 00:07
@danmarshall is this something we can fix or have to live with?

**Comment by danmarshall** [comment] 2016-12-06 22:03
Closing this issue for now, please feel free to open a new issue if you encounter it.

**Comment by ajit-drag** [comment] 2017-02-13 15:53
Also coming in chrome for me.
Version 56.0.2924.87 (64-bit)

**Comment by hailiu2586** [comment] 2017-02-13 18:45
if you can try sign out of https://dev.botframework.com and sign back in, it might clear up your browser side state and unblock you. We will investigating for a code fix in the mean time.

**Comment by ajit-drag** [comment] 2017-02-13 18:48
I tried open in incognito, it solved my problem but the app id and app secret were gone. So I have to create new app id and secret. Other wise opening in incognito worked for me.

**Comment by EricDahlvang** [comment] 2017-04-05 00:54
I'm closing this issue, as it is no longer occurring.

**Comment by IRRDC** [comment] 2017-07-05 14:09
The issue is occuring in IE 11 (11.0.9600.18697) for me. Used the Chrome workaround with Version 59.0.3071.115 (64-Bit).

**Comment by GuilhermeQuelhos** [comment] 2017-07-06 11:00
I'm facing the same issue on IE 11 (11.0.9600.18697).
I tried the workaround using Chrome (Version 59.0.3071.115 (Official Build) (64-bit) ) but it didn't work for me. 
Using Chrome, I cannot select any template.
![image](https://user-images.githubusercontent.com/7399322/27908225-b6b562c6-6242-11e7-9d9c-b3e6688fde91.png)

**Comment by danmarshall** [comment] 2017-07-06 18:30
@IRRDC @GuilhermeQuelhos - thanks for your comments. Are you seeing the exact same issue as in the screenshot at the top of this issue? If not, can you open a new issue since this may not actually be the same situation.

**Comment by IRRDC** [comment] 2017-07-07 06:16
I see the same message as in the original screenshot when I try to create a bot based on the first 3 templates. Also when I try to edit (in IE) the bot I created using Chrome I end up not on the bot's page but on the template selection page.

**Comment by anishetty** [comment] 2017-07-11 15:32
1) Same issue is occurring on IE 11 for first three templates. 
2) When Language Understanding is chosen it ask to sign in and after successful sign in it gives option to create new blank LUIS app or use LUIS api key to connect. When clicked on continue it again displays the same message.

**Comment by nwhitmont** [comment] 2017-10-10 01:13
Open a new issue if you are still having problems

**Closed by nwhitmont** 2017-10-10 01:13 UTC
Labels: Azure Bot Service, bug, ext-s
