### ISSUE TITLE
NotBeforeError comes out as ERROR: ChatConnector: receive - invalid token. Check bot's app ID & Password.

### ISSUE THREAD

**Issue by Sammons** [Microsoft/BotBuilder#1835] opened 2016-12-09 19:54 UTC
Using version 3.4.4 with the ChatConnector

I'm running my bot inside a docker container on mac os - I had to instrument the ChatConnector.js file to see the error that jwt.verify was throwing and realized that it was NotBeforeError, and my bot credentials were fine.

I modified the code to look something like this to figure it out
```
if (key) {
                    try {
                        console.log(key, verifyOptions)
                        jwt.verify(token, key, verifyOptions);
                    }
                    catch (err) {
                        console.log(err)
                        logger.error('ChatConnector: receive - invalid token. Check bot\'s app ID & Password.');
                        res.status(403);
                        res.end();
                        return;
                    }
```

Would be awesome if that logger.error statement mentioned something about the underlying error because it was very misleading as-is.

The root issue I was running into was that my docker vm had its time out of sync, but I thought it was clock tolerance or my credentials being invalidated.

**Comment by Stevenic** [comment] 2016-12-17 19:24
Thanks for tracking the issue down. It's helpful to know the root cause of issues like this.

**Comment by dandriscoll** [comment] 2016-12-21 22:59
Closing as we've identified the issue. We'll keep this in mind if others report similar problems. Thanks!

**Closed by dandriscoll** 2016-12-21 22:59 UTC
Labels: bug, node.js

**Comment by Sammons** [comment] 2016-12-21 23:05
Thanks guys, really appreciate it!
