### ISSUE TITLE
Facebook Messenger channel errors are not delivered to bot

### ISSUE THREAD

**Issue by xitij** [Microsoft/BotBuilder#4556] opened 2018-05-04 03:22 UTC
## Bot Info
* SDK Platform: Node.js (v10.0.0)
* SDK Version: 3.14.1
* Active Channels: Facebook
* Deployment Environment: Local development and bot hosted on Heroku

## Issue Description
When sending [proactive](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-proactive-messages) messages from the bot to an end user who has "turned off all messages" in Facebook messenger, the bot (and therefore the Bot Framework API response) receives an error with code 403 but an empty body. The Facebook error code, and error subcode are both stripped out.

These codes are visible through the Azure portal only. You can find them by:
1. Selecting your bot
2. Selecting Facebook channel
3. Clicking on "Issues"
See the attached [image](http://tinyimg.io/i/994CGLE.png).

Facebook will occasionally send errors to the developer page with the following:
```
In the last three hours 50% of the calls to the method POST {page-id}/messages resulted in errors.

Error Code | 200
-- | --
Error Description | Permissions error
Error Count | 3
```

This problem has been around for a long time. It has been reported multiple times: [here](https://github.com/Microsoft/BotBuilder/issues/2240), and [here](https://github.com/Microsoft/BotBuilder/issues/2519). I've posted in the second issue multiple times but no one seems to have noticed or resolved this issue.

**This is a major issue because every bot that is using BotBuilder/Bot Framework has absolutely no way of determining when a user has muted the bot.**

## Code Example
I've tested this both with the following:
1. This code in my bot.
```
const onSendDone = (err, response, callback, inputs) => {
  if (err) {
    logSendError(err, response, inputs);
  }
  if (typeof callback === 'function') {
    callback(err, response);
  }
};

bot.send(msgs, (err, response) => onSendDone(err, response, callback, inputs));
```
2. Using Postman with the exact same request directly to the Bot Framework API
```
POST https://facebook.botframework.com/v3/conversations/MY_CONVO_ID/activities
Headers:
  Content-Type: application/json
  Authorization: "Bearer MY_BEARER_TOKEN"
Body: {      
  "recipient": {
    "id": "MY_USER_ID"
  },
  "from": {
    "id": "MY_BOT_ID",
    "name": "MY_BOT_NAME"
  },
    "localTimestamp": "2018-05-03T17:57:23.670Z",
    "type": "message",
    "text": "Here's the latest NFL news to get your week started:"
}      
```
Based on my testing I believe the actual problem is in the Bot Framework API but I'm not sure where to post issues for that. Regardless the bot itself doesn't receive an error in these cases.

## Reproduction Steps
1. On Facebook Messenger click "turn off all messages" for the bot (seems like you can only do this on the mobile app)
2. Bot sends a proactive message to user
3. Bot (and Bot framework callback API receive 403 with empty response body)

## Expected Behavior
I expect to receive the Facebook error body which should contain error code, error subcode, etc.

## Actual Results
The bot doesn't receive an error, and the http request (when just attempting to make the exact POST to Bot Framework API) receives a 403 with no body.

**Comment by craigjensen** [comment] 2018-05-04 20:27
If you are getting a 403 it's probably because there is a problem with your token and not related to the user disabling messages.  

I just tried this scenario and here's the response I received:
< HTTP/1.1 400 Bad Request
< Cache-Control: no-cache
< Pragma: no-cache
< Content-Length: 152
< Content-Type: application/json; charset=utf-8
< Expires: -1
< Server: Microsoft-IIS/10.0
< Request-Context: appId=cid-v1:7e1cce65-3088-4e14-9fc2-141393cc01ef
< X-Powered-By: ASP.NET
< Date: Fri, 04 May 2018 20:22:16 GMT
<
{
  "error": {
    "code": "ServiceError",
    "message": "Failed to post message to Facebook: (#551) This person isn't available right now."
  }
}

**Comment by xitij** [comment] 2018-05-04 20:40
> If you are getting a 403 it's probably because there is a problem with your token and not related to the user disabling messages.

This is not correct. The token expires after about 60 minutes iirc. I've done the proper request to get my Bearer Token and used it my request to Bot Framework.

The token request is as follows:
```
POST https://login.microsoftonline.com/botframework.com/oauth2/v2.0/token
Headers:
  Content-Type: application/x-www-form-urlencoded
Body (x-www-form-urlencoded): {
  "scope": "https://api.botframework.com/.default",
  "grant_type": "client_credentials",
  "client_id": "MS_BOT_ID"
  "client_secret": "MS_BOT_PASSWORD"
}
```
This should give you the following response:
```
200:
Body: {
  "token_type": "Bearer",
  "expires_in": 3600,
  "ext_expires_in": 0,
  "access_token": "YOUR_BEARER_TOKEN"
}
```

Use that Bearer Token in the request I posted, you will receive the response I posted if the user has selected "turn off all messages".

**Comment by craigjensen** [comment] 2018-05-04 22:02
I can confirm that our current production deployment does return a 403 with an empty response as you state.  I ran my original test against our internal testing environment where the issue has already been fixed.  

Once the fix is deployed you will receive the following response:

```
400 Bad Request
{
  "error": {
    "code": "ServiceError",
    "message": "Failed to post message to Facebook: (#551) This person isn't available right now."
  }
}
```

Hopefully, this will resolve the issue for you.  The next deployment likely won't be until the week after next due to the \\Build conference next week.

**Comment by xitij** [comment] 2018-05-04 22:18
> I can confirm that our current production deployment does return a 403 with an empty response as you state.

Cool. Thank you.

> I ran my original test against our internal testing environment where the issue has already been fixed.

Great to hear that this has been fixed.

> The next deployment likely won't be until the week after next due to the \Build conference next week.

Sounds good, thanks for the info. Is this release an update to the Bot Framework API, BotBuilder SDK or both?

> Hopefully, this will resolve the issue for you.

In regards to the fixed response you posted, Is there any reason that you decided not to pass along [Facebook error code](https://developers.facebook.com/docs/messenger-platform/reference/send-api/error-codes)? What does `#551` mean, is that the error code? Is there a description of the possible error codes anywhere?

I would think passing along some of the additional error message/codes from facebook would be useful to the bots.

Thanks again for the quick response to this issue.

**Comment by craigjensen** [comment] 2018-05-04 22:43
The fix is in the BF API's so you will not need to update the SDK to pick it up.  The error is coming from Facebook but doesn't seem to be documented very well.  Here's the what we get back from Facebook:

```
{
  "error": {
    "message": "(#551) This person isn't available right now.",
    "type": "OAuthException",
    "code": 551,
    "error_subcode": 1545041,
    "fbtrace_id": "G3GRmtpZiq6"
  }
}
```

**Comment by xitij** [comment] 2018-05-04 22:58
> The fix is in the BF API's so you will not need to update the SDK to pick it up.

Sweet that's great to hear. I know you said the fix will be published after MS Build, but will this be published as "We updated Bot Framework API" anywhere or it will just be a change that we'll eventually see?

> Here's what we get back from Facebook:
```
{
  "error": {
    "message": "(#551) This person isn't available right now.",
    "type": "OAuthException",
    "code": 551,
    "error_subcode": 1545041,
    "fbtrace_id": "G3GRmtpZiq6"
  }
}
```
I agree Facebook doesn't have good documentation for their errors, so I definitely understand your pain. With that in mind, I don't see `code: 551` documented anywhere in their errors (it seems that the subcode we're talking about is document but the code is `200` not `551`). Assuming facebook doesn't update their documentation any time soon, is there a reason you don't pass along the `subcode` in your error response? It seems to me, that passing along the `code` and `subcode` would give developers a better chance of determining what the actual facebook error is.

**Comment by craigjensen** [comment] 2018-05-04 23:15
That's good feedback.  The error response object that we send has only code and message.  We could look into adding the code and subcode (or possibly the entire Json) into our error message but it's a string so parsing on your end won't be very clean.

**Comment by craigjensen** [comment] 2018-05-04 23:30
Sorry, did you mean adding the subcode to the message is _favorable_, or _not favorable_?  Your feedback is important and we do take it very seriously!

**Comment by xitij** [comment] 2018-05-04 23:38
> Sorry, did you mean adding the subcode to the message is favorable, or not favorable? Your feedback is important and we do take it very seriously!

Yeah sorry I realized I edited that. I think it's **favorable** to add the `subcode` because we already have to parse the `code` out of the `message`. Since we're already doing that I don't think it's much more effort to pull the `subcode`.

**Comment by xitij** [comment] 2018-05-04 23:40
Something like this:
```
400 Bad Request
{
  "error": {
    "code": "ServiceError",
    "message": "Failed to post message to Facebook: code (#551) subcode (#1545041) This person isn't available right now."
  }
}
```

Also where does your `code` response come from?

**Comment by xitij** [comment] 2018-05-07 20:14
@craigjensen ... bump.

**Comment by xitij** [comment] 2018-05-07 21:00
Thanks.

**Comment by xitij** [comment] 2018-05-28 06:49
@craigjensen Any update on this? Have these changes been deployed? Thanks.

**Comment by xitij** [comment] 2018-05-31 23:51
@craigjensen Has this been released?

**Comment by craigjensen** [comment] 2018-06-01 00:06
Not yet.  We ended up adding a new property to the error response that contains the complete inner http error from Facebook.  It was checked in today and should be deployed in next week's deployment.  Here's an example of what to expect:

```
400 Bad Request
{
  "error": {
    "code": "ServiceError",
    "message": "Facebook API error",
    "innerHttpError": {
      "statusCode": 400,
      "body": {
        "message": "(#551) This person isn't available right now.",
        "type": "OAuthException",
        "code": 551,
        "error_subcode": 1545041,
        "fbtrace_id": "H4+88ZZ+Td0"
      }
    }
  }
}
```

**Comment by xitij** [comment] 2018-06-19 06:06
@craigjensen Just confirming this is now deployed?

Thanks again.

**Comment by craigjensen** [comment] 2018-06-19 15:17
Yes, it's live now.

**Comment by EricDahlvang** [comment] 2018-06-21 22:12
It looks like this has been resolved.  Closing.

**Closed by EricDahlvang** 2018-06-21 22:12 UTC
Labels: FB Messenger, Node.js SDK

**Comment by uchralganbat** [comment] 2023-06-21 11:21
I have a same issue with error code like below
{
  "error": {
    "message": "(#551) This person isn't available right now.",
    "type": "OAuthException",
    "code": 551,
    "error_subcode": 1545041,
    "fbtrace_id": "AHqehUbyE3Ru4bzaA2ynwSM"
  }
}
trying to send a message from my page to a facebook user with their id. 
I don't understand it is giving me this error.?
