### ISSUE TITLE
[Direct Line] Bot not responding to user messages. Giving Directline error : "[500] Internal Server Error"

### ISSUE THREAD

**Issue by bhushanvadgave** [Microsoft/BotBuilder#3948] opened 2017-12-18 10:29 UTC
## Bot Info 
* SDK Platform: NodeJS
* SDK Version: 3.12.0
* Active Channels: Direct Line, Facebook
* Deployment Environment: Manual deployment in VMs of Azure IaaS
* Region of bot deployment: West Europe

## Issue Description
Bot suddenly stopped working. It is not responding to user messages randomly. 
Showing below errors in logs:
```

Error: Request to 'https://directline.botframework.com/v3/conversations/<some-id>/activities/<some-id>' failed: [500] Internal Server Error
    at Request._callback (/usr/src/app/node_modules/bot-services/node_modules/botbuilder/lib/bots/ChatConnector.js:535:46)
    at Request.self.callback (/usr/src/app/node_modules/bot-services/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/usr/src/app/node_modules/bot-services/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/bot-services/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

**Comment by JpEncausse** [comment] 2017-12-18 10:36
Got the same issue, since few days (and the migration to Microsoft Server) we have A LOT of issues
- That 500 exception
- We received 10x the same message
- Missing ServiecURL (https://github.com/Microsoft/BotBuilder/issues/3905)

**Comment by Highvolt** [comment] 2017-12-18 11:17
Same issue for me as well.

**Comment by zubcomandante** [comment] 2017-12-18 11:26
Same for me, baad situation.
I did not migrate anything yet, my bots are hosted in our company's private infrastructure.

**Comment by NitishDeshpande** [comment] 2017-12-18 11:29
Same for me as well. When will this be resolved?

**Comment by jesus-seijas-sp** [comment] 2017-12-18 11:29
Same issue here with DirectLine:

Failed to load https://directline.botframework.com/v3/directline/conversations/XXXXXXXXXXX/activities: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'XXXXXXXXXXXX' is therefore not allowed access. The response had HTTP status code 500.

**Comment by DyzLecticus** [comment] 2017-12-18 11:31
Same for me as well. When will this be resolved?

**Comment by droidpl** [comment] 2017-12-18 12:42
It also happens to me. It is quite annoying

**Comment by sharmadine** [comment] 2017-12-18 12:58
Our production bot (registration bot with our own hosted bot service) has gone down with exact same error suddenly a few hours ago. The bot service is deployed in West Europe. Please help and suggest the time it will take to be back...

**Comment by JaapKoornstra** [comment] 2017-12-18 13:06
Same for me.

**Comment by jesus-seijas-sp** [comment] 2017-12-18 13:55
To add more info, the issue can be reproduced directly at https://dev.botframework.com in the Test section, when you talk to the bot, the same problems are reflected in the console.

**Comment by DanielTizon** [comment] 2017-12-18 14:44
From yesterday, we are getting the same random 500 errors in our production bot, plz could some Microsoft guy tell us what is going on?

    SDK Platform: NodeJS
    SDK Version: 3.13.1
    Active Channels: Direct Line
    Deployment Environment: WebApp in Azure
    Region of bot deployment: West Europe

**Comment by HenrikFrystykNielsen** [comment] 2017-12-18 15:40
Thanks for the reports, we are investigating and will get back with an update as soon as possible. I apologize for any inconvenience. Henrik

**Comment by DanielTizon** [comment] 2017-12-18 15:40
In my case, the error is slightly different:

```
Error: POST to 'https://directline.botframework.com/v3/conversations/Aq2B7eFov1wKgiPwlx6gwd/activities/Aq2B7eFov1wKgiPwlx6gwd%7C0000013' failed: [500] Internal Server Error

    at Request._callback (D:\home\site\wwwroot\node_modules\botbuilder\lib\bots\ChatConnector.js:545:46)

    at Request.self.callback (D:\home\site\wwwroot\node_modules\request\request.js:186:22)

    at emitTwo (events.js:106:13)

    at Request.emit (events.js:191:7)

    at Request.<anonymous> (D:\home\site\wwwroot\node_modules\request\request.js:1163:10)

    at emitOne (events.js:96:13)

    at Request.emit (events.js:188:7)

    at IncomingMessage.<anonymous> (D:\home\site\wwwroot\node_modules\request\request.js:1085:12)

    at IncomingMessage.g (events.js:291:16)

    at emitNone (events.js:91:20)

    at IncomingMessage.emit (events.js:185:7)
```

**Comment by nwhitmont** [comment] 2017-12-18 16:06
Update: We found the problem and have implemented a fix. 

Performance should improving now.

**Comment by sharmadine** [comment] 2017-12-18 18:08
@nwhitmont Thanks for your support in releasing the fix. Our Bot is alive again in production.

**Comment by nwhitmont** [comment] 2017-12-18 19:21
@sharmadine Thanks for the update! Glad to hear it resolved your issue.

**Comment by nwhitmont** [comment] 2017-12-18 19:21
@bhushanvadgave The issue has been mitigated - Can you confirm the issue is resolved from your end?

**Comment by xjose97x** [comment] 2017-12-18 22:21
Seems to work now. Thanks!

**Comment by bhushanvadgave** [comment] 2017-12-19 03:35
@nwhitmont Yes, I don't see any issue now. The bot is responding to the messages. Thanks for fixing this.

**Comment by DyzLecticus** [comment] 2017-12-19 08:07
The issue seems to be resolved; our bot is responding consistently again.

**Comment by Highvolt** [comment] 2017-12-19 10:05
The issue seems to be resolved for our bot as well.

**Comment by nwhitmont** [comment] 2017-12-19 19:34
Thanks for confirming guys. 

Closing as resolved.

**Closed** 2017-12-19 20:56 UTC
Labels: Direct Line, performance

**Comment by zubcomandante** [comment] 2018-01-22 13:51
is it happening again?

**Comment by rowilken** [comment] 2018-01-22 14:18
I'm just experiencing the same behavior: my bot is randomly failing on directline channel with error 502 nor and a few minutes ago with: No 'Access-Control-Allow-Origin' header is present on the requested resource

**Comment by DanielTizon** [comment] 2018-01-22 14:35
Same here!

**Comment by droidpl** [comment] 2018-01-22 17:38
Same here. Also I have the state API installed.

**Comment by vbhatt** [comment] 2018-11-01 15:42
Help with Bot, I keep getting the following error in production:

Error: POST to 'https://directline.botframework.com/v3/conversations/4ibwaWCUFo81PYACxrkgFm/activities/3Q6daILoNb9' failed: [503] Service Unavailable
    at new Error (native)
    at Request._callback
