### ISSUE TITLE
Chat history is lost on page reload

### ISSUE THREAD

**Issue by vimalarokiaraj** [Microsoft/BotBuilder#2724] opened 2017-05-09 06:02 UTC
Hi,
Can someone help me to resolve the issue with bot as it is losing history if the page is reloaded.

## Pre-flight checklist
- [x] I have [searched the existing issues](https://github.com/Microsoft/BotFramework-WebChat/issues/365) 
---------------------------

## System Information (Required)

* **SDK language (C#/Node)- c#
* **SDK version - 3.5
* **Development environment - localhost 
* **Node.js + npm version**

## Issue Description
Relates to: https://github.com/Microsoft/BotFramework-WebChat/issues/365

Chat history is lost when page is reloaded.

## Example Code
```javascript
function msieversion() {
            var ua = window.navigator.userAgent;
            var msie = ua.indexOf("MSIE ");

            if (msie > 0) // If Internet Explorer, return version number
                return parseInt(ua.substring(msie + 5, ua.indexOf(".", msie)));
            else // If another browser, return 0
                return 0;
        }

        var ieVersion = msieversion();

        if (ieVersion > 0 && ieVersion < 10) {
            $("#botChat").hide();
        } else {
            var params = {};
            location
                .search
                .substring(1)
                .split("&")
                .forEach(function (pair) {
                    var p = pair.split("=");
                    params[p[0]] = p[1];
                });

            if (sessionStorage.luisToken === undefined) {
                $.ajax({
                    url: util.getLink("General", "BotToken"),
                    dataType: "json",
                    type: "GET",
                    data: {},
                }).done(function (data) {

                    if (data) {
                        sessionStorage.luisToken = data;
                        var directLine = new BotChat.DirectLine({
                            token: sessionStorage.luisToken
                        });
                        debugger;
                        var botConnection = directLine;
                        sessionStorage.botUserId = Math.random();
                        botConnection.connectionStatus$
                            .subscribe(function (connectionStatus) {
                                switch (connectionStatus) {

                                    case 2:
                                        sessionStorage.streamUrl = botConnection.streamUrl;
                                        sessionStorage.conversationId = botConnection.conversationId;
                                        break;
                                    case 3:
                                        // ConnectionStatus.ExpiredToken:
                                        $.ajax({
                                            url: util.getLink("General", "BotReconnectToken"),
                                            dataType: "json",
                                            type: "GET",
                                            data: {
                                                token: sessionStorage.luisToken,
                                                streamUrl: sessionStorage.streamUrl,
                                                conversationId: sessionStorage.conversationId
                                            },
                                        }).done(function (reconnect) {
                                            directLine.reconnect({
                                                token: reconnect.luisToken,
                                                streamUrl: reconnect.streamUrl,
                                                conversationId: reconnect.conversationId
                                            });
                                        });
                                        break;                                        
                                }
                            });

                        var user = {
                            id: sessionStorage.botUserId,
                            name: 'Me'
                        };
                        //console.log(user);
                        var bot = {
                            id: params['botid'] || 'botid',
                            name: ''
                        };

                        BotChat.App({
                            botConnection: botConnection,
                            user: user,
                            bot: bot,
                        }, document.getElementById("BotChatGoesHere"));
                    }
                });

            } else {
                var directLine = new BotChat.DirectLine({
                    token: sessionStorage.luisToken,
                    conversationId: sessionStorage.conversationId,
                    //streamUrl: sessionStorage.streamUrl,
                });
                debugger;
                var botConnection = directLine;
                botConnection.connectionStatus$
                    .subscribe(function (connectionStatus) {
                        switch (connectionStatus) {
                            case 2:
                                sessionStorage.streamUrl = botConnection.streamUrl;
                                sessionStorage.conversationId = botConnection.conversationId;
                                break;
                            case 3:
                                $.ajax({
                                    url: util.getLink("General", "BotReconnectToken"),
                                    dataType: "json",
                                    type: "GET",
                                    data: {
                                        token: sessionStorage.luisToken,
                                        streamUrl: sessionStorage.streamUrl,
                                        conversationId: sessionStorage.conversationId
                                    },
                                }).done(function (reconnect) {
                                    directLine.reconnect({
                                        token: reconnect.luisToken,
                                        streamUrl: reconnect.streamUrl,
                                        conversationId: reconnect.conversationId
                                    });
                                });
                                break;
                        }
                    });

                var user = {
                    id: sessionStorage.botUserId,
                    name: 'Me'
                };
                var bot = {
                    id: params['botid'] || 'botid',
                    name: ''
                };

                BotChat.App({
                    botConnection: botConnection,
                    user: user,
                    bot: bot,
                }, document.getElementById("BotChatGoesHere"));
            }
        }.
```
## Steps to Reproduce
1. refresh web page
2. or click browser back button

## Expected Behavior

Chat history to be retained in chat window

## Actual Results

chat history is lost

**Comment by vimalarokiaraj** [comment] 2017-05-09 07:36
below are the debugger log 

BotChat.App props Object {botConnection: t, user: Object, bot: Object}bot: ObjectbotConnection: tuser: Object__proto__: Object
botchat.js:20 history action Object {type: "@@redux/INIT"}
botchat.js:20 history action Object {type: "@@redux/PROBE_UNKNOWN_ACTION_3.n.m.k.s.w.w.b.3.x.r"}
botchat.js:20 history action Object {type: "@@redux/INIT"}
botchat.js:20 BotChat.Chat props Object {botConnection: t, user: Object, bot: Object}
botchat.js:20 history action Object {type: "Start_Connection", user: Object, bot: Object, botConnection: t, selectedActivity: undefined}
botchat.js:20 BotChat.Chat state Object {shell: Object, format: Object, connection: Object, history: Object}
botchat.js:20 history action Object {type: "Start_Connection", user: Object, bot: Object, botConnection: t, selectedActivity: undefined}
botchat.js:20 history action Object {type: "Connection_Change", connectionStatus: 0}
botchat.js:20 history action Object {type: "Connection_Change", connectionStatus: 1}
botchat.js:20 BotChat.Chat state Object {shell: Object, format: Object, connection: Object, history: Object}
botchat.js:20 history action Object {type: "Connection_Change", connectionStatus: 2}
botchat.js:20 BotChat.Chat state Object {shell: Object, format: Object, connection: Object, history: Object}
botchat.js:21 creating WebSocket wss://directline.botframework.com/v3/directline/conversations/JwNQ6mt8uKr5e…FQARQA.sys5YZHI0gE.6h9hXhfviyI.OXZ60A5o0ne2guOzt99wNpdZL5XfGqqj64DuLEJqD20
botchat.js:21 WebSocket open Event {}
botchat.js:20 history action Object {type: "Receive_Message", activity: Object}
botchat.js:20 BotChat.Chat state Object {shell: Object, format: Object, connection: Object, history: Object}
botchat.js:20 history action Object {type: "Receive_Message", activity: Object}
botchat.js:20 BotChat.Chat state Object {shell: Object, format: Object, connection: Object, history: Object}
botchat.js:21 refreshing token MZdQyhkcuag.dAA.SgB3AE4AUQA2AG0AdAA4AHUASwByADUAZQBJAGYAZABqAHQAQgBrAFQARQA.8N6OiJfI0gE.nB0lMl3ihA4.arDThBDFD6ouBrXNcQ4vhV7afRpogf7YKeUYkGPIB7I at Tue May 09 2017 17:10:28 GMT+1000 (AUS Eastern Standard Time)
botchat.js:21 refreshing token MZdQyhkcuag.dAA.SgB3AE4AUQA2AG0AdAA4AHUASwByADUAZQBJAGYAZABqAHQAQgBrAFQARQA.yObhoJnI0gE.97Hs6rx0_Ug.AlBAo67u4xiKF8jiReXO-8rEaYUgwyyzIGnhFhqxQbw at Tue May 09 2017 17:25:28 GMT+1000 (AUS Eastern Standard Time)

**Comment by nwhitmont** [comment] 2017-05-09 22:04
@vimalarokiaraj are you using C# or Node SDK?

**Comment by vimalarokiaraj** [comment] 2017-05-10 03:08
The Bot API is in C# and the client widget is in javascript.

**Comment by nwhitmont** [comment] 2017-05-11 19:16
This is not a bug, its a feature. The web chat module currently does not support out-of-the-box storing and loading of chat histories. 

Closing as duplicate of feature request [BotBuilder-WebChat #365 - Supply history on startup](https://github.com/Microsoft/BotFramework-WebChat/issues/365)

**Closed by nwhitmont** 2017-05-11 19:16 UTC
Labels: C# SDK, WebChat
