### ISSUE TITLE
nodejs -- Conversations_UpdateActivity js api missing in nodejs

### ISSUE THREAD

**Issue by earlyster** [Microsoft/BotBuilder#1829] opened 2016-12-08 19:43 UTC
I was looking at the v3 rest api for updating activities and we found this available as pure rest api [1] and found c# implementation [2] in bot connector but could not find a nodejs implementation is this just not finished and missing in nodejs.

[1] https://docs.botframework.com/en-us/restapi/connector/#!/Conversations/Conversations_UpdateActivity

[2] https://github.com/Microsoft/BotBuilder/blob/3d90ea251b618163cc5796c52fb8088a40f68b11/CSharp/Library/Microsoft.Bot.Connector/ConnectorAPI/Conversations.cs#L610

**Comment by Stevenic** [comment] 2016-12-12 08:28
Yes... The issue is there's currently no way to get the activity ID in the Node SDK. It's on the list of issues to address after we get v3.5 out the door. Is this blocking you? what are you trying to do?

**Comment by earlyster** [comment] 2016-12-13 02:05
Can we get the activity ID from the client and pass it to node SDK?  For example I have Direct line and I get the activity id from the history of the conversation.. I can add a my own rest service that can update the activity with additional data.  This is blocking my usage of updating an existing activity using bot framework.

**Comment by earlyster** [comment] 2016-12-13 19:17
I am trying to now directly use the REST api  without node wrapper but when calling the PUT api for activity I am getting this error message.. I am not sure what this means and couldn't find any information about this message anywhere. Also schema doesn't mention a bot record.

{
  "error": {
    "code": "MissingProperty",
    "message": "The 'bot' record for the from field is unrecognized"
  }
}

**Comment by earlyster** [comment] 2016-12-15 19:52
ok I am trying with directline and update/delete activity apis are giving 405 -- method not allowed... maybe directline is a channel that doesn't allow updating/deleting activities.

**Comment by Stevenic** [comment] 2016-12-17 19:38
Adding Tom and Dan

**Comment by dandriscoll** [comment] 2016-12-17 21:04
Hi @earlyster, the MissingProperty error you encountered is because the 'from' field on the activity you sent does not match your bot. If you copy the 'recipient' field from an activity you receive, this will work properly.

Direct Line does not yet support editing activities. This is coming but we don't have a date yet.

**Comment by dandriscoll** [comment] 2016-12-26 19:26
Closing as it appears we've addressed the open questions. Please at-mention or file a new issue if you'd like to discuss further. Thanks!

**Closed by dandriscoll** 2016-12-26 19:26 UTC
