### ISSUE TITLE
FormFlow confirmation incorrect options

### ISSUE THREAD

**Issue by tiloc** [Microsoft/BotBuilder#4347] opened 2018-03-20 23:13 UTC
## Bot Info
* SDK Platform: .Net
* SDK Version: 3.13.1
* Active Channels: any
* Deployment Environment: any

## Issue Description
When I have a FormFlow with a confirmation question to which I answer "No", I get a correction dialog as displayed in the screenshot. It strikes me as odd that I get "No Preference" as the last choice. Shouldn't it be something to the effect of "Cancel" or "No changes"? Likewise, in German I get a very colloquial "Who cares?" (Egal). In Chinese I get "casual"? 

While you're at it: I think there should also be a blank between the field to be changed and its current value.

![image](https://user-images.githubusercontent.com/16414047/37687390-bd53755e-2c9b-11e8-8f64-5fed67a31fd0.png)

## Code Example

        public static IForm<WeightForm> BuildLocalizedForm()
        {
            var form = new FormBuilder<WeightForm>()
                .Message("Let's record your weight.")
                .Field(nameof(WeightQuantity))
                .Field(nameof(WeightUnit))
                .Confirm("Is it okay for me to record your weight as {WeightQuantity} {WeightUnit}? {||}")
                .Build();

            return form;
        }

**Comment by JasonSowers** [comment] 2018-03-21 20:34
I just tried to reproduce this and was unable, can you please include your whole form class.  Also if you see a fix please feel free to submit a pull request so that we can review the requested changes.

**Comment by tiloc** [comment] 2018-03-22 11:47
@JasonSowers here it comes, see the attachment. I have done some digging, and I think the culprit is the use and translation of the TemplateNoPreference resource in this built-in change dialog. 

From a semantic standpoint, I am not sure what it is supposed to mean that I have "no preference" what I would like to change? That the bot is free to change whatever it pleases?

In my mind, the dialog should display:
_What do you want to change?_

- Weight (85)
- Weight Unit (lb)
- No changes
 
[WeightForm.zip](https://github.com/Microsoft/BotBuilder/files/1837276/WeightForm.zip)

The German translation is a tricky cultural issue where your product management would probably have to define the target audience of your average bot. Right now, all the German translations are written in a language that targets a teenage to college age audience. "Egal" is what you would hear from your teenage kid when they have lost all interest in the world and want you to go away :-)

**Comment by JasonSowers** [comment] 2018-03-22 21:26
There is supposed to be a way to do this using the attribute `[Template(TemplateUsage.NoPreference, "Your text")]` on your class, but it is not working as expected for me. So we will be looking into this deeper and seeing if it is a bug or not.  Will let you know what we find

**Comment by JasonSowers** [comment] 2018-03-27 22:37
We are still looking into this, we think we found the reason this is not working.  The person that wrote formflow is out this week though, so we will have to wait for him to get back to come to a resolution.

**Comment by JasonSowers** [comment] 2018-04-04 23:42
Still waiting for the one that wrote formflow to return from vacation to give a definite answer on this.

**Comment by EricDahlvang** [comment] 2018-04-06 23:35
FormConfiguration determines the NoPreference template.  As well as MatchNoPreference.  This can be found here: https://github.com/Microsoft/BotBuilder/blob/b7b2abbd089b0c0b91f367e4355743f7171dbc26/CSharp/Library/Microsoft.Bot.Builder/FormFlow/IFormBuilder.cs#L390

It can be overridden like:

```cs
public static IForm<WeightForm> BuildLocalizedForm()
{
    // TODO: Cache the localized forms as shown here: https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-formflow-localize


    var form = new FormBuilder<WeightForm>()
        .Message("Let's record your weight.")
        .Field(nameof(WeightQuantity))
        .Field(nameof(WeightUnit))
        .Confirm("Is it okay for me to record your weight as {WeightQuantity} {WeightUnit}? {||}");

    var noPrefTemplate = form.Configuration.Templates.Find(t => t.Usage == TemplateUsage.NoPreference);
    noPrefTemplate.Patterns = new[] { "No Changes" };
    form.Configuration.NoPreference = new[] { "No Changes" };

    return form.Build();
}
```
![image](https://user-images.githubusercontent.com/11055362/38448314-490bba56-39b8-11e8-900a-354dda79f976.png)

**Comment by fanidamj** [comment] 2018-06-21 23:46
Closing the issue assuming it as resolved. Please reopen a new issue if it still persists.

**Closed by fanidamj** 2018-06-21 23:46 UTC
Labels: .NET SDK, FormFlow, investigate
