### ISSUE TITLE
After bot registration: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by juhamust** [Microsoft/BotBuilder#2543] opened 2017-04-04 06:54 UTC
After registering the bot successfully, which also already works in Azure Bot Service view, the bot can no longer accessed in https://dev.botframework.com/bots: When clicking the bot, the following error is raised from backend: https://dev.botframework.com/api/BotManager/Bots?id=wai-clone

![obj-ref](https://cloud.githubusercontent.com/assets/781002/24644414/21369450-191c-11e7-9912-5ef4cd4fd766.png)

I've successfully registered the same bot earlier (same code, another instance), but seems that something has gotten broken since.

**Comment by EricDahlvang** [comment] 2017-04-04 07:26
Hi juhamust,

Thank you for your submission.  

I've seen this many times also.  Closing other dev.botframework tabs, and **signing out/back** has refreshed the session and allowed me to proceed whenever I've encountered it.  Inconvenient, but does get passed the "Object reference" issue.  It is somehow tied to session.  The developers working on the portal are aware of it.

I'm closing this because the issue is with the dev.botframework portal, and this is the Microsoft BotBuilder repository.  If, after cycling your login, the issue persists, please re-open and/or comment.

**Closed by EricDahlvang** 2017-04-04 07:26 UTC

**Comment by juhamust** [comment] 2017-04-04 07:30
Thanks for the quick response! Indeed, the bot started to working after re-login.

As for the tickets, you might want to add a separate address for site -related issue (if they can be recognised as such): https://docs.botframework.com/en-us/support/
