### ISSUE TITLE
[LUIS] Luis does not recognize numbers properly

### ISSUE THREAD

**Issue by martinoss** [Microsoft/BotBuilder#3540] opened 2017-09-28 13:36 UTC
## Bot Info 
* Only LUIS is affected

## Issue Description
I noticed a super strange behavior with LUIS when trying to detect numbers. When the query contains mixed numbers with leading zeroes and regular numbers (or some other random reason) , not all numbers will be detected. 

Lets say I query "02 02 02", the result will be three entities of type "builtin.number", OK!
If I query "2 2 2", the result will be three entities of type "builtin.number" too. OK!
If I query "02 02 2", the result will be three entities of type "builtin.number" too. OK!
Using a query "02 2 02", only the first two entities are found!
Using a query "31 5 30", only the first two entities are found!
"2 02 2", only gives two numbers back too.

## Code Example
Only two numbers are detected:
```
{
  "query": "2 02 2",
  "topScoringIntent": {
    "intent": "None",
    "score": 0.8794656
  },
  "intents": [
    {
      "intent": "None",
      "score": 0.8794656
    }
  ],
  "entities": [
    {
      "entity": "2",
      "type": "builtin.number",
      "startIndex": 0,
      "endIndex": 0,
      "score": 0.994492948
    },
    {
      "entity": "2",
      "type": "builtin.number",
      "startIndex": 5,
      "endIndex": 5,
      "score": 0.981646538
    }
  ]
}
```

All three numbers are detected:
```
{
  "query": "02 02 02",
  "topScoringIntent": {
    "intent": "None",
    "score": 0.8794656
  },
  "intents": [
    {
      "intent": "None",
      "score": 0.8794656
    }
  ],
  "entities": [
    {
      "entity": "02",
      "type": "builtin.number",
      "startIndex": 0,
      "endIndex": 1,
      "score": 0.9349353
    },
    {
      "entity": "02",
      "type": "builtin.number",
      "startIndex": 3,
      "endIndex": 4,
      "score": 0.8550531
    },
    {
      "entity": "02",
      "type": "builtin.number",
      "startIndex": 6,
      "endIndex": 7,
      "score": 0.631638467
    }
  ]
}

```

## Reproduction Steps
1. Create a new LUIS model
2. Add prebuilt entity number
3. Publish app
4. Hit the endpoint url and append 

## Expected Behavior
If I add groups of numbers, all numbers should be detected.

## Actual Results
Groups of numbers are not detected corretly.

**Comment by martinoss** [comment] 2017-09-28 14:31
My workaround will be something like this 😊:
```
var userInput = userInput.Replace(" ", " huh ");
```
(placing strings between the numbers seems to work)

**Comment by stevengum97** [comment] 2017-09-28 21:40
@martinoss, I haven't been able to reproduce this behavior; is this affecting only one of your applications?
___

**Screenshot:**

![capture](https://user-images.githubusercontent.com/14935595/30991660-d133bc10-a45a-11e7-8539-a409b948d696.PNG)

**Comment by martinoss** [comment] 2017-09-29 07:08
@stevengum97, I noticed the error while working on a project and was able to reproduce it in a completely new luis app. Just found out, the problem does not exist for **culture** en-us, but for **german (de-de)**. Can you verify that?

**Comment by stevengum97** [comment] 2017-09-30 16:37
@martinoss, I was able to repro this in a German culture app as you said. The team is working on improvements for the German prebuilt entities (number included) which should be available by the time LUIS reaches GA. I'll talk with the team so they're aware of this issue. For the time being I'm going to close this issue for now since improvements to the number prebuilt entity are already underway.

Thanks for reporting this!

**Closed by stevengum97** 2017-09-30 16:37 UTC
Labels: LUIS
