### ISSUE TITLE
[Question] Can I stop the bot from responding "I didn't understand" during a prompt when calling the help dialog?

### ISSUE THREAD

**Issue by MbV93** [Microsoft/BotBuilder#3391] opened 2017-08-28 15:12 UTC
I have a help dialog with a triggerAction and when called, works properly but if this happens during a Prompt.Choice the bot will respond "I didn't understand, please try again." besides sending the help dialog content. Is there some way to avoid this? Thanks.

**Comment by JasonSowers** [comment] 2017-08-28 15:39
Can you please fill out the original template with your post including which SDK and the version you are using?  Also could you please provide a minimum reproducing code sample?

**Comment by jorupp** [comment] 2017-08-28 15:42
It sounds like you're both passing the message to the normal dialog processing stack (via `Conversation.SendAsync`, which is causing the active Prompt.Choice dialog to process it), as well as doing some one-off processing of your own to the incoming message.  You generally want to do everything as dialogs or else not use them - kinda using them and kinda not gets really tricky to follow who is processing what.

**Comment by nwhitmont** [comment] 2017-08-28 16:42
@MbV93 Are you using .NET or Node.js SDK? Please provide a code example that demonstrates your issue.

**Comment by nwhitmont** [comment] 2017-08-31 23:58
@MbV93 Are you using .NET or Node.js SDK? Please provide a code example that demonstrates your issue.

**Comment by JasonSowers** [comment] 2017-09-01 15:57
Closing this issue as the OP is unresponsive, please continue the conversation and we will reopen if needed.

**Closed by JasonSowers** 2017-09-01 15:57 UTC
Labels: prompts, question

**Comment by troublehacker** [comment] 2017-12-01 14:48
I'm having this issue and aim using Node.js. 
im using this in triggerAction 
```
matches: /help/i,
    onSelectAction: (session, args) => {
        session.beginDialog(args.action, args);
    }
```
but instead it going back to the calling dialog and reprinting the previous messsage its saying 

> I didn’t understand. Please try again.

**Comment by csalexwilliams** [comment] 2018-03-14 00:25
@Stevenic Also having this issue. It'd be great to know if this can be resolved in any capacity.

For clarity, here's an example of the the code that triggers the issue:
```javascript
   that.bot.dialog('switchTasks', [
      function (session, args) {
        that.prompt(session, 'choice', 'Are you sure you want to switch to the easier tasks? You can tell me \'yes\' or \'no\'.', ['yes', 'no'], 'none');
      },
      function (session, results, next) {
        if (results.response.entity.toLowerCase() === 'yes') {
          session.endDialog('This should transition the user to the easier tasks.');
        } else { // otherwise, reprompt
          session.endDialog('Great. Just stay focused!');
        }
      },
    ]).triggerAction({
      matches: /^taskSwitch$/,
      onSelectAction: (session, args) => {
        session.beginDialog(args.action, args);
      },
    });
```

When either of the `session.endDialog("...")` instances are fired, the bot returns two messages. The first message is the message sent as a parameter with `endDialog()` and the second message is `I didn't understand. Please try again.`

Happy to help provide additional information if it can help.

**Comment by csalexwilliams** [comment] 2018-03-14 00:42
For those that visit this issue in the future, I've found a workaround. Instead of using my example code from above, I ended-up switching my code to the following:

```javascript
   that.bot.dialog('/', [function (session, args, next) {
     .... 
      ]).beginDialogAction('taskSwitchAction', 'switchTasks', {
      matches: /^taskSwitch$/i,
    });

   that.bot.dialog('switchTasks', [
      function (session, args) {
        that.prompt(session, 'choice', 'Are you sure you want to switch to the easier tasks? You can tell me \'yes\' or \'no\'.', ['yes', 'no'], 'none');
      },
      function (session, results, next) {
        if (results.response.entity.toLowerCase() === 'yes') {
          // TODO: Add an API call here to our system to transition the user to an easier task.

          session.endDialog('This should transition the user to the easier tasks.');
        } else { // otherwise, just send a dummy message.
          session.endDialog('Great. Just stay focused!');
        }
      },
    ]);
```

 ... and shockingly, it worked. For whatever reason, the `onSelectAction` yields some odd behavior. @Stevenic @nwhitmont Not sure if this is by design, but it is quite confusing. :(

**Comment by OptimusRhine** [comment] 2018-03-19 22:02
Thanks @csalexwilliams ! I encountered the same issue, and switching over to a `beginDialogAction` approach worked (in that it properly repeats the last step before the triggered help dialog, and doesn't show that "I didn't understand. Please try again." message.

Also unclear if this is a bug with `onSelectAction` or by design - if it's design, it's not very clear in [the documentation](https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-dialog-manage-conversation-flow#respond-to-user-input).
