### ISSUE TITLE
Bot Not Responding On Kik

### ISSUE THREAD

**Issue by JamieREvans** [Microsoft/BotBuilder#2025] opened 2017-01-12 17:47 UTC
I have a bot that is available on Kik, Slack and Facebook. I can interface with my bot on Slack, Facebook and the MS web interface, but Kik has been unresponsive since Jan 11th.

When I send a message to my bot, it marks it as read, but no message is sent back. I can validate that the message comes through to my API and I send out a response to MS through the botbuilder without an error, but nothing is being sent back to me in Kik.

Also, there are no new errors in my MS console for the Kik platform.

**Comment by dandriscoll** [comment] 2017-01-12 20:19
Hi @JamieREvans, there's an issue in our adapter that we are deploying ASAP. Sorry for the interruption.

**Comment by JamieREvans** [comment] 2017-01-12 20:35
Thanks @dandriscoll

**Comment by dandriscoll** [comment] 2017-01-13 03:27
Hi again @JamieREvans, we published a fix for this earlier this evening -- other customer reports indicate this has been fixed. Closing this now as the problem is resolved. Please at-mention or open a new issue if you encounter further problems. Thanks for your patience as we resolved the interruption.

**Closed by dandriscoll** 2017-01-13 03:27 UTC

**Comment by kureikain** [comment] 2017-02-15 18:03
Hi @dandriscoll Sorry for commenting on an old issue? My bot is working fine in Webchat, Emulator and Slack but not on Kik. Is there an issue or maybe I'm doing something wrong?

**Comment by dandriscoll** [comment] 2017-03-08 17:36
Hi @kureikain, can you open a new issue for this?

**Comment by bkeller2001** [comment] 2017-09-01 02:05
Hey @dandriscoll can you help with the roleplay bot

**Comment by EricDahlvang** [comment] 2017-09-01 17:51
@bkeller2001 

Please open a new issue https://github.com/Microsoft/BotBuilder/issues/new .  

This issue is closed.
