### ISSUE TITLE
[Question] Best practices for implementing weather bot dialog flow?

### ISSUE THREAD

**Issue by Guedria-Rym** [Microsoft/BotBuilder#3366] opened 2017-08-22 14:00 UTC
Hi everyone, 

I'm developping a meteobot with Microsoft bot framework that returns the current weather conditions, or in future periods. By conditions I mean temperature, wind speed.... For that matter, I am using LUIS prebuilt domain weather to map user intents to Weather.GetCondition or Weather.GetForecast.  

I imagined a scenario like this : 

![image](https://user-images.githubusercontent.com/24191982/29569049-9f08bf3a-8752-11e7-9461-5752d0f0ea41.png)

I tried searching what I can use for this purpose, but I can't quite understand the use of each of this feaures and the best one to use in my case : Form Flow, Dialog invoking another dialog, conversation flow with a waterfall??? 

I am developping the bot with .net SDK. 
Can someone please explain to me the difference between these features and the most suitable one for my case? 
Thank you!

**Comment by JasonSowers** [comment] 2017-08-22 15:06
Duplicate of
https://stackoverflow.com/questions/45819853/best-method-to-modelize-a-weather-request

**Comment by nwhitmont** [comment] 2017-08-23 18:06
@Guedria-Rym Check out @EricDahlvang 's awesome blog article showing how to make a great weather bot here: https://github.com/EricDahlvang/AdaptiveCards-WeatherBot/blob/master/blog/markdown/AdaptiveCard-WeatherBot.md

**Code Example**
- .NET: https://github.com/EricDahlvang/AdaptiveCards-WeatherBot
- Node.js: https://github.com/nwhitmont/botframework-luis-adaptive-cards-weather-example

**Comment by Guedria-Rym** [comment] 2017-08-23 21:24
@nwhitmont  Thaaaank you!! that will surely get me on the right track!

**Closed** 2017-08-23 21:26 UTC
Labels: .NET SDK, LUIS, question
