### ISSUE TITLE
/api/tokens responds with 405 Method Not Allowed

### ISSUE THREAD

**Issue by J3QQ4** [Microsoft/BotBuilder#1556] opened 2016-10-31 11:18 UTC
According to the docs here - https://docs.botframework.com/en-us/support/embed-chat-control2/ - to get a secret token for a web chat you need to issue a GET request to /api/tokens and it will return the token. 

However, a GET request to that endpoint returns a 405 Method Not Allowed error now. Same if I try POST or another method. 

How to reproduce: 

1) Open Postman in Chrome
2) Set address to https://webchat.botframework.com/api/tokens, method = GET
3) Set the header to Authorization: BotConnector RCurR_XV9ZA.cwA.BKA.iaJrC8xpy8qbOF5xnR2vtCX7CZj0LdjAPGfiCpg4Fv0 (this is a sample value from the docs)

Result: error 405. 
`{ "message": "The requested resource does not support http method 'GET'." }`

**Comment by dandriscoll** [comment] 2016-10-31 14:04
Yes, this looks like a regression. We will have it fixed shortly.

**Comment by dandriscoll** [comment] 2016-10-31 15:55
This should be working in all of our datacenters now. Can you try again and let me know if it's failing.

**Comment by dandriscoll** [comment] 2016-10-31 22:06
Closing this issue as it's reportedly solved for many callers. Please comment or open a new issue if you see additional problems.

**Closed by dandriscoll** 2016-10-31 22:06 UTC
