### ISSUE TITLE
[Emulator] Changing the user name has no effect

### ISSUE THREAD

**Issue by AmineI** [Microsoft/BotBuilder#619] opened 2016-07-09 03:16 UTC
in the new (V3) emulator, changing the user name doesn't change anything, and the JSON data of sent (or received, in the recipient field) messages is always showing

```
  "from": {
    "id": "ARandomIdHere",
    "name": "User1"
  }
```
regardless of the entered user name.

**Comment by willportnoy** [comment] 2016-07-12 18:23
I was unable to reproduce this error with version 3.0.0.57 of the emulator.  Maybe it's been fixed?

**Comment by AmineI** [comment] 2016-07-12 19:23
Ah, I should have said that I'm using the node.js version of the bot builder ? I think it doesn't matter since even without a bot launched it still shows "User1"
With version 3.0.0.57 it's still happening on my side. Here is a [screenshot](http://imgur.com/a/aAd7u) . I tried to change the user name before clicking on the "New" button but it's still the same. Also, at launch the username field is empty

**Comment by tomlm** [comment] 2016-07-12 20:15
your screen shot is still V54.  Upgrade and let us know

**Comment by AmineI** [comment] 2016-07-12 20:55
My mistake, sorry about this. It's probably already fixed, then, but my computer usually take around a day to notice an update, no matter how many times I launch the emulator.

I'll keep you updated ! 
Thank you for your time and support, too !

**Comment by willportnoy** [comment] 2016-07-12 22:36
Great to hear. :)  I'm going to close this issue, but feel free to open a new issue with any questions.

**Closed by willportnoy** 2016-07-12 22:36 UTC
