### ISSUE TITLE
[Question] Node.js Azure Example - Choice Prompts style options

### ISSUE THREAD

**Issue by pavanagrawal123** [Microsoft/BotBuilder#3224] opened 2017-07-30 18:04 UTC
## System Information (Required)
* SDK Language: NodeJS
* SDK Version: I tried 3.7 and 3.9
* Development Environment: Azure Bot Service

## Issue Description
Buttons are not working.... (The C# example works, NodeJS doesn't)

## Code Example
https://pastebin.com/jHVj1Xx6
```js
/*-----------------------------------------------------------------------------
This template demonstrates how to use Waterfalls to collect input from a user using a sequence of steps.
For a complete walkthrough of creating this type of bot see the article at
https://aka.ms/abs-node-waterfall
-----------------------------------------------------------------------------*/
"use strict";
var builder = require("botbuilder");
var botbuilder_azure = require("botbuilder-azure");
var path = require('path');

var useEmulator = (process.env.NODE_ENV == 'development');

var connector = useEmulator ? new builder.ChatConnector() : new botbuilder_azure.BotServiceConnector({
    appId: process.env['MicrosoftAppId'],
    appPassword: process.env['MicrosoftAppPassword'],
    stateEndpoint: process.env['BotStateEndpoint'],
    openIdMetadata: process.env['BotOpenIdMetadata']
});

var bot = new builder.UniversalBot(connector);
bot.localePath(path.join(__dirname, './locale'));
bot.dialog('/', [
    function (session) {
        // prompt for search option
        builder.Prompts.choice(session, "What language do you code Node using?", ["JavaScript", "CoffeeScript", "TypeScript"], "button");
    },
    function (session, results) {
        session.userData.name = results.response;
        builder.Prompts.number(session, "Hi " + results.response + ", How many years have you been coding?"); 
    },
    function (session, results) {
        session.userData.coding = results.response;
        builder.Prompts.choice(session, "What language do you code Node using?", ["JavaScript", "CoffeeScript", "TypeScript"]);
    },
    function (session, results) {
        session.userData.language = results.response.entity;
        session.send("Got it... " + session.userData.name + 
                    " you've been programming for " + session.userData.coding + 
                    " years and use " + session.userData.language + ".");
    }
]);

if (useEmulator) {
    var restify = require('restify');
    var server = restify.createServer();
    server.listen(3978, function() {
        console.log('test bot endpont at http://localhost:3978/api/messages');
    });
    server.post('/api/messages', connector.listen());    
} else {
    module.exports = { default: connector.listen() }
}
```

## Expected Behavior
Buttons to appear

## Actual Results
List appears (1, 2, 3)

**Comment by nwhitmont** [comment] 2017-07-30 21:00
@pavanagrawal123 To specify the style of the list that is presented to the user, set the [IPromptOptions.listStyle](https://docs.botframework.com/en-us/node/builder/chat-reference/interfaces/_botbuilder_d_.ipromptoptions.html#liststyle) property:

Example:
```js
builder.Prompts.choice(session, "What language do you code Node using?", ["JavaScript", "CoffeeScript", "TypeScript"], "button");
```

For more information on choice prompts, including the available listStyle options, see: [Prompt types > Prompts.choice](https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-dialog-prompt#prompt-types)

**Comment by pavanagrawal123** [comment] 2017-07-30 21:11
hi nhwitmont,

I have implemented that, please see the first function. Yet it doesn't work. Also, I tried adding it to the third one, and it did not work either.

Thanks.

**Comment by stevengum97** [comment] 2017-07-30 22:24
@pavanagrawal123, The documentation is incorrect. You should be passing in an [object](https://docs.botframework.com/en-us/node/builder/chat-reference/interfaces/_botbuilder_d_.__global.iprompts.html#choice), not a string or the enum as the fourth parameter. 

Here's a [link](https://docs.botframework.com/en-us/node/builder/chat-reference/interfaces/_botbuilder_d_.ipromptchoiceoptions.html) to the interface of the object that should be passed in.

Example:
```js
builder.Prompts.choice(session, "What language do you code Node using?", 
  ["JavaScript", "CoffeeScript", "TypeScript"], 
  { listStyle: builder.ListStyle.button });

// or

builder.Prompts.choice(session, "What language do you code Node using?", 
  ["JavaScript", "CoffeeScript", "TypeScript"], 
  { listStyle: "button" });
```

**Comment by pavanagrawal123** [comment] 2017-07-30 22:36
Hi @stevengum97 ,

I just tested both versions provided, only the first version works. The second doesn't work properly, no list or buttons are rendered. 

Also, when I first added the bot service in Azure, the NPM install didn't execute causing the bot to not work. Should I open a separate issue for this? (This was fixed by going into the function and running npm install). I think having NPM install run automatically on the first time would make the experience a bit more fluid.

Thanks.

**Comment by stevengum97** [comment] 2017-07-30 22:37
I'm leaving this issue open until a PR has been filed for the [documentation](https://github.com/Microsoft/bot-framework-docs/blob/master/articles/nodejs/bot-builder-nodejs-dialog-prompt.md) to fix the error.

**Comment by stevengum97** [comment] 2017-07-30 22:40
@pavanagrawal123, thanks for following up. The second method not working.. I'll look into this but it should logically work and I believe has worked in the past. 

For the NPM install not firing right away, that may be due to the provisioning not finishing setup right away if you're attempting to use your bot as soon as it appears to be available. What was the timeline of testing your bot and then accessing the function to run npm install?

**Comment by pavanagrawal123** [comment] 2017-07-30 22:53
hi, I waited about 5min after finishing deployment+bot service initializing, npm install still was not triggered. 

thanks.

**Comment by stevengum97** [comment] 2017-07-31 17:29
@pavanagrawal123, I haven't been able to reproduce the NPM install error... A newly created bot was up and running successfully within 1 1/2 minutes. If it happens again to you, please feel free to open up a new issue regarding this.

**Comment by stevengum97** [comment] 2017-08-10 20:52
[PR 41](https://github.com/MicrosoftDocs/bot-framework-docs/pull/41) for bot-framework-docs merged, closing this issue.

**Closed by stevengum97** 2017-08-10 20:52 UTC
Labels: Azure Bot Service, code examples, documentation, Node.js SDK, question
