### ISSUE TITLE
I have to maintain chat in chat window whenever I switch my web pages. I am using webchat and I have places the webchat on layout.cshtml whenever I am switching to another page my webchat gets refreshed. Is there a way in which I can persist data in my chat window

### ISSUE THREAD

**Issue by rachita0311** [Microsoft/BotBuilder#3283] opened 2017-08-08 06:33 UTC

**Comment by nrobert** [comment] 2017-08-08 12:03
Duplicate of https://github.com/Microsoft/BotBuilder/issues/3284, should be closed please

**Closed** 2017-08-08 16:00 UTC
