### ISSUE TITLE
[Node.js SDK, FB Messenger] Error: Request to 'https://state.botframework.com/v3/botstate/facebook/users/xxxxx' failed: [500] Internal Server Error

### ISSUE THREAD

**Issue by achadha0111** [Microsoft/BotBuilder#3980] opened 2018-01-01 04:36 UTC
## Bot Info
* SDK Platform: Node.js
* SDK Version: v3
* Active Channels: Facebook Messenger
* Deployment Environment: Heroku

## Issue Description
All messages to the bot throw an error similar to this one now *Error: Request to 'https://state.botframework.com/v3/botstate/facebook/users/1161434730636148' failed: [500] Internal Server Error*

**Comment by advl03** [comment] 2018-01-01 11:48
Happy New Year!
It happens the same with my production bot since yesterday. I also use node.js, SDK v3 and Facebook Messenger, deployed in a VM hosted in Azure. This is what I see in the logs:

{"trans":"39429903-0460-4598-8ec2-fe3c0eabda10","corr":"39429903-0460-4598-8ec2-fe3c0eabda10","time":"2018-01-01T10:15:13.716Z","lvl":"ERROR","err":{"message":"Request to 'https://state.botframework.com/v3/botstate/facebook/users/1046304145498637' failed: [500] Internal Server Error","name":"Error","constructor":"Error","stack":"Error: Request to 'https://state.botframework.com/v3/botstate/facebook/users/1046304145498637' failed: [500] Internal Server Error\n    at Request._callback (/opt/botcorn/node_modules/botbuilder/lib/bots/ChatConnector.js:452:46)\n    at Request.self.callback (/opt/botcorn/node_modules/request/request.js:186:22)\n    at emitTwo (events.js:106:13)\n    at Request.emit (events.js:191:7)\n    at Request.<anonymous> (/opt/botcorn/node_modules/request/request.js:1163:10)\n    at emitOne (events.js:96:13)\n    at Request.emit (events.js:188:7)\n    at IncomingMessage.<anonymous> (/opt/botcorn/node_modules/request/request.js:1085:12)\n    at IncomingMessage.g (events.js:292:16)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)"},"msg":"Error: Request to 'https://state.botframework.com/v3/botstate/facebook/users/1046304145498637' failed: [500] Internal Server Error"}

This does not happen in my preproduction environment (hosted in my own VMs).
Could you help me?

**Comment by nwhitmont** [comment] 2018-01-01 18:03
@achadha0111 @advl03 Thanks for reporting - I have forwarded the issue to our platform team for investigation.

**Comment by advl03** [comment] 2018-01-02 08:54
It is working now. What was the problem?

**Comment by fanidamj** [comment] 2018-06-21 23:00
Closing the issue assuming it as resolved. Please reopen a new issue if it still persists.

**Closed by fanidamj** 2018-06-21 23:00 UTC
Labels: FB Messenger
