### ISSUE TITLE
Skype promp confirm dosen't work for group chat

### ISSUE THREAD

**Issue by knpoklonski** [Microsoft/BotBuilder#1748] opened 2016-11-27 17:19 UTC
Hi, I try to use simple confirmation for skype, it works for 1 to 1 chat with bot, but when I use it in group chat I got a attemptsMicrosoft.Bot.Builder.Dialogs.TooManyAttemptsException: too many attempts exception, when I try use same approach to group chat, bot ask me confirmation question again and again

..
 ```
  PromptDialog.Confirm(
                        context,
                        MakeOrderConfirmateAsync,
                        "Are you sure you want to make order?");
```
...
 ```
 private async Task MakeOrderConfirmateAsync(IDialogContext context, IAwaitable<bool> confirmation)
        {
            if (await confirmation)
            {
                string conversationId = context.MakeMessage().Conversation.Id;
                _conversationService.MakeOrder(conversationId);
                await context.PostAsync($"Ok, I've made order, please wait phone call");
            }
            else
            {
                await context.PostAsync("Ok! Order have been cancelled");
            }

            context.Wait(MessageReceived);
        }
```

**Comment by msft-shahins** [comment] 2016-12-02 01:36
@knpoklonski the problem here is that in a group conversation case the text in the activity is `@bot_id <text from user>` and as a result Prompt.Confirm fails matching the response with its possible values (Yes/No). For now, you can work around this by removing the `@bot_id` from activity.Text before sending it to conversation. For example, the code snippet below makes the echo bot work for group conversation cases: 

```csharp
    activity.Text = activity.RemoveRecipientMention();
    await Conversation.SendAsync(activity, () => new EchoDialog());
```

**Comment by msft-shahins** [comment] 2016-12-16 20:33
Closing this issue. Feel free to open a new issue if the issue is not resolved.

**Closed by msft-shahins** 2016-12-16 20:33 UTC
Labels: C#

**Comment by knpoklonski** [comment] 2016-12-16 20:37
@msft-shahins it really works, thank you so much
