### ISSUE TITLE
Locale issue with cardAction.imBack

### ISSUE THREAD

**Issue by strangecyan** [Microsoft/BotBuilder#2312] opened 2017-02-20 15:39 UTC
I'm creating a card that has a button which has a different imBack value than the title of the button.

I need to be able to localise that message (in this case replacing "Can I book a holiday?" with "Can I book a vacation?"). The title is being correctly localised but the message is being sent as 'home_absence_message_book'. Is this how the framework currently works and if it is, can I raise a feature request to change it?

`builder.CardAction.imBack(session, 'home_absence_message_book', 'home_absence_button_book')`

**Comment by Stevenic** [comment] 2017-02-24 01:01
So it's actually by design that the payload isn't being localized.  If you want to localize the payload you can do so pretty easily:

```
builder.CardAction.imBack(session, session.gettext('home_absence_message_book'), 'home_absence_button_book')
```

**Comment by Stevenic** [comment] 2017-02-24 21:55
Closing this for now. Please feel free to add further comments.

**Closed by Stevenic** 2017-02-24 21:55 UTC
Labels: answered, node.js
