### ISSUE TITLE
beginDialogAction doesn't reprompt

### ISSUE THREAD

**Issue by WhiteMaple13** [Microsoft/BotBuilder#4916] opened 2018-07-31 09:43 UTC
## Bot Info
* SDK Platform: Node.js
* SDK Version: Botbuilder 3.15.0
* Active Channels: bot Emulator
* Deployment Environment: local development with Emulator

## Issue Description
I am currently using the Microsoft Bot Framework with node.js to write a bot that traverses a decision tree through an API. I want to allow the user to cancel the tree at any point in the dialog, so that he doesnt have to go through the entire (possibly huge) tree to exit. Because i need to send a message to the API if the session is closed, i am using `Dialog.beginDialogAction()` to start a "cancel"-Dialog, instead of `Dialog.cancelAction()`, so that i can prompt the user to confirm as well as close the session.

Now that i have that in place, canceling the tree works just fine, but if the user chooses to say "no" to the confirmation prompt and the bot should actually re-prompt the last question, it sometimes uses the "no" to answer the previous question automatically (or throws an error). This only appears if the valueType of the question is "string" and a Prompts.choice dialog is shown, for Prompts.number and Prompts.time the expected behaviour is produced.

I have searched any Documentation i could find, but no information about some Prompts not supporting DialogActions or anything like that. I am only using session.beginDialog, session.endDialog, session.endConversation and builder.Prompts to control the dialog stack.

## Code Example
```
//This dialog gets the next question node of the tree passed in args[1].
    bot.dialog('select', [
        function(session, args, next) {
        //Depending on the value type of the question, different prompts are used.
            switch(args[1].valueType) {
                case "string":
                    builder.Prompts.choice(session, args[1].text, args[1].answerValues, {listStyle: builder.ListStyle.button, maxRetries: 0});
                    break;
                case "number":
                    builder.Prompts.number(session, args[1].text, {integerOnly: true, maxValue: 100, minValue: 0})
                    break;
                case "datetime":
                    builder.Prompts.time(session, message + "\nPlease enter a date in the format 'yyyy-mm-dd'.");
                    break;
            }
        },
        function(session, results) {
            //Use the answer to proceed the tree.
            //...
            //With the new question node start over.
            session.beginDialog('select', [sessionId, questionNode]);
        }
    ]).beginDialogAction('cancelSelect', 'cancel', {matches: /^stop$/i});

    //This dialog is used for cancelling.
    bot.dialog('cancel', [
        function(session, next) {
            builder.Prompts.confirm(session, 'Do you really want to quit?');
        },
        function(session, results) {
            if(results.response) {
                finishSession();
                session.endConversation('Session was closed.')
            } else {
                //Here the bot should stop this cancel-Dialog and reprompt the previous question
                session.endDialog();
            }
        }
    ])
```

## Expected Behavior
When the user answers the confirmation prompt of the "cancel"-dialog with "no", the previously asked Question should be reprompted.

## Actual Results
The "select"-dialog continues in the second `function(session, results)` Waterfallstep with the answer "no" if it is a choice-prompt, which leads to unexpected behaviour.

**Comment by EricDahlvang** [comment] 2018-08-01 22:49
Closing as a duplicate of: https://stackoverflow.com/questions/51608852/begindialogaction-doesnt-reprompt

(Please provide a complete example that reproduces the problem.  If in fact this is a bug, we can re-open this.  As of right now, I'm unable to reproduce the problem.)

**Closed by EricDahlvang** 2018-08-01 22:49 UTC
Labels: Node.js SDK
