### ISSUE TITLE
Issue while project build

### ISSUE THREAD

**Issue by HardikShah289** [Microsoft/BotBuilder#968] opened 2016-08-10 17:15 UTC
Error detail:
Cannot implicitly convert type 'System.Net.Http.HttpRequestMessage' to 'Microsoft.Rest.HttpRequestMessageWrapper'

on Windows 10 machine.

**Comment by willportnoy** [comment] 2016-08-10 18:15
We probably would need more information to help you - is this a sample project?

But the compiler error message is correct - those are different types, and they can not be assigned to each other.

**Comment by HardikShah289** [comment] 2016-08-11 18:40
Yes, this is a sample project. I have clone it in my visual studio and try to build. 
Code location: Microsoft.Bot.Connector.Conversations - ReplyToActivityWithHttpMessagesAsync method.
`if ((int)_statusCode != 200 && (int)_statusCode != 201 && (int)_statusCode != 202 && (int)_statusCode != 400 && (int)_statusCode != 401 && (int)_statusCode != 403 && (int)_statusCode != 404 && (int)_statusCode != 500 && (int)_statusCode != 503)
            {
                var ex = new HttpOperationException(string.Format("Operation returned an invalid status code '{0}'", _statusCode));
                ex.Request = _httpRequest;
                ex.Response = _httpResponse;`

The last two line giving error.

**Comment by willportnoy** [comment] 2016-08-12 23:56
Does a fresh git clone also produce the same issue?  I can't reproduce this compiler error locally.

**Comment by HardikShah289** [comment] 2016-08-15 13:27
Yes. A fresh git clone produce this issue. If it is not giving compile error on the code I have posted, then could you please help me to understand how conversion happened between 'System.Net.Http.HttpRequestMessage' to 'Microsoft.Rest.HttpRequestMessageWrapper'.
Something due to Window 10 OS? When I did cloning, I have to restore almost all nugget packages?

**Comment by willportnoy** [comment] 2016-08-15 19:17
The two types are not related - there is a constructor to instantiate the HttpRequestMessageWrapper around the HttpRequestMessage:

https://github.com/Azure/autorest/blob/master/src/client/Microsoft.Rest.ClientRuntime/HttpRequestMessageWrapper.cs#L20

but this should not have anything to do with Windows 10.  @msft-shahins have you seen this error before?

**Comment by willportnoy** [comment] 2016-08-24 01:07
I'm going to close this issue - feel free to open a new issue for further discussion.

**Closed by willportnoy** 2016-08-24 01:07 UTC
Labels: question
