### ISSUE TITLE
Error (502) Bad Gateway: When trying to access chatbot deployed on Azure

### ISSUE THREAD

**Issue by gaganbajaj** [Microsoft/BotBuilder#4613] opened 2018-05-15 13:20 UTC
## Bot Info
* SDK Platform: .Net
* SDK Version: v4.0.30319
* Active Channels: Web Chat, Direct Line
* Deployment Environment: Azure Bot Service, local development with Emulator

## Issue Description
I am developing a chatbot using Microsoft Botframework. Bot works fine when I run it locally with emulator. How ever when I deploy it on Azure as bot service and try to access it using web chat channel it start giving 502 error. I am tried following steps to deploy it. 

 - Created a resource group in Azure

 - Created a Service Plan in azure

 - open url https://dev.botframework.com/ and under My bots menu item clicked "Create a bot" button
![createabotnavigation](https://user-images.githubusercontent.com/23055959/40059001-84d15312-5870-11e8-8bdc-3aa081ef41d2.png)

 - "Create a bot" page takes me to Azure Bot Service page

 - On Azure Bot service page I select "Web App Bot"
![azurebotservice](https://user-images.githubusercontent.com/23055959/40059016-90998fa2-5870-11e8-9264-828498e0ece9.png)

 - On clicking "Create" Azure ask me few details such as Bot Name, Resource group, App Name etc and 
   creates a Bot

 - In this new Bot when I go to "Test in Web Chat" and type something it gives me a response back.

 - Now I took app id and secret key from Settings and add it to web config file.

 - Now I publish my bot from Visual Studio selecting new bot service as app service

 - Publishing is successful

 - Now when I try to access my bot in Test in Web Chat window in Azure,messages start getting failed
![testinwebchatfailedmessage](https://user-images.githubusercontent.com/23055959/40059072-b2ff3b14-5870-11e8-8e54-95b7a3a9817e.png)

 - I have taken the web chat link from channel section and paste it on html page and updated secret key 
   for web chat

 - Now when I send a message I start getting (502) bad gateway error in console.
![webchathtml](https://user-images.githubusercontent.com/23055959/40059091-c15d5fc4-5870-11e8-833e-4b3b4c97e1ff.png)

I have deployed bots in the past as well but at that I was using dev.botframework.com for configuring bots. 

This is first time I am trying to deploy it on Azure Bot service and don't know what am I missing here.

Can someone help me with this?

## Expected Behavior
I must get a correct response from Bot

## Actual Results
Getting 502 (Bad Gateway) error.
https://webchat.botframework.com/v3/directline/conversations/lFKAUFQCteN92X9B1TmX/activities

**Comment by JasonSowers** [comment] 2018-05-15 16:27
Duplicate of https://stackoverflow.com/questions/50351005/error-502-bad-gateway-when-trying-to-access-chatbot-deployed-on-azure-using-w

**Closed** 2018-05-16 22:30 UTC
Labels: .NET SDK, Direct Line, WebChat
