### ISSUE TITLE
Image is replaced with URL when I send MMS via Twilio channel in Bot Framework nodejs

### ISSUE THREAD

**Issue by gjadhav-saviant** [Microsoft/BotBuilder#4461] opened 2018-04-12 11:06 UTC
## Bot Info
* SDK Platform:  Node.js 
* SDK Version: 3.11.0
* Active Channels: SMS (Twilio)
* Deployment Environment:  Azure Bot Service

## Issue Description
I am configuring a Twilio channel for BOt. I want to send MMS using this Bot to user. But Image which is attached in Bot framework, is replaced with a URL . Here is How I'm sending the MMS.

## Code Example
fs.readFile(attachmentUrl, function (err, data) {
       var base64 = Buffer.from(data).toString('base64');
       var msg = new builder.Message().address(address1)
          .addAttachment({
          contentUrl: util.format('data:%s;base64,%s', contentType, base64),
                   contentType: contentType,
                   name: 'BotFrameworkLogo.png'
                });

           bot.send(msg, function (err, addresses) {
                callback(err, addresses);
           });
    });

## Expected Behavior
![screenshot_20180412-162407](https://user-images.githubusercontent.com/36293672/38673657-90ab42c6-3e6f-11e8-8018-8511370f4a55.png)

## Actual Results
![mufya](https://user-images.githubusercontent.com/36293672/38673681-a1e52570-3e6f-11e8-8aab-c7d72a03dd5c.png)

**Comment by JasonSowers** [comment] 2018-04-12 16:31
Closing as duplicate of https://stackoverflow.com/questions/49794645/image-is-replaced-with-url-when-i-send-mms-via-twilio-channel-in-bot-framework-n

**Closed by JasonSowers** 2018-04-12 16:31 UTC
Labels: Node.js SDK, Twilio SMS
