### ISSUE TITLE
[Skype, Azure Bot Service] No Skype metrics in the Bot analytics

### ISSUE THREAD

**Issue by herrspiess** [Microsoft/BotBuilder#4769] opened 2018-06-20 09:46 UTC
Hello everybody,

we would like to observe the metrics for our Bot Framework bots in the Microsoft Azure portal. But in the analytics section we can only find metrics for Kik and Telegram. Skype is missing, although there are multiple Skype users.

Any ideas?

Our subscription ID: 4abe19a3-a03b-4c74-9b8b-49878b010bea

Thanks,
Timo

**Comment by nyxsys** [comment] 2018-06-20 19:19
How long did you wait between the users sending messages to your bot and checking the analytics? It takes about a day for this information to be published to the bot, so it may not have propagated by the time you checked. That said, I am confirming if the Skype analytics are accessible myself, and I will have more information on this one way or the other tomorrow.

**Comment by nyxsys** [comment] 2018-06-21 20:03
So I've confirmed that this is recreate-able, could you please send me your botID so we can look into this a bit further?

**Comment by nyxsys** [comment] 2018-06-21 23:33
We are currently looking into the root cause of this, I will update this issue when we find a fix.

**Comment by ogarules** [comment] 2018-06-27 17:09
Same here, but on Skype for Business, no analytics for this channel

**Comment by rjgmail88** [comment] 2018-06-27 18:18
Same issue. No anyltics for skype, cortana and ms teams.

**Comment by EricDahlvang** [comment] 2018-07-10 16:58
Analytics not showing is being tracked here: https://github.com/Microsoft/BotBuilder/issues/4500  I'm closing this issue as a duplicate.  Please follow along @ #4500

**Closed by EricDahlvang** 2018-07-10 16:58 UTC
Labels: Azure Bot Service, Skype, duplicate-bug
