### ISSUE TITLE
[State Service] How to save conversation with Azure Cosmos DB in C#?

### ISSUE THREAD

**Issue by amarrero45** [Microsoft/BotBuilder#3990] opened 2018-01-04 01:23 UTC
## Bot Info
* SDK Platform: .Net
* SDK Version: 3.12.2.4
* Active Channels: 
* Deployment Environment:  Local with Emulator

## Issue Description
If the QnA Maker returns "No Match Found", I would like to save the question asked by the person into an Azure Cosmos DB. If Qna Maker returns an answer, I would like to save that question into an Azure Cosmos DB, also.

I have implemented the Azure Cosmos DB to store and manage my bot’s state data, just like the article that was published by Microsoft here. In addition, I intercept and log messages like that the article that was published by Microsoft here.

However, no question or answer has been saved into Azure Cosmos DB. There are many examples to do this in Node.js but none for C#. Is saving the bot's state data the correct method or is it another method?

**Comment by nwhitmont** [comment] 2018-01-04 14:12
Duplicate of https://stackoverflow.com/questions/48087096/how-to-save-conversation-with-azure-cosmos-db-in-c

**Comment by JasonSowers** [comment] 2018-01-04 16:35
Have you looked at the [samples in the botbuilder-azure repo](https://github.com/Microsoft/BotBuilder-Azure/tree/master/CSharp/Samples/DocumentDb).  Let us know if that helps.

**Comment by EricDahlvang** [comment] 2018-02-16 18:40
Closing due to inactivity.  Please open a new issue if you require further assistance.

**Closed by EricDahlvang** 2018-02-16 18:40 UTC
Labels: .NET SDK, QnA Maker, state service
