### ISSUE TITLE
[ABS, Bug] Unable to change Bot Icon at azure

### ISSUE THREAD

**Issue by Shadow85Pl** [Microsoft/BotBuilder#4712] opened 2018-06-07 06:10 UTC
## Bot Info
* SDK Platform: .Net
* SDK Version: 3.15.2.2
* Active Channels: MS Teams, WebChat
* Deployment Environment:  Azure Bot Service

## Issue Description
I'm unable to change bot icon from azure portal.    

## Reproduction Steps
1. Set icon for bot service at Settings tab and save
2. Try to change icon to different image

## Expected Behavior
Bot icon change. Save button is grayed out.

## Actual Results
Nothing happen, icon is not changing. Save and discard buttons are  active, there is no visible exception shown. At browser console i can see:

> [Microsoft_Azure_BotService]  07:39:04 Resource/ResourceArea 19 ResourceArea: patch bot service failed
[Microsoft_Azure_BotService]  07:39:04 Resource/BotSettings/BotSettingsBlade 13 BotSettingsBlade: Failed patching resource entity _errorData: undefined
[Microsoft_Azure_BotService]  07:39:04 Resource/BotSettings/BotSettingsBlade 12 BotSettingsBlade: Failed refreshing resource entity _errorData: undefined
[Microsoft_Azure_BotService]  07:39:12 MsPortalFx.Base.Diagnostics.ErrorReporter 1 MsPortalFx.Base.Diagnostics.ErrorReporter: _errorData: undefined
(...)

**Comment by stevengum97** [comment] 2018-06-07 16:32
@Shadow85Pl, I haven't been able to reproduce this behavior. If you don't mind, can you review the following questions and report back with your answers?

1. Can you confirm the file is a .PNG and below 30KB max? What size is your icon?
2.  Are you the owner or an admin of the bot?
3. If you have been logged into the Azure portal for a while, have you tried logging out and then back in before trying to change the icon?

**Comment by Shadow85Pl** [comment] 2018-06-08 05:46
Hi @stevengum97, thank you for response. 
1. Firstly I set this image as bot icon:
![untitled](https://user-images.githubusercontent.com/23506332/41140367-6a39ab64-6aed-11e8-9d9d-d45a5ba2f659.png)
Then I try to change it to:
![untitled1](https://user-images.githubusercontent.com/23506332/41140385-8cddd50a-6aed-11e8-84ad-963837f5d1ef.png)
And that proces failed. Both are PNG, and second one is 4,29Kb size.
2. I'm the owner
3. Yes I tryed to relog, I also tryed to use three different browsers. 

I even try to do some tests:
1. Deploy new instance of web app bot, SDK v3, Basic C# Bot
2. Set first image as bot icon
3. Set second image as bot icon

3rd step failed.

**Comment by stevengum** [comment] 2018-06-12 19:48
@Shadow85Pl, sorry for the delay... We've got a repro now and are investigating the issue.

**Comment by stevengum** [comment] 2018-06-21 23:03
Minor update, this issue is in our backlog.

**Comment by libihan** [comment] 2018-07-25 06:03
Hello, I meet the same problem.
It suddenly happended. And I try different account and different bot, the problem reamained. (Since early July)

**Comment by JasonSowers** [comment] 2018-10-01 20:39
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team

**Closed by JasonSowers** 2018-10-01 20:39 UTC
Labels: Azure Bot Service, bug
