### ISSUE TITLE
[Skype] Group conversations: mention is not removed from Text in RemoveRecipientMention

### ISSUE THREAD

**Issue by nrobert** [Microsoft/BotBuilder#3067] opened 2017-06-30 14:22 UTC
## System Information
* SDK Language: C#
* SDK Version: BotBuilder 3.8.3 (latest NuGet package)
* Development Environment: Localhost.
* Channel: Bug on Skype, OK on Slack

## Issue Description
There is a bug on the way the `Mentions` are managed in Skype that is linked to the `<at>` tag that is added in the text of the message.

When you want to get the text of a message without the recipient mention by calling `RemoveRecipientMention`, the mention will not be removed from the text.

## Code Example
The following code is used for the demo below:
```C#
var incomingMessage = context.Activity.AsMessageActivity();

var mentionFound = (incomingMessage.Entities?.Where(entity => String.Compare(entity.Type, "mention", ignoreCase: true) == 0).Select(e => e.Properties.ToObject<Mention>()).ToArray() ?? new Mention[0]).Where(mention => mention.Mentioned.Id == context.Activity.Recipient.Id).FirstOrDefault();
if (mentionFound != null)
{ 
    await context.PostAsync($"Activity.Text= {incomingMessage.Text}" +
        $"\n\nMention.Text= {mentionFound.Text}" +
        $"\n\nAfter RemoveRecipientMention()= { incomingMessage.RemoveRecipientMention() }" +
        $"\n\n\n\nChannelData= { Newtonsoft.Json.JsonConvert.SerializeObject(incomingMessage.ChannelData).Replace("<", "&lt;").Replace(">", "&gt;") }" +
        $"\n\nMention json= {Newtonsoft.Json.JsonConvert.SerializeObject(mentionFound).Replace("<", "&lt;").Replace(">", "&gt;")}"
        );
}
```

## Steps to Reproduce the Issue
1. Deploy your bot on Skype
2. Connect to https://web.skype.com/en/?ecsoverride=developer (or use Skype App but in that case put your mention in the beginning of the message)
3. Create a group conversation
4. In this conversation, type a message with a mention to the bot
5. In the bot code treating this message, call `RemoveRecipientMention()` on the messageText

## Expected Behavior
The Text should not contain the bot name mentioned on Skype when using `RemoveRecipientMention()` on the message text.

## Actual Results
Demo:
Valid on Slack (mention removed successfully):
![image](https://user-images.githubusercontent.com/6305666/27739762-fd68ae22-5daf-11e7-9487-15cb008f2fda.png)

Invalid on Skype:
![image](https://user-images.githubusercontent.com/6305666/27739766-02a572d0-5db0-11e7-8a92-83507e3c24f2.png)

The problem seems to be the mismatch between the `Activity.Text` where the `<at>` tag is not present and the `Mention.Text` which contains it.
As a consequence, the method `Regex` called in `RemoveRecipientMention` cannot do its work.

**Comment by nrobert** [comment] 2017-06-30 14:33
I have a doubt on where this bug should be fixed: can you confirm that it is more a Bot Connector problem than on Bot Builder side?

**Comment by helgeh** [comment] 2018-01-15 17:47
This seems to be an issue with the Node SDK as well. I can not get the bot to work as expected in a group conversation on Skype.

**Comment by helgeh** [comment] 2018-01-15 17:53
Sorry, my bad. I *was* actually able to strip the mention after all.

**Comment by fanidamj** [comment] 2018-06-22 00:20
Closing the issue assuming it as resolved. Please reopen a new issue if it still persists.

**Comment by nrobert** [comment] 2018-06-22 07:28
Why should it be resolved without testing and verifying it is?
Please, issues should not be closed if issue is not checked

**Comment by tgckpg** [comment] 2018-07-04 16:34
This is NOT resolved. I can reproduce this issue.

**Comment by joao29a** [comment] 2018-08-02 04:32
This error still occurs on Skype. `RemoveRecipientMention` does not work as intended.

Any fix?

**Comment by benbrown** [comment] 2018-10-01 16:29
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botbuilder-channels/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team

**Closed by benbrown** 2018-10-01 16:29 UTC
Labels: .NET SDK, Skype, bug

**Comment by nrobert** [comment] 2018-10-01 19:43
Ok, sorry to read that as this bug is more than a year old and it looks like it will not be fixed. 

By the way, for your information, your link about channels is not working (404 not found for https://github.com/microsoft/botbuilder-channels/issues)
