### ISSUE TITLE
[Feature Request] Localize EntityRecognizer regular expressions

### ISSUE THREAD

**Issue by palmerabollo** [Microsoft/BotBuilder#1813] opened 2016-12-07 16:07 UTC
There are some [regular expressions in the `EntityRecognizer`](https://github.com/Microsoft/BotBuilder/blob/master/Node/core/src/dialogs/EntityRecognizer.ts#L65):

```typescript
    static dateExp = /^\d{4}-\d{2}-\d{2}/i;
    static yesExp = /^(1|y|yes|yep|sure|ok|true)/i;
    static noExp = /^(2|n|no|nope|not|false)/i;
    static numberExp = /[+-]?(?:\d+\.?\d*|\d*\.?\d+)/;
    static ordinalWords = 'first|second|...|ninth|tenth';
```

Is there any way to localize the expressions (for example `/^(1|s|si|vale|ok)/i` for spanish) or extend the current ones (for example, to include `please` as a valid expression for our confirm prompts)?

**Comment by Stevenic** [comment] 2016-12-12 10:25
Unfortunately not currently but maybe very soon... I have a `LocalizedRegExpRecognizer` class I'm testing that would potentially solve this issue. the problem is it's not currently part of the core library and I just want to think about it a bit before I make it part of the core.

**Comment by alexsorokoletov** [comment] 2017-01-15 17:02
@Stevenic my .02 on this issue. Before we had full blown localization in the framework, we used a cheat to localize bot to Russian. One of the steps was adjusting these `yesExp`/`noExp` to support multiple different options (to contain anything from yes to yup analogs):

```
builder.EntityRecognizer.yesExp = /^(1|y|yes|yep|sure|ok|true|да|ды|так|конечно|подтверждаю|согласен|ага|верно)/i
builder.EntityRecognizer.noExp = /^(2|n|no|nope|not|false|нет|неа|не)/i
```

Right now, as I see, suggested way to localize yes/no is to use `BotBuilder.json` in custom locale (russian in this situation) but this approach will not have such flexibility in understanding different variations of yes/no.

**Comment by nwhitmont** [comment] 2017-04-18 22:43
@Stevenic any updates on localizing EntityRecognizer regular expressions in Node SDK?

**Comment by stevengum97** [comment] 2017-05-04 22:29
Closing issue as feature has been implemented. However, as of 3.8 there exists a new PromptRecognizers class where Boolean choices are also now localizable. 

Per @Stevenic in [PR 2686](https://github.com/Microsoft/BotBuilder/pull/2686)

>The EntityRecognizer class has largely been replaced with a new PromptRecognizers class in 3.8. Boolean choices are now localizable in 3.8. I'm going to go ahead and take this PR in case people are manually calling EntityRecognizer.parseBoolean()

**Closed by stevengum97** 2017-05-04 22:29 UTC
Labels: enhancement, Node SDK
