### ISSUE TITLE
Facing multiple issues.

### ISSUE THREAD

**Issue by ankitbko** [Microsoft/BotBuilder#355] opened 2016-05-26 18:31 UTC
I am getting an error when luis entity is mapped to a dynamic field with terms in a form. I have created a repo and would try my best to explain it here.
Repo: https://github.com/ankitbko/Bot-Issue355

## Issue 1
Run the bot and send text "Where is London". A Null Reference exception is thrown at `Step.cs` Match method at line ` if (stepState.State == FieldStepStates.SentPrompt)` because stepState is null.

This case works fine if you would comment Line 32 and 33(below) of `CityLuisDialog.cs` and send the same input.
```CSharp
if (result.TryFindEntity("builtin.places.absolute_location", out loc))
                entities.Add(new EntityRecommendation(type: nameof(CityForm.Location)) { Entity = loc.Entity })
```

## Issue 2
In CityLuisDialog.cs L83 `field.AddTerms(airport, Language.GenerateTerms(Language.CamelCase(airport), 3));` change 3 to 5.
Send text "Where is London". The following exception is thrown at `Recognize.cs` AddExpression method at `_expressions.Add(new ValueAndExpression(value, new Regex(expr, RegexOptions.IgnoreCase), maxWords));`

```
"exceptionMessage": "parsing \"(\\b(?:(?:(\\s+meet\\s+\\s+&\\s+\\s+greet\\s+)\\s+\\s+liverpool)|(?:greets?\\s+)\\s+\\s+liverpools?)|(?:meets?\\s+\\s+&\\s+\\s+greets?)|(?:liverpools?)|(?:greets?)|(?:meets?))\\b)|(qqqq)\" - Too many )'s.",
"exceptionType": "System.ArgumentException",
```

**Comment by ankitbko** [comment] 2016-05-27 06:39
On further digging, it seems **Issue 2** is caused only when "(Meet & Greet) Liverpool" is present in the string. It seems parenthesis is the culprit.
**Issue 1** only happens if the bot is unable to map the LUIS entity to just one enum option. It should, as next step, prompt user to clarify the ambiguity from the subset of matches as it happens with _non-LUIS_ flow.

**Comment by chrimc62** [comment] 2016-05-27 18:51
Handling disambiguation from LUIS entities was something I left as a TODO when we first released.  I had started down the path of implementing it, but it was complicated so I left it.  I'm going to take a look at again this weekend and try to get it done.  I'll look into the other issue as well.  Thanks for the nice repros!

**Comment by ankitbko** [comment] 2016-05-27 19:43
@chrimc62 Thanks for the quick response. I didn't knew it was not implemented. I thought since the LUIS entity is just __another way__ to input to the form, it would converge and follow the same path as if the user was entering the input. This is a very required feature, if possible please implement this.

Unrelated to this, what happens if you return false from field validation delegate? 
Also is it possible to display an enum field in form as buttons with images? I see there is a FormButton class, but I didn't get how do I use it.

**Comment by chrimc62** [comment] 2016-05-27 19:47
The meet&greet issue is by design.  The terms are regular expressions so you need to make sure you escape the ()'s if you don't want them to be regular expressions.  If you don't then with the n-grams you can end up with invalid regular expressions.  Your strings also have double spaces which meant the matching was not working right and I've fixed that.  

The issues around initial validation have to do with the way the internal state machine works--for example navigation doesn't really work if you are doing validation of initial inputs.  Agree the feature should be there and I'm working on it.

**Comment by chrimc62** [comment] 2016-05-27 19:55
If you return false from the field validation, the value is not set in the form. @msft-shahins can comment on the button/image issue.  I don't think there is an easy way to do it in the current SDK, but it might be possible through manipulating the buttons after they come out of FormFlow.

**Comment by ankitbko** [comment] 2016-05-27 20:08
@chrimc62 Thanks for quick response. I intended to ask what happens if we return false from SetDefine not validation, since now we return ValidationResult from validation delegate. My bad. I believe it would not define the field, so how does the field behave in this situation and is there any case when we would want to return false?

**Comment by chrimc62** [comment] 2016-05-27 20:13
If you return false while in a form, the step is considered complete and will be skipped.  When processing the LUIS entities the return value is currently ignored, but I will probably be changing that when I take care of your issue.

**Comment by chrimc62** [comment] 2016-06-01 07:31
I have a fix for this and will check-in tomorrow and it should be in our next release.

**Closed by chrimc62** 2016-06-01 07:31 UTC

**Comment by ankitbko** [comment] 2016-06-01 09:50
This is just great. Thanks for quick resolution of the issue. Looking forward to it in action.
