### ISSUE TITLE
Address to send proactive message to slack channel has user info in it

### ISSUE THREAD

**Issue by chinchang** [Microsoft/BotBuilder#4440] opened 2018-04-07 10:54 UTC
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.8.3
* Active Channels: Slack
* Deployment Environment: Own server

## Issue Description
I am trying to do proactive messaging to channels in Slack. I save the `message.address` from a channel message and then everything works fine. My concern is with how the address looks like for a channel:

```
{ id: '4bd4B8n8nbJBKV573b2d60',
      channelId: 'slack',
      user: { id: 's87AsdAD:T043534', name: 'myName' },
      conversation:
       { isGroup: true,
         id: 'fbjBJKBd3:BKJ87878:Bh834234',
         name: 'channelName' },
      bot: { id: 'KHJ9FJK:AISEHI34, name: 'botName' },
      serviceUrl: 'https://slack.botframework.com' }
```

I get this address when I send a message from a channel (with multiple members).

Now, if I want to send back a message to that channel, I need to save an address that has my information (name & id) in it too. If I remove the `user` key from the address, it breaks. Shouldn't `conversation` key be enough?

**Comment by EricDahlvang** [comment] 2018-04-09 23:15
**IAddress** defines user as a required field:  https://docs.botframework.com/en-us/node/builder/calling-reference/interfaces/_botbuilder_d_.iaddress.html  In fact, **conversation** is not required (if starting a new conversation with the user), but user is.

**Comment by chinchang** [comment] 2018-04-11 17:31
That is odd because when sending a message to a group/channel, there is no specific `user` that should be receiving the message.

**Comment by EricDahlvang** [comment] 2018-04-25 17:49
Closing as this is by design.

**Closed by EricDahlvang** 2018-04-25 17:49 UTC
Labels: Node.js SDK, Slack, proactive messages
