### ISSUE TITLE
METRICS: P1 : Build PowerBI Template for Virtual Assistant

### ISSUE THREAD

**Issue by daveta** [Microsoft/BotBuilder#5171] opened 2018-11-13 14:56 UTC
## Plan
- Ryan going to create PowerBI for Virtual Assistant.
- Convert based on Virtual Assistant spec and what's directly usable from other customer engagements.

**Comment by sgellock** [comment] 2018-11-30 21:19
Duplicate of #5148

**Closed by sgellock** 2018-11-30 21:19 UTC
Labels: 4.2, Approved, P1, duplicate-bug
