### ISSUE TITLE
[LUIS] Intents not being recognized in bot

### ISSUE THREAD

**Issue by DigitalD1982** [Microsoft/BotBuilder#3553] opened 2017-10-02 18:37 UTC
## Bot Info 
* Bot handle: 
* App ID: 8f079ba6-3102-41ad-96d5-689656e936a8
* SDK Platform: 6.9.1
* SDK Version: 3.10.2
* Active Channels: Direct Line
* Deployment Environment: ngrok

## Issue Description
My bot was working last week but now it just keeps repeating the root dialog. Not sure if the LUIS intents are just not working or if it's something related to the botframework. I haven't changed any code so I'm kinda perplexed at what happened. Is something broken or down related to LUIS or the botframework? I'd say 1 in every 15 try's will work correctly and intents will be recognized correctly. This happens both in the emulator and with my Direct Line application.

**Comment by stevengum97** [comment] 2017-10-02 19:06
Hello @DigitalD1982, can you provide your LUIS application's ID for further investigation? 

Which region are you sending your LUIS queries to and which SDK (.NET or Node.js) are you currently using?

**Comment by DigitalD1982** [comment] 2017-10-02 19:45
Hey @stevengum97, My LUIS app ID is 658318f0-993a-4d70-9c90-01cf840941a4.

Testing intents seems to work fine in the LUIS console btw.

I'm using Node 6.9.1 and the 3.10.2 version of the botframework.

Thanks!

**Comment by stevengum97** [comment] 2017-10-02 20:55
@DigitalD1982, are you using a custom [State Service](https://docs.microsoft.com/en-us/bot-framework/rest-api/bot-framework-rest-state)? Or are you using the default Bot State Service?

**Comment by DigitalD1982** [comment] 2017-10-02 20:59
@stevengum97 Just using the default state service that is part of ChatConnector.

**Comment by stevengum97** [comment] 2017-10-02 21:00
Can you try adding the following code to your bot and seeing if your're able to navigate past the root dialog?

`bot.set('storage', new builder.MemoryBotStorage());`

**Comment by DigitalD1982** [comment] 2017-10-02 21:07
I did see that recommended somewhere else. Unfortunately it didn't seem to help.

Any other suggestions? I did at one point today re publish my luis model (without any changes) and then the intents worked once but not again. Kinda why I think something is strange happening on that end.

**Comment by DigitalD1982** [comment] 2017-10-02 21:10
Just tried publishing the model again to see if that would make it work again. Didn't work this time.

**Comment by stevengum97** [comment] 2017-10-02 21:20
Can you log out the results from your LUIS calls? To do it at the point when the response is received, just add a `console.log(result);`  in between line 89 and 90 of [LuisRecognizer.js][RecognizerL90].

```js
result = JSON.parse(body);
console.log(result);
result.intents = result.intents || [];
```

The reason for this is if we can verify that the results are the same as the results you receive while testing via the portal/LUIS console, then somehow the issue is with the bot. It doesn't sound like this is the case but it doesn't hurt to test this out.

If the results are different between the bot and what you see in the portal, then there's a problem with LUIS that needs to be delved more deeply into.

___

This next ask will sound a bit strange; have you tried hitting your endpoint in different browsers and different browsing modes? If so, are you receiving different scoring patterns from LUIS?
  
  [RecognizerL90]:https://github.com/Microsoft/BotBuilder/blob/master/Node/core/lib/dialogs/LuisRecognizer.js#L90

**Comment by DigitalD1982** [comment] 2017-10-02 21:31
Ahha, there it is ;)

"{ "statusCode": 403, "message": "Out of call volume quota. Quota will be replenished in 4.22:15:51." }"

2 questions. Where can I change my call quota and is there anything I can do to have that message appear when debugging? I had to step through LuisRecognizer.recognize to see that.

**Comment by DigitalD1982** [comment] 2017-10-02 21:43
I reached out to the LUIS people via their website about attaching this to our paid azure account.

Appreciate the help @stevengum97! Feel free to close this.

**Comment by stevengum97** [comment] 2017-10-02 21:48
Awesome! And I'm glad it all worked out 👍 

Unfortunately there isn't a way by default in the SDK that shows you the error message. However, copy-pasting your endpoint into a browser and submitting a query will also show the error code. 

Closing issue.

**Closed by stevengum97** 2017-10-02 21:48 UTC
Labels: Direct Line, LUIS, question

**Comment by SawyerRedpath** [comment] 2018-12-19 16:20
> I reached out to the LUIS people via their website about attaching this to our paid azure account.
> 
> Appreciate the help @stevengum97! Feel free to close this.

@dylandepass How did you end up getting ahold of the LUIS people and any other steps taken?

I am having the same issue.

**Comment by EricDahlvang** [comment] 2018-12-20 01:15
Hi @SawyerRedpath 

Some support options are:
https://stackoverflow.com/questions/tagged/LUIS
https://azure.microsoft.com/en-us/support/plans/
and General Inquiry though User Voice

![image](https://user-images.githubusercontent.com/11055362/50257751-7d6e8300-03b1-11e9-9268-98672595acfb.png)
