### ISSUE TITLE
[Question] Error: "Sorry my bot code has an issue" - on sending messages to the bot at the same time from different instances

### ISSUE THREAD

**Issue by PreranaPolekar** [Microsoft/BotBuilder#3235] opened 2017-08-01 09:59 UTC
## System Information (Required)
* SDK Language: .NET
* SDK Version: 3.8.4
* Development Environment: Azure App Service and DirectLine

## Bot Info 
* Bot name: ProgMngmentBotPOC
* Bot handle: progmntbotpoc  
* App ID:  bbc75279-a183-4bb3-a148-b9faee0bcac9

* Connected channels: Directline
## Issue Description
I have hosted my chatbot inside a webapp via DirectLine. Whenever I am trying to run two different instance of this webapp on same or different browser I get "Sorry my bot code has a issue".
It happens only when I try to send messages to both the bots at the same time. I also have noticed that the error message appears on the bot which was 2nd in sending the request.
For Eg : BotA and BotB running at the same time. I send message to BotA and quickly send a message to BotB. Both will process the request and display the result, but "Sorry my bot code has a issue" will appear only on 'BotB'  sent after BotA.
There is no way I can debug this exception. It does not appear in any of the catch blocks in bot. The only log we have is the following : 

**directline.botframework.com/v3/directline/conversations/A9pzYz8BfNfHl2hXTLdyon/activities:1 POST https://directline.botframework.com/v3/directline/conversations/A9pzYz8BfNfHl2hXTLdyon/activities 502 (Bad Gateway)**

**{error: {code: "ServiceError", message: "Failed to send activity: bot returned an error"}} 
error:{code: "ServiceError", message: "Failed to send activity: bot returned an error"} 
code:"ServiceError" 
message:"Failed to send activity: bot returned an error"** 
The bot dashboard reports the error as  **There was an error sending this message to your bot: HTTP status code InternalServerError**

Its very difficult to figure out the reason based on these few error messages. 
What could be the reason for this error? Any way where I can debug this internal error message "Sorry my bot code has an issue" and get the full stacktrace?
Any help or pointers will be highly appreciated.

## Steps to Reproduce the Issue
1.Run the web app in two different instance and send the message at the same time to the bot.
2. It throws "Sorry my bot code has an issue" message in second bot.
3.The execution of the bot continues smoothless despite the error message.

## Expected Behavior
Smooth execution without "Sorry my bot code has an issue" message.

## Actual Results
![boterror](https://user-images.githubusercontent.com/2700711/28819973-8cbe78f0-76cd-11e7-921d-e826d84560da.PNG)
![boterror2](https://user-images.githubusercontent.com/2700711/28820032-c03342ec-76cd-11e7-8a88-798dbe4e506f.PNG)

**Comment by PreranaPolekar** [comment] 2017-08-07 08:26
Any feedback on this from community? Has anyone faced the same issue ?

**Comment by nwhitmont** [comment] 2017-08-08 00:52
@PreranaPolekar Please post the webchat code you are using on your website. 

I you want to have multiple webchat instances, try configuring the WebChat channel and add multiple site configurations there. This way, each iFrame will have a unique key so the bot/user messages won't clash.

Example multiple site definitions in WebChat channel config:
![add multiple webchat site configs - progmngmentbotpoc](https://user-images.githubusercontent.com/3075047/29051673-33ab3890-7b99-11e7-8367-62545a2a4910.png)

**Comment by nwhitmont** [comment] 2017-08-09 21:01
@PreranaPolekar Were you able to solve the issue by setting up multiple Web Chat site configurations? Let me know if you have additional questions.

**Comment by PreranaPolekar** [comment] 2017-08-10 09:54
Hi @nwhitmont, Sorry for delay in response. Sure I will try your suggestion and will get back with my results. Thanks a ton

**Comment by PreranaPolekar** [comment] 2017-08-21 09:00
@nwhitmont any suggestion?

**Comment by fanidamj** [comment] 2017-10-19 19:18
Hoping that issue has been resolved, closing it. Feel free to reopen if any questions.

**Comment by PreranaPolekar** [comment] 2017-11-08 06:02
Nope the issue was not resolved :(

**Comment by Suneethae7** [comment] 2017-11-14 05:32
Hi @PreranaPolekar  did you able to resolved your problem now? . i also have same problem 
help  me

**Comment by nitecloack** [comment] 2017-11-21 13:32
Hi, I'm having similar issue. At start it runs smoothly but after a couple of test from a few people  it started to show bot is having an issue.

**Comment by EricDahlvang** [comment] 2017-11-21 23:33
@PreranaPolekar @Suneethae7 @nitecloack Multiple connections to the Direct Line from different users should not be causing issues. The Microsoft Bot Framework has a multitude of bots doing this on a daily basis, without this issue.

Would one of you please share your bot code, so we can help determine what the issue is exactly?

**Comment by PreranaPolekar** [comment] 2017-11-23 05:29
@EricDahlvang  Exactly! It should be able to handle thousands of users at the same time. Sorry I didn't understand but exactly which part of code you require as I am not sure the root cause of the issue ? Do mean to say the bot ID and password ?

**Comment by EricDahlvang** [comment] 2017-11-23 21:59
If you can **debug this locally**, you should be able to get a stack trace or obtain more information about the error.  This blog post discusses how to debug any channel locally using ngrok: https://blog.botframework.com/2017/10/19/debug-channel-locally-using-ngrok/

**Application Insights** would also provide more detail, with stack traces for errors between the connector service and the bot: https://docs.microsoft.com/en-us/bot-framework/resources-app-insights-keys

If you are able to provide us with a **simplified code example**, it would be useful for us to help diagnose the issue further. (note: secrets and passwords should always be kept private, or someone could impersonate the bot).

**Comment by nwhitmont** [comment] 2017-12-07 19:13
reopen if you're still having issues

**Closed by nwhitmont** 2017-12-07 19:13 UTC
Labels: .NET SDK, Azure App Service, Direct Line, question

**Comment by PreranaPolekar** [comment] 2017-12-29 07:12
Thanks @EricDahlvang .Sorry for delay in reply, was switched to another project. Currently I am not able to work on this but will get back if the issue persists. Thanks again guys :) Happy New Year, Happy Coding :)

**Comment by mehmetbuber** [comment] 2018-06-08 22:13
If anybody experience this issue in the future, i was able to resolve by specifying unique id for user as following.

 BotChat.App({
     bot: { id: '{{Chat_Bot_Id}}' },
     botConnection: botConnection,
     user: { id: {{Any_Unique_ID}} },
     resize: 'detect',
     locale: 'en-en'
 }, document.getElementById('bot'));
