### ISSUE TITLE
[Question] How to use Email channel?

### ISSUE THREAD

**Issue by aakashkag** [Microsoft/BotBuilder#3327] opened 2017-08-15 14:00 UTC
Currently i am using slack channel with bot builder. I want to use email channel, is there any sample code for this. What is effective way to send email from bot to avoid spam I am using node js

**Comment by nwhitmont** [comment] 2017-08-15 15:59
@aakashkag You can find out more about how to configure the Email channel here:
https://docs.microsoft.com/en-us/bot-framework/channel-connect-email

## Connect a bot to Office 365 email
>Bots can communicate with users via Office 365 email in addition to other channels. When a bot is configured to access an email account, it receives a message when a new email arrives. The bot can then respond as indicated by its business logic. For example, the bot could send an email reply acknowledging an email was received with the message, "Hi! Thanks for your order! We will begin processing it immediately."

Step 1: Create new Microsoft email account for your bot. 
Step 2: Configure Email channel in Bot Portal at https://dev.botframework.com

**Comment by JasonSowers** [comment] 2017-08-15 16:00
Closing as duplicate of https://stackoverflow.com/questions/45694405/how-to-use-email-channel-in-microsoft-bot-builder

**Closed by JasonSowers** 2017-08-15 16:00 UTC
Labels: Email, Node.js SDK, question
