### ISSUE TITLE
[Bot Deployment] Understanding error: “Post to HRSurveySSLBot failed : POST to bot’s endpoint failed with HTTP status 401”.

### ISSUE THREAD

**Issue by Tushti02** [Microsoft/BotBuilder#3852] opened 2017-11-30 08:00 UTC
We are facing an issue while deploying the bot on IIS. It gives an error (as in telegram) “Post to HRSurveySSLBot failed : POST to bot’s endpoint failed with HTTP status 401”.

We are using the registered bot -  App_ID=29eaa0ed-4b42-4055-91fa-5771025c5253 and Password.
(We are sure we have used correct pwd.)
Bot Handle – HRSurveySSLBot.
                                
The bot works perfectly fine while deployed on Azure.

We tried two scenarios (and several other) -
1.	With App Id and Password
Screenshots below - 
![telegram with app id pwd](https://user-images.githubusercontent.com/22979514/33419773-ffd6e742-d5d1-11e7-9a76-7539b302777a.png)

![webchat with app id and pwd](https://user-images.githubusercontent.com/22979514/33419776-0088840c-d5d2-11e7-8b30-b85f4f2ede64.png)

2.	Without App Id and Password 
Screenshots below - 

![telegram without app id pwd](https://user-images.githubusercontent.com/22979514/33419774-000eacd6-d5d2-11e7-9ae0-4abcb6a711f5.png)

![web chat without app id pwd](https://user-images.githubusercontent.com/22979514/33419775-0051ef96-d5d2-11e7-9fc5-8842584df01b.png)

Please also find below bot architecture - 
![botarchitecture](https://user-images.githubusercontent.com/22979514/33419900-875953e4-d5d2-11e7-8d0e-fe60c37d06e6.jpg)

**Comment by msmohan** [comment] 2017-11-30 18:14
@Tushti02 can you please provide more information using the template?
## Bot Info 
* App ID: 
* SDK Platform: 
* SDK Version: 
* Active Channels: 
* Deployment Environment: 

## Issue Description


## Code Example


## Reproduction Steps
1.
2.
3.

## Expected Behavior


## Actual Results

**Comment by nwhitmont** [comment] 2017-11-30 23:42
closing as duplicate of https://stackoverflow.com/questions/47568619/microsoft-bot-framework-we-are-facing-an-issue-while-deploying-the-bot-on-iis-p

**Comment by Tushti02** [comment] 2017-12-01 09:11
**Bot Info**
App ID:  29eaa0ed-4b42-4055-91fa-5771025c5253
SDK Platform:   Microsoft.Bot.Builder
SDK Version:   3.11.0
Active Channels:  Webchat,  emulator , telegram (all three tested)
Deployment Environment:  Windows server 2012

**Issue Description**
Facing an issue while deploying the bot on IIS . It gives an error (as in telegram) “Post to HRSurveySSLBot failed : POST to bot’s endpoint failed with HTTP status 401
**Code Example**
(a simple bot just responding with a "Hi" to user )
In MessageController.cs--
 public async Task<HttpResponseMessage> Post([FromBody]Activity activity)
        {
            if (activity.Type == ActivityTypes.Message)
            {
                await Conversation.SendAsync(activity, () => new Dialogs.RootDialog());
            }
        }
In RootDialog.cs--
public class RootDialog : IDialog<object>
    {       
        public Task StartAsync(IDialogContext context)
        {
            context.Wait(MessageReceivedAsync);
            return Task.CompletedTask;
        }
        private async Task MessageReceivedAsync(IDialogContext context, IAwaitable<object> result)
        {
            var message = await result;
            await context.PostAsync("Hi, Welcome to the bot !");
       }
  }
**Reproduction Steps**
Deploy the bot on Azure---works fine
Deploy the bot on IIS (under valid ssl certificate)-- doesn't work (bot doesn't respond back)
**Expected Behavior**
Deploy the bot on Azure---works fine
Deploy the bot on IIS (under valid ssl certificate)-- Should work (bot should respond back)
**Actual Results**
Deploy the bot on Azure---works fine
Deploy the bot on IIS (under valid ssl certificate)-- doesn't work (bot doesn't respond back)

**Comment by JasonSowers** [comment] 2017-12-01 18:33
This is out canned response for those trying to deploy on any cloud provider or on-prem it has some info that may help you.

The Bot Framework works with bots deployed on any cloud hosting service, as long as you have an internet-accessible endpoint and a valid SSL certificate.
The Bot Framework requires that the x.509v3 certificate exposed by your endpoint be current and valid. Most of the checks for "current and valid" are standard checks for server SSL certificates: the Certificate Name must match the hostname, it must not be expired, it must not be listed in a CRL, it must have the correct set of EKUs, etc.
Most importantly, your SSL certificate must chain to a root certificate authority trusted by Microsoft. The latest list of these CAs is available here: http://social.technet.microsoft.com/wiki/contents/articles/31634.microsoft-trusted-root-certificate-program-participants-v-2016-april.aspx
For more information on deploying your bot, see: https://docs.microsoft.com/en-us/bot-framework/deploy-bot-overview
Relates to:
•	https://stackoverflow.com/questions/40888489/bot-framework-without-azure-possible
•	https://stackoverflow.com/questions/44558760/deploy-bot-in-local-iis-and-incle-it-in-custom-chat-in-a-webpage/44571251#44571251

**Comment by Tushti02** [comment] 2017-12-04 06:08
Hi JasonSowers ,
We had 
Keeping in mind about ssl certificate we had deployed application under valid ssl  version 3 certificate.
Still we are facing this problem.

**Comment by fanidamj** [comment] 2018-06-22 00:15
Can you please let us know if the issue still persists?

**Comment by compulim** [comment] 2018-06-26 19:14
I think this is not related to Web Chat.

**Closed** 2018-06-27 14:18 UTC
Labels: .NET SDK, Telegram, WebChat, bot deployment
