### ISSUE TITLE
[LUIS] List Entities (aka Closed Lists) & Intents/Utterances

### ISSUE THREAD

**Issue by paulkp** [Microsoft/BotBuilder#2671] opened 2017-05-01 02:06 UTC
I can already programmatically (or via LUIS.ai GUI) add ClosedList entities.

But can I define these entities in an intent utterance? Not via the GUI so far, but how about programmatically? Just like any other entity?

How else can we use such lists otherwise?

**Comment by nwhitmont** [comment] 2017-05-01 16:52
@paulkp are you using C# or Node SDK for BotBuilder?

**Comment by stevengum97** [comment] 2017-05-01 23:46
@paulkp You don't need to define the List Entities inside of an utterance. List Entities aren't machine learned, but (basically) used for regexp testing. If LUIS detects the the word of a list entity inside of an utterance it will match it to it's Canonical Form. Here's an example of results for a matched list entity from an utterance:

    {
        "entity": "ice cream",
        "type": "Desserts",
        "startIndex": 12,
        "endIndex": 20,
        "resolution": {
            "values": [
                "FrozenDesserts"
            ]
        }
    }

Examining this code excerpt, the `"type"` is the entity name of the List. The `"value"` property in `"resolution"` is the *Canonical Form(s)*, which we can think of it as the ultimate value we want passed to our chatbot. Which in this case is, "FrozenDesserts", which is admittedly not the best example.

Here is the List Entity `"Desserts"` from the .json of my LUIS model:
```
"closedLists": [
    {
      "name": "Desserts",
      "subLists": [
      {
        "canonicalForm": "FrozenDesserts",
        "list": [
          "sorbet",
          "gleato",
          "popsicle",
          "ice cream",
          "sherbet"
        ]
      }
    ]
  }
],
```

In regards to the SDKs there aren't explicit class/methods to handle them *yet*, but they are coming. So it might require a little work to get them out for the time being.

**Comment by stevengum97** [comment] 2017-05-05 21:06
I'm closing this issue, but if there are any questions or comments please feel free to post them here.

**Closed by stevengum97** 2017-05-05 21:06 UTC
Labels: LUIS, question

**Comment by stevengum97** [comment] 2017-05-11 18:28
So disregard my earlier comments about having methods that automatically parse down to the canonical form,  the list entities are the same as regular entities (except for the addition of canonical forms).

Having a method as previously described is a duplicate of the entity finding methods already in the SDKs,  more importantly users are able to manually extract the canonical forms themselves without needing a lot of legwork.

There are no plans for include such methods in the SDK (at least for Node), feel free to post here or in [PR 2735](https://github.com/Microsoft/BotBuilder/pull/2735) that had methods for finding canonical forms.

**Comment by Ishan22687** [comment] 2018-01-23 12:09
Similar to template mode in Dialogflow to enter utterances directly through Entity Names, do we have any thing similar to that in LUIS to add utterances. e.g. instead of adding "How many bananas are available?", can I add "How many <Fruits> are available?" considering Fruits is the entity here.
