### ISSUE TITLE
Bot Framework openUrl not working for suggested action on Facebook Messenger

### ISSUE THREAD

**Issue by MarekLani** [Microsoft/BotBuilder#3147] opened 2017-07-17 15:20 UTC
## System Information (Required)
* SDK Language: NODE
* SDK Version: 3.8.3

## Issue Description
Bot Framework openUrl not working for suggested action on Facebook Messenger

## Code Example
More details and code example, can be found in this [Stackoverflow post](https://stackoverflow.com/questions/45081848/bot-framework-openurl-not-working-for-suggested-action-on-messenger)

**Comment by nwhitmont** [comment] 2017-07-17 17:04
Closing as duplicate of https://stackoverflow.com/questions/45081848/bot-framework-openurl-not-working-for-suggested-action-on-messenger

**Closed by nwhitmont** 2017-07-17 17:04 UTC

**Comment by mabe-at** [comment] 2017-08-06 23:05
When will this work?

**Comment by mabe-at** [comment] 2017-09-21 23:00
Any updates for this issue?
It does not help that there is a similar question (without any solution) on stackoverflow.
