### ISSUE TITLE
[Question] Recognizing intent in Email

### ISSUE THREAD

**Issue by ashice** [Microsoft/BotBuilder#3166] opened 2017-07-20 02:51 UTC
## System Information (Required)
* SDK Language: C#
* SDK Version: 3.8.0.0
* Development Environment: AZURE_APP_SERVICE

## Issue Description
I have deployed a bot and have enabled Skype and Email channels for it. I also tested it using an emulator. So while it recognizes proper intents with Skype and Emulator, it fails to do so on Email. Only one intent is recognized, even if I send utterance related to another intent. The same utterance if made by Skype works without any issue.

## Steps to Reproduce the Issue
1. Create a bot having multiple intents, deploy it on Azure App Service.
2. Converse with Email. It cannot recognize intent.

## Expected Behavior
1. Same behavior as on Skype, intents being recognized.

## Actual Results

 An intent is to get me tasks  and another is to get files. For both it is returning files. **This works fine in Skype. Hence is not a bug with LUIS** ,but cannot even recognize Greeting intent when I sent Hi in Subject of email. It replied back with output of another intent.

**Comment by nrobert** [comment] 2017-07-21 09:21
Email channel can have a lot of "noise" in the text content as it can be html content, there is also the signature, etc.

Can you post some samples of what you are sending, and also the recognition code (or maybe it's done through LUIS)?

**Comment by ashicertis** [comment] 2017-07-21 10:05
You are correct in assuming it is done by LUIS.

I am sending 'Hi' in the email subject and keeping the rest of the email body blank. If I sent the same message 'Hi' via Skye it would activate Greeting Intent and reply back with a message listing the options I have but that doesn't happen if I am using the email channel.

I have also tried sending just Hi in the body, keeping the subject empty or Hi in both subject and body but all return with capturing the same intent which is 'Searching Files'. 

I understand it could be because of the extra html that is being sent to LUIS for recognition. So how can I write code for just capturing email subject or text and sending to LUIS separately for email channel as the setup seems to work fine with Skype?

**Comment by nrobert** [comment] 2017-07-21 11:56
Have a look to the implementation of `LuisDialog`: the `MessageReceivedAsync` is getting the text of the message from `message.Text` ([here]([url](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Microsoft.Bot.Builder/Dialogs/LuisDialog.cs#L279))). If you test with some emails you will see that it only get email body (email subject is accessible using `channelData`).

For your question about being able to log, I think you can use `Text` property of your incoming message like in the MessageController.
Or if you want to enable a better logging tool, implement `IActivityLogger`:

```C#
public class MyLogger : IActivityLogger
{
    public async Task LogAsync(IActivity activity)
    {
        var message = (Activity)activity;

        var infoThatIsSentToLuis = $"{message.Text}";

        // Log where you want

    }
}
```

**Comment by ashicertis** [comment] 2017-07-21 17:51
I thought both body and subject of email was being read by default. I tried sending emails with text in the body of email for which I want intent to be captured but again, wrong intent is captured.

**Comment by nwhitmont** [comment] 2017-07-21 23:54
The message received by your bot will contain the body of the email, not the subject.

How well trained is your LUIS model? Which intent is not getting recognized, and how many sample utterances was it trained with? Is "hi" one of the example utterances used for training your LUIS model? What does your LUIS model look like? Can you export your LUIS model JSON and share it here for reference?

**Comment by JasonSowers** [comment] 2017-07-25 21:52
@ashicertis can you please share your LUIS model App ID so we can have the LUIS team take a look.
  
I have tested an email bot using multiple LUIS intents and was able to produce the expected behavior.  It would really help to see your LUIS model JSON.

**Comment by ashicertis** [comment] 2017-07-25 21:56
@JasonSowers Here is my LUIS Id : df31b88b-a521-4e5e-800a-3819fe5c261f. 
Also you can email my sample deployed bot at ashutosh.sjsu@outlook.com

**Comment by ashicertis** [comment] 2017-07-25 22:37
@nwhitmont I understand that you may need LUIS model JSON to exactly see what's wrong. Please look at attachment for that.
[luis.txt](https://github.com/Microsoft/BotBuilder/files/1174966/luis.txt)

**Comment by ashice** [comment] 2017-07-27 18:21
Any updates on this??

**Comment by nwhitmont** [comment] 2017-07-28 19:29
Hi @ashice 
I imported your LUIS model JSON and tested it in the LUIS website. When I sent "hi" to your model, it detected the "Greeting" intent with 0.88 score.
![greeting intent detected](https://user-images.githubusercontent.com/3075047/28733244-020455da-7390-11e7-99ff-232481fdd209.png)

It's possible you need to train your LUIS model with additional utterances to make the intent detection more precise. 

If you are still having issues, please post your complete bot code, here or in a shared GitHub repository,  so we can better assist you in reproducing the error.

**Comment by ashice** [comment] 2017-07-31 18:50
@nwhitmont The issue lies not with simple LUIS recognition as the Skype channel works fine with the same model but the email channel does not reply with same dialogs as Skype. To confirm I have a bot deployed on Azure. Skype Add -https://join.skype.com/bot/f9cf18d8-9e89-459b-86c2-5ce1840f449a. Also an email can be sent to ashutosh.sjsu@outlook.com. Both are channels for the same bot and must reply with the same responses but in reality they don't . While Skype captures the correct intent, email fails to do so.

**Comment by ashice** [comment] 2017-08-01 22:13
@nwhitmont I had mentioned earlier in the question that Skype channel works fine, Hence probably LUIS is a non-issue. But email channel is causing issues. You can test this using the details provided above.

**Comment by nwhitmont** [comment] 2017-08-03 01:08
@ashice Thanks for the update.

Please post your complete bot code here or in a public GitHub repository if you want further assistance. If you don't share your code, we cannot help you troubleshoot past this point.

**Comment by ashice** [comment] 2017-08-03 22:47
@nwhitmont Why would it behave differently over Skype and other channels and not work on Email?

**Comment by EricDahlvang** [comment] 2017-08-03 23:07
@ashice  Please try using a new @outlook.com email address.

**Comment by ashice** [comment] 2017-08-03 23:18
I changed email from ashutosh.sjsu@outlook.com to tempicmbot@outlook.com. Still similar behaviour.

**Comment by nwhitmont** [comment] 2017-08-04 00:27
Closing as user did not provide their bot code for investigation, and does not want further assistance

**Closed by nwhitmont** 2017-08-04 00:27 UTC
Labels: .NET SDK, Email, LUIS, question, Skype
