### ISSUE TITLE
HeroCard: can not break line in HeroCard.text

### ISSUE THREAD

**Issue by astrung** [Microsoft/BotBuilder#1439] opened 2016-10-15 15:11 UTC
How can i break line in text of HeroCard ? I try by "\n" or by "\n\n" , but nothing helps

**Comment by danmarshall** [comment] 2016-10-17 17:22
Which channel are you using? Do you see the same behavior in the Emulator?

**Comment by reyesrico** [comment] 2016-10-17 22:15
@astrung  HeroCard text support markdown paragraphs. So try it with "\n" for a simple break line or "\n\n" to create a new paragraph.

Here you can see the documentation:
https://docs.botframework.com/en-us/csharp/builder/sdkreference/activities.html

**Comment by astrung** [comment] 2016-10-18 12:58
On bot facebook and emulator channel, it doesn't work

**Comment by astrung** [comment] 2016-10-24 09:30
No one help me :( ? I am still waiting .
Example:
`var card = new builder.HeroCard()
     .title("name")
          .subtitle("company.address")
          .text("Product:"+ myValue +"\n\n"+"Language:" + Array.join(", "))`

**Comment by ravipulluri** [comment] 2016-10-24 12:26
Can you try string builder...
 StringBuilder str = new StringBuilder(); 
                str.AppendLine("**Welcome**");
                str.AppendLine();
                str.AppendLine("to ");

and assign this to hero card....

**Comment by astrung** [comment] 2016-10-26 04:06
How can i find StringBuilder in node js library ?

**Comment by ravipulluri** [comment] 2016-10-26 05:16
can you check this https://www.npmjs.com/package/stringbuilder

**Comment by ravipulluri** [comment] 2016-10-26 15:50
I thought your solution is in .Net

Best Regards,
Ravi Pulluri.
Sent from my Windows Phone
________________________________

**Comment by astrung** [comment] 2016-10-27 02:58
Bot framework channel is broken when send my card in nodejs with stringbuilder library:

        var StringBuilder = require('stringbuilder');
        var str = new StringBuilder();
        str.appendLine("Welcome");
        str.appendLine();
        str.appendLine("to ");
        var card = new builder.HeroCard()
          .text(str)

**Comment by tomlm** [comment] 2016-11-05 16:15
You are mixing two systems.

Technically the herocard attachment *replaces* the text with a rich card. You should fill out the title, subtitle, etc fields the way that you want.

**Comment by chrimc62** [comment] 2016-11-27 00:09
Closing due to age.  We just released a much improved emulator and the markdown should work.  If not, please let us know.

**Comment by pvanaarde** [comment] 2017-05-15 00:06
Hi,
I am having the same problem. Markup works for the normal messages sent back to the user, but doesn't work for the text on a HeroCard. StringBuilder also doesn't work.
This is using the emulator.
Thanks,
Pieter

**Comment by mohit-jcc** [comment] 2017-07-04 12:03
"\n" or "\n\n" does not work on webchat still.

**Comment by swatibhartiya** [comment] 2017-07-06 00:19
Does the Cortana channel not support the markdown text format?

**Comment by nwhitmont** [comment] 2017-07-07 19:54
If you need advanced card formatting options, use [Adaptive Cards](http://adaptivecards.io/visualizer/) instead of the Hero Card template.

**Comment by reyesrico** [comment] 2017-07-10 19:22
We are fixing the breaks in WebChat and Adaptive Cards.

**Comment by nwhitmont** [comment] 2017-07-11 01:23
duplicate of #2583

**Comment by reyesrico** [comment] 2017-07-20 21:35
@nwhitmont prod is now being pushed. Can you please verify if it is solved?

**Comment by JasonSowers** [comment] 2017-07-20 21:45
@reyesrico Ill take a look

**Closed** 2017-07-20 22:17 UTC
Labels: ext-s, help wanted, WebChat

**Comment by danmarshall** [comment] 2017-07-20 23:02
Hi @JasonSowers - does it work with `\n\n` ?

**Comment by JasonSowers** [comment] 2017-07-20 23:08
Nice catch @danmarshall  I'm 99.99% sure i intended to use \n\n instead of \r\r 

using this code:
```cs
                            HeroCard plCard = new HeroCard()
                            {
                                Title = $"test \n\n a hero \n\r card",
                                Subtitle = $" test \n\n Page \n\r test",
                                Text = "test \n\n line 2 \n\r line 3 \r line 4"
                            };
```
I got this result:
![image](https://user-images.githubusercontent.com/6301037/28442543-9b19efb8-6d65-11e7-818b-ce29b0336be5.png)

**Comment by renukatelang** [comment] 2018-03-06 13:37
can any one tell,how can i display list of text in adaptive card?

**Comment by pankajGODB** [comment] 2018-06-28 10:13
For hero card text wrap is not possible?
In Emulator its worked but in fb the same is not working kindly can you guys provide any solution for this

![heroemulator](https://user-images.githubusercontent.com/30646163/42028449-ed50c3fa-7ae9-11e8-8e8d-743d5903ea08.png) ===> Emulator screenshot
![herofb](https://user-images.githubusercontent.com/30646163/42028450-ed85c88e-7ae9-11e8-80a7-704e10dbe534.png) ===> Fb screenshot

**Comment by renukatelang** [comment] 2018-06-28 11:20
Yes we can add

**Comment by pankajGODB** [comment] 2018-07-27 07:05
In Hero card button is not showing suddenly today(27/07/2018) Morning till 11:00 am(5.30 GMT) its was working but now text in hero card button showing as dot marked. Below is the screen

![screenshot 18](https://user-images.githubusercontent.com/30646163/43306656-823e4ba2-9199-11e8-9ee6-157c5e8955b6.png)

Can anyone let me now what has changed for herocard?
