### ISSUE TITLE
[Question] FormFlow Dialogue with Adaptive Card for rendering in the client?

### ISSUE THREAD

**Issue by sowsan** [Microsoft/BotBuilder#3271] opened 2017-08-05 22:06 UTC
Using DirectLine for in the client (Xamarin) to communicate with the bot. Using the adaptiveCard rendering for xamarin and it works fine whenever we send the adaptive card as attachments. Issues starts when we start using the FormFlow dialogue which send the button and control in a HeroCard rather than adaptive card. 

Question #1 : Is there a way that we can tell the FormFlow to send adaptive card instead of Hero Cards ?

Question #2 : Is there a way to render the adapative card by converting the hero card in the client ? .. in my case AdaptiveCard rendering for Xamarin ?

Related but not similar : https://github.com/Microsoft/BotBuilder/issues/2997

**Comment by nwhitmont** [comment] 2017-08-07 22:45
duplicate of https://stackoverflow.com/questions/45496651/how-to-show-hero-card-in-from-bot-in-xamarin-app

**Closed by nwhitmont** 2017-08-07 22:45 UTC
Labels: .NET SDK, Adaptive Cards, FormFlow, question
