### ISSUE TITLE
Email channel is not working

### ISSUE THREAD

**Issue by MbV93** [Microsoft/BotBuilder#3593] opened 2017-10-10 15:21 UTC
## Bot Info
* Bot handle: epTestBot
* App ID: 402574db-395f-4f2d-80fd-a8ca814dd3c9
* SDK Platform: Node.js
* SDK Version: 3.11.0
* Active Channels: Skype, Web Chat
* Deployment Environment: Azure App Service

## Issue Description
Hey, I've been working on a bot for a while, testing it primarily on the email channel and everything had been working fine, but it suddenly stopped responding (Skype and Web Chat are working fine). The "Health" column showed 401 errors on the email channel, I decided to just delete the channel and try to re-enable it and now it won't take any of our company email addresses, it always shows this error:
![image](https://user-images.githubusercontent.com/25651046/31394261-85e7f904-ada3-11e7-8fcb-9359627ffa89.png)
I have tried four different company email addresses which were working with the bot before this week, could it be an issue with our 365 license or did something change recently? Any help would be appreciated.

Thanks.

**Comment by EricDahlvang** [comment] 2017-10-11 00:39
@MbV93 I'm investigating this.  

Please try creating an outlook.com email account, and add it to the email configuration page (just to see if it will save).

**Comment by MbV93** [comment] 2017-10-11 13:52
Just tried it with a new Outlook account, got "Unable to save":
![image](https://user-images.githubusercontent.com/25651046/31444311-7ea851a2-ae61-11e7-85c0-c0e6bd395893.png)

**Comment by EricDahlvang** [comment] 2017-10-11 17:54
Please try registering a new bot, and see if you are able to save the same email address in the email channel configuration for that bot (if it works, we know there is something up with the epTestBot bot in the portal).

You can also try running the Microsoft Exchange Web Services Connectivity Tests from https://testconnectivity.microsoft.com/ and see if they provide any insight into the problem (but, since the new Outlook.com account didn't work, it seems the issue is with the bot and not the email account).

**Comment by MbV93** [comment] 2017-10-11 19:43
I realized the "new" Outlook account I tried to use had been locked for some reason, sorry about that, I had created it a couple of weeks back. I have unlocked and tested it now and it does get saved, so I guess the issue is in fact on our end. Thank you for your assistance Eric, I will keep investigating here.

**Comment by EricDahlvang** [comment] 2017-10-11 21:11
@MbV93 I'm not convinced the issue is on your end.  Please let us know if you determine what the problem is exactly.  This issue has been open for awhile: https://github.com/Microsoft/BotBuilder/issues/3201 

I'll close this one, since 3201 is tracking the email configuration problem until we determine the exact root cause.

**Closed by EricDahlvang** 2017-10-11 21:11 UTC
Labels: Email, Node.js SDK
