### ISSUE TITLE
Bot Framework not showing attaching file icons other than images i.e (.txt/.css/.doc etc)

### ISSUE THREAD

**Issue by RasheedSiriyala** [Microsoft/BotBuilder#1901] opened 2016-12-22 13:24 UTC
Hi,

I'm attaching a file to bot which will be saved in one location.
When i'm attaching image file to bot its showing image icon properly as shown below,
![image](https://cloud.githubusercontent.com/assets/12622554/21426866/4cc4fabc-c877-11e6-9641-573c02adcc67.png)

But when i'm attaching other than image file i.e txt file, its showing like **[File of type 'text/plain']** as shown below
![image](https://cloud.githubusercontent.com/assets/12622554/21426972/e72b9610-c877-11e6-99b4-f7b956736303.png)

Please help me how i can show file icons other than images?

Thanks & Regards,
Rasheed

**Comment by willportnoy** [comment] 2016-12-22 21:25
I would upgrade to the new bot framework emulator here:
https://docs.botframework.com/en-us/tools/bot-framework-emulator/

If you find that it doesn't display a particular image type, I would ask here:
https://github.com/Microsoft/BotFramework-Emulator

**Comment by RasheedSiriyala** [comment] 2016-12-23 06:16
@willportnoy , my current emulator version is v3.5.23. I can able to see image attachments, but when i'm attaching other files (.txt/.css/.doc etc) bot framework not showing attachment icons as in lync as shown below,
![image](https://cloud.githubusercontent.com/assets/12622554/21448142/2f30ca4c-c905-11e6-97d9-00397d4d6f04.png)

I'm expecting icons for all types of attachments from Bot emulator, where it is showing like **[File of type 'text/plain']**.

Can we display attachment icons (other than image files) in Bot Emulator or is it the limitation? If we can how we can display icons?

**Comment by willportnoy** [comment] 2016-12-24 04:59
@eanders-MS can you comment?

**Comment by ashay-88** [comment] 2017-01-12 06:15
Hi @willportnoy , @eanders-MS , 
I would like to add something more here. 
I have both emulator version as of on my machine. v3.0.0.59 and 3.5.23.
Agree with @RasheedSiriyala , it is not showing attachment, but the response I should get from BOT, is missing though I give same input. please find the images. 
Img1 shows latest emulator screen and Img2 shows previous version. 
Img 2 is older emulator.
I found the diff is, when I send "Hi", the usual response which I was sending from BOT, is missing in new emulator, but can be seen in older. 
And ofcourse, attachment card with button is missing. 

![img1](https://cloud.githubusercontent.com/assets/20703721/21878886/258f6992-d8bb-11e6-932a-e4275a543dcc.PNG)

![img2](https://cloud.githubusercontent.com/assets/20703721/21879086/6bc3432e-d8bc-11e6-8539-c0347c3f4fa7.PNG)

Kind Regards,
Ashay

**Comment by eanders-MS** [comment] 2017-01-12 07:01
Hi @RasheedSiriyala The issue you're seeing is a limitation of the new webchat control: https://github.com/Microsoft/BotFramework-WebChat. The control doesn't yet display icons for non-image file attachments. Assigning @danmarshall to follow up.

@ashay-88 I believe what you're seeing is unrelated to this, but does look like a valid issue. Could you please open a separate item for it so that the two aren't conflated here?

**Comment by danmarshall** [comment] 2017-02-17 23:53
@ashay-88 can you still reproduce this issue? There may have been an update to the WebChat which fixes this.

**Comment by ashay-88** [comment] 2017-02-19 06:39
@danmarshall  now when I am using IDialog to reply to conversation using postAsync, issue is not appearing.
I suspect, it could be because of my code. 
Though, I will paste code which I was using, with which I was getting reply on older emulator but not on new one. That bot was without using dialog interface.

**Comment by danmarshall** [comment] 2017-04-11 17:50
This should be fixed in the latest WebChat and Emulator. Thank you all for reporting. Please open a new GitHub issue if you see anything further.

**Closed by danmarshall** 2017-04-11 17:50 UTC
Labels: emulator, enhancement
