### ISSUE TITLE
Sorry, Web Chat isn't available right now. REST API

### ISSUE THREAD

**Issue by ZohaibAhmed** [Microsoft/BotBuilder#65] opened 2016-04-07 00:19 UTC
I'm trying to use the REST API to post a new message to a conversation. I have the appid and appsecret set in the headers, and the AppSecret again as the "Ocp-Apim-Subscription-Key".

This is what I'm sending in the body (as application/json):

```
{
    "conversationId": "DgpGuIDhhFxzA9r3lmChYBLYDhuln54b96GCvd2ufGxR6ba",
    "text": "reply",
    "lang": "en",
    "to": {"id": "3nULzoSf1gI", "isBot": false, "channelId": "webchat", "name": "FlDc6wTmi2q", "address": "ERFLseiCW1w.FlDc6wTmi2q"},
    "from": {"id": "mytestbot", "isBot": true, "channelId": "webchat", "name": "Test", "address": "mytestbot"},
    "totalParticipants": 2,
    "participants": [{"id": "3nULzoSf1gI", "isBot": false, "channelId": "webchat", "name": "FlDc6wTmi2q", "address": "ERFLseiCW1w.FlDc6wTmi2q"}, {"id": "mytestbot", "isBot": true, "channelId": "webchat", "name": "Test", "address": "mytestbot"}],
    "channelConversationId": "JraVllJjSYL",
    "type": "Message"
}
```

The response I get is:

```
{
  "error": {
    "code": "ServiceError",
    "message": "*Sorry, Web Chat isn't available right now.*",
    "statusCode": 404
  }
}
```

Any ideas what's up here?

**Comment by ZohaibAhmed** [comment] 2016-04-07 00:53
Also for the response - I kind of just worked backwards from the node.js stuff. Which fields are required, how should the response look?

**Comment by dandriscoll** [comment] 2016-04-08 20:55
The error indicates that the conversation or user isn't valid for this bot. The contents of the message seem valid, though. Do you see the error if you return this message from your callback instead of issuing a new POST to the Bot Connector?

**Comment by ZohaibAhmed** [comment] 2016-04-08 22:57
This error doesn't show up on the immediate response from the callback, but I was hoping to make a POST request afterwards to add more messages to this conversation (which is where this error occurs).

**Comment by dandriscoll** [comment] 2016-04-08 23:22
OK, I can confirm this is not working on our side. I'll figure out how to fix it. Thanks

**Comment by mikkhait** [comment] 2016-04-08 23:30
It works over `https` but not `http`

**Comment by dandriscoll** [comment] 2016-04-09 04:27
Good to hear :) We had a separate bug in the web chat control that's fixed now, too.

**Closed by dandriscoll** 2016-04-09 04:27 UTC
Labels: bug

**Comment by lsseckman** [comment] 2016-05-25 20:37
Hey so I ended up here, just thought I would drop a note: 

[here](http://docs.botframework.com/builder/node/guides/core-concepts/#navtitle) it has you set the bot to listen on ```/v1/messages``` but [here](http://docs.botframework.com/connector/getstarted/#registering-your-bot-with-the-microsoft-bot-framework) it has you input ```/api/messages/``` as the endpoint for the connection. 

not sure if those should sync up, but it would have saved me a few minutes.

**Comment by tomlm** [comment] 2016-05-26 19:56
It doesn't matter what you use, what matters is the endpoint you register in the portal and that the endpoint you register is handled by your web service.

**Comment by lsseckman** [comment] 2016-05-26 20:01
you're correct, I'm just saying that might not be apparent to people running the example code.

**Comment by lsseckman** [comment] 2016-05-26 20:02
ps - love the Bot Framework

**Comment by pooyadav** [comment] 2016-06-05 13:31
I am getting this error in BOTFramework, 

However, bot works in emulator.
{
    "error": {
        "code": "ServiceError",
        "message": "*Sorry, X isn't available right now.*",
        "statusCode": 404
    }
}

**Comment by ghstshdw** [comment] 2016-10-04 10:08
@lsseckman The two links you've provided show the same /api/messages. How did you work around the problem...I've been stuck on this problem for ages

**Comment by lsseckman** [comment] 2016-10-04 13:41
So if they are the same they may have updated the documentation. My issue was fixed by making sure I was setting /API/messages & then calling it accordingly.

**Comment by ghstshdw** [comment] 2016-10-17 11:00
Thank you Man!...you're a life saver!....i was setting /api/messages... It turns out it MUST be /API.
Thank you

Date: Tue, 4 Oct 2016 06:42:02 -0700
