### ISSUE TITLE
PromptDialog.Choice not working with special characters

### ISSUE THREAD

**Issue by neetgupta7** [Microsoft/BotBuilder#3546] opened 2017-09-29 09:23 UTC
* SDK Platform: .NET
* SDK Version: 3.9.1
* Active Channels: Web Chat, Cortana
* Deployment Environment: Azure App Service

## Issue Description
We are trying to collect feedback for user experience in bot using  PromptDialog.Choice. So user gets 5 options like -
★★★★★
★★★★
★★★
★★
★
But when user clicks on any of the options bot keep asking retry until max. attempts are exhausted. If I add another option (Skip) in the same code and if user clicks that option it works fine.
★★★★★
★★★★
★★★
★★
★
**Skip**
Can you please help here.

## Code Example

```cs
public static class ConstantFeedBack
{
    public const string One = "★";
    public const string Two = "★★";
    public const string Three = "★★★";
    public const string Four = "★★★★";
    public const string Five = "★★★★★";
    public const string NotInterested = "Skip";
}

public static async Task TakeFeedBack(IDialogContext context, string message)
    {
        string reply = await Utility.TranslateToUserLang(context, message + ConstantGeneralMessages.RequestFeedBack);
        //List<string> cnfrmList = await Utility.ConfirmationOptionsTranslated(context);//await Utility.FeedBack(context);
        List<string> cnfrmList = await Utility.FeedBack(context);
        PromptStyler prmptStyler = new PromptStyler(PromptStyle.Auto);
        string retryMsg = await Utility.TranslateToUserLang(context, ConstantGeneralMessages.RetryMessage);
        context.UserData.SetValue<bool>(ConstantConvData.PromptTriggered, true);
        PromptOptions<string> options;
        {
            options = new PromptOptions<string>(
                               prompt: reply,
                               attempts: ConstantAttempt.Attempts,
                               tooManyAttempts: await Utility.TranslateToUserLang(context, ConstantGeneralMessages.AttemptsCrossed),
                               descriptions: cnfrmList,
                               options: cnfrmList,
                               promptStyler: prmptStyler,
                               retry: retryMsg,
                               retrySpeak: retryMsg,
                               speak: reply);
        }
        PromptDialog.Choice(context, PostFeedBackProviding, options);
    }

 public static async Task PostFeedBackProviding(IDialogContext context, IAwaitable<string> result)
    {
        try
        {
            var userResponse = await result;
            string userAlias;
            context.UserData.TryGetValue<string>(ConstantConvData.CustomerID, out userAlias);
            string Count;
            bool value = ConnectToAzureTable.ShouldTakeFeedBack(userAlias, out Count);
            //userResponse = await Utility.TranslateToUserLang(context, userResponse);
            switch (userResponse)
            {
                case ConstantFeedBack.One:
                    ConnectToAzureTable.StoreFeedBack(userAlias, 1, string.Empty, context.Activity.ChannelId, Convert.ToInt16(Count));
                    break;
                case ConstantFeedBack.Two:
                    ConnectToAzureTable.StoreFeedBack(userAlias, 2, string.Empty, context.Activity.ChannelId, Convert.ToInt16(Count));
                    break;
                case ConstantFeedBack.Three:
                    ConnectToAzureTable.StoreFeedBack(userAlias, 3, string.Empty, context.Activity.ChannelId, Convert.ToInt16(Count));
                    break;
                case ConstantFeedBack.Four:
                    ConnectToAzureTable.StoreFeedBack(userAlias, 4, string.Empty, context.Activity.ChannelId, Convert.ToInt16(Count));
                    break;
                case ConstantFeedBack.Five:
                    ConnectToAzureTable.StoreFeedBack(userAlias, 5, string.Empty, context.Activity.ChannelId, Convert.ToInt16(Count));
                    break;                
            }

            string reply = await Utility.TranslateToUserLang(context, ConstantGeneralMessages.PostFeedback + ConstantGeneralMessages.AnyOtherHelp);
            await context.PostAsync(Utility.GenerateMessageActivity(context, reply));
            context.Done<object>(null);
        }
        catch (TooManyAttemptsException)
        {
            await context.PostAsync(ConstantGeneralMessages.TooManyAttempts + ConstantGeneralMessages.AnyOtherHelp);
            context.Done<object>(null);
        }
        catch (Exception ex)
        {
            throw ex;
        }
    }`

**Comment by neetgupta7** [comment] 2017-09-29 09:34
And if I add any alphabet or any number to any choice then it starts working e.g.   "5. ★★★★★";

**Comment by EricDahlvang** [comment] 2017-09-29 21:00
Hi @neetgupta7 

Maybe provide a different list of options, from the descriptions.  Something like:

```cs


List<string> cnfrmOptions = new List<string>();
cnfrmOptions.Add("1:" + ConstantFeedBack.One);
cnfrmOptions.Add("2:" + ConstantFeedBack.Two);
cnfrmOptions.Add("3:" + ConstantFeedBack.Three);
cnfrmOptions.Add("4:" + ConstantFeedBack.Four);
cnfrmOptions.Add("5:" + ConstantFeedBack.Five);
cnfrmOptions.Add(ConstantFeedBack.NotInterested);

options = new PromptOptions<string>(
                    prompt: reply,
                    attempts: ConstantAttempt.Attempts,
                    tooManyAttempts: await Utility.TranslateToUserLang(context, ConstantGeneralMessages.AttemptsCrossed),

                    descriptions: cnfrmList,
                    options: cnfrmOptions,

                    promptStyler: prmptStyler,
                    retry: retryMsg,
                    retrySpeak: retryMsg,
                    speak: reply);

`

**Comment by sphanley** [comment] 2017-10-10 00:55
There's a real old issue open that sounds similar to this, not sure if the discussion there will help: https://github.com/Microsoft/BotBuilder/issues/1949

**Comment by neetgupta7** [comment] 2017-10-11 09:27
@EricDahlvang Do you think this can be added as a bug in the framework and we can expect the fix in future.

**Comment by EricDahlvang** [comment] 2017-10-11 21:32
@neetgupta7 I've added the bug label.  

BotBuilder is open source, and contributions are welcome.  If you find and fix the root cause of this issue, please submit a Pull Request.

**Comment by compulim** [comment] 2018-06-26 19:17
I think this is not related to Web Chat.

**Comment by sgellock** [comment] 2018-10-02 01:51
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team

**Closed by sgellock** 2018-10-02 01:51 UTC
Labels: .NET SDK, Node.js SDK, bug
