### ISSUE TITLE
[Question] Issue with the instruction to create a bot with the Bot Builder SDK for .NET

### ISSUE THREAD

**Issue by lchen1281** [Microsoft/BotBuilder#3090] opened 2017-07-05 22:35 UTC
## System Information (Required)
* SDK Language:  .net
* SDK Version: 
* Development Environment: 

## Issue Description

The instruction to create a bot with the Bot Builder SDK for .NET,
https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-quickstart, mentioned 2017 visual studio community can be used to build bots. But, the bot application template doesn't work with the community.

1. Install Visual Studio 2017 for Windows.
You can build bots for free with Visual Studio 2017 Community.

## Steps to Reproduce the Issue
1.
2.
3.

**Comment by JasonSowers** [comment] 2017-07-05 22:57
Can you please provide more information?  I have personally built bots with 2017 Community

**Comment by lchen1281** [comment] 2017-07-05 23:40
I installed 2017 community, then downloaded the Bot Application template and install the template as instructed. Then open community and create a new C# project, but didn't see the bot application template in the list. I have to switch to enterprise version to use the template as instructed.

**Comment by nwhitmont** [comment] 2017-07-06 01:52
@lchen1281 I'm unable to reproduce this error.  

I installed Visual Studio Community Edition 2017 and downloaded the template as per the documentation article, and was able to create a new project using the Bot Application template without any issues. 

For reference, can you post a screenshot of the error you are seeing when you create the project using Bot Application template in Community Ed.?

**Comment by lchen1281** [comment] 2017-07-07 01:14
The screenshot is just like the one in the documentation, just without the Bot Application showing in the list. I followed the exact step to open create the C# project, but no Bot Application template is shown. I used Mac with OS Sierra 10.12.5 installed Paralell and Windows 10 image. Just FYI.

**Comment by JasonSowers** [comment] 2017-07-20 20:05
@lchen1281  did you ever get this sorted out, or are you still having trouble?

**Comment by lchen1281** [comment] 2017-07-20 20:12
Still had the issue. I switched to enterprise version.

**Comment by JasonSowers** [comment] 2017-07-20 20:57
I am going to close this issue for now, If you would like to continue the conversation please feel free to reopen the issue

**Closed by JasonSowers** 2017-07-20 20:57 UTC
Labels: .NET SDK, question
