### ISSUE TITLE
how to get binary data of image that we have to send in cognitive service api

### ISSUE THREAD

**Issue by hardikchoudhary** [Microsoft/BotBuilder#3223] opened 2017-07-30 16:33 UTC
Hi team

Thanks in advance

microsofComputerVision.orcImage({
    "Ocp-Apim-Subscription-Key": "2b4043ad15ef444eb4b41182c6ac0dab",
    "request-origin":"westcentralus",
    // "content-type": "application/json",
    //"url": "http://cdn.quotesgram.com/img/81/49/660235022-Random-Funny-Quotes-.jpg",
	 "content-type": "application/octet-stream",
      "body": data,
      // "url": attachment.contentUrl,
    "language": "en",
    "detect-orientation": true
}).then((result)=>{
	session.send(result);
});

I am able to get the response data from image as text 
when i pass the normal url
but when i am passing the url as msg.attachments[0].contentUrl getting error image cant be downloaded

so can you please help me in getting the binary data that i can send in body to have the text

**Comment by nwhitmont** [comment] 2017-07-30 16:50
duplicate of #3188

**Closed by nwhitmont** 2017-07-30 16:50 UTC

**Comment by SaumyKukreti** [comment] 2018-09-10 15:09
@nwhitmont , please add the solution to the problem instead of only marking the defect as duplicate.

I checked 3188,3225 and there is no solution on the threads.
