### ISSUE TITLE
[MS Teams] Call to MS Teams connector is failing with certificate expired error?

### ISSUE THREAD

**Issue by gauravnigam1308** [Microsoft/BotBuilder#3957] opened 2017-12-20 00:43 UTC
Call to MS Team connector is failing with the following error:
```
0|_real_ti | Error: certificate has expired
0|_real_ti |     at TLSSocket.<anonymous> (_tls_wrap.js:1085:38)
0|_real_ti |     at emitNone (events.js:86:13)
0|_real_ti |     at TLSSocket.emit (events.js:185:7)
0|_real_ti |     at TLSSocket._finishInit (_tls_wrap.js:603:8)
0|_real_ti |     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38)
```
I analyzed the service URL https://smba.trafficmanager.net/amer-client-ss.msg/ and found, its root certificate got expired yesterday and that is the reason, I am not able to do this over the secure socket. Can you please let me know if you have the plan to update the certificates for this service URL endpoint because we don't want to disable the SSL check for the https URL. 

Please let me know as per the resolution. 

Regards, 
gaurav@workboard.com

**Comment by nigamg** [comment] 2017-12-20 08:18
Sure...
You can easily reproduce it with botbuilder and ms team extension for bot-builder with the following code snippet---

expressRouter.post('/team', connector.listen());
/****
 * Router and bot-builder listener for the message sent from Microsoft team
 * @type {UniversalBot}
 */
let bot = new builder.UniversalBot(connector, function (session) {
session.send("You said: " + session.message.text); 
});

The error is getting stdout on the console.

**Comment by nigamg** [comment] 2017-12-20 08:19
Node SDKs: botbuilder and botbuilder-teams.

**Comment by vicenschamorro** [comment] 2017-12-20 11:14
We are having the same issue, but also for Skype. 
Something has changed this last 24h because yesterday midday (Spain time) it was working fine.

**Comment by hinojosachapel** [comment] 2017-12-20 11:27
I can confirm @nigamg answer:
> You can easily reproduce it with botbuilder and ms team extension for bot-builder.

In our project we get this stack trace:

Error: certificate has expired
console.pub.js:42
    at TLSSocket.onConnectSecure (_tls_wrap.js:1042:34)
    at TLSSocket.emit (events.js:159:13)
    at TLSSocket._finishInit (_tls_wrap.js:639:8)

Yesterday it was working fine :-(

**Comment by hinojosachapel** [comment] 2017-12-20 11:32
I can confirm @nigamg answer:
> You can easily reproduce it with botbuilder and ms team extension for bot-builder.

In our project we get this stack trace:

Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1042:34)
    at TLSSocket.emit (events.js:159:13)
    at TLSSocket._finishInit (_tls_wrap.js:639:8)

Yesterday it was working fine :-(

**Comment by fms-santos** [comment] 2017-12-20 13:49
I'm having similar problem on the Skype Channel. I've created an issue on https://github.com/Microsoft/BotBuilder/issues/3959

**Comment by sinhlt58** [comment] 2017-12-20 13:51
We are having the same issue on the Skype Channel.

**Comment by dandriscoll** [comment] 2017-12-20 14:25
We're investigating this issue now.

**Comment by gleuch** [comment] 2017-12-20 15:05
I can confirm having same issue with SSL connections to smba.trafficmanager.net. Unable to tell if a load balancer issue as we're able to resolve locally but not able to from any servers in AWS us-west-2 (Oregon).

**Comment by PaulDevelter** [comment] 2017-12-20 15:25
MS called me to say this is fixed now, had to restart my webapps though. I can confirm this worked.

**Comment by dandriscoll** [comment] 2017-12-20 15:26
Hi everyone, can you try again?

We were not able to find any expired certificates, but we rolled the entire set and this resolved the issue for all customers we contacted so far.

**Comment by shinta115** [comment] 2017-12-20 15:28
Yes, for us is working now again :)

**Comment by hinojosachapel** [comment] 2017-12-20 15:29
Yes, @PaulDevelter. Our team has confirmed it's working fine again.

**Comment by fms-santos** [comment] 2017-12-20 15:35
I can confirm that after restarting the webapp this issue is now fixed on my chatbot. Thanks guys!

**Comment by coryshaw1** [comment] 2017-12-20 15:39
Also working here after a restart. Thanks!

**Closed** 2017-12-20 15:48 UTC
Labels: MS Teams

**Comment by nwhitmont** [comment] 2017-12-20 15:51
resolved at 12/20/2017 07:48:03 PST

**Comment by nwhitmont** [comment] 2017-12-20 15:52
Thanks @konstlut !

**Comment by nigamg** [comment] 2017-12-20 18:25
working fine after the restart, thank you so much for the prompt resolution, very much appreciated!
