### ISSUE TITLE
Messaging bot via Webchat works, but messaging via FB results in cryptic [400] bad request error

### ISSUE THREAD

**Issue by OptimusRhine** [Microsoft/BotBuilder#4990] opened 2018-08-20 17:39 UTC
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.14.0
* Active Channels: Facebook
* Deployment Environment: Azure App Service

## Issue Description
Bot was previously working fine. As of recently, however, if I send my bot any messages via Facebook, the bot throws a `[400] Bad Request` error (see stack trace in 'Actual Results' below). Note that if I test the bot via Webchat, it works perfectly.
I'd of course love a solution to the problem, but more than that, I'd primarily like to know how to extract the actual full response message from this error, so I can more easily act upon it myself.

## Code Example
```
bot.on('error', function (e) {
    logger.error('An error ocurred: ' + e.message);
    logger.error(e.stack);
});
```

## Reproduction Steps
1. Message the bot through webchat, and successfully receive a response (to show the bot is working as expected)
2. Message the bot through Facebook

## Expected Behavior
Receive a response, and throw no errors on the backend.
Or, if error received, can pull full error response message in the logs.

## Actual Results
No response is received in Facebook, and the bot code throws a 400 error.
```
Error: POST to 'https://facebook.botframework.com/v3/conversations/1639998999382449-140036350003574/activities/0fFQ6h791B7NxXovNkqMsCr5uCHee9wwJbLz5K-SpoFX_ucOF3b2-5tIKwwMhnGzIADv2_BJTpqbdyZ90_TqfQ' failed: [400] Bad Request
    at Request._callback (/home/site/wwwroot/node_modules/botbuilder/lib/bots/ChatConnector.js:559:46)
    at Request.self.callback (/home/site/wwwroot/node_modules/request/request.js:185:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/home/site/wwwroot/node_modules/request/request.js:1157:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/home/site/wwwroot/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickDomainCallback (internal/process/next_tick.js:198:9)
```

**Comment by amitbend** [comment] 2018-08-21 14:16
I'm also seeing issues on the Facebook channel

**Comment by jwiley84** [comment] 2018-08-21 17:45
Hi Optimus! Can I get your App ID, please?

**Comment by OptimusRhine** [comment] 2018-08-21 17:49
@jwiley84 
Sure, it's b892f3d4-821b-49a3-8f0e-511494b448e8.

I just retriggered the error (at UTC 2018-08-21T17:46:59.750Z), so it should be very recent in the logs.

**Comment by jwiley84** [comment] 2018-08-21 18:01
Excellent! Thank you! Investigating now.

**Comment by OptimusRhine** [comment] 2018-08-21 21:07
Hi @jwiley84 ,

The Bot Channels Registration (which the Microsoft App is tied to) is 'quitbotchannel-prod', but the App Service itself (where the botbuilder code resides, and what the Bot Channels Registration "messaging endpoint" setting points at) is 'quitbot-prod'.

No configuration change was made recently - at least, not intentionally (always possible something was accidentally changed at some point). If there *was* a configuration issue there though, wouldn't that stop the Webchat version from working as well? I'm primarily confused as to why that channel is working, while just the FB channel has stopped.

Additionally, we have the same setup working in our test environment (App ID 99188781-e572-4ea8-a9c0-6fbb71a5015c), and everything (including the FB channel) is working as expected there.

Are you able to see the full response body from the [400] Bad Request error? I think that might help shed some light onto what's happening here.

**Comment by jwiley84** [comment] 2018-08-21 23:04
Hi @OptimusRhine! Thank you for the clarification! I can't see full 400s, but if we can't solve this, I'll reach out to someone who might be able to. 
Does your App Service have Application Insights added to it? If not, we can go ahead and give that a shot, to see further information about your request-response from the bot.

**Comment by jwiley84** [comment] 2018-08-22 16:31
Good morning @OptimusRhine! 
My apologies, I forgot to link this yesterday: [Application Insights](https://www.npmjs.com/package/applicationinsights)

**Comment by OptimusRhine** [comment] 2018-08-22 17:01
<img width="722" alt="failures" src="https://user-images.githubusercontent.com/838805/44478220-dbe94780-a5f1-11e8-84a2-6be5b68f3837.png">

@jwiley84 I've added Application Insights, but it doesn't seem to be picking up whatever the 400 error is?

In the Failures tab (see attached screenshot), there's one 404 failure, but the count for that failure doesn't go up at all when I trigger the 400 error (it looks like that 404 failure only happened once on deployment, and then not again).

Meanwhile, as I trigger the 400 error, the 'Overall' failure count goes up (it's 4 in the screenshot, keeps going up as I attempt to message the bot); however, there's no corresponding subcategory for that failure, so I can't see any information on it.

Is there anything I need to change in the App Insights config to get that to show up? If not, is there any way we can pull in the additional resources on your end to see the full 400 response body?

**Comment by jwiley84** [comment] 2018-08-22 17:54
Hi @OptimusRhine!

Another option to see what's going on with vague errors such as this one is debugging on localhost with ngrok and the bot framework emulator? It will show POST errors with the associated JSON so you can see what's been sent and what's going on more in depth. 
![ngrok](https://user-images.githubusercontent.com/17333688/44481058-b9f3c300-a5f9-11e8-9986-b741be654e3e.png)

**Comment by OptimusRhine** [comment] 2018-08-22 18:31
@jwiley84 Unfortunately there are some issues running ngrok in my work environment, so I'm not sure this is a viable option for testing. Also, would this even reproduce the error? Since the bot is working fine with the Webchat channel, my assumption is that this is something to do with the FB-specific connection.

Overall, I'd love to have a way to automatically capture these error response bodies (whether through Application Insights, or via some other code change), so in the future I can just check logs and/or set up alerts. It's not exactly ideal to have to switch over to the prod branch locally and run ngrok+emulator just to hope to reproduce the issue, rather than just have it captured when it happens in the app itself.

But in the short term, any other method of pulling this particular 400 response body (whether by changing App Insights settings, or by pulling in additional resources on your end) would be greatly appreciated.

**Comment by OptimusRhine** [comment] 2018-08-22 20:57
<img width="727" alt="failure_details" src="https://user-images.githubusercontent.com/838805/44490308-e49e4580-a612-11e8-98ce-6cb066b42b3b.png">

Hi @jwiley84 ,

If it helps, I was able to pull up this more detailed page on the 400 error in App Insights. It doesn't seem to have any response body details, but it at least provides a bit more information.

**Comment by jwiley84** [comment] 2018-08-22 22:15
Hi @OptimusRhine! 
Ngrok would be able to reproduce the error, because you could run your code locally, use ngrok to tunnel to your azure channel registration, and then go on the facebook messenger account and start a dialog with the bot. The command prompt/bash running ngrok would show the error/success code (IE 202, 400, 502 etc) and then the debugger running your node bot would show the actual error. 

![error](https://user-images.githubusercontent.com/17333688/44493603-727f2e00-a61d-11e8-8b25-b7a85579ce10.png)

I had a coworker go over your logs with me earlier. There isn't any data in the 400 response body, unfortunatly. We did note however, that you're using the node version 3.14. The current package is 3.15. Can you upgrade to 3.15 and let me know what happens?

If this fails to resolve the issue, you can send me your code so we can look at what's being sent to the bot. If it's a work concern, you don't have to post it here, you can email it to me at v-jewail@microsoft.com

**Comment by OptimusRhine** [comment] 2018-08-23 17:09
Thanks @jwiley84 . I tested upgrading to 3.15, and am still encountering the same issue.

I also have the exact same code branch deployed to our test environment, and it's working there (including the FB channel) without issue. So I don't think it's code-related.

I'm fairly confident this is a problem either with the Azure resource configs, or the FB config - I was hoping the 400 response details would shed light on what exactly is misconfigured, but it sounds like there's no information to be had.

I'll continue working with the settings, and let you know what I find.

**Comment by jwiley84** [comment] 2018-09-11 16:38
Issue resolved via email.

**Closed by jwiley84** 2018-09-11 16:38 UTC
Labels: channel configuration
