### ISSUE TITLE
[Feature Request] Change topic in Skype chat

### ISSUE THREAD

**Issue by ming08108** [Microsoft/BotBuilder#3604] opened 2017-10-12 23:55 UTC
## Issue Description
I want my bot to change the chat topic in a group chat.

## Code Example
session.send("/topic topic_name");

## Expected Behavior
The chat topic to change.

## Actual Results
The chat topic doesn't change. The message is sent as "/topic topic_name"

**Comment by nwhitmont** [comment] 2017-10-13 17:10
@ming08108 This is not currently a feature, but we can add it to our backlog of feature requests.

**Comment by IoTGirl** [comment] 2017-10-19 17:54
Hi @ming08108 ,
Would it make sense to start a new chat for the new topic to keep the conversations distinct?
Sincerely,
IoTGirl

**Comment by ming08108** [comment] 2017-10-19 19:29
@IoTGirl No I want to change the topic on the fly.

**Comment by IoTGirl** [comment] 2017-10-19 19:59
Hi @ming08108 
I understand your request but by changing the topic mid discussion you lose the context of the previous statements.  My thought is that this behavior may be "By Design" and probably why changing the topic after the discussion starts may not be supported.  For example if I start the discussion "Why I like dogs" then change the topic to "Gardening in the Pacific Northwest" the conversation history no longer makes sense.
Starting a new discussion solves this by both getting the new topic and keeping the contents discrete and relevant.
Sincerely,
IoTGirl

**Comment by ming08108** [comment] 2017-10-20 06:02
@IoTGirl you can change the topic in a normal skype chat as often as you want. I think that chatbots should have feature parity with regular clients. 

It is not practical to create a new chat every time I want to change the topic.

**Comment by IoTGirl** [comment] 2017-10-20 23:39
I have been trying to do this in **Consumer Skype** and don't seem to have a topic available to be edited in the desktop UI.  Are you actually asking for this feature for **Skype For Business**? 
Also, can you provide a walkthrough description your scenario where the topic should change in the BOT conversation?

**Comment by ming08108** [comment] 2017-10-21 00:08
@IoTGirl It works in consumer skype if you type "/topic [new topic name]" in the **group** chat box.

The usecase is to put topical news/ commodity pricing data in the topic so everyone can see it even if they don't want to read through all of the old messages.

**Comment by sgellock** [comment] 2018-10-02 01:53
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team

**Closed by sgellock** 2018-10-02 01:53 UTC
Labels: Feature Request, Skype
