### ISSUE TITLE
onBegin is not invoked after a Prompts dialog ends

### ISSUE THREAD

**Issue by euanlau** [Microsoft/BotBuilder#1820] opened 2016-12-08 01:59 UTC
I am using NodeJS v3.2.3.

Code:
```
bot.dialog('/', new builder.IntentDialog()
  .onBegin(function (session, args, next) {
    console.log("onBegin: " + session.message.text);
    next();
  })
  .matches(/^hello/i, '/hello')
  .matches(/^bye/i, '/bye')
  .onDefault(function (session) {
    session.send("I didn't understand. Say hello to me!");
  }));

bot.dialog('/hello', [
  function (session) {
    builder.Prompts.text(session, "Hi there! How may I help?");
  },
  function (session) {
    session.endDialog("Okay, got it!");
  }
]);

bot.dialog('/bye', [
  function (session) {
    session.endDialog("Good Bye");
  }
]);
```

Conversation (user input only):
```
bye -> onBegin is invoked
hello --> onBegin is invoked
thank you
bye --> This does not invoke onBegin
```

So I looked at the code in `Prompts.js` and found that all the `builder.Prompts` convenience methods (text|choice,etc) create a new dialog.
If I invoke endDialog twice after every `builder.Prompts`, then onBegin will be invoked properly.

e.g. Replacing the `/hello` dialog above with the one below will fix the problem.
```
bot.dialog('/hello', [
  function (session) {
    builder.Prompts.text(session, "Hi there! How may I help?");
  },
  function (session) {
    session.endDialog("Okay, got it!");
    session.endDialog();
  }
]);
```

**Comment by Stevenic** [comment] 2016-12-12 10:51
It's basically because you're using the <string> version of matches() which launches a dialog but isn't going to automatically end the IntentDialog when that dialog returns. That's by design and I'm happy to dive into why its by design (you're assuming the IntentDialog is always used at the root which isn't always the case.)  To achieve your desired behavior you should use a waterfall to start your dialogs instead:

```
bot.dialog('/', new builder.IntentDialog()
  .onBegin(function (session, args, next) {
    console.log("onBegin: " + session.message.text);
    next();
  })
  .matches(/^hello/i, function (session) {
     session.beginDialog('/hello');
  })
  .matches(/^bye/i, function (session) {
     session.beginDialog('/bye');
  })
  .onDefault(function (session) {
    session.send("I didn't understand. Say hello to me!");
  }));

**Comment by Stevenic** [comment] 2016-12-12 10:52
I can think about making the simpler form work like that.  To be honest though in v3.5 there's not a lot of need to use `IntentDialog` anymore.  Can I ask what you're trying to do in onBegin()?

**Comment by euanlau** [comment] 2016-12-12 19:40
I was just following the [documentation](https://docs.botframework.com/en-us/node/builder/chat/IntentDialog/#matching-regular-expressions):

```
bot.dialog('/', new builder.IntentDialog()
    .matches(/^add/i, '/addTask')
    .matches(/^change/i, '/changeTask')
    .matches(/^delete/i, '/deleteTask')
    .onDefault(builder.DialogAction.send("I'm sorry. I didn't understand."))
);
```

What should I use to identify the intent without using `IntentDialog` ?

I use `onBegin` mainly for logging.

**Comment by Stevenic** [comment] 2016-12-12 20:03
You'd be better off writing a piece of middleware to do logging. Version 3.5 hasn't shipped yet so I'm still working on re-writing the docs.

**Comment by euanlau** [comment] 2016-12-12 20:23
Is middleware executed before intent identification?  I wanna log the intent.

**Comment by euanlau** [comment] 2016-12-13 19:38
Also, does that mean 

```
bot.dialog('/', new builder.IntentDialog()
    .matches(/^add/i, '/addTask')
    .matches(/^change/i, '/changeTask')
    .matches(/^delete/i, '/deleteTask')
    .onDefault(builder.DialogAction.send("I'm sorry. I didn't understand."))
);
```
is not the right way to build an intent dialog bot even for Version 3.2.3?

Then it is a documentation bug?

**Comment by Stevenic** [comment] 2016-12-17 19:19
Yes...Middleware is run for every incoming request. That's the correct way to use an IntentDialog, I'm just saying that if what your trying to do is log incoming messages you should use middleware for that.

**Comment by euanlau** [comment] 2016-12-19 18:56
I want to log after the intent is identified. So I don't think middleware can be used.

**Comment by awarn** [comment] 2017-02-12 13:38
What is the way to write this in version 3.5, then? If not using IntentDialogs?

**Comment by Stevenic** [comment] 2017-02-23 00:38
In 3.5+ you'd add a `triggerAction()` to each of your dialogs and to enable logging you can add an `onSelectAction` handler for your trigger that logs the fact your dialog as triggered.

**Comment by Stevenic** [comment] 2017-02-24 21:56
Closing this for now. Please feel free to add further comments.

**Closed by Stevenic** 2017-02-24 21:56 UTC
Labels: answered, node.js
