### ISSUE TITLE
[Cortana] Cortana breaks with context.Wait()

### ISSUE THREAD

**Issue by BelvedereHenrique** [Microsoft/BotBuilder#3641] opened 2017-10-19 12:27 UTC
## Bot Info 
* Bot handle: ActmindsEducauseBot  
* App ID: abc985d3-cc5d-43ce-bf58-b267e80b2ee6
* SDK Platform: .NET
* SDK Version: 3.11
* Active Channels: Skype, Facebook Messenger, Cortana
* Deployment Environment: Azure Web App

## Issue Description
When using contex.SayAsync() followed by context.wait() through Cortana, just after the user reponse, Cortana breaks, throwing "Cortana has run into a problem. Please try again later."

## Code Example
```cs
        private async Task AskWhichClassUserNeedsHelp(IDialogContext context)
        {
            string response = "Alright. What's the name of the Professor?";
            await context.SayAsync(response, response, new MessageOptions() { InputHint = InputHints.ExpectingInput });

            context.Wait(GetProfessorName);
        }
```

## Reproduction Steps
1. Get Cortana waiting for a response through context.wait()
2. Respond

## Expected Behavior
Cortana forwards the message to the desired method on context.wait()

## Actual Results
![image](https://user-images.githubusercontent.com/24565006/31770749-0c990f22-b4b8-11e7-8eb8-15ca254b1acd.png)

I'm missing something?

Thanks!!

**Comment by JasonSowers** [comment] 2017-10-19 21:49
could you please post the code in `GetProfessorName`  so we can take a look.

**Comment by BelvedereHenrique** [comment] 2017-10-20 10:12
Sure, here it is.

```cs
private async Task GetProfessorName(IDialogContext context, IAwaitable<IMessageActivity> result)
        {
            IMessageActivity activity = await result;

            if (activity.Text.Trim().ToLower().Contains("elvin"))
                await ForwardToElvinBranch(context);
            else if (activity.Text.Trim().ToLower().Contains("reginald"))
                await ForwardToReginaldBranch(context);
            else
            {
                string response = "Sorry, I can't help you with that right now.\n\nYou may get in contact directly with your teacher.";
                await context.SayAsync(response, response, new MessageOptions() { InputHint = InputHints.AcceptingInput });
                context.Done(string.Empty);
            }
        }
```

**Comment by JasonSowers** [comment] 2017-10-24 20:19
I tested your code in webchat and got the following error: Exception: IDialog method execution finished with multiple resume handlers specified through IDialogStack.  still looking into cortana

**Comment by JasonSowers** [comment] 2017-10-24 21:53
Where are you calling `AskWhichClassUserNeedsHelp` from?  can you please post your entire dialog?

**Comment by BelvedereHenrique** [comment] 2017-10-25 11:06
Sure,

```cs
public class AskForHelpDialog : IDialog<object>
    {
        LuisResult LuisResult;
        public AskForHelpDialog(LuisResult LuisResult)
        {
            this.LuisResult = LuisResult;
        }

        public async Task StartAsync(IDialogContext context)
        {
            if (LuisResult.Entities.Any(x => x.Entity.ToLower().Trim() == "elvin"))
                await ForwardToElvinBranch(context);
            else if (LuisResult.Entities.Any(x => x.Entity.ToLower().Trim() == "reginald"))
                await ForwardToReginaldBranch(context);
            else
            {
                await AskWhichClassUserNeedsHelp(IDialogContext context);
            }
        }

        private async Task ForwardToReginaldBranch(IDialogContext context)
        {
            string text = GetResponse(true, false);
            string voice = GetResponse(true, true);
            await context.SayAsync(text, voice, new MessageOptions() { InputHint = inputHints.AcceptingInput });

            context.Done(string.Empty);
        }

        private async Task ForwardToElvinBranch(IDialogContext context)
        {
            string text = GetResponse(false, false);
            string voice = GetResponse(false, true);
            await context.SayAsync(text, voice, new MessageOptions() { InputHint = inputHints.AcceptingInput });

            context.Done(string.Empty);
        }

        private async Task AskWhichClassUserNeedsHelp(IDialogContext context)
        {
            string response = "Alright. What's the name of the Professor?";
            await context.SayAsync(response, response, new MessageOptions() { InputHint = InputHints.ExpectingInput });

            context.Wait(GetProfessorName);
        }

        private async Task GetProfessorName(IDialogContext context, IAwaitable<IMessageActivity> result)
        {
            IMessageActivity activity = await result;

            if (activity.Text.Trim().ToLower().Contains("elvin"))
                await ForwardToElvinBranch(context);
            else if (activity.Text.Trim().ToLower().Contains("reginald"))
                await ForwardToReginaldBranch(context);
            else
            {
                string response = "Sorry, I can't help you with that right now.\n\nYou may get in contact directly with your teacher.";
                await context.SayAsync(response, response, new MessageOptions() { InputHint = InputHints.AcceptingInput });
                context.Done(string.Empty);
            }
        }
        private string GetResponse(bool gotRightProfessor, bool isVoice)
        {
              return "test";
        }
    }
```

**Comment by BelvedereHenrique** [comment] 2017-10-25 11:12
I'ts interesting because this dialog works as expected on Facebook Messenger.
The issue only happens on Cortana.

**Comment by JasonSowers** [comment] 2017-10-25 16:51
Unfortunately, I am still unable to reproduce, are you able to put your code in a repo or some place you can share the entire project?  I want to see if you have found a bug or not.

**Comment by BelvedereHenrique** [comment] 2017-10-25 17:17
Alright.

When you say "I am still unable to reproduce",are you saying that your Cortana instance waits (as expected) when context.Wait() is called? 

Unfortunately it's an enterprise code, I may not have permission.
Anyway, It's pretty simple. All that I have is a LuisDialog as RootDialog.
```cs
public class RootDialog : LuisDialog<object>
````

And method for the intention calling this dialog above:

```cs
        [LuisIntent("AskForHelpDialog ")]
        private async Task AskForHelpDialog (IDialogContext context, LuisResult luisResult)
        {
            context.Call(new AskForHelpDialog(luisResult), AfterCallIsDone);
        }
```

I may get in trouble if I post the entire code, I hope you understand.

**Comment by JasonSowers** [comment] 2017-10-27 16:54
when I was testing the bot was posting 3 messages at once with no error.  so the implementation I was trying was not working.  IF you can provide minimum reproducible code that would work as well.  That way you would not need to provide your entire project.
  
Your problem may be that the method you are calling `GetProfessorName` from already has a `Context.Wait()` which will cause the stack to not know where to resume at because of the multiple waits.

**Comment by fanidamj** [comment] 2017-11-10 18:41
Closing the issue assuming it as resolved. Feel free to reopen if you have any questions or comments.

**Comment by adarshpatel30** [comment] 2018-06-20 12:13
You closed the issue but the answer was not satisfactory I am also facing issue which was faced by @BelvedereHenrique ,he was right it does not work as expected at context.Wait(); in cortana on the other hand it works fine.

**Comment by fanidamj** [comment] 2018-06-20 17:15
@adarshpatel30  Please reopen a new issue with all the details so that it would be easier to track. Thanks!!

**Closed by fanidamj** 2018-06-20 17:15 UTC
Labels: .NET SDK, Cortana, answered, question

**Comment by adarshpatel30** [comment] 2018-06-20 17:20
I am facing the same issue why should I write it again and again.That looks
awkward.
Thanks for your help though.

**Comment by BelvedereHenrique** [comment] 2018-06-20 18:41
@JasonSowers 
I completely forgot about this issue.
Anyway, I remember that at the time I just gave up on keep trying. There wasn't double "context.wait()".
I managed to create a workaround, avoiding the context.wait().

I'm not really sure how is the situation right now on Cortana channel.
@adarshpatel30 can you share your code?

**Comment by adarshpatel30** [comment] 2018-06-21 05:20
I am not supposed to share the code @BelvedereHenrique , and the issue still persists on cortana.

**Comment by thanmayee5** [comment] 2018-06-25 12:45
Even I am facing the same issue. Can anyone help me out in resolving it? During the conversation flow in Cortana it's not displaying all the responses from bot. 

And at throwing confirmation promt which we had given, on clicking on yes or no button it is showing error - "Cortana has run into a problem. Please try again later."

**Comment by thanmayee5** [comment] 2018-06-25 12:51
As @adarshpatel30  told even i am facing the same issue . Please provide solution for it. 

Is "await context.PostAsync" or "context.Wait" creating problem ??
