### ISSUE TITLE
session.endConversation('text') fails in Slack channel

### ISSUE THREAD

**Issue by javi-jamaa** [Microsoft/BotBuilder#812] opened 2016-07-26 07:04 UTC
If I invoke session.endConversation('text') with a text the method doesn't work and the text is not sent to the user in the slack channel, in console mode it works fine.

Otherwise if i do:

session.send('text');
session.endConversation();

it works fine,

**Comment by Stevenic** [comment] 2016-08-05 01:00
Have you tried with the latest version of the SDK? There's no reason it shouldn't work but I can try to reproduce the issue.

**Comment by ernanirst** [comment] 2016-08-05 01:14
Hello @Stevenic I'm experiencing the exactly same issue with the latest version of the SDK on Facebook.
`session.endConversation();` works, and `session.endConversation("any text");` doesn't.

**Comment by Stevenic** [comment] 2016-08-05 18:40
I can't reproduce this on facebook...  I tried several combinations of calling endConversation() in the sample below and they all worked.

```
var restify = require('restify');
var builder = require('botbuilder');

// Setup Restify Server
var server = restify.createServer();
server.listen(process.env.port || process.env.PORT || 3978, function () {
   console.log('%s listening to %s', server.name, server.url); 
});
  
// Create chat bot
var connector = new builder.ChatConnector({
    appId: process.env.MICROSOFT_APP_ID,
    appPassword: process.env.MICROSOFT_APP_PASSWORD
});
var bot = new builder.UniversalBot(connector);
server.post('/api/messages', connector.listen());

bot.dialog('/', [
    function (session) {
        builder.Prompts.text(session, "Hi, whats your name?");
    }, 
    function (session, results) {
        session.endConversation("Hello... %s", results.response);
    }
]);
```

Can you see if the sample above reproduces the problem for you guys?

**Comment by Andrea-Orimoto** [comment] 2016-08-24 20:09
Assuming the last message from steve fixed it. Closing due to inactivity, please open a new issue or reply to this one asking us to reopen if needed. Thanks!

**Comment by cnrudd** [comment] 2016-10-13 13:21
I am experiencing the same issue with endConversation in the email channel.

If I use session.endConversation with a text string, it fails intermittently and when it fails no email is sent.  If I use session.endConversation with a msg object, it always works and an email is always sent.

In the emulator channel endConversation always works no matter what kind of argument is used.
-Colin

**Comment by Stevenic** [comment] 2016-10-19 09:16
That's interesting... calling session.send() with a string simply fills out a message for you under the hood. Could be a timing issue...  

I don't know where your at in your dialog flow but have you tried just calling `endDialog()` instead of `endConversation()`?  This cuts some steps off which could help diagnose.

**Comment by Stevenic** [comment] 2016-11-06 06:47
Does this still reproduce on email?

**Comment by chrimc62** [comment] 2016-11-26 23:15
Closing because of age.  If you are still having an issue please raise the issue again.

**Closed by chrimc62** 2016-11-26 23:15 UTC
Labels: bug
