### ISSUE TITLE
Intermittent timeout errors from Token Uri.

### ISSUE THREAD

**Issue by whizlingo** [Microsoft/BotBuilder#4756] opened 2018-06-18 15:06 UTC
## Bot Info
* SDK Platform: .NET
* Active Channels: Direct line
* Deployment Environment: Azure App service

## Issue Description
We are getting Request time out errors from  token generation service intermittently while running a performance test  -https://login.microsoftonline.com/botframework.com/oauth2/v2.0/token , specifically around this time while running a load test - 

Start   time | 6/17/2018   9:23:07 AM
End   time | 6/17/2018   9:33:07 AM

**Comment by EricDahlvang** [comment] 2018-06-18 23:18
Please adjust how you are load testing.  The Direct Line is a shared service, and should not be performance or load tested. We have some instructions for how to load test your bot's code here: https://blog.botframework.com/2017/06/19/load-testing-a-bot/

Secondly:
The Azure Bot Service is experiencing degraded performance that is impacting customers under certain conditions. Our engineering team has identified a root cause and implemented a solution that should mitigate the problem. Today, the fix was deployed to a subset of datacenters where it’s undergoing validation. Pending further verification the team will continue to deploy the fix to datacenters worldwide.

**Comment by v46** [comment] 2018-06-19 17:03
@EricDahlvang - We are also seeing a lot of degradation in performance for our production Slack bots. Any more insights into what is going on, and when to expect things to settle down. 

There are no outage reports on Slack's status page or on the Azure Bot service status page. 

Our symptoms include delayed responses back from Bot framework. If we need to open a separate issue to track this, please let me know.

Thanks

**Comment by EricDahlvang** [comment] 2018-06-19 20:37
If everything goes well, the deployment should be complete this week.

**Comment by whizlingo** [comment] 2018-06-20 05:17
Thanks @EricDahlvang . We ran another round of Performance test around below UTC timing - 

Start time | 6/19/2018 5:47:16 PM
-- | --
End time | 6/19/2018 6:17:16 PM

Could this be also related to the performance improvement you plan to deploy ?. 

We could see over 200 403 forbidden in the BOT channel  with below details. This was a performance test with about 100 concurrent users and the token is regenerated before calling the bot API every time. Below are the error details - 

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> <html xmlns="http://www.w3.org/1999/xhtml"> <head> <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/> <title>403 - Forbidden: Access is denied.</title> <style type="text/css">  </style> </head> <body> <div id="header"><h1>Server Error</h1></div> <div id="content"> <div class="content-container"><fieldset> <h2>403 - Forbidden: Access is denied.</h2> <h3>You do not have permission to view this directory or page using the credentials that you supplied.</h3> </fieldset></div> </div> </body> </html>

**Call stack** - 

Microsoft.Bot.Schema.BotException: at Microsoft.Bot.ChannelConnector.BotAPI+<PostActivityToBotAsync>d__30.MoveNext (Microsoft.Bot.ChannelConnector, Version=3.2.2.1, Culture=neutral, PublicKeyToken=null) Inner exception System.Exception handled at Microsoft.Bot.ChannelConnector.BotAPI+<PostActivityToBotAsync>d__30.MoveNext: at Microsoft.Bot.ChannelConnector.BotAPI+<PostActivityToBotAsync>d__30.MoveNext (Microsoft.Bot.ChannelConnector, Version=3.2.2.1, Culture=neutral, PublicKeyToken=null)

**Comment by EricDahlvang** [comment] 2018-07-02 22:30
> We figured out that the above issue was related to the application gateway Windows application firewall, which was blocking our calls .

Closing this issue, since you've found the underlying cause of the errors.

**Closed by EricDahlvang** 2018-07-02 22:30 UTC
Labels: .NET SDK, Direct Line
