### ISSUE TITLE
Could not use emulator software

### ISSUE THREAD

**Issue by binhpht** [Microsoft/BotBuilder#3245] opened 2017-08-02 12:15 UTC
## System Information
* SDK Language: 
* SDK Version: 
* Development Environment: 

## Bot Info 
* Bot name: 
* Bot handle: 
* App ID: 
* Connected channels: 

## Issue Description

> Today, when I use Emulator software, it has error "[15:13:22] -> POST Request to 'http://127.0.0.1:3979/api/messages' failed: [500] Internal Server Error "

And in the code console the error message is 

> ERROR: ChatConnector: receive - invalid signing key or OpenId metadata document.

I think this is an new issue of Emulator software

**Comment by pomarc** [comment] 2017-08-02 14:47
same thing started happening to me about 3 hrs ago.

**Comment by JasonSowers** [comment] 2017-08-02 15:06
Unfortunately, I was unable to recreate this. Please open an issue in the [emulator repo](https://github.com/Microsoft/BotFramework-Emulator).  Be sure to include the version of the emulator you are using, system information, and any other details you think may be helpful.

**Comment by nwhitmont** [comment] 2017-08-02 17:18
duplicate of https://github.com/Microsoft/BotFramework-Emulator/issues/262

**Closed by nwhitmont** 2017-08-02 17:18 UTC
Labels: emulator
