### ISSUE TITLE
[Node.js SDK, Azure Bot Service] Change Configuration Messaging endpoint - azure

### ISSUE THREAD

**Issue by liavnave** [Microsoft/BotBuilder#4783] opened 2018-06-24 08:35 UTC
## Bot Info
* SDK Platform:  Node.js
* Active Channels: Skype
* Deployment Environment: Azure Bot Service - portal.azure.com

## Issue Description
Cant change the settings endpoint, error received:

{"readyState":4,"responseText":"{\"error\":{\"code\":\"InvalidBotData\",\"message\":\"OwnerIds: OwnerIds must contain at least one email address. \"}}","responseJSON":{"error":{"code":"InvalidBotData","message":"OwnerIds: OwnerIds must contain at least one email address. "}},"status":400,"statusText":"Bad Request"}

## Reproduction Steps
1. Login to - https://portal.azure.com
2. Go to the resource - bot
3. Settings tab
4. Change Configuration Messaging endpoint
5. Save

## Expected Behavior
Messaging endpoint save successfully.

## Actual Results
Nothing happened.

**Comment by stevengum** [comment] 2018-06-25 23:14
@liavnave I haven't been able to reproduce this issue with one of my own bots. 

Have you tried logging out of the portal and then logging back into it? Similarly, have you tried reproducing the issue in an private/incognito browsing session? If it works there you may need to clear your cookies.

**Comment by liavnave** [comment] 2018-07-01 08:02
@stevengum I tried to log out and log in again, and test the issue from a private/incognito browser.
also tried to clear cookies.
Still can't change the endpoint.

**Comment by stevengum** [comment] 2018-07-02 16:37
@liavnave Can you provide your Microsoft App ID and the Bot Handle for further investigation?

**Comment by liavnave** [comment] 2018-07-03 07:29
@stevengum what is your email?

**Comment by pjryan93** [comment] 2018-07-11 22:46
Also running into this problem on Azure.

**Comment by stevengum** [comment] 2018-09-07 00:56
Closing due to inactivity.

**Comment by mintxelas** [comment] 2018-11-27 09:55
I tried to access dev.botframework.com to add my email in the settings, but it is not showing in that portal. I am Owner of the bot according to azure portal.

**Comment by EricDahlvang** [comment] 2018-11-27 20:12
@mintxelas Please look for your bot in the Azure portal.  Bots are managed as Azure Resources now, so access is determined based on Azure Subscription Permissions.

**Comment by mintxelas** [comment] 2018-11-27 20:21
I know, but there's nowhere to put the email of the owner in the portal,
yet that's the error the api throws. And in the permissions of the bot I am
already owner.

**Comment by EricDahlvang** [comment] 2018-11-27 23:40
@mintxelas
 
Please provide the bot handle and ms application id, so we can investigate further.

**Comment by mintxelas** [comment] 2018-11-28 06:38
Thanks, the bot handle is "AstridBot" and the appId
is c77c3dd6-7278-4f4b-92fc-f3642cb7f29c

**Comment by CoHealer** [comment] 2018-11-29 21:01
@mintxelas, can you please confirm that you are the bot

**Comment by CoHealer** [comment] 2018-11-29 21:35
Closing per original author was non responsive.

@mintxelas, I've opened #5190 to handle your issue. Please refer to that issue going forward.

**Closed by CoHealer** 2018-11-29 21:35 UTC
Labels: Azure Bot Service, Node.js SDK
