### ISSUE TITLE
[Question] args undefined when using replaceDialog, only in Slack

### ISSUE THREAD

**Issue by tomoakley** [Microsoft/BotBuilder#2884] opened 2017-06-04 21:44 UTC
## System Information (Required)
* SDK Language: Node
* SDK Version: 3.5.4
* Development Environment: Digital Ocean VPN

## Issue Description
When using `session.replaceDialog('/dialog', session.dialogData)` and then picking this up in the associated dialog, `args` come as undefined. I have my bot set up in Slack and Facebook Messenger (and the emulator), this only happens in Slack.

## Code Example
```
bot.dialog('/dialog1', [
    (session) => {
        session.replaceDialog('/dialog2', session.dialogData)
    }
]

bot.dialog('/dialog2', [
    (session, args) => {
        console.log(args) // undefined
    }
]
```

## Expected Behavior
I expect to be able to retrieve whatever data I entered in the second argument for `replaceDialog`, in `args` in `dialog2`.

## Actual Results
`args` in `dialog2` comes back as `undefined`. This only happens in Slack; messenger and the emulator are fine.

**Comment by stevengum97** [comment] 2017-06-05 15:50
Can you upgrade to 3.8.4 and let us know if you're still encountering this issue?

**Comment by nwhitmont** [comment] 2017-06-05 22:35
@tomoakley Are you still experiencing the issue after upgrading to botbuilder@3.8.4?

**Comment by nwhitmont** [comment] 2017-06-08 22:09
@tomoakley Are you still experiencing the issue after upgrading to botbuilder v3.8.4?

**Comment by nwhitmont** [comment] 2017-06-12 15:35
@tomoakley Are you still experiencing the issue after upgrading to botbuilder v3.8.4?

**Comment by tomoakley** [comment] 2017-06-12 17:35
Hi @nwhitmont, sorry this is a side-project and I haven't had time to focus on it for a few days. Will hopefully be able to do something in the next couple of days.

**Comment by nwhitmont** [comment] 2017-06-14 16:31
@tomoakley I setup a test bot that uses `replaceDialog()` as you described, but I'm unable to reproduce the error. 

Here is a working example:
```js
var builder = require('botbuilder');
var restify = require('restify');

//Server setup
var server = restify.createServer();

server.listen(process.env.port || process.env.PORT || 3978, function() {
    console.log('%s listening to %s', server.name, server.url);
});

//Get secrets from server environment
var connector = new builder.ChatConnector({
    appId: process.env.MICROSOFT_APP_ID,
    appPassword: process.env.MICROSOFT_APP_PASSWORD
});

//Create chat bot
var bot = new builder.UniversalBot(connector);

//Handle bot framework messages
server.post('/api/messages', connector.listen());

bot.dialog('/',function(session) {
     session.send('Starting replaceDialog example...');
     // set some value in dialogData
     session.dialogData.coupon = true;
     session.send('calling replaceDialog');
     // pass in dialogData to replaceDialog
     session.replaceDialog('second-dialog', session.dialogData);
});

bot.dialog('second-dialog', function(session, args) {
    // what did we get from previous replaceDialog call?
    console.log('\ngot args from replaceDialog:');
    console.log(args);
    session.send('Welcome to second-dialog');
    if(!args.coupon) {
        // we didn't get the args from previous dialog
        session.endDialog('args not present');
    }
    else {
        // args arrived OK from previous dialog
        session.endDialog('args found OK');
    }
})

// END OF LINE
```

I'm closing this as no-repro. Reopen if you're still having issues.

**Closed by nwhitmont** 2017-06-14 16:31 UTC
Labels: Node SDK, question, Slack

**Comment by tomoakley** [comment] 2017-06-18 23:49
Hi @nwhitmont, I think my issue was due to interrupting an already running session - typing reset into the input appears to fix the issue. (reset is handled by `bot.use(builder.Middleware.dialogVersion({ version: 1.0, resetCommand: /^reset/i }));` Thanks, and sorry for my unresponsiveness! Will do better in future.
