### ISSUE TITLE
How to send PromptDialog to the custom created Activity?

### ISSUE THREAD

**Issue by denisyfrolov** [Microsoft/BotBuilder#3560] opened 2017-10-03 12:25 UTC
## Bot Info 
* Bot handle: N/A
* App ID: N/A
* SDK Platform: .NET
* SDK Version: Microsoft.Bot.Builder.Azure 3.2.3
* Active Channels: Telegram
* Deployment Environment: Auzure Bot Service

## Issue Description
In short the main task is receive a message from one user and forward it to another. SendToConversation works perfectly, but I need to send PromptDialog and that's the problem. The context I'm passing to PromptDialog sends a message to the first user, but I need it does send the message to the second one. How can I do that?

## Code Example

```cs
public class ForwardDialog : IDialog<bool>
{
    public async Task StartAsync(IDialogContext context)
    {
        context.Wait(MessageReceivedAsync);
    }

    async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> argument)
    {
        string ServiceUrl = "http://localhost:56675";
        string OriginalMessageSenderName = "Test";
        string OriginalMessageSenderId = "TestId";
        string OriginalMessageText = "sd";
        ChannelAccount BotAccount = new ChannelAccount(
            name: "Bot", 
            id: "default-bot"
        );
        ChannelAccount UserAccount = new ChannelAccount(
            name: "User", 
            id: "default-user"
        );
        ConnectorClient ForwardClient = new ConnectorClient(new Uri(ServiceUrl));
        ConversationResourceResponse ForwardConversation = ForwardClient.Conversations.CreateDirectConversation(BotAccount, UserAccount);

        ForwardMessage.From = BotAccount;
        ForwardMessage.Recipient = UserAccount;
        ForwardMessage.Conversation = new ConversationAccount(id: ForwardConversation.Id);
        ForwardMessage.Text = $"{OriginalMessageSenderName}: {OriginalMessageText}";
        ForwardMessage.Locale = "ru-ru";

        //ForwardClient.Conversations.SendToConversation((Activity)ForwardMessage);

        PromptDialog.Text(context, PostResultAsync, "Reply", "What?", 3);
    }

    private async Task PostResultAsync(IDialogContext context, IAwaitable<string> prompt)
    {
        var result = await prompt;
        await context.PostAsync($"{result}");
        context.Wait(MessageReceivedAsync);
    }
}
```

## Reproduction Steps
/--/

## Expected Behavior
PromptDialog will send to ChannelAccount UserAccount

## Actual Results
PromptDialog sends to sender of the original message

**Comment by JasonSowers** [comment] 2017-10-03 15:18
Closing as duplicate of https://stackoverflow.com/questions/46535032/microsoft-bot-builder-how-to-send-promptdialog-to-the-custom-created-activity since you are receiving help there.

**Closed by JasonSowers** 2017-10-03 15:18 UTC

**Comment by denisyfrolov** [comment] 2017-10-03 16:20
No, I'm not. I hoped I receive help here because on stackoverflow.com nobody answers me.

**Comment by denisyfrolov** [comment] 2017-10-05 10:33
@JasonSowers Could you reopen this issue please?
