### ISSUE TITLE
Hosting bot on Openshift using Microsoft bot framework Nodejs SDK with proxy

### ISSUE THREAD

**Issue by filipyoo** [Microsoft/BotBuilder#4248] opened 2018-03-01 02:26 UTC
I have a problem when hosting my bot on OpenShift (OpenShift Container Platform) registered with the Bot Channels Registration on Azure. I am using the Botbuilder SDK Nodejs, and the Openshift is behind a corporate proxy.

I've tried to set a up a global tunnel to force all HTTP requests to go through the tunnel (see [this GitHub issue](https://github.com/Microsoft/BotBuilder/issues/399#issuecomment-223256399) and [this one](https://github.com/Microsoft/BotBuilder/issues/1668)). I also have set environments variables on Openshift, but still it doesn't work...

It should be a simple way to set up the proxy with the botbuilder... Anyone can help me please ?

Thanks !

**Comment by JasonSowers** [comment] 2018-03-01 18:05
Duplicate of https://stackoverflow.com/questions/49041679/hosting-bot-on-openshift-using-microsoft-bot-framework-nodejs-sdk-with-proxy

**Closed** 2018-03-01 18:05 UTC
Labels: Node.js SDK
