### ISSUE TITLE
[Node.js SDK, WebChat] When clicked botbuilder.HeroCard.buttons() open keyboard on mobile devices 

### ISSUE THREAD

**Issue by mos-ie** [Microsoft/BotBuilder#3645] opened 2017-10-20 15:09 UTC
## Bot Info 
* Bot handle: vvdiscoverybot_BeYlLy6LR8b
* App ID:  7ed4d351-deac-4278-90a5-62fc31751f60
* SDK Platform:  Node.js
* Active Channels: Direct Line
* Deployment Environment: Azure Bot Service/Azure App Service

## Issue Description
Our bot client is a simple Ionic app that embeds our bot which uses Direct Line. When clicking a button on a hero card created using BotBuilder the device's keyboard opens. Is there any way to stop this? Interestingly, running the app locally in the browser doesn't produce the same result. There's a possibility this is more an Ionic issue than a BotBuilder issue but I wouldn't be sure!

## Code Example
This how the hero card and its buttons are created:
```
lib.dialog('/', [
    (session) => {
        var choices = Object.keys(TypeOptions).map(key => { return session.gettext(TypeOptions[key]); });
        var choiceCard = new builder.HeroCard(session)
            .title('type_title')
            .buttons(choices.map(choice => new builder.CardAction.imBack(session, choice, choice)));
        var message = new builder.Message(session)
            .addAttachment(choiceCard);
        builder.Prompts.choice(session, message, choices);
    },
    (session, results) => { ... }
]);
```

## Reproduction Steps
1. Click a button on a hero card on a mobile devices (Ionic app).

## Expected Behavior
The device's keyboard doesn't open when a button on a hero card is clicked.

## Actual Results
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2778940/31827947-dc55a614-b5b0-11e7-95a9-d2387c1a387b.gif)

**Comment by nwhitmont** [comment] 2017-10-20 17:56
@mos-ie What device + OS are you using when the error happens? 

It looks like you might have the WebChat control embedded in an Android app?

**Comment by nwhitmont** [comment] 2017-10-20 17:57
@danmarshall

**Comment by mos-ie** [comment] 2017-10-20 18:12
@nwhitmont Device is a Sony Xperia running Android 7.1.1

WebChat embedded in an Ionic app - when running the app locally in web browser with ([Ionic serve](https://ionicframework.com/docs/cli/serve/)) the issue doesn't occur but if I build and run the app on my Android device it does, so it could be a native issue?

**Comment by harshithkashyap** [comment] 2017-10-22 16:48
We are running into similar issue as well with ionic 3.9. Instead of embed, we have rendered the app using `BotChat.App({..})` approach. The keyboard opens up on button click and the chat window doesn't scroll to the end when new messages arrive. Reproduced it on both ios and android ionic apps.

**Comment by danmarshall** [comment] 2017-10-23 18:23
@compulim have we deployed the autofocus stuff?

**Comment by mos-ie** [comment] 2017-11-01 16:46
Any update on this guys? @nwhitmont @danmarshall

**Comment by compulim** [comment] 2018-06-26 19:16
I am yet to check for a repro.

But this is more related to Web Chat than Bot Builder. Can you [file a bug](https://github.com/Microsoft/BotFramework-WebChat/issues/) to Web Chat and we track over there?

**Comment by EricDahlvang** [comment] 2018-06-26 23:40
Closing, since this is a webchat issue not a bot builder issue.

**Closed by EricDahlvang** 2018-06-26 23:40 UTC
Labels: Direct Line, Node.js SDK, Rich Cards, WebChat, question
