### ISSUE TITLE
[.Net SDK, Emulator] Error with embedded attachments?

### ISSUE THREAD

**Issue by curia-damiano** [Microsoft/BotBuilder#4092] opened 2018-01-24 15:36 UTC
## Bot Info
* SDK Platform: .NET
* SDK Version: latest in NuGet
* Active Channels: Bot Emulator
* Deployment Environment: local development with Emulator

## Issue Description
If I code an embedded attachment, I can't download the file and open it automatically in Excel.
Instead, it tries to open the file in Windows Store, searching for the string "data"

## Code Example
private static Task<Attachment> GetInlineExcelAttachment(string serviceUrl, string conversationId)
		{
			var imagePath = HttpContext.Current.Server.MapPath("~/Dialogs/test.xlsx");

			var imageData = Convert.ToBase64String(File.ReadAllBytes(imagePath));

			return Task.FromResult(new Attachment
			{
				Name = "test.xlsx",
				ContentType = "application /vnd.openxmlformats-officedocument.spreadsheetml.sheet",
				ContentUrl = $"data:application /vnd.openxmlformats-officedocument.spreadsheetml.sheet;base64,{imageData}"
			});
		}

## Reproduction Steps
1. Start with the code at https://github.com/Microsoft/BotBuilder-Samples/blob/master/CSharp/core-SendAttachment/SendAttachmentDialog.cs
2. Replace the method generating the attachment with what here above
3. Try in the Bot Emulator

## Expected Behavior
I would expect to download the file or open it in Excel automatically

## Actual Results
Instead, clicking on the download link, I am presented the option to search for a suitable application in the store. What is even more weird, is that the search criteria used for the store is "data"
![attachment1](https://user-images.githubusercontent.com/18611507/35340930-b242272a-0124-11e8-8975-3aec4b6d64d9.jpg)
![attachment2](https://user-images.githubusercontent.com/18611507/35340931-b2738784-0124-11e8-8f5b-49481a39b697.jpg)
![attachment3](https://user-images.githubusercontent.com/18611507/35340932-b294686e-0124-11e8-8a7e-6c9d66c848e6.jpg)

**Comment by JasonSowers** [comment] 2018-01-24 16:38
Give something like this a try:
 ```cs  
 [Serializable]
    public class EchoDialog : IDialog<object>
    {
        private Uri _baseUri;
        public EchoDialog(Uri baseUri)
        {
            _baseUri = baseUri;
        }

        public async Task StartAsync(IDialogContext context)
        {
            context.Wait(MessageReceivedAsync);
        }

        public async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> argument)
        {
            var reply2 = await argument as Activity;
            Activity reply = reply2.CreateReply();
            string base64String;
            string image64;
            Attachment pdf;
            try
            {
                //This was written for images, so you can display something else here if you would like
                Byte[] bytes = File.ReadAllBytes(HttpContext.Current.Server.MapPath("~/bomb300.png"));
                base64String = Convert.ToBase64String(bytes);
                image64 = "data:image/png;base64," + base64String;
                reply.Attachments = new List<Attachment>();
                pdf = new Attachment(contentType: "image/png", content: image64);
                reply.Attachments.Add(pdf);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
            await context.PostAsync(reply);


            var absolute = System.Web.VirtualPathUtility.ToAbsolute("~/testxl.xlsx");
            Uri resourceFullPath = new Uri(_baseUri, absolute);
            HeroCard heroCard = new HeroCard()
            {
                Images = new List<CardImage>
                {
                    new CardImage(
                        url: image64)
                },
                Tap = new CardAction()
                {
                    Value = resourceFullPath,
                    Type = "openUrl",
                }
            };

            reply.Attachments = new List<Attachment>
            {
                heroCard.ToAttachment()
            };
            await context.PostAsync(reply);
            context.Wait(MessageReceivedAsync);
        }
    }
```
and make sure to add something like this in your messages controller:
```cs
Uri baseUri = new Uri(Request.RequestUri.AbsoluteUri.Replace(Request.RequestUri.PathAndQuery, String.Empty));
            // check if activity is of type message
            if (activity != null && activity.GetActivityType() == ActivityTypes.Message)
            {
                await Conversation.SendAsync(activity, () => new EchoDialog(baseUri));
            }
```

**Comment by nwhitmont** [comment] 2018-01-24 19:29
duplicate of #4091 ?

**Comment by curia-damiano** [comment] 2018-01-25 11:11
No, it is not a duplicate. The method to attach a file is different, and also the resulting behavior (but in both cases not correct).
Both should be supported give the GitHub example I linked the issue description.

**Comment by JasonSowers** [comment] 2018-06-25 14:23
@curia-damiano did my suggestion work or did you find another solution?

**Comment by curia-damiano** [comment] 2018-06-25 15:42
Hi Jason,
honestly too much time has passed since I've visited my customer with this issue and now I don't remember.
I think you can close this issue.
In any case, thank you very much for your support.
Regards, Damiano

**Closed** 2018-06-25 18:09 UTC
Labels: .NET SDK, emulator
