### ISSUE TITLE
While connecting to MS SQL server(hosted on Azure env with public IP) from Azure bot services I get an error:  {"code":"MethodNotAllowed","message":"GET is not allowed"}. Any idea why?

### ISSUE THREAD

**Issue by suryadeepchatterjee3107** [Microsoft/BotBuilder#3832] opened 2017-11-28 07:06 UTC
## Bot Info 
* App ID: 
* SDK Platform: 
* SDK Version: 
* Active Channels: 
* Deployment Environment: 

## Reproduction Steps
1.
2.
3.

**Comment by nwhitmont** [comment] 2017-11-28 14:59
closing as user did not provide any issue description

**Closed by nwhitmont** 2017-11-28 14:59 UTC

**Comment by JasonSowers** [comment] 2017-11-28 17:57
Duplicate of https://stackoverflow.com/questions/47525893/unable-to-connect-to-ms-sql-server-from-azure-bot-services
