### ISSUE TITLE
An exception of type 'System.Runtime.Serialization.SerializationException' occurred in mscorlib.dll

### ISSUE THREAD

**Issue by m-ehxan** [Microsoft/BotBuilder#2579] opened 2017-04-10 16:17 UTC
I am having a run time serialization exception and I am not sure how to handle it. It happens at

` await postToBot.PostAsync(activity, CancellationToken.None);`

Following:
 

> An exception of type 'System.Runtime.Serialization.SerializationException' occurred in mscorlib.dll but was not handled in user code Additional information: Type 'Microsoft.Bot.Builder.Internals.Fibers.Null Wait`1[[Microsoft.Bot.Builder.Dialogs.Internals.Dialog Task, Microsoft.Bot.Builder, Version=3.5.5.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]' in Assembly 'Microsoft.Bot.Builder, Version=3.5.5.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' is not marked as serializable.

My SendToBot() method is as following:

```
private async Task SendToBot(RecognizedPhrase recognizedPhrase)
        {
            
            Activity activity = new Activity()
            {
                From = new ChannelAccount { Id = conversationResult.Id },
                Conversation = new ConversationAccount { Id = conversationResult.Id },
                Recipient = new ChannelAccount { Id = "Bot" },
                ServiceUrl = "https://skype.botframework.com",
                ChannelId = "skype",
            };

            activity.Text = recognizedPhrase.DisplayText;

            using (var scope = Microsoft.Bot.Builder.Dialogs.Conversation
                .Container.BeginLifetimeScope(DialogModule.LifetimeScopeTag, Configure))
            {
                scope.Resolve<IMessageActivity>
                    (TypedParameter.From((IMessageActivity)activity));
                DialogModule_MakeRoot.Register
                    (scope, () => new LUISDialogClass());
                var postToBot = scope.Resolve<IPostToBot>();
                await postToBot.PostAsync(activity, CancellationToken.None);
            }
        }
```

**Comment by ejadib** [comment] 2017-04-10 17:10
Duplicate of http://stackoverflow.com/questions/43329078/an-exception-of-type-system-runtime-serialization-serializationexception-occur

**Comment by m-ehxan** [comment] 2017-04-10 17:14
@ejadib That's my post

**Comment by ejadib** [comment] 2017-04-10 17:36
I know, please don't re post.

**Comment by m-ehxan** [comment] 2017-05-01 13:19
Similar issue: [https://github.com/Microsoft/BotBuilder/issues/2277](url)

**Comment by JasonSowers** [comment] 2017-06-01 22:27
@m-ehxan has this been resolved for you when upgrading to the newest SDK?

**Closed** 2017-06-27 22:10 UTC
Labels: .NET SDK

**Comment by m-ehxan** [comment] 2017-08-14 14:26
@JasonSowers Yes, with the update of 3.9.x it resolved the issue. Thanks alot :)
