### ISSUE TITLE
BUG: Passing in existing state for a field of type double is not working

### ISSUE THREAD

**Issue by rodzillarr** [Microsoft/BotBuilder#111] opened 2016-04-14 20:38 UTC
In C# see below:

```
//update the initial state before calling dialog
var state = new MyDialog();

state.StringItem = someString; //this string gets copied into the called dialog
state.StringItem2 = someString2; //this string gets copied into the called dialog
state.DoubleItem = doubleVal; //this double DOES NOT get copied into the called dialog and i am prompted to enter it in the dialog

context.Call(new FormDialog<MyDialog>(state, MyDialog.BuildForm, options: FormOptions.PromptInStart), null);

```

neither of the following assignment substitutions work either:

```
state.DoubleItem = 99; //doesn't work
state.DoubleItem = 99d; //nor does this

```

**Comment by rodzillarr** [comment] 2016-04-14 21:06
Actually, this is the same as the closed issue #38 

I've verified that the value is known by the bot however the step is not skipped for Double values.

**Comment by msft-shahins** [comment] 2016-04-14 22:49
@rodzillarr which version of Nuget are you depending on. Issue #38 should be fixed in 1.0.2 release.

**Comment by rodzillarr** [comment] 2016-04-14 23:40
1.0.2
I believe this is a different issue.  The logic to skip fields with existing state is getting called but it's not handling Doubles.

Thanks,

-r

**Comment by rodzillarr** [comment] 2016-04-15 00:43
FYI, this is occurring because the function:

```
        internal static bool IsNullable(this Type type)
        {
            return (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(Nullable<>));
        }
```
in \Library\FormFlow\extensions.cs (Line 140) is returning false for System.Double so the formbuilder code isn't skipping it when it finds existing state.

-R

**Comment by chrimc62** [comment] 2016-04-15 01:38
This is by design.  We have no idea whether or not there is a value in your field--how do we know 0.0 is no value, but 1.0 is a value?  If you change your double to be a nullable field then we can distinguish and it will be skipped if you supply a value.

**Closed by chrimc62** 2016-04-15 01:38 UTC
Labels: bug

**Comment by rodzillarr** [comment] 2016-04-15 01:42
I figured it out right when you posted  your reply and after hunting down that chunk of code.  Changed my field from a double to a double? and naturally it works.  Thanks!
