### ISSUE TITLE
[Question] No way to grab IDialogContext / IDialogStack from within MessageController?

### ISSUE THREAD

**Issue by J3QQ4** [Microsoft/BotBuilder#1086] opened 2016-08-26 07:35 UTC
Hi. My bot is launching a root dialog from the MessageController, and then the root dialog launches child dialogs. 

I am trying to enable the user to jump out of any dialog at any point by just typing "exit" or "quit". The problem is that I would need to add a check for that at every single method within each IDialog that I have, so I am looking for another way to intercept the "exit" keyword and restart the conversation.

I can intercept the message in the Post method in MessageController, but at that point, all I have is the Activity object. I do not have the IDialogContext object, so I cannot call .Done() or .Reset() to reset the bot state and let the user start from the beginning. 

Is this a current limitation or I just haven't found a way to get the IDialogStack from outside an IDialog yet?

Thanks.

**Comment by eydelrivero** [comment] 2016-08-26 09:19
I know it's not pretty, but you can always create a state client and delete the state for the user in the current channel like this:

```
StateClient stateClient = activity.GetStateClient();
await stateClient.BotState.DeleteStateForUserAsync(activity.ChannelId,
                                            activity.From.Id,
                                            CancellationToken.None);
```

The problem is that this not only deletes the dialog stack but also all data stored for the current user, and conversations for that user in the current channel. Maybe the someone can comment on a better way.

**Comment by J3QQ4** [comment] 2016-08-26 09:37
@eydelrivero Yep, this is what I'm doing right now (except I'm using the non-async method).

My best idea so far is to grab the user data (such as preferences and settings), delete the state and then immediately restore user data. 

I have a question with bounty on another website right now, if someone finds a solution I'll post here too. 

It's a pity that we have the IDialogStack.Reset() method but no way to access it.

**Comment by eydelrivero** [comment] 2016-08-26 11:35
@J3QQ4 I've been thinking of this and found that you can delete only the private conversation data, which is where the dialog stack is saved according to the [documentation](https://docs.botframework.com/en-us/technical-faq/#where-is-conversation-state-stored), and not the whole user data like this:

```
StateClient stateClient = activity.GetStateClient();
privateConversationData = new BotData(eTag: "*");
await
   stateClient.BotState.SetPrivateConversationDataAsync(activity.ChannelId,
        activity.Conversation.Id, activity.From.Id, privateConversationData);
```

that way you left untouched the user data that is not particular to a conversation. Still looks like a hack to me. I guess the way to go is to integrate your reset mechanism in within your dialogs.

**Comment by willportnoy** [comment] 2016-08-26 20:19
You might consider using a scorable like this example cancel scorable:

https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Tests/Microsoft.Bot.Builder.Tests/ScorablesTests.cs#L54

Tell me if you have further questions.

**Comment by willportnoy** [comment] 2016-09-02 16:08
I'm going to close this issue, but feel free to open a new issue for further discussions.

**Closed by willportnoy** 2016-09-02 16:08 UTC
Labels: question
