### ISSUE TITLE
[FormFlow] How to call child dialog from JSON schema dialog?

### ISSUE THREAD

**Issue by vovanb** [Microsoft/BotBuilder#3380] opened 2017-08-24 13:18 UTC
Hi Guys, seems community support from stackoverflow is not working....
Same opened on https://stackoverflow.com/questions/45817409/call-child-dialog-from-json
Put the question here:

I would like to call child dialog from JSON schema dialog:

Dialog 1

    {
 
      "References": [ "my .dll", "Newtonsoft.Json.dll" ],  
      "Imports": [ "my class", "Newtonsoft.Json.Linq" ],
      "type": "object",
      "required": [
       "Question 1"
    
       ],
    "Templates": {
    "NotUnderstood": {
      "Patterns": [ "I do not understand \"{0}\".", "Try again, I don't get \"{0}\"." ]
    },
    "EnumSelectOne": {
      "Patterns": [ "Please let me know the {&}: {||}" ],
      "ChoiceStyle": "PerLine"
    }
    },
     "properties": {
     "Question 1": {
      "Prompt": {
        "Patterns": [ "my Question 1 ? {||}" ]
      },
      "type": [
        "string",
        "null"
      ],
      "enum": [
        "Info",
        "Submit an Issue",
        "Track Cases",
        "Finish"
      ]
    
    },
     "OnCompletion": "context.Call(FormDialog.FromForm<JObject>(()=>BuildJsonForm(\"another.json\"),FormOptions.PromptInStart), (con, res) =>CompletedQ1AndQ2(con, res));"

    }

Dialog 2

    {
 
      "References": [ "my .dll", "Newtonsoft.Json.dll" ],  
      "Imports": [ "my class2", "Newtonsoft.Json.Linq" ],
      "type": "object",
      "required": [
       "Question 1"
    
       ],
    "Templates": {
    "NotUnderstood": {
      "Patterns": [ "I do not understand \"{0}\".", "Try again, I don't get \"{0}\"." ]
    },
    "EnumSelectOne": {
      "Patterns": [ "Please let me know the {&}: {||}" ],
      "ChoiceStyle": "PerLine"
    }
    },
     "properties": {
     "Question 2": {
      "Prompt": {
        "Patterns": [ "my Question 2 ? {||}" ]
      },
      "type": [
        "string",
        "null"
      ],
      "enum": [
        "support ",
        "sales ",
        "marketing"
      ]
    
    },
     "OnCompletion": "context.Done<bool>(true);"

    }
c# code :

    public async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> argument)
    {
           context.Call(
               FormDialog.FromForm<JObject>(() => BuildJsonForm("Q1.json"),
                   FormOptions.PromptInStart), (con, res) => CompletedCaseSubmission(con, res));
    }
The issue that CompletedCaseSubmission called after filling Q1 but Q2 dialog did not execute at all. I can call Dialog 2 from CompletedCaseSubmission , but I want do it from JSON. 
Second question is how to **get details of both dialogs Q1 and Q2** in c#?

**Comment by JasonSowers** [comment] 2017-08-24 15:29
Duplicate of https://stackoverflow.com/questions/45817409/call-child-dialog-from-json

**Comment by nwhitmont** [comment] 2017-08-24 15:54
closing as duplicate of https://stackoverflow.com/questions/45817409/call-child-dialog-from-json

**Closed by nwhitmont** 2017-08-24 15:54 UTC
Labels: .NET SDK, FormFlow, question
