### ISSUE TITLE
[Cortana] Does Microsoft Bot Framework allows to develop interactive UIs?

### ISSUE THREAD

**Issue by omairzia** [Microsoft/BotBuilder#3862] opened 2017-12-02 08:23 UTC
Hi,
I have a requirement to implement some interactive UIs using Microsoft Bot Framework for Cortana Channel but I have not found any way to implement this. I want to apply styles on buttons and importantly use graphs & charts (like web dashboard) on Cortana.

**Comment by ejadib** [comment] 2017-12-04 22:28
Duplicate of https://stackoverflow.com/questions/47627280/does-microsoft-bot-framework-allows-to-develop-interactive-uis

**Comment by nwhitmont** [comment] 2017-12-04 22:55
Hi @omairzia - Cortana is a part of the Windows operating system and does not support HTML or CSS.  Cortana platform is designed primarily for voice input. We are working on a new Adaptive Cards specification which will allow you to create customized rich media cards and send them via the Cortana channel. 

You can read more about Adaptive Cards here: 
https://adaptivecards.io

Cortana channel general info:
https://docs.microsoft.com/en-us/cortana/skills/get-started

**Closed by nwhitmont** 2017-12-04 22:55 UTC
Labels: Cortana

**Comment by omairzia** [comment] 2017-12-05 05:34
Thanks @nwhitmont
