### ISSUE TITLE
[.Net SDK, Skype Image Service]  Receive attachment code example is not working - getting 403 error?

### ISSUE THREAD

**Issue by megjoshi** [Microsoft/BotBuilder#3994] opened 2018-01-04 11:10 UTC
Hi,

we used this sample to create a bot to respond to images, but from today, the receieve image is not working and is giving 403. 

https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/core-ReceiveAttachment

It was working till yesterday. 

Regards
Meghana

**Comment by nwhitmont** [comment] 2018-01-04 14:22
@megjoshi For reference - what is your system information when you encountered the error?

- Operating system?
- Skype client type? (mobile, desktop)
- Skype client version number where you saw the problem
- The actual text of the 403 error message you saw

**Comment by megjoshi** [comment] 2018-01-04 17:27
1. i m using botframework c# code, the one in above sample after removal of the "skype.com" check. 
2. skype all clients. 
3. skype latest versions
4. {StatusCode: 403, ReasonPhrase: 'Forbidden', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Connection: close
  Date: Thu, 04 Jan 2018 17:26:32 GMT
  Server: Microsoft-HTTPAPI/2.0
  Content-Length: 58
  Content-Type: application/json; charset=utf-8
}}
This is happening only for image, text is working fine.

**Comment by nwhitmont** [comment] 2018-01-04 19:30
duplicate of https://stackoverflow.com/questions/48095572/skype-recieve-message-not-working-getting-403

**Comment by megjoshi** [comment] 2018-01-04 19:49
I am also using the latest stable version of bot framework, so that is not the issue.

**Comment by fanidamj** [comment] 2018-06-21 23:05
Can you please let us know if the issue still persists?

**Comment by JasonSowers** [comment] 2018-10-01 23:43
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team

**Closed by JasonSowers** 2018-10-01 23:43 UTC
Labels: .NET SDK, Skype, Skype image service, code examples
