### ISSUE TITLE
Chat bot single sign on

### ISSUE THREAD

**Issue by pedrosalider** [Microsoft/BotBuilder#5244] opened 2019-01-04 16:11 UTC
I have a bot running on a hosting page where users are logged in using SSO.
I want to authenticate the user in the bot automatically when the bot starts and I do not want to use anAuthCard to do it. Just want to automatically authenticate the user without prompting anything to him, just using SSO.

I found an [article](https://blog.botframework.com/2018/08/28/sign-in-experiences/) that refers three ways to authenticate an user in the bot:
1. Sharing the client's user token directly with the bot via ChannelData
2. Using an OAuthCard to drive a sign-in experience to any OAuth provider
A third option, called Single Sign-On (SSO), that is in development.

And, according to the article my situation is:

> WebChat in an authenticated website where the user is already signed in and the website has a token to the same identity provider but to a different app that the bot needs -> in the future, this is single sign-on, but for now you 'll need to use an OAuthCard.

Is there any update about this functionality? How can I authenticate the user into the bot without using an OAuthCard or a SigninCard?

Thanks in advance

**Comment by stevkan** [comment] 2019-01-16 19:56
Closing as duplicate of BotFramework-WebChat issue [#1564](https://github.com/Microsoft/BotFramework-WebChat/issues/1564#issuecomment-453266733). Issue being triaged there.

**Closed by stevkan** 2019-01-16 19:56 UTC
