### ISSUE TITLE
[Node.js SDK] Bot does not seem to use regex recognizer of its child libraries

### ISSUE THREAD

**Issue by FredEnEric** [Microsoft/BotBuilder#4362] opened 2018-03-23 13:41 UTC
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.14.0
* Deployment Environment: local development with Emulator

## Issue Description
When adding a regex recognizer to a library and then adding that library to your bot does not make the bot use that library's recognizer.

## Code Example
If you create a simple library like this.
```
const myLibrary = new builder.Library('testLibrary')
myLibrary.dialog('/', session => session.send('success')).triggerAction({ matches: 'testing' })
myLibrary.recognizer(new builder.RegExpRecognizer('testing', /^test/i))
bot.library(myLibrary.clone())
```

The bot doesn't redirect to the correct dialog. 
```
UniversalBot("*") routing "test" from "emulator"
Library("*").findRoutes() explanation:
        ActiveDialog(0.1)
/ - waterfall() step 1 of 1
/ - Session.send()
/ - Session.sendBatch() sending 1 message(s)
```

But it does when the recognizer is attached to the bot directly instead.
```
bot.recognizer(new builder.RegExpRecognizer('testing', /^test/i))
bot.library(myLibrary.clone())
```
```
UniversalBot("*") routing "test" from "emulator"
Library("*")recognize() recognized: testing(1)
Library("*").findRoutes() explanation:
        ActiveDialog(0.1)
Library("testLibrary").findRoutes() explanation:
        GlobalAction(1)
Session.beginDialog(testLibrary:/)
testLibrary:/ - waterfall() step 1 of 1
testLibrary:/ - Session.send()
testLibrary:/ - Session.sendBatch() sending 1 message(s)
```

## Expected Behavior
I would expect that the bot also uses the recognizers of its child libraries.

**Comment by Stevenic** [comment] 2018-03-24 01:03
That's interesting...  It looks like for some reason it may not even be getting into the child libraries `findRoutes()` method.  It definitely hasn't called the recognizer otherwise we should see that in the log.  @JasonSowers could you or someone try to reproduce this monday and if it's not working I can try to see where things are getting off track.  I'm trying to remember all of the rules I'd worked out for how that should work and I would have expected that to trigger as well.

**Comment by stevengum97** [comment] 2018-03-26 16:58
@Stevenic, I was able to reproduce this error, but also ran into problems with trying to use two `RegExpRecognizers` at `bot` level:

```js
const myLibrary = new builder.Library('testLibrary')
myLibrary.dialog('/', session => {
    session.send('success').endDialog('Reached root dialog of myLibrary');
}).triggerAction({ matches: 'testing' })
// myLibrary.recognizer(new builder.RegExpRecognizer('testing', /^test/i))

bot.library(myLibrary.clone())
bot.dialog('/', (session, args) => {
    session.send('Huh').send('Reached root dialog of bot.');
    session.beginDialog('testLibrary:testCancel');
})
bot.recognizer(new builder.RegExpRecognizer('testing', /^test/i))
   .recognizer(new builder.RegExpRecognizer('testCancel', /^testcancel/i));
   // Register another RegExpRecognizer to trigger "testLibrary"-registered dialog
   // while in the middle of a prompt.
   // Except 'testCancel' intent isn't being triggered.

// Dialog with prompt, uses triggerAction and beginDialogAction
myLibrary.dialog('testCancel', [
    session => {
        session.send('Reached testCancel.');
        // Create a prompt so users can begin a new "testLibrary"-registered dialog from this dialog.
        builder.Prompts.choice(session, 'Choose a number', ['1', '2']);
    },
    (session, results) => {
        session.send('You chose: ', JSON.stringify(results));
        session.endDialog();
    }
]).triggerAction({
    matches: 'testCancel'
})
.beginDialogAction('BeginNewDialogFrom"testCancel"',
    'newDialog',
    { matches: /beginNewDialog/gi }
);

// The dialog we're trying to jump to from the "testLibrary:testCancel" dialog.
myLibrary.dialog('newDialog', [
    session => {
        session.send('You reached the newDialog dialog.');
        session.endConversation();
    }
]);
```

I also console.logged the `bot`, should the default (first) library have `testLibrary` registed on it?

```js
  dialogs:
   { '/': WaterfallDialog { actions: {}, _onBeforeStep: [], steps: [Array] } },
  libraries:
   { BotBuilder:
      Library {
        domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        name: 'BotBuilder',
        dialogs: [Object],
        libraries: {}, // Should this be an empty object though we called bot.library()?
        actions: [Object],
        recognizers: [Object],
        triggersAdded: false,
        _localePath: '<some-long-path>' },
     testLibrary:
      Library {
        domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        name: 'testLibrary',
        dialogs: [Object],
        libraries: {},
        actions: [Object],
        recognizers: [Object],
        triggersAdded: false,
        _localePath: undefined,
        _onFindRoutes: undefined,
        _onSelectRoute: undefined } },
```

**Comment by sgellock** [comment] 2018-10-02 01:55
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team

**Closed by sgellock** 2018-10-02 01:55 UTC
Labels: Node.js SDK
