### ISSUE TITLE
[WebChat] Allow assigning UserId after BotConnection has been initialized?

### ISSUE THREAD

**Issue by punitganshani** [Microsoft/BotBuilder#3266] opened 2017-08-04 13:47 UTC
We are hosting a WebChat where JS code looks like,

```
var user = {
    id: params["userid"] || "myuser",
    name: params["username"] || "You"
};
```

After the WebChat is displayed, the user is presented with an option to SignIn. User completes the sign in process using Azure AD and state is updated with appropriate JWT token. So now the bot knows the actual user and his/her identity.

Please provide some way to override `myuser` after the bot connection has been initialized. This will help maintain activities & state with specific user identity instead of storing all activities/state using the fixed `myuser`

**Comment by nwhitmont** [comment] 2017-08-04 18:18
@punitganshani Are you using .NET or Node.js SDK for Bot Builder?

**Comment by punitganshani** [comment] 2017-08-04 22:41
C# SDK

**Comment by JasonSowers** [comment] 2017-08-04 22:54
closing as duplicate of https://stackoverflow.com/questions/45508234/assign-user-id-explicitly

**Closed by JasonSowers** 2017-08-04 22:54 UTC
Labels: question, WebChat
