### ISSUE TITLE
[Question] Bot works in the emulator but doesn't work on dev.botframework or on skype channel

### ISSUE THREAD

**Issue by Chetanchezz** [Microsoft/BotBuilder#3177] opened 2017-07-22 17:20 UTC
## System Information (Required)
* SDK Language:  .NET/C# 

 My bot works fine in the emulator,even with Microsoft app id and password but when I'm testing it at https://dev.botframework.com i get a message "couldn't send message retry".I get a 401 unauthorized error when I'm trying to get a reply from the emulator with bot url https://botwebdeployment.azurewebsites.net/ (deployed in azure).I have added my  bot in microsoft bot directory and have enabled skype .But even on my machine i can send message on skype app to bot but i don't get any reply.
![401](https://user-images.githubusercontent.com/18398086/28493173-71b3fac6-6f2f-11e7-94a8-51f4ca9f3c08.JPG)
![error1](https://user-images.githubusercontent.com/18398086/28493177-77ae7a5a-6f2f-11e7-92a3-ef1c100084f0.JPG)

**Comment by michaelhutchful** [comment] 2017-07-22 17:53
Makes sure that your MicrosoftAppId and MicrosoftAppPassword are set in Web.config

Sent from Mail for Windows 10

From: Chetanchezz
Sent: 22 July 2017 17:20
To: Microsoft/BotBuilder
Cc: Subscribed
Subject: [Microsoft/BotBuilder] Bot works in the emulator but doesn't work ondev.botframework or on skype channel (#3177)

System Information (Required)
• SDK Language: .NET/C#
My bot works fine in the emulator,even with Microsoft app id and password but when I'm testing it at https://dev.botframework.com i get a message "couldn't send message retry".I get a 401 unauthorized error when I'm trying to get a reply from the emulator with bot url https://botwebdeployment.azurewebsites.net/ (deployed in azure).I have added my bot in microsoft bot directory and have enabled skype .But even on my machine i can send message on skype app to bot but i don't get any reply.

**Comment by nwhitmont** [comment] 2017-07-24 15:15
Duplicate of https://stackoverflow.com/questions/45256550/my-bot-works-fine-in-the-emulator-even-with-microsoft-app-id-and-password-but-wh

**Closed by nwhitmont** 2017-07-24 15:15 UTC
Labels: .NET SDK, emulator, question
