### ISSUE TITLE
welcome message lose it's context

### ISSUE THREAD

**Issue by amitbend** [Microsoft/BotBuilder#1930] opened 2016-12-29 15:27 UTC
I've been using conversationUpdate to initiate the conversation with a welcome message 

 ```javascript
bot.on('conversationUpdate', (message) => {
    if (message.membersAdded) {
        message.membersAdded.forEach((identity) => {
            if (identity.id === message.address.bot.id) {
                bot.beginDialog(message.address, '/');
            }
        });
    }
});
```

welcome message is in `onBegin` of the root dialog calling another welcome dialog, that asking for a prompt.

now, after the welcome message when the user replies to the prompts - it sends the welcome message once again.

is it a bug? am i doing anything wrong? 

P.S.
when looking at session.message.user, i see first `{“id”:”img54g47lied64g56”}` 
and after `{“id”:”default-user”,”name”:”User”}`

**Comment by Stevenic** [comment] 2017-02-22 23:43
So we recently identified that not all channels handle this the same way. The problem is the `message.address` for that event often has the wrong `user.id` value.  You'll want to patch the `address` before calling `bot.beginDialog()`.  For the identity you want to message do:

```
message.address.user = identity;
```

That should ensure that you start a conversation with the correct user. If you want to start a conversation with multiple users you may want to copy the `address` object first.

We're planning to update our samples to better reflect this as a best practice.

**Comment by Stevenic** [comment] 2017-02-24 21:55
Closing this for now. Please feel free to add further comments.

**Comment by LarsLiden** [comment] 2017-02-27 23:53
Two things to note:
•	onConversationUpdate is called twice.  Once for the bot joining the conversation and once for the user.  You’ll need to ignore the bot one so you don’t fire messages twice
•	It’s a system message not a message from the user, so in order to send a reply you’ll need to update message.address.user

Both are shown below:


bot.on('conversationUpdate', function (message) {
    if (message.membersAdded) {
        var name = message.user ? message.user.name : null;

        // Don't respond to bot joining
        if (message.membersAdded[0].name = "Bot")
        {
            return;
        }

        // This is a system message so need to replace user with actual user
        message.address.user = message.membersAdded[0];

        // Send reply
        var msg = "hi";
        var reply = new builder.Message().address(message.address).text(msg);
        bot.send(reply);
    } 
});

**Comment by iMicknl** [comment] 2017-02-28 11:14
Thanks for the example, @LarsLiden! However I think something is not correct in the snippet. I can't get it working. Inside the declaration of the if statement you use = instead of == / ===. Also the declared var name isn't used. I already changed this in my code, however I still can't get it working.

I am trying to achieve the same as the author of this issue and I have exactly the same issue. When someone opens the website (with the WebChat), I would like to send them an intro message. The user hasn't said anything in this case yet. 

```TypeScript
//Start default dialog on first open
bot.on('conversationUpdate', (message) => {
    if (message.membersAdded) {

        // Don't respond to bot joining
        if (message.membersAdded[0].name == "Bot") {
            return;
        }

        message.address.user = message.membersAdded[0]; // https://github.com/Microsoft/BotBuilder/issues/1930
        bot.beginDialog(message.address, '/');
    }
});

// Default dialog
bot.dialog('/', [
    (session, results, next) => {
        session.preferredLocale('nl');
        session.send(`Intro text!`);

        setTimeout(() => {
            next();
        }, 2000);
    },
    (session) => {
        Prompts.choice(session, "Wanna join?", ["Yes", "No"]);
    },
```

**Comment by Stevenic** [comment] 2017-02-28 23:18
Here's an updated example which I just tested:

```
bot.on('conversationUpdate', function (message) {
    if (message.membersAdded) {
        message.membersAdded.forEach(function (identity) {
            if (identity.id == message.address.bot.id) {
                // Bot is joining conversation (page loaded)
                var reply = new builder.Message()
                        .address(message.address)
                        .text("Welcome to my page");
                bot.send(reply);
            } else {
                // User is joining conversation (they sent message)
                var address = Object.create(message.address);
                address.user = identity;
                var reply = new builder.Message()
                        .address(address)
                        .text("Hello %s", identity.name);
                bot.send(reply);
            }
        });
    }
});
```

Some things of note... On page load you're going to get a "conversationUpdate" indicating the bot has joined the conversation and you won't get notifications of a user joining until they send an actual message.  This is fairly standard though as most channels won't let you initiate contact with a user unless they've contacted you at least once.

Unfortunately, we currently track conversations on a per/user basis so calling `bot.beginDialog()` when the bot joins isn't going to do what you want. We need to add the ability to start a conversation with a group which we've talked about but haven't implemented yet.

**Closed** 2017-04-07 18:07 UTC
Labels: answered, node.js

**Comment by assaf-cream** [comment] 2017-07-31 21:58
hi,
any updated on this issue?
will the ability to start dialogs from conversationUpdaten be added in the near future?

**Comment by nwhitmont** [comment] 2017-08-04 02:35
@assaf-cream You are commenting on a closed issue. 

If you have a question or problem, please [open a new issue.](https://github.com/microsoft/botbuilder/issues/new)
