### ISSUE TITLE
[MS Teams] I need help with sideloading my bot correctly.

### ISSUE THREAD

**Issue by megancooper** [Microsoft/BotBuilder#3010] opened 2017-06-22 14:44 UTC
I am trying to side load my bot but I am finding the process for constructing the manifest.json file confusing? I created a manifest like this:
```
{
  "$schema": "https://statics.teams.microsoft.com/sdk/v1.0/manifest/MicrosoftTeams.schema.json",
  "manifestVersion": "1.0",
  "version": "1.0.0",
  "id": "ID",
  "packageName": "com.CORRECTURL",
  "developer": {
    "name": "Megan",
    "websiteUrl":    "https://website.com/",
    "privacyUrl":    "https://website.com/privacy",
    "termsOfUseUrl": "https://website.com/app-tos"
  },
  "name": {
    "short": "BotName"
  },
  "description": {
    "short": "A Bot",
    "full": "This is a bot."
  },
  "icons": {
    "outline":"outline.png",
    "color": "color.png"
  },
  "accentColor": "#FF0000",
  "bots": [
    {
      "botId": "ID",
      "needsChannelSelector":  "false",
      "scopes": ["personal", "team"]
    }
  ]
}
```
... And the bot was successfully sideloaded. But when I try to chat with my bot I can't see it? The bot is added to my team but it is not being recognized for some reason. Is this because I forgot to add something to the manifest?

**Comment by nwhitmont** [comment] 2017-06-22 14:56
@megancooper Check out the official guide here: https://msdn.microsoft.com/en-us/microsoft-teams/sideload

**Comment by nwhitmont** [comment] 2017-06-22 14:56
@megancooper for reference are you using .NET or Node SDK?

**Comment by nwhitmont** [comment] 2017-06-22 14:58
Here's the full manifest schema reference which will help you validate your manifest. https://msdn.microsoft.com/en-us/microsoft-teams/schema

**Comment by megancooper** [comment] 2017-06-22 15:56
@nwhitmont I'm using .net

**Comment by megancooper** [comment] 2017-06-22 16:18
@nwhitmont I need help setting the bot up so members of my team can have a private conversation with the bot. Right now the bot is only available via @mentions in our main group chat. How can I specify this in the manifest?
Thanks for the help.

**Comment by nwhitmont** [comment] 2017-06-22 16:52
Quick MS Teams bot deployment checklist:
- Did your O365 tenant administrator [enable sideloading](https://msdn.microsoft.com/en-us/microsoft-teams/setup) of apps for your organization?
- Did you [create an app package](https://msdn.microsoft.com/en-us/microsoft-teams/createpackage)
- Did you [sideload your bot app](https://msdn.microsoft.com/en-us/microsoft-teams/sideload) into the relevant team?

**Comment by nwhitmont** [comment] 2017-06-22 17:17
@megancooper In your manifest file - replace "ID" with your bot's Microsoft App ID that you used to register the bot.

**Comment by megancooper** [comment] 2017-06-22 20:53
@nwhitmont It wasn't an ID Issue, I redacted that for privacy. I did all these steps, and I think I figured it out. But now I'm getting an error that says:

Error while reading manifest.json: Invalid value(s) specified for icons.outline.filesize: "2098"
 Invalid value(s) specified for icons.color.filesize: "10450"


I've double checked both PNGs in my zip folder and they are the correct pixel sizes. My outline is 20x20 and color is 96x96. Is there another cause for this error?

**Comment by nwhitmont** [comment] 2017-06-22 21:26
>With the new sideloading process, the transparent .png icons that you reference in the manifest must now be smaller than ~1.5KB. Alternatively, you can reference the icon using a URL on a publicly accessible server, instead of a local path to icons inside the zip package: the size limit does not apply in this case.

https://msdn.microsoft.com/en-us/microsoft-teams/troubleshooting#error-while-reading-manifestjson

**Comment by megancooper** [comment] 2017-06-22 21:33
@nwhitmont Okay, thanks

**Comment by megancooper** [comment] 2017-06-22 21:56
Sorry for all the questions but I'm still having this one issue. I can't mention my bot in the General chat for my team. It's added to the team, but for some reason isn't being recognized. I'd like for members to start a 1:1 with it but I'm not seeing it pop up.

Here is my final manifest.json:
```
{
  "$schema": "https://statics.teams.microsoft.com/sdk/v1.0/manifest/MicrosoftTeams.schema.json",
  "manifestVersion": "1.0",
  "version": "1.0.0",
  "id": "MICROSOFT_ID_REDACTED",
  "packageName": "PKG_REDACTED",
  "developer": {
    "name": "Megan",
    "websiteUrl": "https://website.com/",
    "privacyUrl": "https://website.com/privacy",
    "termsOfUseUrl": "https://website.com/app-tos"
  },
  "name": {
    "short": "Bridget v0.0"
  },
  "description": {
    "short": "A Build Bot",
    "full": "This app displays real-time information about builds using data from a database."
  },
  "icons": {
    "outline": "outline.png",
    "color": "color.png"
  },
  "accentColor": "#FFFFFF",
  "bots": [
    {
      "botId": "MICROSOFT_ID_REDACTED",
      "isNotificationOnly": false,
      "needsChannelSelector": "true",
      "scopes": [ "personal", "team" ]
    }
  ]
}
```

And here is a snapshot of the bot in Teams:
![1](https://user-images.githubusercontent.com/8683055/27457808-b54a25d4-576b-11e7-9a85-109b79070fe4.PNG)

But for some reason I still can't mention or chat with the bot? Thanks again and apologies

**Comment by nwhitmont** [comment] 2017-06-22 23:04
@megancooper I'm unable to reproduce the error.  When I sideloaded my test bot into MS Teams (desktop app version) I was able to invoke the bot immediately using @BotName in any channel on the team.  Are you using MS Teams web or desktop app?

**Comment by megancooper** [comment] 2017-06-22 23:05
@nwhitmont I'm using the desktop app

**Comment by nwhitmont** [comment] 2017-06-22 23:09
I have Microsoft Teams Version 1.0.00.13252 (64-bit) on Win 10.

**Comment by nwhitmont** [comment] 2017-06-22 23:17
what happens if you delete the bot app & sideload it again?

**Comment by RichMoeMSFT** [comment] 2017-06-23 12:47
@megancooper  You said above that the bot was able to be @mentioned in a team but not callable in 1:1, and then after re-sideloading you're not able to @mention it?  Does it resolve the @mention by filling in the bot name?  (Note too that the bot name would be the one from the Bot Framework registration.)  In other words, is it a response issue, or can it not resolve the @botname?  Happy to try myself if you want to PM the bot id.

**Comment by nwhitmont** [comment] 2017-06-26 21:36
@megancooper How's it going on this one? Are you still having issues?

**Comment by megancooper** [comment] 2017-06-30 19:31
@nwhitmont Sorry for my late response. I have fixed the issue.

**Comment by nwhitmont** [comment] 2017-07-11 00:38
@megancooper Thanks for the update. closing

**Closed by nwhitmont** 2017-07-11 00:38 UTC
Labels: .NET SDK, MS Teams, question

**Comment by nagarjun** [comment] 2017-11-18 12:20
@megancooper @nwhitmont How did you manage to resolve this? Apparently no matter what I do, I can't get Microsoft Teams to sideload my bot. This is what my manifest.json (app ID redacted) looks like:

```
{
    "$schema": "https://statics.teams.microsoft.com/sdk/v1.0/manifest/MicrosoftTeams.schema.json",
    "manifestVersion": "1.0",
    "version": "1.0.0",
    "id": "MY_REDACTED_APP_ID",
    "packageName": "co.nagarjun.www",
    "developer": {
        "name": "Nagarjun Palavalli",
        "websiteUrl": "http://nagarjun.co/",
        "privacyUrl": "http://nagarjun.co/",
        "termsOfUseUrl": "http://nagarjun.co/"
    },
    "name": {
        "short": "ZipBot",
        "full": "ZipBot"
    },
    "description": {
        "short": "My bot description",
        "full": "my bot description"
    },
    "icons": {
        "outline": "icon-outline.png",
        "color": "icon-color.png"
    },
    "accentColor": "#2ca9d6",
    "bots": [
        {
            "botId": "MY_REDACTED_APP_ID",
            "isNotificationOnly": false,
            "scopes": [
                "personal"
            ],
            "commandLists": [
                {
                    "scopes": [
                        "personal"
                    ],
                    "commands": [
                        {
                            "title": "Help",
                            "description": "Learn how to use ZipBot within Microsoft Teams"
                        }
                    ]
                }
            ]
        }
    ],
    "permissions": [
        "identity",
        "messageTeamMembers"
    ],
    "validDomains": [
        "*.ngrok.io",
        "*.herokuapp.com"
    ]
}
```

I created a zip folder on my Mac by CD'ing into the app package directory and doing `zip -r -X "../app_package.zip" *`. I believe this makes it so that there is no root folder inside the zip folder (which Microsoft Teams does not allow). Struggling with this issue for hours. Appreciate any help.

**Comment by megancooper** [comment] 2017-11-18 17:34
@nagarjun What error do you see when you try to sideload your bot? For me it was a combination of my outline and color files being too large.

**Comment by nagarjun** [comment] 2017-11-18 18:30
@megancooper It says `Error while reading manifest.json` and nothing else. I looked at the browser console and the network calls but couldn't find anything to help me there.

**Comment by megancooper** [comment] 2017-11-20 00:33
There might be something you left out of the manifest. Have you double checked yours against the sample located [here](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema)?

**Comment by megancooper** [comment] 2017-11-20 00:36
I did notice on the sample they named the png files using their names excluding the file extension

**Comment by nagarjun** [comment] 2017-11-20 07:44
@megancooper I originally copied the entire JSON sample from the page you suggested and only changed the values of the fields that were relevant to me so, looks like it matches the format. I use Visual Studio Code and I don't see any errors in the JSON format either. Changed the icon names and tried, same outcome. Should I move this to a dedicated issue?

**Comment by megancooper** [comment] 2017-11-20 20:00
@nagarjun The only other thing I can think of would be if the manifest.json is not at the highest level of your bot sideload package. This may be a dedicated issue (if so maybe @RichMoeMSFT or @JasonSowers can help?), although I'm not sure. If you feel comfortable sharing the bot package .zip file I can see if it works for me.

**Comment by nagarjun** [comment] 2017-11-21 07:51
@megancooper I think you're right. I have a folder called /bot_package in my project root that contains the manifest.json file and images. When I run `zip -r -X "../bot_package.zip" *` or `zip -r bot_package.zip .`, and I unpack the resulting zip file, it creates a folder called bot_package and the 3 files are inside that.

I'm looking at the documentation for the zip utility but I just can't figure out how to stop this from happening. Any suggestions?

**Comment by megancooper** [comment] 2017-11-21 20:22
@nagarjun Try creating a new .zip folder and just adding in the manifest.json at the root along with your .png files

**Comment by GomathiNallasivan** [comment] 2018-04-06 11:30
Hi, I have a bot deployed in Azure and has a valid Microsoft App Id and Password , and connected the bot it into Teams and the manifest file follows, but I am not getting reply from bots in teams
{
"$schema": "https://statics.teams.microsoft.com/sdk/v1.2/manifest/MicrosoftTeams.schema.json",
"manifestVersion": "1.2",
"version": "1.0.0",
"id": "280b5919-7217-4072-ba52-adaa8e4f8b72",
"packageName": "com.contoso.helloworld",
"developer": {
"name": "Contoso",
"websiteUrl": "https://www.microsoft.com",
"privacyUrl": "https://www.microsoft.com/privacy",
"termsOfUseUrl": "https://www.microsoft.com/termsofuse"
},
"name": {
"short": "BottestHti",
"full": "To test sample bot in Azure"
},
"description": {
"short": "Hello World App for Microsoft Teams",
"full": "This sample app provides a very simple app for Microsoft Teams. You can extend this to add more content and capabilities."
},
"icons": {
"outline": "contoso20x20.png",
"color": "round.png"
},
"accentColor": "#60A18E",
"staticTabs": [{
"entityId": "com.contoso.helloworld.hellotab",
"name": "Hello Tab",
"contentUrl": "https://bottesthti.azurewebsites.net/",
"scopes": [
"personal"
]
}],
"configurableTabs": [{
"configurationUrl": "https://bottesthti.azurewebsites.net/about",
"canUpdateConfiguration": true,
"scopes": [
"team"
]
}],
"bots": [{
"botId": "280b5919-7217-4072-ba52-adaa8e4f8b72",
"needsChannelSelector": false,
"isNotificationOnly": false,
"scopes": [
"team",
"personal"
]
}],
"composeExtensions": [{
"botId": "280b5919-7217-4072-ba52-adaa8e4f8b72",
"scopes": [
"personal",
"team"
],
"commands": [{
"id": "getRandomText",
"description": "Gets some random text and images that you can insert in messages for fun.",
"title": "Get some random text for fun",
"initialRun": true,
"parameters": [{
"name": "cardTitle",
"description": "Card title to use",
"title": "Card title"
}]
}]
}],
"permissions": [],
"validDomains": []
}

**Comment by EricDahlvang** [comment] 2018-04-06 17:01
@GomathiNallasivan 

Please open a new issue: https://github.com/Microsoft/BotBuilder/issues/new
