### ISSUE TITLE
Why Botframework bot is not online anymore?

### ISSUE THREAD

**Issue by nirmalrayan** [Microsoft/BotBuilder#3895] opened 2017-12-08 16:28 UTC
## Bot Info 
* App ID: 31db772c-9761-4b25-b568-f1e140b26b4a
* SDK Platform: Node.js
* SDK Version: v6.9.1 on server and v6.11.1 on my pc
* Active Channels: Web Chat, Skype
* Deployment Environment: Azure App Service

## Issue Description
Our bot (Medibot, https://medibot.azurewebsites.net) has suddenly stopped working on all channels including WebChat. It used to work perfectly on Emulator though but stopped working from yesterday. We've been trying to debug this issue since days and have not been successful with any solutions/suggestions online. I've tried using Log stream and debug console to catch exceptions but there aren't any. 

You had commented on my earlier post (https://stackoverflow.com/questions/46564927/why-botframework-bot-only-works-only-on-emulator-and-none-of-the-other-channels?noredirect=1#comment82372024_46564927) that the bot server is not online. How do I bring it back up? In my Azure App Service Overview, it shows that the status is running and I've attached a screenshot of the same for your reference. 

## Code Example
The code is hosted in https://github.com/nirmalrayan/medibot

## Reproduction Steps
1. Visit medibot.azurewebsites.net. This should open WebChat channel's index.html document.
2. The page tries to load for a long time and throws HTTP status: 500, HTTP subStatus: 1001, HTTP Reason: Internal Server Error.
3. Bot framework displays the error message 'There was an error sending this message to your bot: HTTP status code GatewayTimeout' for Web Chat channel.

## Expected Behavior
1. Render index.html page with Web Chat iframe.
2. After the user sends the first message, the bot welcomes with a hero card.

## Actual Results
Nothing happens. The page does not get rendered. No exceptions are shown in log stream while testing. Even chatting in botframework's 'Test' section does not throw any error in Azure app service log stream. It responds back with "couldn't send, retry" message.

![1](https://user-images.githubusercontent.com/5275500/33774614-d3349900-dc61-11e7-9881-23baa80fd1fa.PNG)
![2](https://user-images.githubusercontent.com/5275500/33775460-774be5aa-dc64-11e7-8180-d285b0aa0cc6.PNG)
![3](https://user-images.githubusercontent.com/5275500/33775461-777f2848-dc64-11e7-8eb2-97d10679b406.PNG)
![4](https://user-images.githubusercontent.com/5275500/33775464-77b9b2ec-dc64-11e7-995f-b8fd82db6dc1.PNG)
![5](https://user-images.githubusercontent.com/5275500/33775465-783ef95c-dc64-11e7-86e7-4358479753b9.PNG)
![6](https://user-images.githubusercontent.com/5275500/33776744-55301820-dc68-11e7-8239-4f092f9f6d73.PNG)

**Comment by JasonSowers** [comment] 2017-12-08 17:46
Closing as duplicate of #3566

**Closed by JasonSowers** 2017-12-08 17:46 UTC
