### ISSUE TITLE
[State management Bug - Node.js] privateConversationData always get cleaned when persisted

### ISSUE THREAD

**Issue by beatgates** [Microsoft/BotBuilder#4851] opened 2018-07-12 06:21 UTC
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.15.0
* Active Channels: Web
* Deployment Environment:  Azure App Service, local development with Emulator

## Issue Description
In relates to issue #3682, in session.endConversation(), privateConversationData is always reset to {} before it's persisted, making it useless in reality because all data were purged in the storage. Users are forced to hack the userData or implement their own state management.

## Code Example
```js
bot.dialog('/', [
      session => {
        session.privateConversationData = {
            sessionId: session.message.address.conversation.id,
            beginTime: (new Date()).toISOString()
          }
        builder.Prompts.text(session, 'feedback')
      },
     (session, arg) => {
        session.privateConversationData.feedback= arg.response
        session.endConversation('feedback-received')
      }
 ])
```

## Expected Behavior
Conversation data stored in e.g. cosmos db

## Actual Results
data property is empty or only contains "BotBuilder.Data.SessionState"

**Comment by ashi1702** [comment] 2018-07-13 05:18
Hi beatgates,

I think you have missed on correctly setting/initializing the bot state data using cosmosDb. [Link](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-state-azure-cosmosdb?view=azure-bot-service-3.0). 

Additionally, try using `session.save()` explicitly before endConversation().
I hope this provides some input before a member responds here.

Cheers!

**Comment by beatgates** [comment] 2018-07-15 23:00
@ashi1702 This piece of code is only an extract for you to understand the problem. The initializing of bot state using cosmosDB is not essential for that purpose and thus not included. You can certainly use your own set up of cosmosDB and this problem will still reproduce with the provided example code above or actually any code trying to persist privateConversationData.

Secondly, using session.save() before endConversation() doesn't have any effect either. I hope you could read through issue #3682 as I quoted in the problem description to understand the problem better.

Like I described, the problem lies in the code in session.endConversation(). It always set privateConversationData and ConversationData to {} before sendBatch(), when those states get persisted. Yes, during the session, those states were persisted as expected, however once endConversation() is called, they are all gone. That's the problem. It's either a design or an implementation mistake I reckon.

**Comment by Stevenic** [comment] 2018-07-16 22:05
@beatgates `privateConversationData` and `conversationData` are both intended to be temporary storage to help track where the bot is conversationally with a user. When you call `session.endConversation()` it makes sense for this temporary storage to be cleaned up given that you've said the conversation is over.

It's worth noting that while this behavior is `by design` in the v3 SDK it's no longer automatically cleaned up for you in the v4 SDK.  With that said, it's still a best practice to delete your conversation state when the conversation is over in v4.  If you don't you run the risk of getting users into a stuck state.

**Comment by beatgates** [comment] 2018-07-16 22:38
@Stevenic Thanks for the explanation. I believe the v4 design makes more sense. There could be risks but at least they are under users' control. Developers should be responsible for any risks associated if they are taking advantage of these features.
So instead of using the built-in state management scheme, the design seems to promote separation of conversation state management from conversation logging and prefer uses to implement their own state/conversation logging?

**Comment by stevengum** [comment] 2018-10-01 17:41
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team

**Closed by stevengum** 2018-10-01 17:41 UTC
Labels: Node.js SDK
