### ISSUE TITLE
[Node.js SDK] EntityRecognizer findBestMatch returns score > 1

### ISSUE THREAD

**Issue by ubreddy** [Microsoft/BotBuilder#3516] opened 2017-09-25 04:09 UTC
## Bot Info 
* SDK Platform: Node.js
* SDK Version: 3.9.1
* Active Channels: web
* Deployment Environment: Azure App Service

## Issue Description
`botbuilder.EntityRecognizer(array, value)` returns score > 1 
Perfect matches return 1
some  near perfect matches return > 1

## Code Example

```js
syns = ["email link", "link", "email", "Through a link to salesforce in an email message", "3", "three", "c"]
inputOption = "Through a link to salesforce in an email message" 
var match = builder.EntityRecognizer.findBestMatch(syns, inputOption, 0.65);
// match.score = 1.2
```

## Expected Behavior
a score <= 1 as defined in specs

**Comment by stevengum97** [comment] 2017-09-25 23:21
@ubreddy, I was able to reproduce this, I'm looking into a fix now.

**Comment by ubreddy** [comment] 2017-10-04 11:03
any expected time to fix this?

**Comment by stevengum97** [comment] 2017-11-01 18:34
Sorry for the delay, we're working on a fix for the underlying bug that's causing this behavior.

**Comment by stevengum97** [comment] 2017-11-10 18:43
@ubreddy We're planning a new release for next week which will contain the fix I wrote. That said, we also recommend moving towards using the `PromptRecognizers `class which does feature improved recognition, and has been used in the new Prompt system since **3.8**. (**3.7.x** and earlier used the `EntityRecognizer` class for its recognition)

Closing this issue, if the fix or the `PromptRecognizers` class doesn't provide what you're looking for, feel free to reopen this issue and mention me.

**Closed by stevengum97** 2017-11-10 18:43 UTC
Labels: known issue, LUIS, Node.js SDK, question
