### ISSUE TITLE
[Question] Handling Complex Confirm Prompt

### ISSUE THREAD

**Issue by jfb74** [Microsoft/BotBuilder#3255] opened 2017-08-03 14:57 UTC
## System Information
* SDK Language: Node.js
* Development Environment: localhost

I am trying to emulate the behavior of builder.Prompts.confirm and match the yes/no response if it is there, otherwise do something with the text provided (could be anything). My use case is that I display a list of options which all have buttons that the user can click and then I ask "Was that helpful?". If the user clicks one of the buttons I need to process it. Though if its not a button click then I need to emulate the builder.Prompts.confirm intent to determine if they answered yes or no to the question. I can't seem to figure out how to get it to check if it matches the confirm intent and if not then do something else.

**Comment by nwhitmont** [comment] 2017-08-03 18:56
@jfb74 What did you try? What worked? What didn't work? Please share your code.

**Comment by nwhitmont** [comment] 2017-08-03 20:56
closing as duplicate of https://stackoverflow.com/questions/45484216/how-to-handle-yes-no-response-from-user-similar-to-builder-prompts-confirm

**Closed by nwhitmont** 2017-08-03 20:56 UTC
Labels: Node SDK, prompts, question
