### ISSUE TITLE
[.NET SDK] Telegram client doesn't recognize replies from bot as replies

### ISSUE THREAD

**Issue by akakoychenko** [Microsoft/BotBuilder#4399] opened 2018-03-30 09:41 UTC
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.14.1.1
* Active Channels: Telegram
* Deployment Environment: own server + Azure Bot Service, 

## Issue Description
Telegram client (Telegram X for Android) still shows the waiting picture on the bot's button after the bot reply. After a while Telegram also shows a notification. "The bot doesn't respond. Try again later ". Nevertheless, the reply from the bot shows correct.

## Code Example

var message = messageFromUser.CreateReply()
... filling the message
var result = await _connector.Conversations.ReplyToActivityAsync(message);

## Reproduction Steps
1. get the message with buttons from bot
2. push any button
3. wait for the bot reply

## Expected Behavior
The waiting pictogram (small rolling circle) on the button disappears
## Actual Results
The waiting pictogram still active. After 30 seconds-1 minute. Telegram shows notification "The bot doesn't respond. Try again later "

**Comment by nodeomega** [comment] 2018-04-03 22:47
What version of Android are you using?  Is Telegram updated to the latest executable?

**Comment by akakoychenko** [comment] 2018-04-03 23:09
Android 7.0, Telegram X 0.20.6.909-arm64-v8a (latest version, published on April,  1)
-------- Исходное сообщение --------От: Jon Russell <notifications@github.com> Дата: 04.04.18  1:47  (GMT+02:00) Кому: Microsoft/BotBuilder <BotBuilder@noreply.github.com> Копия: akakoychenko <a.kakoychenko@gmail.com>, Author <author@noreply.github.com> Тема: Re: [Microsoft/BotBuilder] Telegram client doesn't recognize replies from bot as replies (#4399) 
What version of Android are you using?  Is Telegram updated to the latest executable?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Microsoft/BotBuilder","title":"Microsoft/BotBuilder","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Microsoft/BotBuilder"}},"updates":{"snippets":[{"icon":"PERSON","message":"@nodeomega in #4399: What version of Android are you using?  Is Telegram updated to the latest executable?"}],"action":{"name":"View Issue","url":"https://github.com/Microsoft/BotBuilder/issues/4399#issuecomment-378423545"}}}

**Comment by nyxsys** [comment] 2018-06-27 20:00
Apologies for the wait are you still experiencing this problem? It seems like maybe ReplyToActivityAsync could be your problem with this use case.

Here is a code snippet that creates a message and adds buttons. When used with the telegram channel and when one of the buttons is pressed, there is no timeout and the value of the button is returned and processed by the bot, which echoes the value back to the chat.

       `private async Task MessageReceivedAsync(IDialogContext context, IAwaitable<object> result)
        {
            var activity = await result as Activity;


            // Calculate something for us to return
            int length = (activity.Text ?? string.Empty).Length;
            var message = activity.CreateReply();
            message.Text = $"You sent {activity.Text} which was {length} characters";
            
            message.SuggestedActions = new SuggestedActions()
            {
                Actions = new List<CardAction>()
                {
                    new CardAction(){ Title = "Blue", Type=ActionTypes.ImBack, Value="Blue" },
                    new CardAction(){ Title = "Red", Type=ActionTypes.ImBack, Value="Red" },
                    new CardAction(){ Title = "Green", Type=ActionTypes.ImBack, Value="Green" }
                }
            };



            await context.PostAsync(message);

            context.Wait(MessageReceivedAsync);
        }`
Please let me know if this pattern works for you.

**Comment by akakoychenko** [comment] 2018-06-28 10:56
I don't work with IDialogContext, using Activity instead
Here is a sample of my code

```[BotAuthentication]
    public class MessagesController : ApiController
    {
        public async Task<HttpResponseMessage> Post([FromBody]Activity activity)
        {
            ...
        }
    }

**Comment by akakoychenko** [comment] 2018-06-28 13:10
And regarding the problem - yes, I still experiencing the problem

**Comment by JasonSowers** [comment] 2018-06-28 15:30
Can you please provide a complete minimum reproducible example with actual code?

**Comment by akakoychenko** [comment] 2018-06-28 15:43
```[BotAuthentication]
    public class MessagesController : ApiController
    {
        public async Task<HttpResponseMessage> Post([FromBody]Activity activity)
        {
            Activity reply = activity.CreateReply();
            reply.AttachmentLayout = AttachmentLayoutTypes.List;
            reply.Attachments = new List<Attachment>()
            {
                new HeroCard
                {
                    Buttons = new [] 
                    {
                        new CardAction
                        {
                            Type = "imBack",
                            Title = "Push me!",
                            Value = "value"
                        }
                    }.ToList()
                }
                .ToAttachment()
            };

            using (var client = new ConnectorClient(
                new Uri(activity.ServiceUrl),
                new MicrosoftAppCredentials(
                    ConfigurationManager.AppSettings["MicrosoftAppId"],
                    ConfigurationManager.AppSettings["MicrosoftAppPassword"])
                ))
            {
                await client.Conversations.ReplyToActivityAsync(reply);
            }
            return new HttpResponseMessage(HttpStatusCode.OK);
        }
    }

**Comment by nyxsys** [comment] 2018-06-28 21:05
Just to double check, are you seeing this implementation work in any other channel? Is it only broken in Telegram?

**Comment by akakoychenko** [comment] 2018-06-29 20:08
I use telegram and skype only. Skype does not provide waiting wheel at all, so this problem is not relevant for Skype, and this code works with Skype perfectly. 
null

**Comment by akakoychenko** [comment] 2018-06-29 21:57
Yes, I don't use ngrok, but I have forwarded traffic via IIS url rewrite to the bot, running from VS. Nevertheless, it works the same from both IIS and VS.
null

**Comment by nyxsys** [comment] 2018-07-02 20:30
Currently herocard will not output its button values to the chatlog in telegram when they are pressed. However SuggestedActions will do this. I've edited my previous example to fit your code to illustrate what this looks like. 

```c#
public async Task<HttpResponseMessage> Post([FromBody]Activity activity)
        {
            Activity reply = activity.CreateReply();
            reply.Text = "choose an action";
            reply.SuggestedActions = new SuggestedActions()
            {
                Actions = new List<CardAction>()
                        {   new CardAction()
                            {
                                Type = "imBack",
                                Title = "Push me!",
                                Value = "value"
                            }
                        }
            };


            using (var client = new ConnectorClient(
                new Uri(activity.ServiceUrl),
                new MicrosoftAppCredentials(
                    ConfigurationManager.AppSettings["MicrosoftAppId"],
                    ConfigurationManager.AppSettings["MicrosoftAppPassword"])
                ))
            {
                await client.Conversations.ReplyToActivityAsync(reply);
            }
            return new HttpResponseMessage(HttpStatusCode.OK);
        }
```

**Comment by nyxsys** [comment] 2018-07-17 15:46
Closing, please reopen if you need further help.

**Closed by nyxsys** 2018-07-17 15:46 UTC
Labels: .NET SDK, Telegram, investigate
