### ISSUE TITLE
Error in QnaMakerAI chat bot while using feedback on the conversation. Object reference not set to instance of an object. File of type 'text/plain'.

### ISSUE THREAD

**Issue by RakeshKumarPradhan** [Microsoft/BotBuilder#4267] opened 2018-03-07 10:07 UTC
## Bot Info
* SDK Platform: .NET 
* SDK Version: .NET Framework 4.6 (visual studio 2017). 
* Active Channels: web chat, skypeforbusiness. 
* Deployment Environment: local development with Emulator

## Issue Description- 
I have been following the exact code sample as is referred in - 
https://github.com/Microsoft/BotFramework-Samples/tree/master/blog-samples/CSharp/Bot-Feedback-Sample/Bot-Feedback-Sample. 
While my normal qnaMakerAi chat bot works fine, there is an issue while I was trying to enhance it's feature and include the bot feedback within the response. 

issue is in the file section - 
https://github.com/Microsoft/BotFramework-Samples/blob/master/blog-samples/CSharp/Bot-Feedback-Sample/Bot-Feedback-Sample/App_Start/WebApiConfig.cs
Exception: Object reference not set to an instance of an object.
[File of type 'text/plain']
**Error log in bot emulator -** 
[15:14:01] <- GET 200 getPrivateConversationData 
[15:14:01] <- GET 200 getConversationData 
[15:14:01] <- GET 200 getUserData 
[15:14:04] <- POST 200 setConversationData 
[15:14:04] <- POST 200 setUserData 
[15:14:04] <- POST 200 setPrivateConversationData 
[15:14:04] <- POST 200 Reply[message] text/plain 
[15:14:04] -> POST Request to 'http://localhost:3984/api/messages' failed: [500] Internal Server Error 
**Details of error in emulator -** 
"membersAdded": [],
  "membersRemoved": [],
  "locale": "en-US",
  "text": "Exception: Object reference not set to an instance of an object.",
  "attachments": [
    {
      "contentType": "text/plain",
      "content": "   at Microsoft.Bot.Builder.CognitiveServices.QnAMaker.QnAMakerService.<Microsoft-Bot-Builder-CognitiveServices-QnAMaker-IQnAService-QueryServiceAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Builder.CognitiveServices.QnAMaker.Extensions.<QueryServiceAsync>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Builder.CognitiveServices.QnAMaker.QnAMakerDialog.<MessageReceivedAsync>d__8.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Builder.Dialogs.Internals.DialogTask.ThunkResume`1.<Rest>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Builder.Internals.Fibers.Wait`2.

## Code Example
        public static void Register(HttpConfiguration config)
        {
            // Json settings
            config.Formatters.JsonFormatter.SerializerSettings.NullValueHandling = NullValueHandling.Ignore;
            config.Formatters.JsonFormatter.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
            config.Formatters.JsonFormatter.SerializerSettings.Formatting = Formatting.Indented;
            **JsonConvert.DefaultSettings = () => new JsonSerializerSettings()
            {
                ContractResolver = new CamelCasePropertyNamesContractResolver(),
                Formatting = Newtonsoft.Json.Formatting.Indented,
                NullValueHandling = NullValueHandling.Ignore,
            };**

            // Web API configuration and services

            // Web API routes
            config.MapHttpAttributeRoutes();

            config.Routes.MapHttpRoute(
                name: "DefaultApi",
                routeTemplate: "api/{controller}/{id}",
                defaults: new { id = RouteParameter.Optional }
            );
        }
The above code example is the generic code, but somehow it is giving this error, specifically in the lines as highlighted above. 

## Reproduction Steps
1. Run the C# program. 
2. Open the bot framework emulator - connect to http://localhost:3984/api/messages. Provide the microsoft app id and password. Settings is bypass ngrok for local address. 
3. Once connected. Ping the chat bot through the emulator and debug the application. 

## Expected Behavior
response as is in the DCenterBot, with feedback option on the answers provided by the bot. 

## Actual Results

![image](https://user-images.githubusercontent.com/14177596/37086807-84ed1936-221e-11e8-8b8a-d6288c6c2837.png)

**Comment by JasonSowers** [comment] 2018-03-07 17:03
Duplicate of https://stackoverflow.com/questions/49149970/error-in-bot-framework-emulator-microsoft-qnamakerapi where the community has already engaged.

**Comment by JasonSowers** [comment] 2018-03-07 23:27
I have thoroughly tested this sample and have it running with no issues, you are going to have to share any code that is different from this sample.  The WebApiConfig.cs is not the code causing the problem it is a part of handling the problem.

**Comment by RakeshKumarPradhan** [comment] 2018-03-08 00:55
@JasonSowers  - please find the following:- 
Here is the code for the messages controller - 
using System;
using System.Threading.Tasks;
using System.Web.Http;

using Microsoft.Bot.Connector;
using Microsoft.Bot.Builder.Dialogs;
using System.Web.Http.Description;
using System.Net.Http;
using QnABot.Dialogs;

namespace Microsoft.Bot.Sample.QnABot
{
    [BotAuthentication]
    public class MessagesController : ApiController
    {
        /// <summary>
        /// POST: api/Messages
        /// receive a message from a user and send replies
        /// </summary>
        /// <param name="activity"></param>
        [ResponseType(typeof(void))]
        public virtual async Task<HttpResponseMessage> Post([FromBody] Activity activity)
        {
            // check if activity is of type message
            if (activity.GetActivityType() == ActivityTypes.Message)
            {
                //await Conversation.SendAsync(activity, () => new RootDialog());
                await Conversation.SendAsync(activity, () => new QnaDialog());
            }
            else
            {
                HandleSystemMessage(activity);
            }
            return new HttpResponseMessage(System.Net.HttpStatusCode.Accepted);
        }

        private Activity HandleSystemMessage(Activity message)
        {
            if (message.Type == ActivityTypes.DeleteUserData)
            {
                // Implement user deletion here
                // If we handle user deletion, return a real message
            }
            else if (message.Type == ActivityTypes.ConversationUpdate)
            {
                // Handle conversation state changes, like members being added and removed
                // Use Activity.MembersAdded and Activity.MembersRemoved and Activity.Action for info
                // Not available in all channels
            }
            else if (message.Type == ActivityTypes.ContactRelationUpdate)
            {
                // Handle add/remove from contact lists
                // Activity.From + Activity.Action represent what happened
            }
            else if (message.Type == ActivityTypes.Typing)
            {
                // Handle knowing tha the user is typing
            }
            else if (message.Type == ActivityTypes.Ping)
            {
                
            }

            return null;
        }
    }
}

And here is the code for - QnADialog - 
using Microsoft.Bot.Builder.Azure;
using Microsoft.Bot.Builder.CognitiveServices.QnAMaker;
using Microsoft.Bot.Builder.Dialogs;
using Microsoft.Bot.Connector;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Threading.Tasks;
using System.Web;

namespace QnABot.Dialogs
{
    [Serializable]
    public class QnaDialog : QnAMakerDialog
    {
        public QnaDialog() : base(new QnAMakerService(new QnAMakerAttribute("b372e477-0a2f-4a5a-88d5-3a664d16a4c3", "4ee02ead36a34ba5abc33edbf7952535", "Sorry, I couldn't find an answer for that", 0.5)))
        {
        }

        protected override async Task RespondFromQnAMakerResultAsync(IDialogContext context, IMessageActivity message, QnAMakerResults result)
        {
            // answer is a string
            var answer = result.Answers.First().Answer;

            Activity reply = ((Activity)context.Activity).CreateReply();

            string[] qnaAnswerData = answer.Split(';');
            int dataSize = qnaAnswerData.Length;

            string title = qnaAnswerData[0];
            string description = qnaAnswerData[1];
            string url = qnaAnswerData[2];
            string imageURL = qnaAnswerData[3];

            HeroCard card = new HeroCard
            {
                Title = title,
                Subtitle = description,
            };

            card.Buttons = new List<CardAction>
            {
                new CardAction(ActionTypes.OpenUrl, "Learn More", value: url)
            };

            card.Images = new List<CardImage>
            {
                new CardImage( url = imageURL)
            };

            reply.Attachments.Add(card.ToAttachment());


            await context.PostAsync(reply);
        }

        protected override async Task DefaultWaitNextMessageAsync(IDialogContext context, IMessageActivity message, QnAMakerResults result)
        {
            // get the URL
            var answer = result.Answers.First().Answer;
            string[] qnaAnswerData = answer.Split(';');
            string qnaURL = qnaAnswerData[2];

            // pass user's question
            var userQuestion = (context.Activity as Activity).Text;

            context.Call(new FeedbackDialog(qnaURL, userQuestion), ResumeAfterFeedback);

        }

        private async Task ResumeAfterFeedback(IDialogContext context, IAwaitable<IMessageActivity> result)
        {
            if (await result != null)
            {
                await MessageReceivedAsync(context, result);
            }
            else
            {
                context.Done<IMessageActivity>(null);
            }
        }

    }
}

And here for feedback dialog - 

using Microsoft.ApplicationInsights;
using Microsoft.Bot.Builder.Dialogs;
using Microsoft.Bot.Connector;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;

namespace QnABot.Dialogs
{
    [Serializable]
    public class FeedbackDialog : IDialog<IMessageActivity>
    {
        private string qnaURL;
        private string userQuestion;

        public FeedbackDialog(string url, string question)
        {
            // keep track of data associated with feedback
            qnaURL = url;
            userQuestion = question;
        }

        public async Task StartAsync(IDialogContext context)
        {
            var feedback = ((Activity)context.Activity).CreateReply("Did you find what you need?");

            feedback.SuggestedActions = new SuggestedActions()
            {
                Actions = new List<CardAction>()
                {
                    new CardAction(){ Title = "👍", Type=ActionTypes.PostBack, Value=$"yes-positive-feedback" },
                    new CardAction(){ Title = "👎", Type=ActionTypes.PostBack, Value=$"no-negative-feedback" }
                }
            };

            await context.PostAsync(feedback);

            context.Wait(this.MessageReceivedAsync);
        }

        public async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> result)
        {
            var userFeedback = await result;

            if (userFeedback.Text.Contains("yes-positive-feedback") || userFeedback.Text.Contains("no-negative-feedback"))
            {
                // create telemetry client to post to Application Insights 
                TelemetryClient telemetry = new TelemetryClient();

                if (userFeedback.Text.Contains("yes-positive-feedback"))
                {
                    // post feedback to App Insights
                    var properties = new Dictionary<string, string>
                    {
                        {"Question", userQuestion },
                        {"URL", qnaURL },
                        {"Vote", "Yes" }
                        // add properties relevant to your bot 
                    };

                    telemetry.TrackEvent("Yes-Vote", properties);
                }
                else if (userFeedback.Text.Contains("no-negative-feedback"))
                {
                    // post feedback to App Insights
                }

                await context.PostAsync("Thanks for your feedback!");

                context.Done<IMessageActivity>(null);
            }
            else
            {
                // no feedback, return to QnA dialog
                context.Done<IMessageActivity>(userFeedback);
            }
        }
    }
}

**Comment by RakeshKumarPradhan** [comment] 2018-03-08 11:38
Hi, 
The issue currently stands resolved based on the answer provided at https://stackoverflow.com/questions/49149970/error-using-qnamaker-sample-with-feedback. 
Basically, the subscriptionKey and the KnowledgebaseId were inverted/interchanged. 

The messages are being responded properly. However, currently, coming back to the original use case of fetching the user feedback on the response - I am facing an error , since the response has got only one string, not a description and url, which would make it 3 parameters in order to move into the - 
                    context.Call(new FeedbackDialog(qnaUrl, userQuestion), ResumeAfterFeedback);

**Comment by RakeshKumarPradhan** [comment] 2018-03-08 11:40
The updated code for the QnaDialog.cs file is as follows - 
using Microsoft.Bot.Builder.Azure;
using Microsoft.Bot.Builder.CognitiveServices.QnAMaker;
using Microsoft.Bot.Builder.Dialogs;
using Microsoft.Bot.Connector;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Threading.Tasks;
using System.Web;

namespace QnABot.Dialogs
{
    [Serializable]
    public class QnaDialog : QnAMakerDialog
    {
        public QnaDialog() : base(new QnAMakerService(new QnAMakerAttribute("4ee02ead36a34ba5abxxxxxxx", "b372e477-0a2f-4a5a-88d5-yyyyyyyy", "Sorry, I couldn't find an answer for that", 0.5)))
        {
        }
        // b372e477-0a2f-4a5a-88d5-3a664d16a4c3

        protected override async Task RespondFromQnAMakerResultAsync(IDialogContext context, IMessageActivity message, QnAMakerResults result)
        {
            // answer is a string
            var answer = result.Answers.First().Answer;

            Activity reply = ((Activity)context.Activity).CreateReply();

            var qnaAnswerData = answer.Split(';');
            var dataSize = qnaAnswerData.Length;

            if (dataSize == 3)
            {
                var title = qnaAnswerData[0];
                var description = qnaAnswerData[1];
                var url = qnaAnswerData[2];
                var imageUrl = qnaAnswerData[3];

                var card = new HeroCard
                {
                    Title = title,
                    Subtitle = description,
                    Buttons = new List<CardAction>
            {
                new CardAction(ActionTypes.OpenUrl, "Learn More", value: url)
            },
                    Images = new List<CardImage>
            {
                new CardImage(url = imageUrl)
            },
                };

                reply.Attachments.Add(card.ToAttachment());
            }
            else
            {
                reply.Text = answer;
            }

            await context.PostAsync(reply);
        }

        protected override async Task DefaultWaitNextMessageAsync(IDialogContext context, IMessageActivity message, QnAMakerResults result)
        {
            if (result.Answers.Count > 0)
            {
                // get the URL
                var answer = result.Answers.First().Answer;
                var qnaAnswerData = answer.Split(';');

                var dataSize = qnaAnswerData.Length;

                if (dataSize == 3)
                {
                    var qnaUrl = qnaAnswerData[2];

                    // pass user's question
                    var userQuestion = (context.Activity as Activity).Text;

                    context.Call(new FeedbackDialog(qnaUrl, userQuestion), ResumeAfterFeedback);
                }
                else
                {
                    await ResumeAfterFeedback(context, new AwaitableFromItem<IMessageActivity>(null));
                }
            }
            else
            {
                await ResumeAfterFeedback(context, new AwaitableFromItem<IMessageActivity>(null));
            }
        }

        private async Task ResumeAfterFeedback(IDialogContext context, IAwaitable<IMessageActivity> result)
        {
            if (await result != null)
            {
                await MessageReceivedAsync(context, result);
            }
            else
            {
                context.Done<IMessageActivity>(null);
            }
        }

    }
}

**Comment by JasonSowers** [comment] 2018-03-08 19:11
Glad you got this working

**Comment by matthewshim-ms** [comment] 2018-03-08 19:24
Hi @RakeshKumarPradhan ,

There are several ways you can handle this, mostly with basic conditional flow within your bot code. The sample code from the blog post really only provisioned the 'feedback' suggested action for the full rendered card responses. In this case, we can do something like this:

`        protected override async Task RespondFromQnAMakerResultAsync(IDialogContext context, IMessageActivity message, QnAMakerResults result)
        {
            // used to determine if response is valid to format to a card, or serve static answer
            bool QnaStandardAnswer = result.Answers.First().Answer.Contains(";"); 

            if(result.Answers.Count == 0)
            {
                context.Done<IMessageActivity>(null);
            }
            else if (!QnaStandardAnswer) 
            {
                Activity reply = ((Activity)context.Activity).CreateReply();
                reply.Text = result.Answers[0].Answer;
                await context.PostAsync(reply);

                 // Your QnA response I'm assuming is just text, so from the activity you can get the reply, then
                 // use context.Call(new FeedbackDialog), etc. 
            }
            else
              // render 'card' response, i.e semi-colon delimited string;url;description... 
`

Does this make sense? If your bot is expecting different types of response from your QnA service, then your bot needs to have code to handle different types of responses. 

Hope this helps

**Comment by RakeshKumarPradhan** [comment] 2018-03-09 01:16
@matthewshim-ms  - thanks.

**Closed** 2018-03-09 17:48 UTC
