### ISSUE TITLE
webchat not working

### ISSUE THREAD

**Issue by ubreddy** [Microsoft/BotBuilder#631] opened 2016-07-10 04:47 UTC
The chatbot is working on skype. but on webchat channel, it is not working.
on ngrok console I notice this difference between the two.
skype: 202 and 100
webchat: 202 only.

**Comment by alexsorokoletov** [comment] 2016-07-10 05:01
I can also reproduce the problem with the hello world sample
https://github.com/Microsoft/BotBuilder/blob/master/Node/examples/hello-ChatConnector/app.js

For me, bot works in Skype and Telegram, but doesn't work in webchat and facebook.
Tracing requests I see that the node server sends responses ("Hello World") back, I assume they're lost somewhere in between

**Comment by arieschwartzman** [comment] 2016-07-11 14:21
Same here. Skype, Slack and Emulator works. I can see this error in Browser's debug window when sending text to the bot

```
Name	Protocol	Method	Result	Content type	Received	Time	Initiator
https://webchat.botframework.com/api/conversations/H9Lh3tTfJ2O/messages	HTTPS	POST	500	application/json	42 B	2.13 s	parsedElement
Request Body
{"conversationId":"H9Lh3tTfJ2O","from":null,"to":null,"text":"leg"}

Response Body
{
  "message": "Internal server error"
}

```

**Comment by dandriscoll** [comment] 2016-07-12 01:59
Thanks for reporting. We're still seeing occasional bots generating 403/500 in this API. I made some fixes about a week ago but it looks like you're hitting problems still.

**Comment by alexsorokoletov** [comment] 2016-07-12 03:33
I see this problem also, webchat is not working for me, though chrome console shows bit different errors 
https://www.dropbox.com/s/5cssfoqe88wodol/Screenshot%202016-07-11%2023.30.02.png?dl=0

**Comment by alexsorokoletov** [comment] 2016-07-17 04:56
Webchat started working for me yesterday. I've upgraded bot to 3.0.1 and redeployed to Azure, then refreshed the credentials in the Webchat configuration. 
One thing I noticed is that if you respond quickly to Webchat, it looses some messages and conversation lags behind.

**Comment by v-thgratMSGit** [comment] 2016-07-28 23:46
Closing this issue. Thanks!

**Closed by v-thgratMSGit** 2016-07-28 23:46 UTC

**Comment by alexsorokoletov** [comment] 2016-07-29 16:07
We still see problems with webchat, unfortunately. It's working but after a while messages start lagging behind. So you see bot's response only if you send a one more message and when that problem starts it goes on.
