### ISSUE TITLE
Dialog handler not getting invoked with BotConnectorBot connected to facebook channel

### ISSUE THREAD

**Issue by thealokkr** [Microsoft/BotBuilder#351] opened 2016-05-26 09:48 UTC
My default dialog is not getting invoked with BotConnectorBot which is connected to facebook channel.  It is working fine on test connection tool. it would be helpful if bots examples includes facebook channel sample apps. Here is my code for it.

```
var restify = require('restify');
var builder = require('botbuilder');

// Create bot and add dialogs
var bot = new builder.BotConnectorBot({ appId: 'xxxx', appSecret: 'xxxxxxx' });
bot.add('/', function (session) {
   console.log('Anything good');
   session.send('Hello World'); 
});

// Initialize server
var server = restify.createServer();
server.use(restify.bodyParser());

server.get('/webhook/', function (req, res) { 
     
    if (req.params.hub.verify_token === 'xxxx') {
          console.log(req.params.hub.challenge);
          res.contentType = "text/plain";    
          res.send(req.params.hub.challenge);
        //res.send(req.query['hub.challenge']);
      }       
      res.send('Error, wrong validation token');
    });

server.post('/webhook', bot.verifyBotFramework(), bot.listen());

// Start server
server.listen(3978, function () {
    console.log('%s listening to %s', server.name, server.url); 
});

```
The server.post does get invoked when i replace the bot.verifyBotFramework(), bot.listen() with a normal logging statement.

**Comment by Stevenic** [comment] 2016-05-27 19:09
Two questions... Does it work if you remove just the call to `bot.verifyBotFramework()`? If so, did you use the primary secret from the portal for your app secret or the secondary one? The secondary one doesn't work.

**Comment by thealokkr** [comment] 2016-05-28 04:01
no it didn't work on facebook even if removed the call to verifyBotFramework. I am using the primary secret.

**Comment by Stevenic** [comment] 2016-05-28 16:59
So you're saying that your bot receives the post from facebook but isn't replying?  If that's the case your bot could just be in a bad state. Try sending a message of "/deleteprofile" from your messenger client. This will ensure that the bot is in a clean state.

**Comment by Stevenic** [comment] 2016-06-01 08:12
any luck?

**Comment by thealokkr** [comment] 2016-06-02 07:26
I deleted and re-registered the bot and it received the message but still couldn't send it.  Bot connector is using deprecated function of express middleware. Just to let you that i am using express middleware and not restify.
```
express deprecated res.send(status): Use res.sendStatus(status) instead node_mod
ules\botbuilder\lib\bots\BotConnectorBot.js:62:21

```

**Comment by thealokkr** [comment] 2016-06-02 07:57
Few more things...
The authorization is failing inside connector bot. Though the app works fine in test harness on dashboard.
Also i see two examples on connector bot. Which example is appropriate to follow?
[](http://docs.botframework.com/builder/node/bots/BotConnectorBot/#navtitle)

[](http://docs.botframework.com/connector/libraries/node/#navtitle)

**Comment by Stevenic** [comment] 2016-06-02 09:57
Use the BotConnectorBot examples..

So one thing I just noticed in the original code you posted, it looks like you're hard coding the server to use port 3978 which will work fine locally but I'm assuming probably won't work when deployed to the cloud. I don't know where you're hosting your bot but are you following all of the guidance laid out by the service for how you should dynamically bind your server to its port?  If the port truly is 3978 did you include ":3978" in the host name for the endpoint you configured in the Bot Framework portal?

If nothing is working that means your server is unreachable which likely means something about the endpoint you configured is wrong.

**Comment by thealokkr** [comment] 2016-06-02 10:10
I am using ngrok to map the callback url. My non MSFT based bot is working fine via this networking so don't think network is a problem. 
one question - is it possible to just use bot builder and not go via bot registration for FB

**Comment by Stevenic** [comment] 2016-06-02 17:19
We don't have a native facebook connector unfortunately.

**Comment by Stevenic** [comment] 2016-06-02 17:20
you said your using ngrok... What's the endpoint you've configured in the Bot Framework portal? I'm sorry I just need to see everything and I could tell you in 30 seconds what the issue is.

**Comment by thealokkr** [comment] 2016-06-03 10:46
It is failing at 
`if (req.headers.hasOwnProperty('authorization'))` in verifyBot

**Comment by Stevenic** [comment] 2016-06-03 15:53
Are there no headers?  Let me try to replicate this. Which version of Express are you using?

**Comment by thealokkr** [comment] 2016-06-04 12:28
No headers. Express version -2.15.5

**Comment by v-thgratMSGit** [comment] 2016-07-12 22:16
Closing this issue. @thealokkr - please open a new issue if this issue is not fixed and needs further discussion. @Stevenic - reopen if necessary. Thanks!

**Closed by v-thgratMSGit** 2016-07-12 22:16 UTC
Labels: bug
