### ISSUE TITLE
Skype bot | ServiceError: Acl check failed

### ISSUE THREAD

**Issue by igor-pukhlov** [Microsoft/BotBuilder#4651] opened 2018-05-23 16:26 UTC
## Issue Description
We are helpdesk service and our clients using Skype bots for their user's support. Sometimes they unable to send a message's to Skype because we got fail message: «ServiceError: Acl check failed».

For example, a problem sometimes appear on this bot Microsoft App ID: c360a752-d5f1-46f4-9e4a-37cf0c41f1cc

I found here that it is a long time issue. Is there any news about it? Can we do something or recommend anything to our clients to resolve it?

**Comment by EricDahlvang** [comment] 2018-05-25 00:27
This error only occurs when the bot attempts to send a message to the user and the bot is not in the user's contact list.  Maybe some users have removed or blocked your bot?

**Comment by igor-pukhlov** [comment] 2018-05-25 06:03
The error always appears with new user's. They write their first message to bot, but we can't send them an answer. They should add a bot to contact list before sending a message, but we still get this ACL (access control list) check failed.

Because it happens after first's message from a user and we don't know him, we evenly can't contact with him in another way to ask re-add bot or send us more information about skype version etc.

Our clients very disappointed about it and always writing us, because they thought this error is on our side but it is not so.

**Comment by EricDahlvang** [comment] 2018-05-25 16:29
The Skype team has looked into this issue before, and informed us that it only occurs when the bot attempts to contact a user who does not have the bot in their contacts list.  Do you believe you are seeing this error under some other circumstance?

I just added your bot to my skype, and was able to communicate with it without errors.

There have been other reports of ACL check failed:
https://github.com/Microsoft/BotBuilder/issues/3268
https://github.com/Microsoft/BotBuilder/issues/3297
https://github.com/Microsoft/BotBuilder/issues/3310
https://github.com/Microsoft/BotBuilder/issues/3326
https://github.com/Microsoft/BotBuilder/issues/3721

**Comment by igor-pukhlov** [comment] 2018-05-25 19:34
Yes, we found that we are not first who writing about this issue, but it still exists.

Most time everything goes fine and we receiving and sending messages via skype bot like it was with you. But our client already reports us about minimum 5 times when they got a new message from a new user, but can't answer him because of acl check failed. One of example's: http://jmp.sh/a4xP5CL

So, scenario always like this: user push the link on a website (https://skyeng.ru) to get contact via skype — bot should be added to his contact list before a user can write a message, but it doesn't happen. A user sends a message to bot, that not in his contact list — user can't receive an answer, because of we can't send it to him.

**Comment by EricDahlvang** [comment] 2018-05-25 21:18
Ok, I will notify the Skype Bot team.  

However, whenever this has come up before, they have stated that the following is the only case they have seen where ACL Check fails: "User adds a bot, then blocks it, the bot never knows about a blocked event and keeps posting. "

**Comment by igor-pukhlov** [comment] 2018-05-28 06:54
We get some more examples when we couldn't send an answer to the first message from a user because of ACL Check failed. 

http://jmp.sh/fXpYLip
http://jmp.sh/qYyAYpU
http://jmp.sh/8pLoZNs

**Comment by EricDahlvang** [comment] 2018-05-29 18:56
@igor-pukhlov The skype team has replied that "It’s not possible through the Skype client because we disable the message composer itself if the bot is not in your contacts or is blocked.  Also, the screenshots shared don't look like the Skype client."

What client are you using?

**Comment by cissav** [comment] 2018-05-30 08:52
@EricDahlvang Hello,

Yes, it's not the Skype client. The bot is used via API.

We have helpdesk software that companies use to provide multichannel support. Our customers connect their Skype bots to helpdesk (via Microsoft App ID and App Password). As soon as the bot is connected to the helpdesk company's agents see all the messages from Skype Bot in our interface.

Generally everything works fine, and agents communicate with the users using helpdesk. However sometimes it doesn't work: agent receives a message from new user, but can't reply to him\her because we (helpdesk) are getting the error while trying to send the reply via API:

http://jmp.sh/fXpYLip
http://jmp.sh/qYyAYpU
http://jmp.sh/8pLoZNs

These screenshots are from our interface, but we get them from you.

As I understand the error (ACL Check failed) is there when user doesn't add bot to the contact list, but it's too unlikely that a lot of users add the bot to the contact list and delete it straightaway before company's agent can reply to them.

Thus there should be a bug during the process of adding the bot to the contact list. Looks like sometimes it just doesn't work, and users need to make another attempt to add the bot to the contact list. However the problem is that users don't know they need to do something, they think that the company doesn't reply to the messages.

Maybe this problem happens only when users use older versions of Skype clients.

**Comment by EricDahlvang** [comment] 2018-05-31 01:28
@cissav I've requested someone from the Skype bot team assist you with this.  Thank you for your patience.

**Comment by igor-pukhlov** [comment] 2018-06-15 09:34
@EricDahlvang Hello,

Any news about our issue?

Today our client get a new error with Skype bot — «ServiceError: Unknown»: http://jmp.sh/slkjhqo
Interesting that some messages were sent to the user, but some of them not.

This is our logs:
15.06.2018 11:23:30 | 12 Mb | 13 Mb | service_url: https://smba.trafficmanager.net/apis/
15.06.2018 11:23:31 | 12 Mb | 13 Mb | Result:
15.06.2018 11:23:31 | 12 Mb | 13 Mb | Array
(
[error] => Array
(
[code] => ServiceError
[message] => Unknown
)
) 

What can be the reason for this? What should we do in such situations?

**Comment by EricDahlvang** [comment] 2018-06-18 23:01
@igor-pukhlov I'm sorry, but I have no update to share from the Skype team.

In regards to your new "ServiceError" issue:

> The Azure Bot Service is experiencing degraded performance that is impacting customers under certain conditions. Our engineering team has identified a root cause and implemented a solution that should mitigate the problem. Today, the fix was deployed to a subset of datacenters where it’s undergoing validation. Pending further verification the team will continue to deploy the fix to datacenters worldwide

In the future, if you run into a new problem, please open a new issue rather than commenting on an unrelated issue.  

Thanks.

**Comment by igor-pukhlov** [comment] 2018-06-19 07:18
@EricDahlvang ok, thank you for the answer.

**Comment by atanych** [comment] 2018-06-25 11:08
We also have the same issue.
Some clients writes messages, but can not receive answers.

Bot api response:
```
%{"code" => "ServiceError", "message" => "Acl check failed"}
```
Use this endpoint:
`/v3/conversations/#{conversation_id}/activities`

**Comment by EricDahlvang** [comment] 2018-06-27 18:16
The Skype team is aware of this issue.

**Comment by igor-pukhlov** [comment] 2018-07-10 13:20
@EricDahlvang Hello,

We got one more example of ACL check failed from another client and he provides us some information about it, so maybe it will be helpful for the Skype team.

1) He created Skype bot in Azure ( Microsoft App ID: c068880c-b35a-4db6-926c-40e1d7eab00f )
2) Added it to his contact list in Skype
3) He writes to bot and receives messages in our helpdesk, but cant send answers because of ACL check failed: https://jmp.sh/fruYjCJ

Earlier we thought that problem appears when a user has an old version of Skype client, but this one uses fresh version: 12.1815.209.0

4) I added his bot to my contact list and everything works fine, so I recommend him to delete bot from his contact list and add it again. But it doesn't help. He receives ACL check failed again.  
5) User decided that the new bot will solve the problem and he creates it ( Microsoft App ID: cb1a6dcd-9e86-4731-b54c-cc3769505f26 )
6) And he got ACL check failed again: https://jmp.sh/RYqTUpA
7) I also try message with this new bot and everything works fine again
8) The user sends a message to the bot from mobile Skype application on his smartphone and ACL check failed magically disappeared 🙂 

Maybe the problem appears only with some special Skype accounts or accounts with special settings?

**Comment by EricDahlvang** [comment] 2018-07-11 23:19
@igor-pukhlov Thank you for these details.  I will pass them along to the skype team.

**Comment by customcoops77** [comment] 2018-08-06 17:06
Help me!

Thomas

**Comment by JasonSowers** [comment] 2018-10-01 20:33
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team

**Closed by JasonSowers** 2018-10-01 20:33 UTC
Labels: ACL check failed, Skype, bug, known issue
