### ISSUE TITLE
Parallel Login to SKB channel

### ISSUE THREAD

**Issue by rahulugee** [Microsoft/BotBuilder#4442] opened 2018-04-09 09:26 UTC
## Bot Info
* SDK Platform: < Node.js -->
* SDK Version: <-- 6.9.1 -->
* Active Channels: <-- Skype fro Business -->
* Deployment Environment: <-- Azure Bot Service, -->

## Issue Description
<my bot is hosted on skype for business.It is a LUIS bot wherein bot extracts data from a SQL db based on user input. Typical questions are : sales in A OR revenue in B.When multiple user login at same time on skype for business ,bot mixes conversation.For example if 1 user asks what is sale in A and user 2 asks what is revenue in B, bot answers sales in B is XXX and revenue in A is XXXX. Basically variable values gets changed based on latest input. 
How can we create a separate session for each user so that the variables dont change >

**Comment by nodeomega** [comment] 2018-04-09 18:24
How are you storing user data?  Are you using Azure table storage, cosmos DB, etc.?

**Comment by rahulugee** [comment] 2018-04-10 01:47
I am storing data in azure SQL db

**Comment by EricDahlvang** [comment] 2018-04-10 18:07
@rahulugee  Can you share some sample code that reproduces this problem?

**Comment by rahulugee** [comment] 2018-04-11 18:08
@EricDahlvang  here is a small piece.
Whenever LUIS identifies intent as "Margin" this piece gets triggered

bot.dialog('MarginDialog',
    (session, args) => {       
        loginIds(session.message.address.user.id).then(result => {
            console.log("Matched value is: "+ result); // execution flow #8
            if (result == true) {
                var intent = args.intent;
                clearGlobalVariablesIntents();
                
                global_kpi = 'Gross Margin 3rd Party';
                /* Sql parameter */
                global_kpi = "'"+global_kpi+"'"; 
                global_kpi_user_friendly = 'Gross Margin';
                


However if another user is also active on skype for business and asks bot about revenue almost simultaneously (before bot is able to fetch data for margin query)..bot goes to revenue intent and triggers code corresponding to Revenue intent.

What actually is happening is bot is not able to keep both sessions as separate. Concurrent chatting is not being supported. Is their a way by which we can fix it in code so that we can facilitate 100s of users to connect to bot at same time and ask questions without overlapping.

**Comment by rahulugee** [comment] 2018-04-11 18:56
One imp thing is that i am using table storage for saving variable values based on user input 

bot.set('storage', tableStorage);

In most documents i am seeing storage as inmemory

bot.set('storage', inMemoryStorage);
Could this be a cause of my problem?..Or it is better to use table storage anyways

**Comment by EricDahlvang** [comment] 2018-04-11 20:07
This looks like the issue is with the global variables.  Instead of having global_kpi and global_kpi_user_friendly why not use session.userData.kpi and session.userData.kpi_user_friendly?  Then, these values will be scoped to the user alone and will not be overwritten when another user interacts with the bot.

inMemoryStorage is a volatile method for handling state.  It will be cleared out whenever the service itself is restarted.  In this sense, table storage is better .

**Comment by EricDahlvang** [comment] 2018-04-11 20:08
This documentation on managing state might help: https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-state

**Comment by nodeomega** [comment] 2018-05-23 00:50
@rahulugee Did the documentation referenced by @EricDahlvang help in resolving this issue?

**Comment by rahulugee** [comment] 2018-05-23 02:18
Yes indeed. Thanks a lot

**Comment by nodeomega** [comment] 2018-05-23 18:32
Excellent.  I'll be closing this issue then.  If you run into any more problems, don't hesitate to open a new issue!

**Closed by nodeomega** 2018-05-23 18:32 UTC
Labels: Node.js SDK, Skype for Business, state service
