### ISSUE TITLE
There was an error sending this message to your bot: HTTP status code NotFound

### ISSUE THREAD

**Issue by hardikchoudhary** [Microsoft/BotBuilder#2989] opened 2017-06-20 16:12 UTC
![image](https://user-images.githubusercontent.com/14367146/27343618-185b6820-5601-11e7-9f3d-42f016d6916b.png)

I have deployed my node js app to azure

it is running on local

and when i start testing on dev botframework test web chat , i get retry on message

and issues on status of web chat saying

There was an error sending this message to your bot: HTTP status code NotFound

Please help me regarding same 

thanks

**Comment by nwhitmont** [comment] 2017-06-20 16:27
Duplicate of #2985

**Closed by nwhitmont** 2017-06-20 16:27 UTC
