### ISSUE TITLE
[Bot Portal] Skype channel configuration error: "There was a problem synchronizing your bot to Skype."  + "Join" link not present

### ISSUE THREAD

**Issue by sushodhan** [Microsoft/BotBuilder#3121] opened 2017-07-12 11:33 UTC
##Bot Details
Microsoft Bot ID : 74688871-a2b5-412d-b54d-4147c08b2d63
Endpoint : http://skypecallerbot20170627035805.azurewebsites.net/api/messages

##Note 
It is the sample skype calling bot created by Microsoft for user's understanding.

**Comment by nwhitmont** [comment] 2017-07-12 14:25
@sushodhan Are you using .NET or Node SDK for BotBuilder?

**Comment by nwhitmont** [comment] 2017-07-12 14:42
@sushodhan When I tested your bot via webchat, your  bot did not respond. This indicates there is a problem with your bot code or deployment. 

Also, there appears to be an error in the Skype channel configuration where the "Join" link is not present on the channels page. The portal team is in the process of investigating this issue.  

You might want to try setting up a new bot registration and connecting it to your bot, then see if you experience the same Skype channel configuration errors.

**Comment by nwhitmont** [comment] 2017-07-12 15:12
Duplicate of: https://stackoverflow.com/questions/45059149/need-help-on-developing-a-bot-using-ms-bot-framework-in-c-sharp-which-handles-sk

**Comment by sushodhan** [comment] 2017-07-13 06:42
@nwhitmont  I am using C#.

**Comment by sushodhan** [comment] 2017-07-13 06:59
@nwhitmont I was trying some things that is why you were unable to chat through web chat. Now try to do the some it will work fine.

**Comment by JasonSowers** [comment] 2017-10-05 18:54
Please let us know if you are still experiencing issues.

**Closed by JasonSowers** 2017-10-05 18:54 UTC
Labels: .NET SDK, Bot Portal, channel configuration, Skype
