### ISSUE TITLE
[Images] Unable to download larger images from Skype or Web Chat channels.

### ISSUE THREAD

**Issue by NathanCOakes** [Microsoft/BotBuilder#3603] opened 2017-10-12 15:22 UTC
## Bot Info 
* Bot handle: Internal bot, won't be releasing to public.
* SDK Platform: .NET
* SDK Version: 3.9.1
* Active Channels: Skype, WebChat, Telegram
* Deployment Environment: Locally hosted, Deployed to web server

## Issue Description
Using either Web Chat or Skype, I am unable to download any image attachments >3.5MB, on the bot's side.  Sending the image to the bot through Telegram works, but using the other two channels, it gives the error "A task was canceled".  

## Code Example
//Pull out the byte stream from the ContentURL
```
var url = a.ContentUrl;
var attachmentData = await connector.HttpClient.GetByteArrayAsync(url);
```
The second line where we're awaiting the byte array throws the error.  The same code works with Telegram.

## Expected Behavior
Download the bleeding image.

## Actual Results
Throws an error.

**Comment by JasonSowers** [comment] 2017-10-12 18:15
Each channel is going to have its own limitations on file size.

**Comment by JasonSowers** [comment] 2017-10-12 18:15
please do not double post, we actively monitor both forums.
closing as duplicate of https://stackoverflow.com/questions/46712476/microsoft-bot-framework-attachment-size-limit

**Closed by JasonSowers** 2017-10-12 18:15 UTC
Labels: .NET SDK, images, question
