### ISSUE TITLE
having a private generic method in LuisDialog breaks it

### ISSUE THREAD

**Issue by amoldeshpande** [Microsoft/BotBuilder#634] opened 2016-07-11 01:41 UTC
my class derived from LuisDialog contains this method:

private async Task doNothing<T>(String x) where T: SomeBaseClass
        {
            await Task.Delay(0);
        }

This causes my overriden MessageReceived which to throw at this line:

await base.MessageReceived(context,response)

the exception is
Exception thrown: 'System.ArgumentException' in mscorlib.dll
Cannot bind to the target method because its signature or security transparency is not compatible with that of the delegate type.

Obviously, the actual generic method I want to use is more complicated, but I don't understand why the framework cares about private methods in my class.

ETA: I'm using botbuilder 1.2.5

**Comment by amoldeshpande** [comment] 2016-07-11 17:58
here's a diff that made things work for me. works (why try to find handlers for methods which are not LuisIntents ?), but there may be a more elegant way of doing the same.
```
$ git diff
diff --git a/CSharp/Library/Dialogs/LuisDialog.cs b/CSharp/Library/Dialogs/LuisDindex 50b7614..d3d5a79 100644
--- a/CSharp/Library/Dialogs/LuisDialog.cs
+++ b/CSharp/Library/Dialogs/LuisDialog.cs
@@ -219,6 +219,10 @@ namespace Microsoft.Bot.Builder.Dialogs
             foreach (var method in methods)
             {
                 var intents = method.GetCustomAttributes<LuisIntentAttribute>(i
+                if(intents.Length == 0)
+                {
+                    continue;
+                }
                 var intentHandler = (IntentHandler)Delegate.CreateDelegate(type                 if (intentHandler != null)
                 {
(END)
```

**Comment by willportnoy** [comment] 2016-07-11 18:10
Thank you for the report - there was a similar issue https://github.com/Microsoft/BotBuilder/issues/435 that I was unable to reproduce (we have a relevant test as well).

The code uses the method name as the default name for the LUIS intent:

https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/LuisDialog.cs#L225

which is why we don't skip the loop for an empty attributes array.

We're passing a "false" throwOnBindFailure to CreateDelegate, so I'm having trouble understanding why it's throwing at all.  What platform do you run on?

**Comment by willportnoy** [comment] 2016-07-11 20:28
Fyi, I was able to reproduce the issue and have submitted a fix for code review.

**Comment by amoldeshpande** [comment] 2016-07-11 20:42
sorry was out for a bit. I'm on Windows. good to know you found a repro anyway.

I personally don't see a problem with forcing people to decorate with an attribute (it makes the association explicit, which seems to me a good thing ) or not crawling private methods.

I'll keep an eye on this issue for the fix so I can revert my local change. thanks!

**Comment by willportnoy** [comment] 2016-07-12 15:40
We include non-attributed methods for the user's convenience.  I agree there are benefits to explicit attributes.  I believe this commit should fix the issue.

I'm going to close this issue, but feel free to open a new issue for more discussion.

**Closed by willportnoy** 2016-07-12 15:40 UTC
