### ISSUE TITLE
Carousel cards right icon to scroll right not appearing

### ISSUE THREAD

**Issue by UtkarshBehre** [Microsoft/BotBuilder#3411] opened 2017-09-01 10:52 UTC
## Bot Info 
* Bot handle: ctlibot
* App ID: fbd62590-7a79-466d-8c3b-9a6e14784190
* SDK Platform: .NET
* SDK Version: 3.9
* Active Channels: Web Chat
* Deployment Environment: Azure Bot Service

## Issue Description
I started using **Carousel Cards** feature in my code to display multiple Hero cards. In local when i run the code in emulator everything seems to be working fine. _Specifically_, I am able to see both **left** and **right** **arrow** **icons** to help scroll through the cards properly. But when i deployed the code to Azure Bot Service and tested in **web chat channel**, I am **unable** to **see** the **right arrow icon** at all. However left arrow icon appears once i scroll to right using middle mouse button.
I think emulator might be using older UI code since i downloaded it a while ago whereas webchannel is using latest code so maybe some code changes introduced this bug.

## Code Example
Using any Carousel code should produce the same issue since the issue is in UI and not in logic.

## Reproduction Steps
1. Testing Carousel cards locally in emulator gives required result.
2. Deploying same code in Azure.
3. Testing in web channel is now not giving right arrow icon in Carousel Cards.

## Expected Behavior
Both left and right arrow icons should appear in Carousel Cards. (ScreenShot from emulator. Same expected in Web Channel)
![expected carousel](https://user-images.githubusercontent.com/13257193/29966706-c13f822e-8f30-11e7-902d-d93b2f55b57b.png)

## Actual Results
Only left arrow icon is appearing to help scroll left side horizontally. Right arrow icon is missing to help scroll right side horizontally. (ScreenShot from web channel. Working as expected in local emulator as in previous screenshot)
![actual carousel](https://user-images.githubusercontent.com/13257193/29966714-ca756084-8f30-11e7-97db-585654b13034.png)

**Comment by stevengum97** [comment] 2017-09-01 16:55
Closing this issue as it's a duplicate of WebChat issue 567: [[WebChat Carousel] doesn't display right scroll button](https://github.com/Microsoft/BotFramework-WebChat/issues/567). Please follow the issue there.

**Closed by stevengum97** 2017-09-01 16:55 UTC
