### ISSUE TITLE
[Deploy] There was a problem synchronizing your bot to Skype.

### ISSUE THREAD

**Issue by yasmimp** [Microsoft/BotBuilder#4356] opened 2018-03-22 01:30 UTC
## Bot Info
* SDK Platform: .NET
* SDK Version: Latest version
* Active Channels: Skype
* Deployment Environment: Azure Bot Channels Registration
* MS App ID: 695a11fe-a820-4490-be1a-4940b810edb2

## Issue Description
My bot is working when I test it using Azure's "test in web chat" function.
Unfortunately, whenever I add Skype as a channel I get this error and my bot won't work.

## Reproduction Steps
1. Skype channel is added in Channels
2. Click on 'Health'
3. Shows the warning

## Expected Behavior
Skype channel should be added correctly and bot should respond.

## Actual Results
Skype channel Health shows 'There was a problem synchronizing your bot to Skype.' error

**Comment by JasonSowers** [comment] 2018-03-22 21:28
@yasmimp I recently ran into this issue myself and have a query out to the Skype team for help, I will let you know when I get an answer what the solution is.

**Comment by JasonSowers** [comment] 2018-03-27 16:24
Just to Update you i am still working with the skype team to investigate this.  Will update you ASAP

**Comment by rogerweb** [comment] 2018-03-29 15:24
Same problem here. Webchat works fine, Slack works fine, but Skype doesn't. It display this "There was a problem synchronizing your bot to Skype." warning in the health screen. In the Skype client the messages I try to send are marked as "not sent". Same for the embedded version.

**Comment by alvaarengaaa** [comment] 2018-03-29 16:44
I'm having the same issue.

**Comment by ItsMeArthur** [comment] 2018-03-29 17:10
I'm also facing the same issue.  I created a new chatbot from scratch, just the basic echo application from the Bot Builder template, and deployed it to Azure and the Bot Channel Connector.  Tried on the classic Skype application for Windows 7, the new Skype application for Windows 10 , via web and and Android app, every Skype client failed to deliver the messages.

![skype_bot_channel_registration_error](https://user-images.githubusercontent.com/11617999/38102826-cbd6564e-335a-11e8-9828-b2441b1256c6.png)

![skype_android_error](https://user-images.githubusercontent.com/11617999/38102825-cbaf3762-335a-11e8-82b2-02b2cac1800b.png)

![skype_classic_error](https://user-images.githubusercontent.com/11617999/38102827-cc4e7552-335a-11e8-9ad6-b205480e1093.png)

![skype_new_error](https://user-images.githubusercontent.com/11617999/38102828-cc71febe-335a-11e8-9879-451e63e8e8bb.png)

![skype_web_error](https://user-images.githubusercontent.com/11617999/38102829-ccadb580-335a-11e8-9b01-a78c01be58ee.png)

**Comment by rogerweb** [comment] 2018-04-02 13:50
I've deleted and re-created the Bot Channels Registration resource and now the Skype channel is working. Unable to identify the root cause though.

**Comment by ItsMeArthur** [comment] 2018-04-02 14:16
@rogerweb Good to know. I was also able to create a Skype Chatbot successfully last Friday. However I can't just delete the Bot Channels Registration for my bots in production...

**Comment by JasonSowers** [comment] 2018-04-03 18:31
I was out of the office, I will continue to conversation with the skype team and work toward getting this resolved.  Will report back when I have more information.

**Comment by JasonSowers** [comment] 2018-04-04 23:37
Still looking into this, no resolution yet.

**Comment by JasonSowers** [comment] 2018-04-11 18:16
#4455

**Comment by JasonSowers** [comment] 2018-04-24 16:50
Closing this issue since it seems everyone's problem is resolved, please open a new issue if you continue to experience this problem

**Closed by JasonSowers** 2018-04-24 16:50 UTC
Labels: .NET SDK, Bot Portal, Skype
