### ISSUE TITLE
Carousel Cards' sequence getting changed for FB Messenger channel

### ISSUE THREAD

**Issue by bhushanvadgave** [Microsoft/BotBuilder#5321] opened 2019-03-05 15:03 UTC
## Issue
We have a bot service running in production which serves multiple channels like directline, FB messenger etc.
We are using **botbuilder's NodeJS SDK v3.14.0**. 
The issue is - The sequence of cards of a carousel is getting changed for FB messenger user. The sequence is retained correctly for directline channel users. This issue is breaking the user experience in production.

**Comment by sharmadine** [comment] 2019-03-05 17:59
Can someone please share where's the issue? All is well with the sequence of cards in a carousel on Skype and Direct Line channels but it changing randomly in FB Not. We are forced to switch off the FB not in production because of this issue :-(

We debugged the code and found the cards sequence correct till they go out but FB Messenger is showing them in a very different and random sequence.

Looking forward for early help.

**Comment by v-kydela** [comment] 2019-03-05 19:53
@bhushanvadgave 
@sharmadine 

I have just reproduced this issue extensively myself. The Facebook Messenger platform has its own card system called [templates](https://developers.facebook.com/docs/messenger-platform/send-messages/template/generic/#carousel) that can accessed directly using an activity's [channel data](https://blog.botframework.com/2017/03/28/custom-channel-data/). However, the issue persists whether I use a Facebook Messenger payload directly or whether I send a Bot Framework card and let the connector handle it.

It appears to be caused by a change on the Facebook side. There are bug reports that are not limited to the Bot Framework: https://developers.facebook.com/support/bugs/2310937235657679

I am closing this issue because there is nothing we can do from our end, but I hope Facebook fixes this soon.

(Duplicate of https://github.com/Microsoft/BotBuilder-V3/issues/121)

**Closed by v-kydela** 2019-03-05 19:53 UTC

**Comment by sharmadine** [comment] 2019-03-06 03:26
@v-kydela many thanks for your response and guidance. Much appreciated.

**Comment by SalehAlbuga** [comment] 2019-03-11 20:38
@v-kydela Thank you very much for the response! I'm using iOS Facebook Messenger
