### ISSUE TITLE
Documentation Build Failing

### ISSUE THREAD

**Issue by kentstroker** [Microsoft/BotBuilder#2238] opened 2017-02-10 16:55 UTC
After installing the three programs: doxygen, graphvia and mscgen the bat file exits out with this error:

Generating docs for nested compound Microsoft::Bot::Builder::Internals::Fibers::Serialization::StoreInstanceByTypeSurrogate::ObjectReference...
Exiting...

Any suggestions on how to resolve and get the docs generated?

**Comment by msft-shahins** [comment] 2017-02-14 01:14
can you check the version of doxygen you are using? We are building the documentation with doxygen 1.8.11 and everything builds cleanly without any failure.

**Comment by msft-shahins** [comment] 2017-02-15 18:31
Closing this since it is not an issue that we can reproduce and documentation build is not broken. Feel free to comment or open another issue if you still have the problem.

**Closed by msft-shahins** 2017-02-15 18:31 UTC
