### ISSUE TITLE
Skype: no image attachement received

### ISSUE THREAD

**Issue by JpEncausse** [Microsoft/BotBuilder#276] opened 2016-05-13 10:10 UTC
I try to send image attachement from Skype to my BotConnectorBot but the message do not contains attachements.

It works with Emulator

I added a middleware to download and store attachements because Skype send attachement in a dedicated message

**Comment by tomlm** [comment] 2016-05-13 16:10
If you are using the bot framework you do not need to use the middle ware, we take attachment images and store in skype as appropriate

**Comment by Stevenic** [comment] 2016-05-14 06:53
Can you share your code that isn't working?

**Comment by JpEncausse** [comment] 2016-05-14 09:47
@tomlm I think it's on the other side:

On Skype,
1. I join an Image => message is sent
2. I say "what is this"

On my server,

```
bot.use(downloadImage);

var downloadImage = function (session, next) {
    var attach = session.message.attachments;
    if (!attach || !attach[0]) { return next(); }
    var filename = __dirname + '/../tmp/att'+ (new Date()).getTime() +'.jpg';
    download(attach[0], filename, function(){
      session.userData.lastAttachment = filename;
      next();
    });  
};
```
So I download attachement bind do Skype message, but when I consolo.log the skype message there is no attachement.

It works with the emulator.

**Comment by Stevenic** [comment] 2016-05-14 17:03
So the issue is `attachments` is always empty on skype. Tom or Craig will need to weigh in on that one.

**Comment by craigjensen** [comment] 2016-05-16 15:41
Please add your botId and i'll take a look in our logs and see if I can where the problem is.

**Comment by JpEncausse** [comment] 2016-05-16 15:49
The Skype-Bot is `viseo-bot`
I click on attachement icon and join a photo.
On NodeJS server side I receive a message but without attachements

**Comment by craigjensen** [comment] 2016-05-16 16:12
We're seeing the following error in our logs which seems to point to a problem with your bot.  Let me know if you need additional help on our side.

viseo-bot VISEO Bot InternalServerError
{"code":"InternalError","message":"ENOENT: no such file or directory, open '/home/jp_encausse/node-bot/bots/../tmp/att1463414364121.jpg'"}

**Comment by JpEncausse** [comment] 2016-05-16 18:52
I don't understand,

I fixed a bug with image path not correctly stored on my server and I normamize my path. But there is still something strange...

1. From my windows desktop, I select an image and set it. The image is displayed in my Skype
2. Server side

```
bot.use(function (session, next) {
  console.log(session.message);
  next();
});
```

Display the message with **sometimes**:
```
[ {   contentType: 'image/jpeg',
       contentUrl: 'https://bcattachmentsprod.blob.core.windows.net/000',
       title: 'cat.jpg' } ],
```

I don't understand sometimes there is the attachement sometimes there is not ! I tried with multiple images

**Comment by craigjensen** [comment] 2016-05-17 19:58
I can confirm that this is a bug on our end.  We're working on a fix and will deploy it soon.

**Comment by craigjensen** [comment] 2016-05-17 21:31
The fix has been deployed.  Please let us know if you see this again

**Closed** 2016-05-18 23:16 UTC
Labels: bug

**Comment by cwdyang** [comment] 2016-05-24 11:49
i am having trouble getting the bot to attach an image to the message & make it materialise on skype ...


var img = new Bitmap(HttpContext.Current.Server.MapPath("~/Images/bot.png"));

                     System.IO.MemoryStream ms = new System.IO.MemoryStream();
                     img.Save(ms, System.Drawing.Imaging.ImageFormat.Png);
                     byte[] byteImage = ms.ToArray();
                     var image64 = Convert.ToBase64String(byteImage,Base64FormattingOptions.InsertLineBreaks); //Get Base64

 Message message = new Message()
                     {
                         From = fromAccount,
                         To = toAccount,
                            Text =  "Hey you awake? Mrs Doris has just had an accident in her bed",
                        Language = "en",
                         Attachments = new List<Attachment>()
                         
                          
                     };

var attachment = new Attachment()
                     {
                         Text = "fall.png",
                         Content = image64,
                         //ContentUrl = @"http://freeiconbox.com/icon/256/34429.png",
                         ContentType = "image/png"
                     };

                     message.Attachments.Add(attachment);


when i send this the user only gets the text, no photos.. 
i have verified that the photo exists by outputting img.Size
am i doing something wrong here?

**Comment by craigjensen** [comment] 2016-05-24 16:57
The preferred way to send an image attachment is by sending a link to the image in the contentUrl property (see example attachment below).  We have limitations on the total message size so you might be running into that when passing the image inline.

 {
     "contentType": "image/jpeg",
     "contentUrl": "http://www.theoldrobots.com/images62/Bender-18.JPG",
     "content": null,
     "fallbackText": "Bender: http://www.theoldrobots.com/images62/Bender-18.JPG",
     "title": "Bender",
     "titleLink": "https://en.wikipedia.org/wiki/Bender_(Futurama)",
     "text": "Bender Bending Rodríguez, commonly known as Bender, is a main character in the animated television series Futurama.",
     "thumbnailUrl": null,
     "actions": null
   },

**Comment by cwdyang** [comment] 2016-05-26 03:55
hi thanks @craigjensen . i tried it (verbatim) and still only getting just the text message my skypebot id =  862db2c0-3ea6-4e47-a64d-df63247ef40e if thats of any use for debugging - no attachment/photo at all. the bot itself is hosted on Azure (web app not backed by a virtual machine) 

thanks heaps for helping!

**Comment by craigjensen** [comment] 2016-05-26 20:04
We pushed out an update to the Skype channel that hopefully addresses this.  Please try sending your attachment again and let us know if the problem still exists.

**Comment by cwdyang** [comment] 2016-05-27 10:14
@craigjensen  > you are a legend thanks heaps man!
