### ISSUE TITLE
[Skype] Bot not working in Skype once deleted and added?

### ISSUE THREAD

**Issue by hpksp** [Microsoft/BotBuilder#3952] opened 2017-12-19 10:45 UTC
## Bot Info 
* App ID: 48831ec2-1da8-4bd2-bd2e-8b102ecbf3de
* SDK Platform: .NET
* SDK Version: 3.12.2.4
* Active Channels: Slack, Direct Line, Web Chat, Skype
* Deployment Environment: Azure App Service

I had to delete my bot from the skype contacts to do some testing. I added it back to the contacts of the same account and it's no longer working. Messages in skype show as sent but no replay from the bot. I tried running the bot locally with ngrok, but skype messages never reach the controller. It's working fine in another skype account. Also it's perfectly working in slack, directline and webchat. The bot was created in bot framework portal. 

P.S. migrating to azure is not an option for the moment. Thanks in advance. 

## Expected Behavior
Messages sent through skype should reach the bot

## Actual Results
No response from the bot.

**Comment by nwhitmont** [comment] 2017-12-19 16:43
@hpksp duplicate of #3951 ?

**Comment by hpksp** [comment] 2017-12-20 02:42
@nwhitmont not really. these are two different bots. with #3951 , initially i wasn't even able to add the bot to skype. After a while i was able to. then it say not sent! this issue is related to the bot that's been there from jan 2017. anyhow this started working now. so i'm gonna close the issue. thanks for the support

**Comment by JasonSowers** [comment] 2017-12-21 18:07
@hpksp things can sometimes take some time to propagate, this is probably the issue you ran into.

**Closed** 2018-01-05 10:08 UTC
Labels: .NET SDK, Direct Line, Skype
