### ISSUE TITLE
C# ActivityTypes.DeleteUserData Not triggered

### ISSUE THREAD

**Issue by alokraj68** [Microsoft/BotBuilder#1631] opened 2016-11-10 15:50 UTC
```
if (message.Type == ActivityTypes.DeleteUserData)
            {
// test
             }
```
This Code segment in Message controller is not triggered when user removes Bot from skype contact.
We tried to do this in order to comply the bot framework Guidelines of user data removal.

Is this not a bug?

**Comment by chrimc62** [comment] 2016-11-28 00:44
@tomlm @konstlut any progress on this?

**Comment by konstlut** [comment] 2017-02-21 13:26
@alokraj68 That looks like a bug on the backend and there was quite a lot of changes since this defect was reported. Is it still a problem? if yes, will you please provide your bot msa app id, and I will be able to troubleshoot it. Thanks!

**Comment by alokraj68** [comment] 2017-02-23 07:45
@konstlut I would check that get back as soon as possible

**Comment by konstlut** [comment] 2017-03-14 14:35
@alokraj68 I will close it, but please feel free to reopen if the problem gets reproduced.

**Closed by konstlut** 2017-03-14 14:35 UTC
Labels: bug, skype

**Comment by Noc2** [comment] 2017-03-25 19:43
I just tested it with ngrok, because it still isn't working: 
If I remove my bot from my skype account, it triggers an ActivityTypes.ContactRelationUpdate with the Action “remove”. 
So, when is ActivityTypes.DeleteUserData triggered by skype?

**Comment by alokraj68** [comment] 2017-03-27 05:18
Yeah, it's not triggering even now.
