### ISSUE TITLE
Sending email addresses to slack causes formatting issue

### ISSUE THREAD

**Issue by mattlanham** [Microsoft/BotBuilder#377] opened 2016-05-31 15:28 UTC
If you include a single email address in your message, and send that to slack, it comes out as blah@blah.com|blah@blah.com|blah@blah.com (3 times with pipes between). I have checked URLs and they seem to act as expected.

I believe slack expects there to be 2 pipes, but not three, so not sure why this is happening, any advice would be appreciated.

**Comment by Stevenic** [comment] 2016-05-31 18:28
@mattlanham which version of the SDK are you using, C# or Node? And is your bot going through the Bot Connector Service?

**Comment by mattlanham** [comment] 2016-05-31 18:34
I'm using the Node version 1.0.0 and yes it's going through the connector service. @Stevenic

**Comment by Stevenic** [comment] 2016-05-31 20:32
We're looking into the issue. I think @tomlm has a repro

**Comment by mattlanham** [comment] 2016-05-31 20:38
I'm getting something similar on Skype too, if I ask the user via a dialog to give me their email, it's returning it as `<ahref="mailto:matt@geckolabs.co.uk">matt@geckolabs.co.uk</a>` let me know if you want me to log that as a seperate issue.

**Comment by kienct89** [comment] 2016-06-28 10:30
I'm also having the same issue with C# SDK 1.1.0.0

Input in slack: `a@a.com`
What I received in the SDK: `<http://a%40a.com|a%40a.com>`

**Comment by v-thgratMSGit** [comment] 2016-07-25 17:59
Closing this issue due to age. @mattlanham - please open a new issue if this issue is not fixed and needs further discussion. @Stevenic - reopen if necessary. Thanks!

**Closed by v-thgratMSGit** 2016-07-25 17:59 UTC
Labels: bug

**Comment by JamieREvans** [comment] 2016-09-29 00:56
@Stevenic This is still an issue.

I think this should be automatically formatted / cleaned by the botbuilder, because this will affect all Slack bots.

The issue is as follows:

- Ask a user for an email or url
- User responds with an email or url
- Slack sends an automatically formatted response to the bot (e.g.: `<mailto:you@domain.com|you@domain.com>`)
- Bot fails to match regex

It just seems strange to have integration specific (Slack only) logic in the bot after coming out of the botbuilder, which is supposed to genericize the bot experience.

**Comment by craigjensen** [comment] 2016-10-24 14:57
We have a fix ready for the (3 times with pipes between) issue reported by the OP.  It will deployed soon (probably sometime next week).
