### ISSUE TITLE
Sender Address Missing in API V3

### ISSUE THREAD

**Issue by inornos** [Microsoft/BotBuilder#1488] opened 2016-10-22 08:59 UTC
public async Task MessageReceivedAsync(IDialogContext context, IAwaitable<Message> argument)
{
            Message message = await argument;
            string FromSkype = message.From.Address;
}

Unable To Use Message.Address IN API V3
I Want To Get Sender Skype Id 
Please Help

**Comment by ThisWillDoIt** [comment] 2016-10-24 12:07
Duplicate of #1487 with a little bit more information.

**Comment by tomlm** [comment] 2016-11-03 22:25
message.from.id

**Closed by tomlm** 2016-11-03 22:25 UTC
Labels: help wanted
