### ISSUE TITLE
[Feature Request] Add staging support to LuisDialog

### ISSUE THREAD

**Issue by DL-LiveTiles** [Microsoft/BotBuilder#2534] opened 2017-04-03 02:32 UTC
Add staging (optional bool) constructor to LuisDialog allowing targeting of the LUIS staging deployment slot.

**Comment by gregoryfabry** [comment] 2017-04-18 19:39
Would I be able to contribute this? My main question would be how to let the user indicate that they would like to use the staging endpoint slot instead of the production one.

**Comment by nwhitmont** [comment] 2017-04-21 16:40
Duplicate of #2498

**Closed by nwhitmont** 2017-04-21 16:40 UTC
Labels: C# SDK, enhancement, LUIS
