### ISSUE TITLE
[Question, Skype] Sharing code & conversation between Skype Calling Bot and Skype Chat Bot

### ISSUE THREAD

**Issue by devedse** [Microsoft/BotBuilder#4702] opened 2018-06-05 15:45 UTC
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.15.2.2
* Active Channels: Skype and Skype Voice
* Deployment Environment: Azure Bot Service

## Issue Description

We are currently building a bot running in Azure that should be accessible through both Skype and Skype Calling.

We've setup the Text part of the bot to accept an Activity in the Post request and then use `Conversation.SendAsync(Activity, () => new RootLuisDialog(_chatHelper));` to start the dialogflow.

_chatHelper is basically a wrapper around IDialogContext.PostAsync so that we can unit test this as well.

In the voice part however the entry point you have is basically an object named `RecordOutcomeEvent` + `new Dictionary<string, CallState>()`
This does contain some data about the call being made, so I wrote some code to do the conversion from these objects to an Activity object:

```
var activity = new Activity();
activity.ChannelData = JObject.Parse("{\"text\": \"" + text + "\"}");
activity.ChannelId = "skype";
activity.Conversation = new ConversationAccount(id: thisParticipant.Identity);
activity.From = new ChannelAccount(id: thisParticipant.Identity);
activity.Id = Guid.NewGuid().ToString();
activity.Locale = thisParticipant.LanguageId;
activity.Recipient = new ChannelAccount(id: theRecipient.Identity, name: "leazatest4juni");
activity.ServiceUrl = "https://smba.trafficmanager.net/apis/";
activity.Text = text;
activity.TextFormat = "plain";
activity.Timestamp = new DateTimeOffset(DateTime.UtcNow);
activity.LocalTimestamp = activity.Timestamp.Value.ToLocalTime();
activity.Type = "message";
```

Then we used the following code to actually call the Conversation:

```
var chatHelper = new ChatHelperVoice(actionsList);
var mainDialogBot = new MainDialogBot(chatHelper);
string responseMessage = await mainDialogBot.ProcessMessageFromBotProject(activity);
await this.SendSTTResultToUser("Response from the bot: " + responseMessage, callState.Participants);
```

The chatHelper that's being created above should fill the actionList with certain speech commands whenever the RootLuisDialog calls the method _chatHelper.PostAsync().

The issue I'm running into now is that because the Activity matches with an already known activity the RootLuisDialog is never being recreated. This means the ChatHelper is also never reïnstantiated so the bot keeps talking to the actual Text based Skype Conversation that was previously started.

I'm looking for some guidance in this area, I tried setting the activity.ChannelId to something different but then an error occured saying that it couldn't reach the following URL:
`https://state.botframework.com/v3/botstate/skypevoice/conversations/29:...........................`

I think it would be ideal though that when calling a bot the actual Conversation stays alive but that somehow the Bot understands that it now needs to also send responses with speech.

## Code Example
Some code from the RootLuisDialog:

```
[LuisIntent("Calculation_v2")]
public async Task CalculateInterest(IDialogContext context, LuisResult result)
{
    //This should either speak through skype or paste text through skype.
    await _chat.PostAsync(context, $"Let me get my calculator.");

    var calculation_v2Form = new Calculation_v2Form();
    var calculation_v2FormDialog = new FormDialog<Calculation_v2Form>(calculation_v2Form, Calculation_v2Form.BuildForm, FormOptions.PromptInStart, result.Entities);
            
    context.Call(calculation_v2FormDialog, ResumeAfterCalculation_v2FormDialog);
}
```

## Reproduction Steps
We used the IVR Sample for this

## Expected Behavior

When calling a Skype bot I would expect the Conversation to be the same as the one in Text just that the responses are being spoken (maybe as well as being typed).

## Actual Results

Numerous problems and I'm mainly looking for guidance in this matter.

**Comment by nyxsys** [comment] 2018-06-22 16:29
This would be easier to confirm with a minimal bot to confirm the functionality, but it sounds like you should be able to differentiate between your voice messages and text messages on skype by adding an additional field to ChannelData during activity translation. It'd look something like this:
```
 var activity = new Activity();
activity.ChannelData = JObject.Parse("{\"text\": \"" + text + "\"}");
activity.ChannelData.voice = "true";
...
```

**Comment by nyxsys** [comment] 2018-07-02 16:31
Closing, please reopen if the previous comment does not help.

**Comment by nyxsys** [comment] 2018-08-07 22:05
I'm currently looking into seeing if there might be a slightly easier way to do this. Unfortunately tying these two together is always a bit of a hassle, however [this sample](https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/skype-CallingBot) might be patterned in a slightly easier fashion (utilizing the skype calling channel within azure portal). I would suggest considering mapping the userID to both conversations in a temporary memory store. 

Additionally, I'm confirming now, but have you experienced a user signing in with OAuth in text and then not also being authenticated within the voice channel? That is not the intended experience if so, I'm working to reproduce and confirm.

**Comment by devedse** [comment] 2018-08-10 14:49
@nyxsys , We did use that sample as a starting point. But had to then use the DirectLine channel to forward messages from SkypeVoice to the actual bot.
I'm not sure if we can make these calls directly by simply doing new Activity then with specific data that matches the Skype text values?

Does this also mean if we do this that the conversation is also shared?

Also do you know what values in an Activity determine wether or not a conversation is a seperate conversation?

**Comment by nyxsys** [comment] 2018-08-20 15:46
Hi, sorry for the delay. A conversation should only really be differentiated (if going to the same channel, same user, etc) on conversationID. 

Can you explain a bit more specifically what was broken with the Skype voice channel that you ended up needing additional translation? It is possible there might be a bug that can be fixed. 

The unassignment is probably just a bug, that user isn't currently working on this anymore so it may have just updated when you posted a comment.

**Comment by devedse** [comment] 2018-08-21 07:54
It would need a bit more investigation from our side. I'll discuss this in our sprint planning.

I do have a few more questions which I'd like to know to help us decide on the priority of this.

1. But from what I read in your comments is that it should work to have both Skype Voice and Skype Text talking in the same conversation right?

2. So if you call with skype voice, and the bot asks, what is your age, and you reply 10 in text that should work?

3. And how will this work if you're already in a conversation in Skype Text and you call the bot, will it then pickup from the start or start a new conversation?

4. Or am I mistaken here and will this sharing of a conversation only work for the sign in functionality. So that if you sign in with Skype Text the conversation still stays signed in for Skype Voice?

**Comment by nyxsys** [comment] 2018-08-29 20:29
Apologies for the wait, I'm currently verifying the login situation on my end. 

I am also attempting to get a sample up that allows messages to be sent to text and interpreted by the calling side of the bot. However, anything that can do this would be a pretty specialized bot, as will definitely require feeding both sides of the conversation into the CallingConversation. I can at least give preliminary answers from what I can see from my plan.

1. It doesn't quite work like this in the traditional conversationID sense, and would likely result in either all text messages getting a voice response or all voice messages getting a text response, but it should technically be possible on some level.
2. Working on getting something like this functional as mentioned before.
3. This is likely not possible.
4. Working on verifying this, but it is what I meant.

**Comment by nyxsys** [comment] 2018-09-18 19:43
Just to confirm it here, it isn't currently possible to share aspects of the conversation state across voice/text in the skype channels due to the way their events are processed (at least in terms of accessing it via the incoming event). However it does appear that sharing the conversation between text and voice is something currently being looked into in an upcoming release.

**Comment by JasonSowers** [comment] 2018-10-01 20:38
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team

**Closed by JasonSowers** 2018-10-01 20:38 UTC
Labels: .NET SDK, Skype, calling
