### ISSUE TITLE
Directline Task Cancelled Issue

### ISSUE THREAD

**Issue by Benabaka** [Microsoft/BotBuilder#4754] opened 2018-06-18 09:58 UTC
## Bot Info
* SDK Platform: .NET 
* SDK Version: 3.15.2.2
* Active Channels: Direct Line + websockets
* Deployment Environment: Bot Channel registration + Azure App Service

## Issue Description
We have been running our bot for more than a year now. We are starting to see the following error (randomly since 2 weeks now) when our bot tries to post async something back to our channel : 
"System.Threading.Tasks.TaskCanceledException","Message":"A task was canceled."

which tends to indicate something is taking longer than expected ? Our bot channel registration plan is S1 and our app service is a Premium Large so dont think this is about scaling issue on our side...

This bot is running in PRODUCTION and this error is hurting us very badly.

## Expected Behavior
should able to handle that with no error...

## Actual Results
"System.Threading.Tasks.TaskCanceledException","Message":"A task was canceled."

**Comment by ukphillips** [comment] 2018-06-18 12:06
Can you post a code example or discuss perhaps what you are trying to send to the back channel? And there has been absolutely no code changes that might have caused this?

**Comment by Benabaka** [comment] 2018-06-18 12:13
no code change indeed.... The data we are passing back is just text...
This is the code we use to post back to the channel:

 public class PostUnhandledExceptionToUser : IPostToBot
    {
        private readonly ResourceManager resources;
        private readonly IPostToBot inner;
        private readonly IBotToUser botToUser;
        private readonly TraceListener trace;

        public PostUnhandledExceptionToUser(IPostToBot inner, IBotToUser botToUser, ResourceManager resources, TraceListener trace)
        {
            SetField.NotNull(out this.inner, nameof(inner), inner);
            SetField.NotNull(out this.botToUser, nameof(botToUser), botToUser);
            SetField.NotNull(out this.resources, nameof(resources), resources);
            SetField.NotNull(out this.trace, nameof(trace), trace);
        }

        public async Task PostAsync(IActivity activity, CancellationToken token)
        {
            try
            {
                await this.inner.PostAsync(activity, token);
            }
            catch (Exception error)
            {
                try
                {
                    if (Debugger.IsAttached)
                    {
                        var message = this.botToUser.MakeMessage();
                        message.Text = $"Exception: { error.Message}";
                        message.Attachments = new[]
                        {
                            new Attachment(contentType: MediaTypeNames.Text.Plain, content: error.StackTrace)
                        };

                        await this.botToUser.PostAsync(message);
                    }
                    else
                    {
                        await this.botToUser.PostAsync(Resources.Common.BotCodeIssue);
                    }
                }
                catch (Exception inner)
                {
                    this.trace.WriteLine(inner);
                }

                throw;
            }
        }
    }

**Comment by EricDahlvang** [comment] 2018-06-18 23:21
The Azure Bot Service is experiencing degraded performance that is impacting customers under certain conditions. Our engineering team has identified a root cause and implemented a solution that should mitigate the problem. Today, the fix was deployed to a subset of datacenters where it’s undergoing validation. Pending further verification the team will continue to deploy the fix to datacenters worldwide. 

Please let us know if you are still experiencing this issue.

**Comment by EricDahlvang** [comment] 2018-06-21 21:38
The fix has been deployed worldwide.  If you experience any further problems of this nature, please open a new issue.

**Closed by EricDahlvang** 2018-06-21 21:38 UTC
Labels: .NET SDK, Direct Line
