### ISSUE TITLE
On premise Microsoft bot setup

### ISSUE THREAD

**Issue by dhirajgupta1** [Microsoft/BotBuilder#1750] opened 2016-11-28 06:12 UTC
Hello,

Our client is concerned about data and don't want anything on cloud, is it possible to deploy all components of Microsoft bot on premise?
I understand bot service can be deployed on premise (Correct me if i am wrong) but whats about
1) Bot Connector
2) LUIS (This is something we can still use on cloud by avoiding sensitive data)

Thanks,
Dhiraj

**Comment by dchumpitaz** [comment] 2016-12-05 07:25
+1 to Bot Connector

**Comment by cesarvarela** [comment] 2016-12-16 04:23
Any comment from MS guys about this?

This is a really big concern for us as well., banks specially don't like it. 

In fact, if this isn't possible, we might have to switch to another framework.

**Comment by dandriscoll** [comment] 2016-12-21 17:59
Hi @cesarvarela, @dhirajgupta1, and @dchumpitaz, currently the bot must have an internet-accessible endpoint for it to work with Bot Connector servers, such as servers for Skype, Microsoft Teams, etc. You can deploy your bot in an on-premise installation as long as its endpoint can be addressed from the internet.

The Bot Builder libraries do not fundamentally rely on internet access, although some features do use internet services. LUIS, for example, is only available on the internet, so you would need to rely on a different technique for classifying text (such as regex intents/dialogs, which are supported but which offer different features than LUIS). Additionally, the service-to-service auth used to verify the authenticity of Bot Framework calls also requires internet access.

So if you replace those parts (Bot Connector, LUIS, auth) you can operate your bot completely offline.

At the moment we're focusing on the online versions of all three. It's not impossible that we would offer offline versions, but right now we don't have concrete plans.

**Comment by abhishan** [comment] 2016-12-22 11:07
@dandriscoll - Agreed that its best that bot be deployed in Azure and many of our clients are comfortable with that.
One client wants an on-prem deployment for the Bot, but is okay to use LUIS.
We are currently **exploring using the code from the emulator and web-chat to build a "chat box" interface** that can be deployed on-premise and will **call our bot's end point directly** without going though Bot Framework Cloud Service. Essentially the server where the bot will be hosted will have access to the internet. But the server itself will not be available on the internet.
I would really appreciate your thoughts and comments about this approach.

Thank you!
~abhishan

**Comment by cesarvarela** [comment] 2016-12-22 11:39
Yeah, customers understand that NLP has to be an external service. The issue is with the bot connector which is what @abhishan is referring to.

Open sourcing the bot connector would be awesome, otherwise, instructions on how to build one would help too.

**Comment by dandriscoll** [comment] 2016-12-26 19:44
I don't have specific guidance at this point, except to say that as an open platform, you can pick/choose which pieces to how to compose them together.

**Comment by dandriscoll** [comment] 2017-01-28 11:41
Closing as it appears we've addressed the question, and that calling a non-internet-connected endpoint is a valid request but not supported at this time. Feel free to at-mention or open a new issue if you'd like to discuss further.

**Closed by dandriscoll** 2017-01-28 11:41 UTC

**Comment by mbettan** [comment] 2017-09-21 14:40
Any updates on this ?

**Comment by dandriscoll** [comment] 2017-09-21 14:48
No change to the current architecture.

**Comment by mbettan** [comment] 2017-09-21 15:24
Do you know if we can have Bot Emulator on-prem working with Skype as temporary solution?

**Comment by dandriscoll** [comment] 2017-09-21 15:34
You would need to disable your bot's security and the emulator's security for that. If you do, it may work on-prem.

**Comment by solvaidmin** [comment] 2017-10-13 12:13
GDPR will be an issue. Are the connector service servers all located in the US? Or, if I am hosting my web app bot in UK azure, will it connect to a UK bot connector service?
