### ISSUE TITLE
In iPhone, stateful dialog does not work properly.

### ISSUE THREAD

**Issue by ToshiAtKuroneko** [Microsoft/BotBuilder#1430] opened 2016-10-14 08:25 UTC
I have developed a following of stateful Bot, it is operating test in Web Chat Connector.
Test of this Bot is available at the following URL.
https://microsoft-apiapp937554448978497cb48a05cb30f2eb14.azurewebsites.net/
NOTE: In this Bot, use the Japanese.

My Bot, in the following Web browser, will work properly.
1. PC Win 10 --- Edge, IE 11, Chrome
2. Android Smart Phone --- Chrome

But, My Bot, in the following Web browser, does not work properly.
1. Apple iPhone 6s/7 --- Safari, Chrome

The following screen capture is a case to work properly.
![jyoshi_kai_chat_bot2-bdfd0](https://cloud.githubusercontent.com/assets/22735358/19380041/45639404-9230-11e6-8b2c-b718071d2762.png)

However, in the Web browser of the iPhone, it will not be as in the above screen capture.
**It seems like the state of the conversation is not maintained.**
**Why in the Web browser of the iPhone, stateful conversation, it will not work properly?**

**Comment by danmarshall** [comment] 2016-10-14 17:59
The state is maintained on the state server, so perhaps the web page client has a bug. Can you share an example of the bug?

**Comment by ToshiAtKuroneko** [comment] 2016-10-15 08:56
Yes, I can share
Operation in Safari on my iPhone is the following screen capture.
![img_0645](https://cloud.githubusercontent.com/assets/22735358/19408795/9e0dc6c6-9300-11e6-8038-9f4efeae1ab1.PNG)
In the iPhone's Web browser, stateful conversation, does not work properly.
Perhaps, it would be a bug in the Web Chat Connector.

**Comment by ToshiAtKuroneko** [comment] 2016-10-18 04:47
Apple seems to be policy to reject the application you are using a cookie.
In iPhone, cookie is will often disappear, is because of that, it cut off the session.

The iPhone, as an alternative of the cookie, there is a hand to use the Safari of local storage.
Safari of local storage is SQLite that can be used in javascript.
In the case of a request from the iPhone, I think in Web Chat Conector is not to save the Conversation ID to Safari of local storage.

In addition, iOS version of Chrome, as the UserAgent, is that of to disguise the Safari.
For this reason, in Chrome, it will appear the same defect as the Safari.

My reasoning is over.

**Comment by chrimc62** [comment] 2016-11-27 00:04
@danmarshall is this something we can fix or we need to live with?

**Comment by ToshiAtKuroneko** [comment] 2016-11-27 02:42
I'm checking the "Web chat preview" box on the Web Chat configuration page.
But it does not work on Safari.

**Comment by ajayp** [comment] 2016-11-28 02:02
I have also reproduced the same issue with my own bot on my iphone 6 but only with Safari, it works just fine if I use Chrome.

**Comment by danmarshall** [comment] 2016-12-06 22:16
Using the Web Chat Preview I am able to chat in Safari on a Mac, and on an iPhone. Can you publish the link to your web chat?

**Comment by haganbt** [comment] 2016-12-15 17:21
@danmarshall - im seeing the same. I have a simple menu setup whereby starting a new session prompts for a selection. No matter what is selected from the menu, the same start menu is reloaded. This does not occur in Chrome (i.e. the menu session continues), but fails in Safari (desktop and ios).

Ive recorded a quick screen grab here of the issue: https://dl.dropboxusercontent.com/u/39437082/safari-session.mov

Please let me know if there is anything I can do to assist with debugging, this is quite a serious issue for us.

**Comment by danmarshall** [comment] 2016-12-15 19:07
@haganbt looks like you are using the v1 webchat control - can you try using the Preview version?

**Comment by haganbt** [comment] 2016-12-15 19:15
Thanks @danmarshall - daft question, where do I find the preview version? Im using this: https://docs.botframework.com/en-us/support/embed-chat-control2/

**Comment by danmarshall** [comment] 2016-12-15 20:56
@haganbt looks like that document should be updated :)
At the end of step 1 you will see a "use preview" checkbox.

**Comment by haganbt** [comment] 2016-12-15 21:22
Wonderful, confirmed fixed in Safari @dandriscoll. The preview control looks much lighter also, so kudos on the optimizations.

Appreciate the quick support.

**Comment by danmarshall** [comment] 2016-12-16 00:01
@ToshiAtKuroneko can you verify this behavior in the new version of the webchat control?

**Comment by danmarshall** [comment] 2016-12-16 00:02
@ajayp can you send a link to your bot's webchat?

**Comment by ToshiAtKuroneko** [comment] 2016-12-16 12:21
I will try Preview Version on December 17th in Japan time.
Please wait a little more.

**Comment by ToshiAtKuroneko** [comment] 2016-12-17 03:42
@danmarshall I checked "Enable Preview" and tested Web Chat on my iPhone 7.

(1) Chrome: It worked correctly.
(2) Safari: It worked correctly.

The problem of Web Chat on my Phone has been solved.
Thank you very much.

However, why is the newline code ignored, is this a specification?

**Comment by ajayp** [comment] 2016-12-19 05:46
@danmarshall - Apologies, I was on vacation, I just tested this and it is now working on my iPhone 6 using both Safari and Chrome after I checked "Enable Preview"

**Comment by ToshiAtKuroneko** [comment] 2016-12-19 13:37
@danmarshall  This bug was fixed in the Preview version. Please close it.

**Closed** 2016-12-19 16:07 UTC
Labels: bug
