### ISSUE TITLE
Cookies in microsoft web bot nodejs

### ISSUE THREAD

**Issue by PratikshaGupta** [Microsoft/BotBuilder#4368] opened 2018-03-26 06:30 UTC
## Bot Info
* SDK Platform: Node.js
* Active Channels: Website
* Deployment Environment: Azure Bot Service, Azure App Service

## Issue Description
Feature to retain user conversation when a user closes the window and reopen. Can we use cookies in this case or is there any other way to implement this?

**Comment by JasonSowers** [comment] 2018-03-26 15:40
Closing as duplicate of https://stackoverflow.com/questions/49484922/cookies-in-microsoft-web-bot-nodejs.  please don't double post

**Closed by JasonSowers** 2018-03-26 15:40 UTC
