### ISSUE TITLE
JwtToken cannot be send to emulator

### ISSUE THREAD

**Issue by v-tbert** [Microsoft/BotBuilder#1107] opened 2016-08-29 12:38 UTC
I am trying to track down an issue whereby I cannot get a simple IDialog derived class to display. The one oddity I have noticed is that every time ReplyToActivityAsync is called I get the following message in the debug output:
iisexpress.exe Warning: 0 : Service url localhost:9000 is not trusted and JwtToken cannot be sent to it.

I can't find any documentation indicating how to setup trust for the emulator so I can eliminate it as a possible source of my dialog issue.

**Comment by willportnoy** [comment] 2016-08-30 18:26
We track a list of trusted service urls so that we don't forward the JwtToken (and your auth information) to some other unknown service.  I believe localhost:9000 would be marked as trusted already if you had sent a message from it (i.e. through the emulator).  Maybe you can manually modify MicrosoftAppCredentials.TrustedHostNames in the debugger to diagnose your issue?  @msft-shahins any other thoughts?

**Comment by msft-shahins** [comment] 2016-08-30 23:43
@v-tbert can you elaborate on how you are testing your bot? Are you missing BotAuthentication attribute from your bot's message controller? That attribute is responsible on authenticating the incoming request and adding its service url to the set of trusted urls.

**Comment by msft-shahins** [comment] 2016-09-02 20:09
Closing this assuming that the issue is resolved and the main reason was the missing BotAuthentication attribute. Feel free to open another issue if you still have this problem.

**Closed by msft-shahins** 2016-09-02 20:09 UTC
