### ISSUE TITLE
Send sticker (using file_id, not url) with Telegram and BotFramework

### ISSUE THREAD

**Issue by caxepok** [Microsoft/BotBuilder#4609] opened 2018-05-15 06:25 UTC
## Bot Info
* SDK Platform: .NET
* SDK Version: 
* Active Channels: Telegram
* Deployment Environment: Azure App Service

## Issue Description
Unable to send sticker using "file_id". Documentation on docs.microsoft.com comes only with sample using "url"
Trying to send like this:

## Code Example
```
activity.ChannelData = new { method = "sendSticker", parameters = new { sticker = new { file_id = "CAADAgADmwEAAoo0zQirH-KhlK1ZMwI", width = 512, height = 355 } } };
await connector.Conversations.ReplyToActivityAsync(activity);
```

## Expected Behavior
Sticker sended to user

## Actual Results
HTTP 500 occured, says Telegram

**Comment by JasonSowers** [comment] 2018-05-15 16:39
Duplicate of https://stackoverflow.com/questions/50334564/send-sticker-using-file-id-not-url-with-telegram-and-botframework

**Closed** 2018-05-15 19:58 UTC
Labels: .NET SDK, Telegram
